use crate::model::{
    BindingBundle, BindingReport, BridgeFunctionBinding, BridgeParam, BridgeType, DependencySpec,
    GeneratedArtifacts, ImportCrateOutput, ModuleNode, ResolvedCrate,
};
use heck::ToSnakeCase;
use kain_core::error::KainError;
use kain_fs as kfs;
use std::path::{Path, PathBuf};

pub const BRIDGE_FORMAT_VERSION: &str = "crate-ffi-v1";
pub const BRIDGE_SYMBOL_NAME: &[u8] = b"kain_register_bridge";

pub fn write_generated_artifacts(
    resolved: &ResolvedCrate,
    bundle: &BindingBundle,
    cache_dir: &Path,
    output_dir_override: Option<&Path>,
) -> Result<(GeneratedArtifacts, ImportCrateOutput), KainError> {
    let generated_dir = output_dir_override
        .map(Path::to_path_buf)
        .unwrap_or_else(|| cache_dir.to_path_buf());
    kfs::create_dir_all(&generated_dir).map_err(fs_to_kain_error)?;
    let bridge_dir = cache_dir.join("bridge");
    kfs::create_dir_all(bridge_dir.join("src")).map_err(fs_to_kain_error)?;

    let canonical_module_source = render_canonical_module_source(resolved, &bundle.module_root);
    let prelude_source = render_prelude_source(resolved, &bundle.bridge_functions);
    let bridge_source = render_bridge_source(resolved, &bundle.bridge_functions);

    let canonical_module_path = generated_dir.join(format!("{}.kn", resolved.import_name));
    let prelude_path = generated_dir.join(format!("{}_prelude.kn", resolved.import_name));
    let report_json_path = generated_dir.join(format!("{}_report.json", resolved.import_name));
    let report_text_path = generated_dir.join(format!("{}_report.txt", resolved.import_name));
    let bridge_manifest_path = bridge_dir.join("Cargo.toml");
    let bridge_source_path = bridge_dir.join("src").join("lib.rs");

    let mut report = BindingReport {
        crate_name: resolved.import_name.clone(),
        package_name: resolved.package_name.clone(),
        version: resolved.version.clone(),
        manifest_path: resolved.manifest_path.display().to_string(),
        resolution_kind: resolved.resolution_kind,
        cache_dir: cache_dir.display().to_string(),
        report_json_path: report_json_path.display().to_string(),
        report_text_path: report_text_path.display().to_string(),
        entries: bundle.report_entries.clone(),
        source_fingerprints: bundle.source_fingerprints.clone(),
    };
    let report_text = render_report_text(&report);
    let report_json = serde_json::to_string_pretty(&report).map_err(|err| {
        KainError::runtime(format!(
            "Failed to serialize crate FFI binding report for '{}': {err}",
            resolved.import_name
        ))
    })?;
    kfs::atomic_write_text(&canonical_module_path, &canonical_module_source)
        .map_err(fs_to_kain_error)?;
    kfs::atomic_write_text(&prelude_path, &prelude_source).map_err(fs_to_kain_error)?;
    kfs::atomic_write_text(&report_json_path, &report_json).map_err(fs_to_kain_error)?;
    kfs::atomic_write_text(&report_text_path, &report_text).map_err(fs_to_kain_error)?;
    kfs::atomic_write_text(
        &bridge_manifest_path,
        &render_bridge_manifest(resolved, &bridge_dir),
    )
    .map_err(fs_to_kain_error)?;
    kfs::atomic_write_text(&bridge_source_path, &bridge_source).map_err(fs_to_kain_error)?;

    report.report_json_path = report_json_path.display().to_string();
    report.report_text_path = report_text_path.display().to_string();
    let artifacts = GeneratedArtifacts {
        canonical_module_source: canonical_module_source.clone(),
        prelude_source: prelude_source.clone(),
        bridge_source,
        report,
        report_text,
    };

    let output = ImportCrateOutput {
        resolved: resolved.clone(),
        config_root: None,
        rust_ffi_config: None,
        cache_dir: cache_dir.to_path_buf(),
        canonical_module_path,
        prelude_path,
        report_json_path,
        report_text_path,
        bridge_manifest_path,
        bridge_source_path,
        dylib_path: None,
        canonical_module_source,
        prelude_source,
        cache_hit: false,
    };
    Ok((artifacts, output))
}

fn fs_to_kain_error(error: kain_fs::FsError) -> KainError {
    KainError::runtime(format!("Filesystem error: {error}"))
}

fn render_canonical_module_source(resolved: &ResolvedCrate, module_root: &ModuleNode) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "# Generated by kain-crate-ffi for crate {}\n# Resolution: {:?}\n\n",
        resolved.import_name, resolved.resolution_kind
    ));
    output.push_str("mod rust:\n");
    output.push_str("    ");
    output.push_str(&format!("mod {}:\n", resolved.import_name));
    render_module_node(module_root, 2, &mut output);
    output
}

fn render_module_node(node: &ModuleNode, indent: usize, output: &mut String) {
    for item in &node.items {
        write_docs(&item.docs, indent, output);
        for line in item.source.trim_end().lines() {
            output.push_str(&"    ".repeat(indent));
            output.push_str(line);
            output.push('\n');
        }
        output.push('\n');
    }

    for (module_name, child) in &node.children {
        output.push_str(&"    ".repeat(indent));
        output.push_str(&format!("mod {module_name}:\n"));
        render_module_node(child, indent + 1, output);
    }
}

fn write_docs(lines: &[String], indent: usize, output: &mut String) {
    for line in lines {
        output.push_str(&"    ".repeat(indent));
        output.push_str("# ");
        output.push_str(line);
        output.push('\n');
    }
}

fn render_prelude_source(resolved: &ResolvedCrate, functions: &[BridgeFunctionBinding]) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "# Generated import shim for crate {}\n",
        resolved.import_name
    ));
    let mut emitted = std::collections::BTreeSet::new();
    for function in functions {
        if let Some(prefixed) = function.exported_aliases.get(1) {
            if emitted.insert(prefixed.clone()) {
                output.push_str(&format!(
                    "use rust::{}::{} as {}\n",
                    resolved.import_name, prefixed, prefixed
                ));
            }
        }
    }
    output
}

fn render_bridge_manifest(resolved: &ResolvedCrate, _bridge_dir: &Path) -> String {
    let dependency_block = match &resolved.dependency_spec {
        DependencySpec::Path {
            package,
            dependency_name,
            path,
        } => format!(
            "{dependency_name} = {{ package = {:?}, path = {:?} }}",
            package,
            path.display().to_string()
        ),
        DependencySpec::Registry {
            package,
            dependency_name,
            version,
            features,
            default_features,
        } => {
            let mut rendered = format!(
                "{dependency_name} = {{ package = {:?}, version = {:?}",
                package, version
            );
            if !features.is_empty() {
                rendered.push_str(&format!(", features = {:?}", features));
            }
            if !default_features {
                rendered.push_str(", default-features = false");
            }
            rendered.push_str(" }");
            rendered
        }
    };

    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|value| value.parent())
        .map(Path::to_path_buf)
        .unwrap_or_else(|| resolved.workspace_root.clone());
    let crate_name = bridge_crate_name(&resolved.import_name);
    format!(
        "[package]\nname = {:?}\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\ncrate-type = [\"cdylib\"]\n\n[dependencies]\nkain-core = {{ path = {:?} }}\nkain-host = {{ path = {:?}, default-features = false }}\n{dependency_block}\n\n[profile.dev]\ndebug = 0\npanic = \"unwind\"\n\n[workspace]\nresolver = \"2\"\n",
        crate_name,
        repo_root
            .join("crates")
            .join("kain-core")
            .display()
            .to_string(),
        repo_root
            .join("crates")
            .join("kain-host")
            .display()
            .to_string(),
    )
}

fn render_bridge_source(_resolved: &ResolvedCrate, functions: &[BridgeFunctionBinding]) -> String {
    let mut output = String::new();
    output.push_str("use kain_core::error::KainError;\n");
    output.push_str("use kain_core::runtime::{Env, Value};\n");
    output.push_str("use kain_host::{FromKainValue, ToKainValue};\n");
    output.push('\n');

    for function in functions {
        output.push_str(&render_bridge_wrapper(function));
        output.push('\n');
    }

    output.push_str("fn register_all(env: &mut Env) {\n");
    for function in functions {
        let wrapper_name = wrapper_name(&function.emitted_name);
        for alias in &function.exported_aliases {
            output.push_str(&format!(
                "    env.register_native_fn({alias:?}, {wrapper_name});\n"
            ));
        }
    }
    output.push_str("}\n\n");
    output.push_str("#[no_mangle]\n");
    output.push_str("pub extern \"C\" fn kain_register_bridge(env: *mut Env) {\n");
    output.push_str("    let Some(env) = (unsafe { env.as_mut() }) else {\n");
    output.push_str("        return;\n");
    output.push_str("    };\n");
    output.push_str("    register_all(env);\n");
    output.push_str("}\n");
    output
}

fn render_bridge_wrapper(function: &BridgeFunctionBinding) -> String {
    let wrapper_name = wrapper_name(&function.emitted_name);
    let mut output = String::new();
    output.push_str(&format!(
        "fn {wrapper_name}(_env: &mut Env, args: Vec<Value>) -> Result<Value, KainError> {{\n"
    ));
    output.push_str(&format!(
        "    if args.len() != {} {{\n",
        function.params.len()
    ));
    output.push_str(&format!(
        "        return Err(KainError::runtime(format!(\"{} expected {} argument(s), got {{}}\", args.len())));\n",
        function.emitted_name,
        function.params.len()
    ));
    output.push_str("    }\n");
    output.push_str("    let mut iter = args.into_iter();\n");
    for (index, param) in function.params.iter().enumerate() {
        output.push_str(&render_param_conversion(index, param));
    }
    let call_args = function
        .params
        .iter()
        .map(|param| param.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        "    let result = {}({call_args});\n",
        function.rust_call_path
    ));
    output.push_str(&render_return_conversion(&function.return_type));
    output.push_str("}\n");
    output
}

fn render_param_conversion(_index: usize, param: &BridgeParam) -> String {
    match &param.ty {
        BridgeType::StringRef => format!(
            "    let __{}_owned = <String as FromKainValue>::from_kain_value(iter.next().expect(\"checked arg count\"))?;\n    let {} = __{}_owned.as_str();\n",
            param.name, param.name, param.name
        ),
        _ => {
            let ty = param
                .ty
                .from_kain_trait_type()
                .unwrap_or_else(|| param.ty.render_rust());
            format!(
                "    let {} = <{} as FromKainValue>::from_kain_value(iter.next().expect(\"checked arg count\"))?;\n",
                param.name, ty
            )
        }
    }
}

fn render_return_conversion(ty: &BridgeType) -> String {
    match ty {
        BridgeType::Unit
        | BridgeType::Bool(_)
        | BridgeType::Int(_)
        | BridgeType::Float(_)
        | BridgeType::StringOwned
        | BridgeType::StringRef
        | BridgeType::Option(_)
        | BridgeType::Array(_) => "    Ok(ToKainValue::to_kain_value(result))\n".to_string(),
    }
}

fn render_report_text(report: &BindingReport) -> String {
    let mut output = String::new();
    output.push_str(&format!(
        "crate: {}\npackage: {}\nversion: {}\nresolution: {:?}\nmanifest: {}\ncache_dir: {}\n\n",
        report.crate_name,
        report.package_name,
        report.version,
        report.resolution_kind,
        report.manifest_path,
        report.cache_dir
    ));
    output.push_str("entries:\n");
    for entry in &report.entries {
        output.push_str(&format!(
            "- [{}] {:?} {}\n",
            match entry.status {
                crate::model::ItemStatus::Callable => "callable",
                crate::model::ItemStatus::TypeOnly => "type_only",
                crate::model::ItemStatus::Stubbed => "stubbed",
                crate::model::ItemStatus::SkippedInternal => "skipped_internal",
            },
            entry.kind,
            entry.symbol_path
        ));
        if let Some(reason) = &entry.reason {
            output.push_str(&format!("  reason: {reason}\n"));
        }
        if let Some(emitted_symbol) = &entry.emitted_symbol {
            output.push_str(&format!("  emitted: {emitted_symbol}\n"));
        }
    }
    output.push_str("\nsource_fingerprints:\n");
    for fingerprint in &report.source_fingerprints {
        output.push_str(&format!("- {} {}\n", fingerprint.sha256, fingerprint.path));
    }
    output
}

fn wrapper_name(emitted_name: &str) -> String {
    format!("__kain_bridge_{}", emitted_name.to_snake_case())
}

pub fn bridge_crate_name(crate_name: &str) -> String {
    format!("kain_crate_ffi_bridge_{}", crate_name.to_snake_case())
}
