// Generated by KAIN-PRO - Module Registration
#include "KainFlow.h"
#include "Modules/ModuleManager.h"

class FKainFlowModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        // Module startup
    }

    virtual void ShutdownModule() override
    {
        // Module shutdown
    }
};

IMPLEMENT_MODULE(FKainFlowModule, KainFlow)
