// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "KainFlowBlueprintLibrary.h"
#include "RenderGraph.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphResources.h"
#include "RenderGraphUtils.h"
#include "RenderTargetPool.h"
#include "Engine/TextureRenderTarget2D.h"

		FFluidSimulationProfile UKainFlowBlueprintLibraryFunctionLibrary::create_default_profile()
		{
			auto p = FFluidSimulationProfile();
			p.id = TEXT("Default Smoke");
			p.mode = EFluidMode::Smoke;
			p.viscosity = 0.001000f;
			p.vorticity_strength = 2.000000f;
			p.diffusion = 0.000000f;
			return p;
		}

