// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "SourceCompute.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FSourceComputeShader, "/Plugin/KainFlow/SourceCompute.usf", "SourceComputeCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_SourceCompute(
    FRDGBuilder& GraphBuilder,
    FVector3f source_pos,
    FVector3f source_val,
    float radius,
    float res,
    float is_velocity,
    FRDGTextureRef target_tex,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FSourceComputeShader::FParameters* Params = GraphBuilder.AllocParameters<FSourceComputeShader::FParameters>();
    // Bind Scalars
    Params->source_pos = source_pos;
    Params->source_val = source_val;
    Params->radius = radius;
    Params->res = res;
    Params->is_velocity = is_velocity;
    // Bind Textures
    Params->target_tex = target_tex;
    Params->target_texSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FSourceComputeShader::Exec(GraphBuilder, *Params, GroupCount);
}
