// Generated by KAIN - UE5 Editor Tools
#include "FAlphaGenEditorModule.h"

void FAlphaGenEditorModule::StartupModule()
{
	UE_LOG(LogTemp, Log, TEXT("AlphaGenEditorModule has started!"));
	
	// Register shader directory (guarded against duplicate auto-registration)
	if (!AllShaderSourceDirectoryMappings().Contains(TEXT("/Plugin/AlphaGen")))
	{
		FString PluginShaderDir = FPaths::Combine(IPluginManager::Get().FindPlugin(TEXT("AlphaGen"))->GetBaseDir(), TEXT("Shaders"));
		AddShaderSourceDirectoryMapping(TEXT("/Plugin/AlphaGen"), PluginShaderDir);
	}
}

void FAlphaGenEditorModule::ShutdownModule()
{
	UE_LOG(LogTemp, Log, TEXT("AlphaGenEditorModule has shut down!"));
}

IMPLEMENT_MODULE(FAlphaGenEditorModule, AlphaGen)

