// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "TestComponentAccess.h"
#include "TestComponentAccessBlueprintLibrary.h"

UHealthComponent::UHealthComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
}

ATestActor::ATestActor()
{
	PrimaryActorTick.bCanEverTick = true;

	RootComponent = CreateDefaultSubobject<USceneComponent>(TEXT("DefaultSceneRoot"));
	health_comp = CreateDefaultSubobject<UHealthComponent>(TEXT("HealthComp"));
}

void ATestActor::BeginPlay()
{
	Super::BeginPlay();
}

void ATestActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

	void ATestActor::tick(const auto self, const float dt)
	{
		const auto hp = health_comp->current_health;
		const auto count = items.Num();
		UE_LOG(LogTemp, Warning, TEXT("Health: %s, Items: %s"), *LexToString(hp), *LexToString(count));
	}

