[package]
name = "kain-commands"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { workspace = true }
kain-lattice = { path = "../kain-lattice" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[build-dependencies]
serde = { workspace = true }
toml = { workspace = true }
