// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "FSketchfabImporterComponent.h"

USketchfabImporterComponent::USketchfabImporterComponent()
{
	PrimaryComponentTick.bCanEverTick = false;
}

