// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "SketchFabBlueprintLibrary.h"

		TArray<FSketchfabModel> USketchFabBlueprintLibraryFunctionLibrary::search_sketchfab(const FString query, const int32 count, const FString api_token)
		{
			const TArray<FSketchfabModel> results = {};
			return results;
		}

		FSketchfabDownloadResult USketchFabBlueprintLibraryFunctionLibrary::get_download_url(const FString model_uid, const FString api_token)
		{
			const auto result = FSketchfabDownloadResult{false, TEXT(""), TEXT("glb"), TEXT("")};
			return result;
		}

		bool USketchFabBlueprintLibraryFunctionLibrary::download_and_import_model(const FString model_uid, const FString api_token, const FString import_path)
		{
			return false;
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::get_sort_mode_string(const ESketchfabSortMode mode)
		{
			return ((mode == ESketchfabSortMode::Relevance) ? TEXT("-relevance") : (mode == ESketchfabSortMode::LikeCount) ? TEXT("-likeCount") : (mode == ESketchfabSortMode::ViewCount) ? TEXT("-viewCount") : (mode == ESketchfabSortMode::PublishedDate) ? TEXT("-publishedAt") : (mode == ESketchfabSortMode::CreatedDate) ? TEXT("-createdAt") : TEXT("-relevance"));
		}

		bool USketchFabBlueprintLibraryFunctionLibrary::validate_api_token(const FString token)
		{
			return (token.length > 0);
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::build_search_url(const FString query, const int32 count, const FString sort_mode)
		{
			const auto base_url = TEXT("https://api.sketchfab.com/v3/search");
			const auto encoded_query = query;
			const auto url = TEXT("{base_url}?type=models&q={encoded_query}&downloadable=true&sort_by={sort_mode}&count={count}");
			return url;
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::parse_thumbnail_url(const FSketchfabModel model)
		{
			return model.thumbnail_url;
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::format_model_info(const FSketchfabModel model)
		{
			return TEXT("{model.name} by {model.author_name} ({model.like_count} likes, {model.view_count} views)");
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::create_auth_header(const FString api_token)
		{
			return TEXT("Token {api_token}");
		}

		bool USketchFabBlueprintLibraryFunctionLibrary::is_valid_model_uid(const FString uid)
		{
			return (uid.length == 32);
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::get_model_viewer_url(const FString model_uid)
		{
			return TEXT("https://sketchfab.com/3d-models/{model_uid}");
		}

		FString USketchFabBlueprintLibraryFunctionLibrary::get_api_base_url()
		{
			return TEXT("https://api.sketchfab.com/v3");
		}

		bool USketchFabBlueprintLibraryFunctionLibrary::is_cache_valid(const FSketchfabCache cache, const float current_time)
		{
			const auto age = (current_time - cache.cache_timestamp);
			return (age < cache.max_cache_age);
		}

		FSketchfabCache USketchFabBlueprintLibraryFunctionLibrary::clear_cache(const FSketchfabCache cache)
		{
			const auto new_cache = FSketchfabCache{{}, {}, 0.000000f, 300.000000f};
			return new_cache;
		}

