// Generated by KAIN-PRO - Module Registration
#include "SketchFab.h"
#include "Modules/ModuleManager.h"

class FSketchFabModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        // Module startup
    }

    virtual void ShutdownModule() override
    {
        // Module shutdown
    }
};

IMPLEMENT_MODULE(FSketchFabModule, SketchFab)
