// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771345486
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "FAdaptiveMeshComponent.h"
#include "FElectroMagneticComponent.h"
#include "FGridResolutionComponent.h"
#include "FMultiphaseComponent.h"
#include "FParticulateComponent.h"
#include "FPhysicalPropertiesComponent.h"
#include "FQuantumComponent.h"
#include "FThermalComponent.h"
#include "FTimeIntegrationComponent.h"
#include "FTurbulenceComponent.h"
#include "FVisualizationComponent.h"

#include "AHyperFluidWorld.generated.h"

UCLASS()
class FLUIDFLOW_API AHyperFluidWorld : public AActor
{
	GENERATED_BODY()

	public:
		AHyperFluidWorld();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UGridResolutionComponent* grid;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UTimeIntegrationComponent* time;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UPhysicalPropertiesComponent* physics;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UTurbulenceComponent* turbulence;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UMultiphaseComponent* multiphase;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UThermalComponent* thermal;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UElectroMagneticComponent* em;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UQuantumComponent* quantum;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UParticulateComponent* particles;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UAdaptiveMeshComponent* adaptive;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UVisualizationComponent* viz;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		TArray<int32> active_presets;

		// Double-buffered Simulation Resources
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_B;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_B;
		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_Initialize")
		void Server_Initialize(const TArray<int32>& preset_ids);

		bool Server_Initialize_Validate(const TArray<int32>& preset_ids);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_StepSimulation")
		void Server_StepSimulation(const int32 steps);

		bool Server_StepSimulation_Validate(const int32 steps);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_SetVisualization")
		void Server_SetVisualization(const EVisualizationMode mode);

		bool Server_SetVisualization_Validate(const EVisualizationMode mode);

		UFUNCTION(Client, Reliable, BlueprintCallable, Category = "Client_ReceiveTelemetry")
		void Client_ReceiveTelemetry(const TArray<float>& data);

		void ApplyPresets(const TArray<int32> preset_ids);

		void DispatchSimulation(const int32 steps);

		void DispatchLBM(const int32 steps);

		void DispatchSPH(const int32 steps);

		void DispatchFVM(const int32 steps);

		void DispatchFEM(const int32 steps);

		void DispatchSpectral(const int32 steps);

		void DispatchVortex(const int32 steps);

		void UpdateVisualization();

	};

