// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579009
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EBreakupModel.generated.h"



UENUM(BlueprintType)
enum class EBreakupModel : uint8
{
	None UMETA(DisplayName = "None"),
	TAB UMETA(DisplayName = "TAB"),
	ETAB UMETA(DisplayName = "ETAB"),
	KH_RT UMETA(DisplayName = "KH_RT"),
	Pilch_Erdman UMETA(DisplayName = "Pilch_Erdman"),
	Reitz_Diwakar UMETA(DisplayName = "Reitz_Diwakar"),
	BreakupModel_MAX UMETA(DisplayName = "BreakupModel_MAX"),
};










































































