// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579003
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "ECouplingStrategy.generated.h"



UENUM(BlueprintType)
enum class ECouplingStrategy : uint8
{
	Explicit_Sequential UMETA(DisplayName = "Explicit_Sequential"),
	Implicit_Sequential UMETA(DisplayName = "Implicit_Sequential"),
	Implicit_Parallel UMETA(DisplayName = "Implicit_Parallel"),
	Staggered_Iterative UMETA(DisplayName = "Staggered_Iterative"),
	Monolithic UMETA(DisplayName = "Monolithic"),
	Partitioned UMETA(DisplayName = "Partitioned"),
	CouplingStrategy_MAX UMETA(DisplayName = "CouplingStrategy_MAX"),
};










































































