// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771345485
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EGPUBackend.generated.h"

UENUM(BlueprintType)
enum class EGPUBackend : uint8
{
	Default UMETA(DisplayName = "Default"),
	RDGDirect UMETA(DisplayName = "RDGDirect"),
	AsyncCompute UMETA(DisplayName = "AsyncCompute"),
	MeshShader UMETA(DisplayName = "MeshShader"),
	WaveOps UMETA(DisplayName = "WaveOps"),
	CooperativeMatrix UMETA(DisplayName = "CooperativeMatrix"),
	GPUBackend_MAX UMETA(DisplayName = "GPUBackend_MAX"),
};

