// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579004
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EReactionMechanism.generated.h"



UENUM(BlueprintType)
enum class EReactionMechanism : uint8
{
	None UMETA(DisplayName = "None"),
	Single_Step UMETA(DisplayName = "Single_Step"),
	Two_Step UMETA(DisplayName = "Two_Step"),
	Skeletal UMETA(DisplayName = "Skeletal"),
	Detailed_GRI_Mech UMETA(DisplayName = "Detailed_GRI_Mech"),
	Detailed_San_Diego UMETA(DisplayName = "Detailed_San_Diego"),
	Flamelet UMETA(DisplayName = "Flamelet"),
	PDF_Transport UMETA(DisplayName = "PDF_Transport"),
	ReactionMechanism_MAX UMETA(DisplayName = "ReactionMechanism_MAX"),
};










































































