// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771390208
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "EBoundaryType.h"

#include "FBoundaryProfile.generated.h"

USTRUCT(BlueprintType)
struct FLUIDFLOW_API FBoundaryProfile : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	int32 id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	EBoundaryType boundary_type;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	float friction;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	float slip_factor;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	FVector inflow_velocity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	float inflow_temperature;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	float inflow_density;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	float sponge_strength;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "BoundaryProfile")
	FVector moving_velocity;

};

