// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579014
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "FFluidPreset.generated.h"



USTRUCT(BlueprintType)
struct FLUIDFLOW_API FFluidPreset
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	int64 id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EFluidClass class;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ESolverFamily solver;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ETurbulenceModel turbulence;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EBoundaryType boundary;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	TArray<ECouplingField> coupling;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EQualityTier quality;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EGPUBackend backend;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EAdaptiveStrategy adaptive;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ETimeIntegrator time_integrator;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float viscosity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float density = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float surface_tension = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float compressibility = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float conductivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float permittivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float permeability = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float chemical_reactivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float radiation_absorption = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float gravity_scale = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float anisotropy = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float cavitation_threshold = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float yield_stress = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float foam_threshold = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float spray_threshold = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float bubble_coalescence = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float turbulence_intensity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float vorticity_confinement = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float adaptive_refine_threshold = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float adaptive_coarsen_threshold = 0.0f;

};










































































