// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579015
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"

#include "FFluidMaterial.generated.h"



USTRUCT(BlueprintType)
struct FLUIDFLOW_API FFluidMaterial : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	int64 id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float molecular_weight = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float critical_temperature = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float critical_pressure = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float boiling_point = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float melting_point = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float triple_point_temp = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float triple_point_pressure = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float viscosity_ref = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float viscosity_temperature_coeff = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float thermal_conductivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float thermal_diffusivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float mass_diffusivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float gas_constant = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float specific_heat_cp = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float specific_heat_cv = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float gamma = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float surface_tension_ref = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float surface_tension_temp_coeff = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float contact_angle_glass = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float contact_angle_metal = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float contact_angle_polymer = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float refractive_index = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	FVector3f absorption_coefficient = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	FVector3f scattering_coefficient = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float anisotropy_factor = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float electrical_conductivity = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float magnetic_susceptibility = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float dielectric_constant = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float ph_value = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float oxidation_potential = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float reaction_enthalpy = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidMaterial")
	float activation_energy = 0.0f;

};










































































