// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771421951
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EBreakupModel.h"
#include "ECoalescenceModel.h"
#include "ECollisionModel.h"
#include "EDragModel.h"
#include "EEvaporationModel.h"
#include "EParticleType.h"
#include "ETrackingScheme.h"

#include "FHyperFluidParticleSystemComponent.generated.h"



UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class FLUIDFLOW_API UHyperFluidParticleSystemComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UHyperFluidParticleSystemComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EParticleType particle_type;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 particle_count;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float particle_diameter;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float particle_density;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float particle_shape_factor;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EDragModel drag_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float drag_coefficient;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ECollisionModel collision_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float restitution_coefficient;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float friction_coefficient;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float cohesion_energy;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EBreakupModel breakup_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ECoalescenceModel coalescence_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float weber_number_critical;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EEvaporationModel evaporation_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float latent_heat;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float vapor_pressure;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ETrackingScheme tracking_scheme;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 interpolation_order;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool two_way_coupling;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool four_way_coupling;

};











































































