// Generated by KAIN Compiler - Shared Shader POD Types
// Included by per-shader headers that use @component uniforms.
// DO NOT define POD structs in individual shader headers.

#pragma once

#include "CoreMinimal.h"

// POD mirror for BoundaryConditionComponent (GPU-compatible)
struct FBoundaryConditionComponentData {
    EBoundaryType primary_type;
    EVelocityProfile velocity_profile;
    ETemperatureProfile temperature_profile;
    EPressureProfile pressure_profile;
    float turbulence_intensity_inlet;
    float turbulence_length_scale_inlet;
    float wall_roughness;
    float wall_temperature;
    float wall_heat_flux;
    float slip_length;
    float contact_angle_advancing;
    float contact_angle_receding;
    float contact_angle_hysteresis;
    float porous_permeability;
    float porous_porosity;
    float sponge_layer_thickness;
    float sponge_damping_coefficient;
    FVector3f moving_wall_velocity;
    FVector3f moving_wall_angular_velocity;
    int32 inflow_turbulence_seed;
    float outflow_convective_velocity;
};

// POD mirror for CollisionComponent (GPU-compatible)
struct FCollisionComponentData {
    bool enabled;
    float restitution;
    float friction;
    float sdf_threshold;
    bool use_global_distance_field;
};

// POD mirror for CouplingComponent (GPU-compatible)
struct FCouplingComponentData {
    ECouplingStrategy coupling_strategy;
    int32 coupling_timestep_ratio;
    float coupling_tolerance;
    int32 coupling_max_iterations;
    bool boussinesq_approximation;
    float natural_convection_gain;
    float forced_convection_gain;
    ERadiationModel radiation_model;
    EFSIMethod fsi_method;
    float structural_damping;
    bool added_mass_effect;
    float electrokinetic_mobility;
    float zeta_potential;
    float debye_length;
    float magnetic_reynolds_number;
    float hartmann_number;
    float interaction_parameter;
    EReactionMechanism reaction_mechanism;
    int32 species_count;
    bool acoustic_coupling;
    float speed_of_sound;
    float acoustic_impedance;
};

// POD mirror for ElectroMagneticComponent (GPU-compatible)
struct FElectroMagneticComponentData {
    float charge_density;
    FVector3f electric_field;
    FVector3f magnetic_field;
    float lorentz_force_gain;
    float resistivity;
    float hall_parameter;
    float ambipolar_diffusion;
};

// POD mirror for HyperFluidParticleSystemComponent (GPU-compatible)
struct FHyperFluidParticleSystemComponentData {
    EParticleType particle_type;
    int32 particle_count;
    float particle_diameter;
    float particle_density;
    float particle_shape_factor;
    EDragModel drag_model;
    float drag_coefficient;
    ECollisionModel collision_model;
    float restitution_coefficient;
    float friction_coefficient;
    float cohesion_energy;
    EBreakupModel breakup_model;
    ECoalescenceModel coalescence_model;
    float weber_number_critical;
    EEvaporationModel evaporation_model;
    float latent_heat;
    float vapor_pressure;
    ETrackingScheme tracking_scheme;
    int32 interpolation_order;
    bool two_way_coupling;
    bool four_way_coupling;
};

// POD mirror for MultiphaseComponent (GPU-compatible)
struct FMultiphaseComponentData {
    int32 phases;
    float phase_field_mobility;
    float interface_thickness;
    float surface_tension_coupling;
    float contact_angle;
    float bubble_spawn_rate;
    float droplet_spawn_rate;
};

// POD mirror for ParticulateComponent (GPU-compatible)
struct FParticulateComponentData {
    int32 particle_count;
    float particle_radius;
    float drag_coefficient;
    float cohesion;
    float restitution;
    float friction;
    float adhesion;
    float granular_compaction;
};

// POD mirror for PhysicalPropertiesComponent (GPU-compatible)
struct FPhysicalPropertiesComponentData {
    EFluidClass fluid_class;
    ESolverFamily solver_family;
    EHybridSolver hybrid_solver;
    EPressureSolver pressure_solver;
    EAdvectionScheme advection_scheme;
    ETurbulenceModel turbulence_model;
    EBoundaryType boundary_type;
    EQualityTier quality;
    EGPUBackend backend;
    float viscosity;
    float density;
    float surface_tension;
    float compressibility;
    float conductivity;
    float permittivity;
    float permeability;
    float reactivity;
    float radiation_absorption;
    float gravity_scale;
    float anisotropy;
    float cavitation_threshold;
    float yield_stress;
    float foam_threshold;
    float spray_threshold;
    float bubble_coalescence;
};

// POD mirror for QuantumComponent (GPU-compatible)
struct FQuantumComponentData {
    float coherence_length;
    float healing_length;
    float vortex_core_size;
    float phase_wrapping;
    float dispersion_gain;
    float superfluid_fraction;
    float condensate_density;
};

// POD mirror for ThermalComponent (GPU-compatible)
struct FThermalComponentData {
    float temperature;
    float thermal_diffusivity;
    float buoyancy_alpha;
    float buoyancy_beta;
    float radiation_gain;
    ERadiationModel radiation_model;
};

// POD mirror for TimeIntegrationComponent (GPU-compatible)
struct FTimeIntegrationComponentData {
    float dt;
    ETimeIntegrator time_integrator;
    float cfl;
    int32 substeps;
    bool real_time_sync;
    bool clamp_dt;
    float max_dt;
    float min_dt;
};

// POD mirror for TurbulenceAdvancedComponent (GPU-compatible)
struct FTurbulenceAdvancedComponentData {
    ELESModel les_model;
    ERANSModel rans_model;
    EWallFunction wall_function;
    float smagorinsky_constant;
    float wale_constant;
    float vreman_constant;
    float k_epsilon_c_mu;
    float k_epsilon_c1;
    float k_epsilon_c2;
    float k_omega_beta_star;
    float k_omega_sigma_k;
    float k_omega_sigma_omega;
    float y_plus_target;
    bool wall_damping;
    ETransitionModel transition_model;
    float intermittency;
    float transition_onset_reynolds;
    ESyntheticTurbulence synthetic_method;
    int32 eddy_count;
    float eddy_lifetime;
    EReynoldsStressModel reynolds_stress_model;
};

// POD mirror for TurbulenceComponent (GPU-compatible)
struct FTurbulenceComponentData {
    float intensity;
    float vortex_confinement;
    float energy_injection;
    float dissipation;
    float length_scale;
    int32 noise_seed;
};

// POD mirror for VisualizationComponent (GPU-compatible)
struct FVisualizationComponentData {
    EVisualizationMode visualization;
    float exposure;
    float contrast;
    float saturation;
    float line_thickness;
    int32 sample_count;
    float step_size;
    FVector3f color_a;
    FVector3f color_b;
    FVector3f color_c;
};

