// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

// POD mirror for VisualizationComponent (GPU-compatible)
struct FVisualizationComponentData {
    EVisualizationMode visualization;
    float exposure;
    float contrast;
    float saturation;
    float line_thickness;
    int32 sample_count;
    float step_size;
    FVector3f color_a;
    FVector3f color_b;
    FVector3f color_c;
};

class FFluidSchlierenShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FFluidSchlierenShader);
    SHADER_USE_PARAMETER_STRUCT(FFluidSchlierenShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVisualizationComponentData, viz)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FFluidSchlierenShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("FluidSchlieren Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FFluidSchlierenShader, "/Plugin/YourPlugin/FluidSchlieren.usf", "FluidSchlierenCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FluidSchlieren(
    FRDGBuilder& GraphBuilder,
    FVisualizationComponentData viz,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
