// Copyright 2026 Epic Games, Inc.. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3 (Modular Output)
// Master header - forward declarations and includes

#pragma once

#include "CoreMinimal.h"

// Forward declarations
enum class EFluidClass : uint8;
enum class ESolverFamily : uint8;
enum class EBoundaryType : uint8;
enum class ETurbulenceModel : uint8;
enum class ECouplingField : uint8;
enum class EVisualizationMode : uint8;
enum class EQualityTier : uint8;
enum class EGPUBackend : uint8;
enum class EAdaptiveStrategy : uint8;
enum class ETimeIntegrator : uint8;
struct FFluidPreset;
struct FMaterialLookup;
struct FBoundaryProfile;
struct FTurbulenceProfile;
struct FCouplingProfile;
struct FVisualizationPreset;
struct FGridResolutionComponent;
struct FTimeIntegrationComponent;
struct FPhysicalPropertiesComponent;
struct FTurbulenceComponent;
struct FMultiphaseComponent;
struct FThermalComponent;
struct FElectroMagneticComponent;
struct FQuantumComponent;
struct FParticulateComponent;
struct FAdaptiveMeshComponent;
struct FVisualizationComponent;
class AHyperFluidWorld;
class AHyperFluidEmitter;
class AHyperFluidProbe;
class AHyperFluidController;
struct FHyperFluidEditorModule;
struct FHyperFluidDetails;
struct FHyperFluidViewport;

// Stdlib functions
#include "KainStdlib.h"

// Module includes
#include "EFluidClass.h"
#include "ESolverFamily.h"
#include "EBoundaryType.h"
#include "ETurbulenceModel.h"
#include "ECouplingField.h"
#include "EVisualizationMode.h"
#include "EQualityTier.h"
#include "EGPUBackend.h"
#include "EAdaptiveStrategy.h"
#include "ETimeIntegrator.h"
#include "FFluidPreset.h"
#include "FMaterialLookup.h"
#include "FBoundaryProfile.h"
#include "FTurbulenceProfile.h"
#include "FCouplingProfile.h"
#include "FVisualizationPreset.h"
#include "FGridResolutionComponent.h"
#include "FTimeIntegrationComponent.h"
#include "FPhysicalPropertiesComponent.h"
#include "FTurbulenceComponent.h"
#include "FMultiphaseComponent.h"
#include "FThermalComponent.h"
#include "FElectroMagneticComponent.h"
#include "FQuantumComponent.h"
#include "FParticulateComponent.h"
#include "FAdaptiveMeshComponent.h"
#include "FVisualizationComponent.h"
#include "AHyperFluidWorld.h"
#include "AHyperFluidEmitter.h"
#include "AHyperFluidProbe.h"
#include "AHyperFluidController.h"
#include "FluidFlowBlueprintLibrary.h"
