// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771345485
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"

#include "FMaterialLookup.generated.h"

USTRUCT(BlueprintType)
struct FLUIDFLOW_API FMaterialLookup : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	int32 id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FVector absorption;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FVector scattering;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FVector emission;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	float ior;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	float roughness;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	float metallic;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	float subsurface;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FVector foam_color;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	FVector bubble_color;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MaterialLookup")
	float dispersion;

};

