// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771390208
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "ETimeIntegrator.h"

#include "FTimeIntegrationComponent.generated.h"

UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class FLUIDFLOW_API UTimeIntegrationComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UTimeIntegrationComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float dt;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ETimeIntegrator time_integrator;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float cfl;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 substeps;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool real_time_sync;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool clamp_dt;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float max_dt;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float min_dt;

};

