// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771579018
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"

#include "FValidationCase.generated.h"



USTRUCT(BlueprintType)
struct FLUIDFLOW_API FValidationCase : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	int64 id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	EValidationCaseType case_type;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	FString reference_solution;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	float tolerance = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	float expected_convergence_rate = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	FVector3f grid_resolution = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	int64 time_steps = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ValidationCase")
	float physical_time = 0.0f;

};










































































