// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771421949
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "EVisualizationMode.h"

#include "FVisualizationPreset.generated.h"



USTRUCT(BlueprintType)
struct FLUIDFLOW_API FVisualizationPreset : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	int32 id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	EVisualizationMode mode;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float exposure = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float contrast = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float saturation = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float line_thickness = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	int32 sample_count = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float step_size = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	FVector color_a = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	FVector color_b = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	FVector color_c = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float foam_emissive = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float bubble_emissive = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float shock_gain = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VisualizationPreset")
	float holography_phase_gain = 0.0f;

};










































































