// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FImmersedBoundaryForceShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FImmersedBoundaryForceShader);
    SHADER_USE_PARAMETER_STRUCT(FImmersedBoundaryForceShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(PhysicalPropertiesComponent, physics)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FImmersedBoundaryForceShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("ImmersedBoundaryForce Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FImmersedBoundaryForceShader, "/Plugin/YourPlugin/ImmersedBoundaryForce.usf", "ImmersedBoundaryForceCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_ImmersedBoundaryForce(
    FRDGBuilder& GraphBuilder,
    PhysicalPropertiesComponent physics,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
