// Generated by KAIN Compiler - Stdlib Function Definitions
// Do not edit - regenerate from .kn source

#pragma once

#include "CoreMinimal.h"
#include "Kismet/KismetMathLibrary.h"
#include "AHyperFluidController.h"
#include "AHyperFluidEmitter.h"
#include "AHyperFluidProbe.h"
#include "AHyperFluidWorld.h"
#include "EAdaptiveStrategy.h"
#include "EBoundaryType.h"
#include "ECouplingField.h"
#include "EFluidClass.h"
#include "EGPUBackend.h"
#include "EQualityTier.h"
#include "ESolverFamily.h"
#include "ETimeIntegrator.h"
#include "ETurbulenceModel.h"
#include "EVisualizationMode.h"
#include "FAdaptiveMeshComponent.h"
#include "FBoundaryProfile.h"
#include "FCouplingProfile.h"
#include "FElectroMagneticComponent.h"
#include "FFluidPreset.h"
#include "FGridResolutionComponent.h"
#include "FHyperFluidDetails.h"
#include "FHyperFluidEditorModule.h"
#include "FHyperFluidViewport.h"
#include "FMaterialLookup.h"
#include "FMultiphaseComponent.h"
#include "FParticulateComponent.h"
#include "FPhysicalPropertiesComponent.h"
#include "FQuantumComponent.h"
#include "FThermalComponent.h"
#include "FTimeIntegrationComponent.h"
#include "FTurbulenceComponent.h"
#include "FTurbulenceProfile.h"
#include "FVisualizationComponent.h"
#include "FVisualizationPreset.h"

static inline void main()
{
	preset;
	FFluidPreset{0, TEXT("DefaultWater"), FluidClass.Water, SolverFamily.LatticeBoltzmann, TurbulenceModel.LES, BoundaryType.NoSlip, {CouplingField.Thermal}, QualityTier.High, GPUBackend.RDGDirect, AdaptiveStrategy.AMR, TimeIntegrator.RK4, 0.001000f, 1000.000000f, 0.072000f, 0.000100f, 0.500000f, 1.000000f, 1.000000f, 0.000000f, 0.010000f, 1.000000f, 0.000000f, (-10000.000000f), 0.000000f, 0.250000f, 0.300000f, 0.200000f, 0.100000f, 0.400000f, 0.050000f, 0.010000f};
	preset;
	FFluidPreset{1, TEXT("PlasmaMHD"), FluidClass.Plasma, SolverFamily.MagnetoHydro, TurbulenceModel.DNS, BoundaryType.Slip, {CouplingField.Magnetic, CouplingField.Thermal}, QualityTier.Ultra, GPUBackend.AsyncCompute, AdaptiveStrategy.SparseGrid, TimeIntegrator.CrankNicolson, 0.000010f, 1.000000f, 0.000000f, 0.050000f, 10.000000f, 0.100000f, 5.000000f, 0.000000f, 0.500000f, 0.000000f, 0.500000f, (-1000.000000f), 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.200000f, 0.600000f, 0.020000f, 0.005000f};
}

