// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

#include "FluidFlowShaderTypes.h"

class FPhaseChange_EvaporationShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FPhaseChange_EvaporationShader);
    SHADER_USE_PARAMETER_STRUCT(FPhaseChange_EvaporationShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER_STRUCT(FMultiphaseComponentData, multiphase)
        SHADER_PARAMETER_STRUCT(FThermalComponentData, thermal)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FPhaseChange_EvaporationShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("PhaseChange_Evaporation Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FPhaseChange_EvaporationShader, "/Plugin/FluidFlow/PhaseChange_Evaporation.usf", "PhaseChange_EvaporationCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_PhaseChange_Evaporation(
    FRDGBuilder& GraphBuilder,
    FMultiphaseComponentData multiphase,
    FThermalComponentData thermal,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
