// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FAtmosphericScatteringShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FAtmosphericScatteringShader);
    SHADER_USE_PARAMETER_STRUCT(FAtmosphericScatteringShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, rayleigh_coefficient)
        SHADER_PARAMETER(float, rayleigh_scale_height)
        SHADER_PARAMETER(float, mie_coefficient)
        SHADER_PARAMETER(float, mie_scale_height)
        SHADER_PARAMETER(float, mie_direction)
        SHADER_PARAMETER(float, sun_intensity)
        SHADER_PARAMETER(FVector3f, sun_direction)
        SHADER_PARAMETER(FVector3f, sun_color)
        SHADER_PARAMETER(float, planet_radius)
        SHADER_PARAMETER(float, atmosphere_radius)
        SHADER_PARAMETER(float, sample_count)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG pixel shader pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters)
    {
        TShaderMapRef<FAtmosphericScatteringShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry
        // This is a simplified example - adapt to your rendering pipeline
        // Use AddDrawPass or integrate with your post-process pipeline
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FAtmosphericScatteringShader, "/Plugin/YourPlugin/AtmosphericScattering.usf", "AtmosphericScatteringPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_AtmosphericScattering(
    FRDGBuilder& GraphBuilder,
    FVector3f rayleigh_coefficient,
    float rayleigh_scale_height,
    float mie_coefficient,
    float mie_scale_height,
    float mie_direction,
    float sun_intensity,
    FVector3f sun_direction,
    FVector3f sun_color,
    float planet_radius,
    float atmosphere_radius,
    float sample_count
);
