// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FFilmGrainShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FFilmGrainShader);
    SHADER_USE_PARAMETER_STRUCT(FFilmGrainShader, FGlobalShader);

    using FPermutationDomain = TShaderPermutationDomain<>;

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, grain_intensity)
        SHADER_PARAMETER(float, grain_size)
        SHADER_PARAMETER(float, grain_luminance_contribution)
        SHADER_PARAMETER(float, grain_color_contribution)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG pixel shader pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters)
    {
        TShaderMapRef<FFilmGrainShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FPermutationDomain PermutationVector;

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry
        // This is a simplified example - adapt to your rendering pipeline
        // Use AddDrawPass or integrate with your post-process pipeline
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FFilmGrainShader, "/Plugin/YourPlugin/Shaders/FilmGrain.usf", "FilmGrainPS", SF_Pixel);

// Helper function to dispatch shader from game thread
void DispatchFilmGrainShader(
    float grain_intensity,
    float grain_size,
    float grain_luminance_contribution,
    float grain_color_contribution);
