// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FOceanRenderingShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FOceanRenderingShader);
    SHADER_USE_PARAMETER_STRUCT(FOceanRenderingShader, FGlobalShader);

    using FPermutationDomain = TShaderPermutationDomain<>;

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, wave_amplitude)
        SHADER_PARAMETER(float, wave_frequency)
        SHADER_PARAMETER(float, wave_speed)
        SHADER_PARAMETER(float, wave_choppiness)
        SHADER_PARAMETER(float, wave_scale_1)
        SHADER_PARAMETER(float, wave_scale_2)
        SHADER_PARAMETER(float, wave_scale_3)
        SHADER_PARAMETER(float, foam_threshold)
        SHADER_PARAMETER(FVector3f, foam_color)
        SHADER_PARAMETER(float, foam_decay)
        SHADER_PARAMETER(FVector3f, water_color_shallow)
        SHADER_PARAMETER(FVector3f, water_color_deep)
        SHADER_PARAMETER(float, scatter_strength)
        SHADER_PARAMETER(float, roughness)
        SHADER_PARAMETER(float, metallic)
        SHADER_PARAMETER(float, refraction_strength)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG pixel shader pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters)
    {
        TShaderMapRef<FOceanRenderingShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FPermutationDomain PermutationVector;

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry
        // This is a simplified example - adapt to your rendering pipeline
        // Use AddDrawPass or integrate with your post-process pipeline
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FOceanRenderingShader, "/Plugin/YourPlugin/Shaders/OceanRendering.usf", "OceanRenderingPS", SF_Pixel);

// Helper function to dispatch shader from game thread
void DispatchOceanRenderingShader(
    float wave_amplitude,
    float wave_frequency,
    float wave_speed,
    float wave_choppiness,
    float wave_scale_1,
    float wave_scale_2,
    float wave_scale_3,
    float foam_threshold,
    FVector3f foam_color,
    float foam_decay,
    FVector3f water_color_shallow,
    FVector3f water_color_deep,
    float scatter_strength,
    float roughness,
    float metallic,
    float refraction_strength);
