// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "KainCosmosBlueprintLibrary.h"
#include "RenderGraph.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphResources.h"
#include "RenderGraphUtils.h"
#include "RenderTargetPool.h"
#include "Engine/TextureRenderTarget2D.h"

		float UKainCosmosBlueprintLibraryFunctionLibrary::CalculateGravitationalForce(const float mass1, const float mass2, const float dist)
		{
			const auto g_const = 0.000000f;
			return ((g_const * ((mass1 * mass2))) / ((dist * dist)));
		}

		int64 UKainCosmosBlueprintLibraryFunctionLibrary::GetBiomeAtHeight(const float height, const float temp, const float moisture)
		{
			return /* complex if expr */;
		}

		FVector3f UKainCosmosBlueprintLibraryFunctionLibrary::PredictOrbitalPosition(const FVector3f current_pos, const FVector3f vel, const float time)
		{
			return (current_pos + ((vel * time)));
		}

