/*    Copyright (c) 2024, Alexandre GREMONT@Overwhelmed Guys Studio
 *    All rights reserved
 *
 *    This file is part of the Dialogue Master plugin for Unreal Engine
 *    and is licensed under the Unreal Engine EULA:
 *    https://www.unrealengine.com/en-US/eula/publishing
 */

#include "QuestGraphSchema.h"
#include "QuestGraphNode.h"
#include "QuestStartGraphNode.h"
#include "DialogueMasterTask.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "EdGraphNode_Comment.h"    // https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Editor/UnrealEd/UEdGraphNode_Comment


static bool GetBlueprintsFromBaseClass(UClass* InBaseClass, TArray<FAssetData>& FoundAssets)
{
    if (!IsValid(InBaseClass))
    {
        return false;
    }
		
    FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry");

    TMultiMap<FName, FString> TagsValues;

    // All native CDOs should be in memory - we can look up native subclasses of InNativeClass
    for (FThreadSafeObjectIterator It(InBaseClass); It; ++It)
    {
        const UClass* Class = It->GetClass();
        if (Class->IsNative() && Class->ClassDefaultObject == *It)
        {
            TagsValues.AddUnique(FBlueprintTags::NativeParentClassPath,
                                 FObjectPropertyBase::GetExportPath(Class));
        }
    }

    return AssetRegistryModule.Get().GetAssetsByTagValues(TagsValues, FoundAssets);
}

void UQuestGraphSchema::ListDerivedClasses(UClass* BaseClass, TArray<UClass*> &SubClasses) const
{
    if (!BaseClass)
    {
        UE_LOG(LogTemp, Warning, TEXT("BaseClass is null"));
        return;
    }

    // Preload all derived blueprint (because they are not visible if not already loaded in the editor
    // so we forced it to be loaded).
    TArray<FAssetData> AssetDataList;
    GetBlueprintsFromBaseClass(BaseClass, AssetDataList);
    for (const FAssetData& AssetData : AssetDataList)
    {        
        UObject * LoadedAsset = AssetData.GetAsset();
        UBlueprint * CastedBP = Cast<UBlueprint>(LoadedAsset);
        if(CastedBP)
        {
            SubClasses.Add(*CastedBP->GeneratedClass);
        }
    }
}

void UQuestGraphSchema::GetGraphContextActions(FGraphContextMenuBuilder& contextMenuBuilder) const {
    // Get asset info from graph context menu builder object.
    //UQuestAsset * asset = Cast<UQuestAsset>(contextMenuBuilder.CurrentGraph->GetTypedOuter(UQuestAsset::StaticClass()));    

    // Construct the contextual menu dynamically.
    // If we drag from a pin, the menu :
    // - will display task list options when dragged from a step node's pin.
    // - will display step option when dragged from a task list node.
    // - will display all options when not dragged from a pin.
    bool draggedFromNode = (contextMenuBuilder.FromPin != nullptr);
    bool draggedFromStepNode = false;
    bool draggedFromTaskListNode = false;
    bool draggedFromStartNode = false;
    if(draggedFromNode)
    {
        draggedFromStartNode = contextMenuBuilder.FromPin->GetOwningNode()->IsA<UQuestStartGraphNode>();
        draggedFromStepNode = contextMenuBuilder.FromPin->GetOwningNode()->IsA<UQuestStepGraphNode>();
        draggedFromTaskListNode = contextMenuBuilder.FromPin->GetOwningNode()->IsA<UQuestTaskListGraphNode>();
    }

    if(!draggedFromNode || draggedFromStepNode)
    {
        TArray<UClass*> SubClasses;
        ListDerivedClasses(UDialogueMasterTask::StaticClass(), SubClasses);

        for(UClass * TaskClass : SubClasses)
        {
            // Excludes SKEL_ and REINST_ prefix (generated by UE).
            if(!(
                TaskClass->GetName().StartsWith("SKEL_")
                ||
                TaskClass->GetName().StartsWith("REINST_")
                )
                )
            {
                UDialogueMasterTask* Task = TaskClass->GetDefaultObject<UDialogueMasterTask>();
                // Use the task description if there is no display name defined by the user.
                FText TaskDescription = Task->GetDescription();
                FText TaskSubCategory = FText::FromString("Uncategorized");
                FText TooltipDescription = FText::FromString("");

                // Try to get the blueprint display name (if set by the user).
                UBlueprint* BlueprintClass = UBlueprint::GetBlueprintFromClass(TaskClass);
                if(BlueprintClass != nullptr)
                {
                    if(!BlueprintClass->BlueprintDisplayName.IsEmpty())
                    {
                        TaskDescription = FText::FromString(BlueprintClass->BlueprintDisplayName);
                    }

                    // Also try to get the blueprint category (if set by the user).
                    if(!BlueprintClass->BlueprintCategory.IsEmpty())
                    {
                        TaskSubCategory = FText::FromString(BlueprintClass->BlueprintCategory);
                    }

                    TooltipDescription = FText::Format(FTextFormat::FromString("Add a {0} task node"), TaskDescription);
                    
                    // Try to get the blueprint description (if set by the user).
                    if(!BlueprintClass->BlueprintDescription.IsEmpty())
                    {
                        TooltipDescription = FText::Format(FTextFormat::FromString("{0}. {1}"),
                            TooltipDescription, FText::FromString(BlueprintClass->BlueprintDescription));
                    }
                }
                
                FText entryDescription = FText::Format(FTextFormat::FromString("{0}"), TaskDescription);
                FText category = FText::Format(FTextFormat::FromString("Tasks - {0}"), TaskSubCategory);
        
                TSharedPtr<FNewQuestNodeAction> newTaskNodeAction(
                    new FNewQuestNodeAction(
                        UQuestTaskListGraphNode::StaticClass(),
                        category,
                        entryDescription,
                        TooltipDescription,
                        0,
                        TaskClass
                    )
                );

                contextMenuBuilder.AddAction(newTaskNodeAction);
            }
        }
    }

    if(!draggedFromNode || draggedFromTaskListNode || draggedFromStartNode)
    {
        TSharedPtr<FNewQuestNodeAction> newStepNodeAction(
            new FNewQuestNodeAction(
                UQuestStepGraphNode::StaticClass(),
                FText::FromString(TEXT("Quest Step Nodes")),
                FText::FromString(TEXT("New Quest Step node")),
                FText::FromString(TEXT("Makes a new quest step node")),
                0
            )
        );
    
        contextMenuBuilder.AddAction(newStepNodeAction);

        TSharedPtr<FNewQuestNodeAction> newQuestSucceededStepNodeAction(
            new FNewQuestNodeAction(
                UQuestStepGraphNode::StaticClass(),
                FText::FromString(TEXT("Quest Step Nodes")),
                FText::FromString(TEXT("New Quest Succeeded step node")),
                FText::FromString(TEXT("Makes a new quest succeeded step node")),
                0,
                nullptr,
                QUEST_SUCCEEDED
            )
        );
    
        contextMenuBuilder.AddAction(newQuestSucceededStepNodeAction);

        TSharedPtr<FNewQuestNodeAction> newQuestFailedStepNodeAction(
            new FNewQuestNodeAction(
                UQuestStepGraphNode::StaticClass(),
                FText::FromString(TEXT("Quest Step Nodes")),
                FText::FromString(TEXT("New Quest Failed step node")),
                FText::FromString(TEXT("Makes a new quest failed step node")),
                0,
                nullptr,
                QUEST_FAILED
            )
        );
    
        contextMenuBuilder.AddAction(newQuestFailedStepNodeAction);
    }

    // Work on comment in standby, so it is disabled.
    /*
    if(!draggedFromNode)
    {
        TSharedPtr<FNewCommentNodeAction> newCommentNodeAction(
            new FNewCommentNodeAction(
                FText::FromString(TEXT("Add a comment")),
                FText::FromString(TEXT("Add a comment node to the graph"))
            )
        );
        contextMenuBuilder.AddAction(newCommentNodeAction);
    }
    */
}

const FPinConnectionResponse UQuestGraphSchema::CanCreateConnection(const UEdGraphPin* a, const UEdGraphPin* b) const {
    if (a == nullptr || b == nullptr) {
        return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, TEXT("Need 2 pins"));
    }

    if (a->Direction == b->Direction) {
        return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, TEXT("Inputs can only connect to outputs"));
    }

    if(a->PinType.PinSubCategory.IsEqual(FName(QUEST_STEP_PIN_CATEGORY)))
    {
        if(b->PinType.PinSubCategory != QUEST_TASK_LIST_PIN_CATEGORY)
        {
            return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, TEXT("Quest Step node can only be connected to a Quest Task List node"));
        }
    }
    else if(a->PinType.PinSubCategory.IsEqual(FName(QUEST_TASK_LIST_PIN_CATEGORY)))
    {
        if(b->PinType.PinSubCategory != QUEST_STEP_PIN_CATEGORY)
        {
            return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, TEXT("Quest Task List node can only be connected to a Quest Step node"));
        }
    }
    else if(a->PinType.PinSubCategory.IsEqual(FName(QUEST_START_PIN_CATEGORY)))
    {
        if(b->PinType.PinSubCategory != QUEST_STEP_PIN_CATEGORY)
        {
            return FPinConnectionResponse(CONNECT_RESPONSE_DISALLOW, TEXT("Start node can only be connected to a Quest Step node"));
        }
    }

    //return FPinConnectionResponse(CONNECT_RESPONSE_MAKE/*CONNECT_RESPONSE_BREAK_OTHERS_AB*/, TEXT(""));
    return FPinConnectionResponse(CONNECT_RESPONSE_BREAK_OTHERS_A, TEXT(""));
}

void UQuestGraphSchema::CreateDefaultNodesForGraph(UEdGraph& graph) const {
    UQuestStartGraphNode* startNode = NewObject<UQuestStartGraphNode>(&graph);
    startNode->CreateNewGuid();
    startNode->NodePosX = 0;
    startNode->NodePosY = 0;

    UEdGraphPin * startNodeOutPin = startNode->CreateQuestPin(EEdGraphPinDirection::EGPD_Output, FName(TEXT("Start")));
    
    graph.AddNode(startNode, true, true);
    graph.Modify();
    
    UQuestStepGraphNode* firstStep = NewObject<UQuestStepGraphNode>(&graph);
    firstStep->CreateNewGuid();
    firstStep->NodePosX = 150;
    firstStep->NodePosY = 0;
    firstStep->InitNodeInfo(firstStep);

    UQuestStepNodeInfo * firstStepInfo = Cast<UQuestStepNodeInfo>(firstStep->GetNodeInfo());
    if(firstStepInfo)
    {
        firstStepInfo->ID = "QuestStart";
        firstStepInfo->Description = FText::FromString("This is the start of my Quest");
    }
    

    UEdGraphPin* inputPin = firstStep->CreateDefaultInputPin();
    firstStep->CreateDefaultOutputPins();

    if (startNodeOutPin != nullptr) {
        firstStep->GetSchema()->TryCreateConnection(startNodeOutPin, inputPin);
    }

    graph.Modify();
    graph.AddNode(firstStep, true, true);    
}

// TODO : Test this when found how to add commands to editor ...
void UQuestGraphSchema::DeleteSelectedNodes(UEdGraph* Graph)
{
    if (!Graph)
    {
        return;
    }

    const FGraphPanelSelectionSet SelectedNodes;// = //Graph->//GetSelectedNodes();

    Graph->Modify(); // Pour enregistrer les modifications

    for (UObject* NodeObject : SelectedNodes)
    {
        if (UEdGraphNode* Node = Cast<UEdGraphNode>(NodeObject))
        {
            Node->Modify(); // Support pour l'annulation
            Node->DestroyNode();
        }
    }
    //node->GetGraph()->RemoveNode(node);
}

UEdGraphNode* FNewQuestNodeAction::PerformAction(UEdGraph* parentGraph, UEdGraphPin* fromPin, const FVector2D location, bool bSelectNewNode) {
    UQuestGraphNodeBase* result = NewObject<UQuestGraphNodeBase>(parentGraph, _classTemplate);
    result->CreateNewGuid();
    result->NodePosX = location.X;
    result->NodePosY = location.Y;
    result->InitNodeInfo(result);
    result->UpdateIDToBeUnique();
    
    UEdGraphPin* inputPin = result->CreateDefaultInputPin();
    result->CreateDefaultOutputPins();

    if (fromPin != nullptr) {
        result->GetSchema()->TryCreateConnection(fromPin, inputPin);
    }

    if(AutoFillTaskClass != nullptr && result->GetNodeInfo()->IsA<UQuestTaskListNodeInfo>())
    {
        UQuestTaskListNodeInfo * nodeInfo = Cast<UQuestTaskListNodeInfo>(result->GetNodeInfo());
        UDialogueMasterTask * task = NewObject<UDialogueMasterTask>(nodeInfo, AutoFillTaskClass);
        nodeInfo->Tasks.Add(task);
    }

    if(AutoFillTaskClass == nullptr && result->GetNodeInfo()->IsA<UQuestStepNodeInfo>())
    {
        UQuestStepNodeInfo * nodeInfo = Cast<UQuestStepNodeInfo>(result->GetNodeInfo());
        nodeInfo->StepType = stepType;

        if(stepType == QUEST_SUCCEEDED || stepType == QUEST_FAILED)
        {
            nodeInfo->NodeOutputs.Empty();
            result->OnPropertiesChanged();
        }
    }
    
    parentGraph->Modify();
    parentGraph->AddNode(result, true, true);
    
    return result;
}


/*
 *  Create comment node action. TODO: Fix that...
 */
UEdGraphNode* FNewCommentNodeAction::PerformAction(UEdGraph* parentGraph, UEdGraphPin* fromPin,
    const FVector2D location, bool bSelectNewNode)
{
    // Get asset info from graph context menu builder object.
    UQuestAsset * asset = Cast<UQuestAsset>(parentGraph->GetTypedOuter(UQuestAsset::StaticClass()));
    UEdGraphNode_Comment * CommentNode = NewObject<UEdGraphNode_Comment>();
    QuestAssetEditorApp * editor = nullptr;
    FVector2D _location = location;
    
    if(asset != nullptr)
    {
        // Search the editor to get bounds of the selected nodes :
        UAssetEditorSubsystem* AssetEditorSubsystem = GEditor->GetEditorSubsystem<UAssetEditorSubsystem>();
        if(AssetEditorSubsystem != nullptr)
        {
            editor = static_cast<QuestAssetEditorApp*>(AssetEditorSubsystem->FindEditorForAsset(asset, false));
        }

        if(editor != nullptr)
        {
            FSlateRect bounds;
            if(editor->GetBoundsOfSelection(bounds, 50))
            {
                CommentNode->SetBounds(bounds);
                _location.X = CommentNode->NodePosX;
                _location.Y = CommentNode->NodePosY;
            }
            else
            {
                CommentNode->SetBounds(FSlateRect(_location.X, _location.Y, _location.X + 200, _location.Y + 100));
            }
        }
    }

    UEdGraphNode* NewNode = FEdGraphSchemaAction_NewNode::SpawnNodeFromTemplate<UEdGraphNode_Comment>(parentGraph, CommentNode, _location, bSelectNewNode);
    
    return NewNode;
}
