//! TypeScript Code Generation - Transpiles KAIN AST to strict TypeScript
//!
//! Goals vs JS backend:
//! - Strong static types for functions, structs, enums, and components
//! - Discriminated unions for enums with typed constructors
//! - Typed JSX/component interop for safer web output
//! - Emitted output is valid TypeScript (no runtime dependency)

use kain_core::ast::{
    BinaryOp, Block, ElseBranch, EnumVariantFields, Expr, Function, Impl, JSXAttrValue, JSXNode,
    Pattern, Stmt, Type, UnaryOp, VariantFields, VariantPatternFields,
};
use kain_core::error::KainResult;
use kain_core::types::{
    FloatSize, IntSize, ResolvedType, TypedComponent, TypedEnum, TypedFunction, TypedItem,
    TypedProgram, TypedStruct,
};
use kain_core::{
    lower_typed_program_memory_for_target, validate_typed_program_memory_support, CompileTarget,
};
use std::collections::HashSet;

/// Generate TypeScript source code from a typed program.
pub fn generate(program: &TypedProgram) -> KainResult<String> {
    let lowered = lower_typed_program_memory_for_target(program, CompileTarget::Ts)?;
    validate_typed_program_memory_support(&lowered, CompileTarget::Ts)?;
    let mut gen = TSGen::new();
    Ok(gen.gen_program(&lowered))
}

#[derive(Default)]
struct StringBuilder {
    lines: Vec<String>,
}

impl StringBuilder {
    fn push(&mut self, text: &str) {
        self.lines.push(text.to_string());
    }

    fn push_line(&mut self, text: &str) {
        self.lines.push(format!("{}\n", text));
    }

    fn build(self) -> String {
        self.lines.join("")
    }
}

struct TSGen {
    output: StringBuilder,
    indent: usize,
    /// Tracks type names already emitted to avoid duplicate class/interface declarations.
    seen_types: HashSet<String>,
    /// Whether JSX/DOM types are needed (set when a Component or JSX expr is encountered).
    needs_dom_types: bool,
}

impl TSGen {
    fn new() -> Self {
        Self {
            output: StringBuilder::default(),
            indent: 0,
            seen_types: HashSet::new(),
            needs_dom_types: false,
        }
    }

    fn indent(&mut self) {
        self.indent += 1;
    }

    fn dedent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }

    fn write(&mut self, text: &str) {
        self.output.push(text);
    }

    fn writeln(&mut self, text: &str) {
        let indent = "  ".repeat(self.indent);
        self.output.push_line(&format!("{}{}", indent, text));
    }

    fn gen_program(&mut self, program: &TypedProgram) -> String {
        // Pre-scan to detect if DOM/JSX types are needed
        for item in &program.items {
            if matches!(item, TypedItem::Component(_)) {
                self.needs_dom_types = true;
                break;
            }
        }

        self.writeln("// Generated by KAIN compiler");
        self.writeln("// Target: TypeScript (strict)");
        self.writeln("/* eslint-disable @typescript-eslint/no-explicit-any */");
        self.writeln("");

        // Numeric type helpers for type coercion
        self.writeln("// Numeric type helpers");
        self.writeln("function u8(n: number): number { return n & 0xFF; }");
        self.writeln("function u16(n: number): number { return n & 0xFFFF; }");
        self.writeln("function u32(n: number): number { return n >>> 0; }");
        self.writeln("function i8(n: number): number { return (n << 24) >> 24; }");
        self.writeln("function i16(n: number): number { return (n << 16) >> 16; }");
        self.writeln("function i32(n: number): number { return n | 0; }");
        self.writeln("function f32(n: number): number { return Math.fround(n); }");
        self.writeln("");

        self.writeln("// Low-level memory emulation runtime");
        self.writeln("type __KainPtrMeta = { kind: \"value\" } | { kind: \"field\"; base: number; field: string } | { kind: \"index\"; base: number; index: number };");
        self.writeln("const __kainMem = new Map<number, any>();");
        self.writeln("const __kainPtrMeta = new Map<number, __KainPtrMeta>();");
        self.writeln("let __kainNextPtr = 1;");
        self.writeln("function __kain_new_ptr(meta: __KainPtrMeta): number { const ptr = __kainNextPtr++; __kainPtrMeta.set(ptr, meta); return ptr; }");
        self.writeln("function __kain_clone_value<T>(value: T): T { if (Array.isArray(value)) { return value.map((item) => __kain_clone_value(item)) as T; } if (value && typeof value === \"object\") { return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k, v]) => [k, __kain_clone_value(v)])) as T; } return value; }");
        self.writeln("function __kain_addr_of<T>(value: T): number { const ptr = __kain_new_ptr({ kind: \"value\" }); __kainMem.set(ptr, value); return ptr; }");
        self.writeln(
            "function __kain_bind_local<T>(value: T): number { return __kain_addr_of(value); }",
        );
        self.writeln("function __kain_field_ptr(ptr: number, field: string, _offset: number): number { return __kain_new_ptr({ kind: \"field\", base: ptr, field }); }");
        self.writeln("function __kain_index_ptr(ptr: number, index: number, _stride: number): number { return __kain_new_ptr({ kind: \"index\", base: ptr, index }); }");
        self.writeln("function __kain_ptr_offset(ptr: number, offset: number, stride: number): number { return ptr + (offset * Math.max(stride, 1)); }");
        self.writeln("function __kain_mem_load<T>(ptr: number): T { const meta = __kainPtrMeta.get(ptr); if (!meta || meta.kind === \"value\") { return __kainMem.get(ptr) as T; } if (meta.kind === \"field\") { const base = __kain_mem_load<any>(meta.base); return base?.[meta.field] as T; } const base = __kain_mem_load<any>(meta.base); return base?.[meta.index] as T; }");
        self.writeln("function __kain_mem_store<T>(ptr: number, value: T): T { const meta = __kainPtrMeta.get(ptr); if (!meta || meta.kind === \"value\") { __kainMem.set(ptr, value); return value; } if (meta.kind === \"field\") { const base = __kain_mem_load<any>(meta.base); if (base != null) { base[meta.field] = value; } return value; } const base = __kain_mem_load<any>(meta.base); if (base != null) { base[meta.index] = value; } return value; }");
        self.writeln("function __kain_union_buffer(value: any, size: number): ArrayBuffer { if (!value || typeof value !== \"object\") { return new ArrayBuffer(Math.max(size, 1)); } if (!Object.prototype.hasOwnProperty.call(value, \"__kain_union_buffer\")) { Object.defineProperty(value, \"__kain_union_buffer\", { value: new ArrayBuffer(Math.max(size, 1)), writable: true, enumerable: false, configurable: true }); } const existing = value.__kain_union_buffer as ArrayBuffer; if (existing.byteLength < Math.max(size, 1)) { const next = new ArrayBuffer(Math.max(size, 1)); new Uint8Array(next).set(new Uint8Array(existing.slice(0))); Object.defineProperty(value, \"__kain_union_buffer\", { value: next, writable: true, enumerable: false, configurable: true }); return next; } return existing; }");
        self.writeln("function __kain_union_encode(view: DataView, typeKey: string, byteSize: number, value: any): void { switch (typeKey) { case \"Float\": if (byteSize >= 8) { view.setFloat64(0, Number(value ?? 0), true); } else { view.setFloat32(0, Number(value ?? 0), true); } break; case \"Bool\": view.setUint8(0, value ? 1 : 0); break; case \"Char\": view.setUint8(0, typeof value === \"string\" && value.length > 0 ? value.charCodeAt(0) & 0xFF : 0); break; default: if (byteSize >= 8) { view.setBigInt64(0, BigInt(Math.trunc(Number(value ?? 0))), true); } else if (byteSize >= 4) { view.setInt32(0, Number(value ?? 0), true); } else if (byteSize >= 2) { view.setInt16(0, Number(value ?? 0), true); } else { view.setInt8(0, Number(value ?? 0)); } break; } }");
        self.writeln("function __kain_union_decode(typeKey: string, byteSize: number, fallback: any, view: DataView): any { switch (typeKey) { case \"Float\": return byteSize >= 8 ? view.getFloat64(0, true) : view.getFloat32(0, true); case \"Bool\": return view.getUint8(0) !== 0; case \"Char\": return String.fromCharCode(view.getUint8(0)); default: if (byteSize >= 8) { return Number(view.getBigInt64(0, true)); } if (byteSize >= 4) { return view.getInt32(0, true); } if (byteSize >= 2) { return view.getInt16(0, true); } if (byteSize >= 1) { return view.getInt8(0); } return fallback; } }");
        self.writeln("function __kain_union_wrap<T extends object>(value: T, active: string, typeKey: string, byteSize: number, unionSize: number, activeValue: any): T { Object.defineProperty(value, \"__kain_union_active\", { value: active, writable: true, enumerable: false, configurable: true }); const buffer = __kain_union_buffer(value, unionSize); const view = new DataView(buffer); __kain_union_encode(view, typeKey, byteSize, activeValue); return value; }");
        self.writeln("function __kain_union_get<T>(value: any, field: string, typeKey: string, byteSize: number, unionSize: number, fallback: T): T { if (value == null) { return fallback; } if (value.__kain_union_active === field) { return value[field] as T; } const buffer = __kain_union_buffer(value, unionSize); const next = __kain_union_decode(typeKey, byteSize, fallback, new DataView(buffer)) as T; value[field] = next; return next; }");
        self.writeln("function __kain_union_set<T>(value: any, field: string, typeKey: string, byteSize: number, unionSize: number, next: T): T { if (value != null) { const buffer = __kain_union_buffer(value, unionSize); __kain_union_encode(new DataView(buffer), typeKey, byteSize, next); value[field] = next; Object.defineProperty(value, \"__kain_union_active\", { value: field, writable: true, enumerable: false, configurable: true }); } return next; }");
        self.writeln("function __kain_bitfield_units(value: any): Record<string, number> { if (value == null) { return {}; } if (!Object.prototype.hasOwnProperty.call(value, \"__kain_bitfield_units\")) { Object.defineProperty(value, \"__kain_bitfield_units\", { value: {}, writable: true, enumerable: false, configurable: true }); } return value.__kain_bitfield_units as Record<string, number>; }");
        self.writeln("function __kain_bitfield_get(value: any, field: string, unitOffset: number, bitOffset: number, width: number, signed: boolean): number { if (value == null) { return 0; } const units = __kain_bitfield_units(value) as Record<string, bigint>; const key = String(unitOffset); const unit = BigInt(units[key] ?? 0n); const safeWidth = BigInt(Math.max(width, 0)); const shift = BigInt(Math.max(bitOffset, 0)); const mask = safeWidth === 0n ? 0n : ((1n << safeWidth) - 1n); let next = Number((unit >> shift) & mask); if (signed && width > 0) { const signBit = 1n << BigInt(width - 1); let signedValue = (unit >> shift) & mask; if ((signedValue & signBit) !== 0n) { signedValue -= (1n << BigInt(width)); } next = Number(signedValue); } value[field] = next; return next; }");
        self.writeln("function __kain_bitfield_set(value: any, field: string, unitOffset: number, bitOffset: number, width: number, signed: boolean, next: number): number { if (value == null) { return next; } const units = __kain_bitfield_units(value) as Record<string, bigint>; const key = String(unitOffset); const unit = BigInt(units[key] ?? 0n); const safeWidth = BigInt(Math.max(width, 0)); const shift = BigInt(Math.max(bitOffset, 0)); const mask = safeWidth === 0n ? 0n : ((1n << safeWidth) - 1n); let encoded = BigInt(Math.trunc(Number(next))); if (safeWidth > 0n) { encoded &= mask; } const cleared = unit & ~(mask << shift); units[key] = cleared | ((encoded & mask) << shift); const normalized = __kain_bitfield_get(value, field, unitOffset, bitOffset, width, signed); return normalized; }");
        self.writeln("function __kain_alloc(size: number, stride: number, _zeroed: boolean, seed: any): number { const step = Math.max(stride, 1); const count = Math.max(1, Math.ceil(Math.max(size, step) / step)); const base = __kainNextPtr; for (let i = 0; i < count; i++) { __kainMem.set(base + (i * step), __kain_clone_value(seed)); } __kainNextPtr = base + (count * step); return base; }");
        self.writeln("function __kain_realloc(ptr: number, size: number, stride: number, seed: any): number { if (!ptr) { return __kain_alloc(size, stride, false, seed); } const step = Math.max(stride, 1); const count = Math.max(1, Math.ceil(Math.max(size, step) / step)); for (let i = 0; i < count; i++) { const nextPtr = ptr + (i * step); if (!__kainMem.has(nextPtr)) { __kainMem.set(nextPtr, __kain_clone_value(seed)); } } return ptr; }");
        self.writeln("");

        // Only emit DOM type alias when JSX/components are actually used
        if self.needs_dom_types {
            self.writeln("type KainNode = Node | DocumentFragment;");
            self.writeln("");
        }

        for item in &program.items {
            match item {
                TypedItem::Function(f) => self.gen_typed_function(f),
                TypedItem::Struct(s) => self.gen_typed_struct(s),
                TypedItem::Enum(e) => self.gen_typed_enum(e),
                TypedItem::Component(c) => {
                    self.needs_dom_types = true;
                    self.gen_typed_component(c);
                }
                TypedItem::Const(c) => self.gen_const(&c.ast.name, Some(&c.ast.ty), &c.ast.value),
                TypedItem::Impl(i) => self.gen_impl(&i.ast),
                _ => {}
            }
            self.writeln("");
        }

        std::mem::take(&mut self.output).build()
    }

    fn gen_typed_function(&mut self, func: &TypedFunction) {
        let params = func
            .ast
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, self.type_to_ts(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");

        let ret = self.function_return_ts(func);
        self.writeln(&format!(
            "export function {}({}): {} {{",
            func.ast.name, params, ret
        ));
        self.indent();
        self.gen_block(&func.ast.body);
        self.dedent();
        self.writeln("}");
    }

    fn gen_typed_struct(&mut self, s: &TypedStruct) {
        // Skip duplicate type declarations (common with multi-module C imports)
        if self.seen_types.contains(&s.ast.name) {
            return;
        }
        self.seen_types.insert(s.ast.name.clone());

        // Empty structs (opaque C types) → compact type alias
        if s.ast.fields.is_empty() {
            self.writeln(&format!(
                "export type {} = Record<string, unknown>;",
                s.ast.name
            ));
            return;
        }

        self.writeln(&format!("export interface {}Shape {{", s.ast.name));
        self.indent();
        for field in &s.ast.fields {
            let ty = self.type_to_ts(&field.ty);
            self.writeln(&format!("{}: {};", field.name, ty));
        }
        self.dedent();
        self.writeln("}");

        self.writeln(&format!(
            "export class {} implements {}Shape {{",
            s.ast.name, s.ast.name
        ));
        self.indent();

        for field in &s.ast.fields {
            let ty = self.type_to_ts(&field.ty);
            self.writeln(&format!("{}: {};", field.name, ty));
        }
        self.writeln("");

        let ctor_params = s
            .ast
            .fields
            .iter()
            .map(|f| format!("{}: {}", f.name, self.type_to_ts(&f.ty)))
            .collect::<Vec<_>>()
            .join(", ");

        let ctor_defaults = s
            .ast
            .fields
            .iter()
            .map(|f| {
                let ty = self.type_to_ts(&f.ty);
                let default = if ty == "number" {
                    "0".to_string()
                } else if ty == "boolean" {
                    "false".to_string()
                } else if ty == "string" {
                    "\"\"".to_string()
                } else {
                    "null as any".to_string()
                };
                format!("{}: {} = {}", f.name, ty, default)
            })
            .collect::<Vec<_>>()
            .join(", ");
        let _ = ctor_params; // use defaulted version

        self.writeln(&format!("constructor({}) {{", ctor_defaults));
        self.indent();
        for field in &s.ast.fields {
            self.writeln(&format!("this.{} = {};", field.name, field.name));
        }
        self.dedent();
        self.writeln("}");

        self.dedent();
        self.writeln("}");
    }

    fn gen_typed_enum(&mut self, e: &TypedEnum) {
        // Skip duplicate type declarations
        if self.seen_types.contains(&e.ast.name) {
            return;
        }
        self.seen_types.insert(e.ast.name.clone());

        let mut union_members = Vec::new();

        for variant in &e.ast.variants {
            match &variant.fields {
                VariantFields::Unit => {
                    union_members.push(format!(
                        "{{ type: '{}'; tag: '{}' }}",
                        e.ast.name, variant.name
                    ));
                }
                VariantFields::Tuple(types) => {
                    let fields = types
                        .iter()
                        .enumerate()
                        .map(|(i, ty)| format!("_{}: {}", i, self.type_to_ts(ty)))
                        .collect::<Vec<_>>()
                        .join("; ");
                    union_members.push(format!(
                        "{{ type: '{}'; tag: '{}'; {} }}",
                        e.ast.name, variant.name, fields
                    ));
                }
                VariantFields::Struct(fields) => {
                    let payload = fields
                        .iter()
                        .map(|f| format!("{}: {}", f.name, self.type_to_ts(&f.ty)))
                        .collect::<Vec<_>>()
                        .join("; ");
                    union_members.push(format!(
                        "{{ type: '{}'; tag: '{}'; {} }}",
                        e.ast.name, variant.name, payload
                    ));
                }
            }
        }

        if union_members.is_empty() {
            self.writeln(&format!("export type {} = never;", e.ast.name));
        } else {
            self.writeln(&format!("export type {} =", e.ast.name));
            self.indent();
            for (i, member) in union_members.iter().enumerate() {
                if i + 1 == union_members.len() {
                    self.writeln(&format!("| {};", member));
                } else {
                    self.writeln(&format!("| {}", member));
                }
            }
            self.dedent();
        }

        self.writeln(&format!("export const {} = {{", e.ast.name));
        self.indent();
        for variant in &e.ast.variants {
            match &variant.fields {
                VariantFields::Unit => {
                    self.writeln(&format!(
                        "{}: (): {} => ({{ type: '{}', tag: '{}' }}),",
                        variant.name, e.ast.name, e.ast.name, variant.name
                    ));
                }
                VariantFields::Tuple(types) => {
                    let params = types
                        .iter()
                        .enumerate()
                        .map(|(i, ty)| format!("_{}: {}", i, self.type_to_ts(ty)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.writeln(&format!(
                        "{}: ({}) : {} => ({{",
                        variant.name, params, e.ast.name
                    ));
                    self.indent();
                    self.writeln(&format!("type: '{}',", e.ast.name));
                    self.writeln(&format!("tag: '{}',", variant.name));
                    for i in 0..types.len() {
                        self.writeln(&format!("_{}: _{},", i, i));
                    }
                    self.dedent();
                    self.writeln("}),");
                }
                VariantFields::Struct(fields) => {
                    let params = fields
                        .iter()
                        .map(|f| format!("{}: {}", f.name, self.type_to_ts(&f.ty)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    self.writeln(&format!(
                        "{}: ({}) : {} => ({{",
                        variant.name, params, e.ast.name
                    ));
                    self.indent();
                    self.writeln(&format!("type: '{}',", e.ast.name));
                    self.writeln(&format!("tag: '{}',", variant.name));
                    for field in fields {
                        self.writeln(&format!("{}: {},", field.name, field.name));
                    }
                    self.dedent();
                    self.writeln("}),");
                }
            }
        }
        self.dedent();
        self.writeln("} as const;");
    }

    fn gen_typed_component(&mut self, comp: &TypedComponent) {
        let props_name = format!("{}Props", comp.ast.name);

        self.writeln(&format!("export interface {} {{", props_name));
        self.indent();
        for prop in &comp.ast.props {
            self.writeln(&format!("{}: {};", prop.name, self.type_to_ts(&prop.ty)));
        }
        self.writeln("children?: KainNode[];");
        self.dedent();
        self.writeln("}");

        self.writeln(&format!(
            "export function {}(props: {}): KainNode {{",
            comp.ast.name, props_name
        ));
        self.indent();

        // Destructure props including children
        if !comp.ast.props.is_empty() {
            let names = comp
                .ast
                .props
                .iter()
                .map(|p| p.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            self.writeln(&format!("const {{ {}, children = [] }} = props;", names));
        } else {
            self.writeln("const { children = [] } = props;");
        }

        for state in &comp.ast.state {
            self.write(&format!(
                "let {}: {} = ",
                state.name,
                self.type_to_ts(&state.ty)
            ));
            self.gen_expr(&state.initial);
            self.writeln(";");
        }

        for method in &comp.ast.methods {
            self.gen_function(method);
        }

        self.write("return ");
        self.gen_jsx(&comp.ast.body);
        self.writeln(";");

        self.dedent();
        self.writeln("}");
    }

    fn gen_function(&mut self, func: &Function) {
        let params = func
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, self.type_to_ts(&p.ty)))
            .collect::<Vec<_>>()
            .join(", ");

        let ret = func
            .return_type
            .as_ref()
            .map(|t| self.type_to_ts(t))
            .unwrap_or_else(|| "void".to_string());

        self.writeln(&format!("function {}({}): {} {{", func.name, params, ret));
        self.indent();
        self.gen_block(&func.body);
        self.dedent();
        self.writeln("}");
    }

    fn gen_const(&mut self, name: &str, ty: Option<&Type>, value: &Expr) {
        if let Some(ty) = ty {
            self.write(&format!(
                "export const {}: {} = ",
                name,
                self.type_to_ts(ty)
            ));
        } else {
            self.write(&format!("export const {} = ", name));
        }
        self.gen_expr(value);
        self.writeln(";");
    }

    fn gen_impl(&mut self, impl_block: &Impl) {
        if let Type::Named { name, .. } = &impl_block.target_type {
            for method in &impl_block.methods {
                let has_self = method
                    .params
                    .first()
                    .map(|p| p.name == "self")
                    .unwrap_or(false);

                let params = method
                    .params
                    .iter()
                    .skip(if has_self { 1 } else { 0 })
                    .map(|p| format!("{}: {}", p.name, self.type_to_ts(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(", ");

                let ret = method
                    .return_type
                    .as_ref()
                    .map(|t| self.type_to_ts(t))
                    .unwrap_or_else(|| "void".to_string());

                if has_self {
                    self.writeln(&format!(
                        "{}.prototype.{} = function({}): {} {{",
                        name, method.name, params, ret
                    ));
                } else {
                    self.writeln(&format!(
                        "{}.{} = function({}): {} {{",
                        name, method.name, params, ret
                    ));
                }

                self.indent();
                self.gen_block(&method.body);
                self.dedent();
                self.writeln("};");
            }
        }
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }
    }

    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Expr(expr) => {
                self.gen_expr(expr);
                self.writeln(";");
            }
            Stmt::Let {
                pattern, ty, value, ..
            } => {
                if let Pattern::Binding { name, .. } = pattern {
                    self.write(&format!("let {}", name));
                    if let Some(t) = ty {
                        self.write(&format!(": {}", self.type_to_ts(t)));
                    }
                    self.write(" = ");
                    if let Some(v) = value {
                        self.gen_expr(v);
                    } else {
                        self.write("null");
                    }
                    self.writeln(";");
                }
            }
            Stmt::Return(expr, _) => {
                self.write("return");
                if let Some(e) = expr {
                    self.write(" ");
                    self.gen_expr(e);
                }
                self.writeln(";");
            }
            Stmt::For {
                binding,
                iter,
                body,
                ..
            } => {
                if let Pattern::Binding { name, .. } = binding {
                    self.write(&format!("for (const {} of ", name));
                    self.gen_expr(iter);
                    self.writeln(") {");
                    self.indent();
                    self.gen_block(body);
                    self.dedent();
                    self.writeln("}");
                }
            }
            Stmt::While {
                condition, body, ..
            } => {
                self.write("while (");
                self.gen_expr(condition);
                self.writeln(") {");
                self.indent();
                self.gen_block(body);
                self.dedent();
                self.writeln("}");
            }
            Stmt::Loop { body, .. } => {
                self.writeln("while (true) {");
                self.indent();
                self.gen_block(body);
                self.dedent();
                self.writeln("}");
            }
            Stmt::Break(expr, _) => {
                if expr.is_some() {
                    self.writeln("// break with value is not representable in TypeScript");
                }
                self.writeln("break;");
            }
            Stmt::Continue(_) => {
                self.writeln("continue;");
            }
            // If is not a Stmt variant — it's Stmt::Expr(Expr::If{..})
            // This arm is unreachable but kept as dead code guard
            Stmt::Expr(Expr::If {
                condition,
                then_branch,
                else_branch,
                ..
            }) if false => {
                self.write("if (");
                self.gen_expr(condition);
                self.writeln(") {");
                self.indent();
                self.gen_block(then_branch);
                self.dedent();
                let mut cur = else_branch.as_ref();
                while let Some(branch) = cur {
                    match branch.as_ref() {
                        ElseBranch::Else(b) => {
                            self.writeln("} else {");
                            self.indent();
                            self.gen_block(b);
                            self.dedent();
                            cur = None;
                        }
                        ElseBranch::ElseIf(cond, body, next) => {
                            self.write("} else if (");
                            self.gen_expr(cond);
                            self.writeln(") {");
                            self.indent();
                            self.gen_block(body);
                            self.dedent();
                            cur = next.as_ref();
                        }
                    }
                }
                self.writeln("}");
            }
            Stmt::Item(_) => {
                // Nested item definitions inside a function body — skip at stmt level
                // (they are hoisted to module scope by the type checker)
            }
            _ => {
                self.writeln("// Unsupported statement");
            }
        }
    }

    fn gen_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::Int(n, _) => self.write(&n.to_string()),
            Expr::Float(f, _) => self.write(&f.to_string()),
            Expr::String(s, _) => {
                // Proper JavaScript string escaping (not Rust's escape_default)
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                self.write(&format!("\"{}\"", escaped))
            }
            Expr::Bool(b, _) => self.write(if *b { "true" } else { "false" }),
            Expr::None(_) => self.write("null"),
            Expr::Ident(name, _) => self.write(name),

            Expr::Binary {
                left, op, right, ..
            } => {
                self.write("(");
                self.gen_expr(left);
                self.write(&format!(" {} ", self.gen_binop(*op)));
                self.gen_expr(right);
                self.write(")");
            }

            Expr::Unary { op, operand, .. } => {
                self.write(&format!("({}", self.gen_unop(*op)));
                self.gen_expr(operand);
                self.write(")");
            }

            Expr::Ref { value, .. } => {
                // JS/TS has no address/reference operator; pass through value.
                self.gen_expr(value);
            }

            Expr::Deref(inner, _) => {
                // JS/TS has no pointer model; treat deref as transparent value access.
                self.gen_expr(inner);
            }

            Expr::PtrOffset { pointer, .. } => {
                // Raw pointer arithmetic is rejected before TS codegen; keep fallback transparent.
                self.gen_expr(pointer);
            }

            Expr::Call { callee, args, .. } => {
                self.gen_expr(callee);
                self.write("(");
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(&arg.value);
                }
                self.write(")");
            }

            Expr::Array(elements, _) | Expr::Tuple(elements, _) => {
                self.write("[");
                for (i, elem) in elements.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(elem);
                }
                self.write("]");
            }

            Expr::Index { object, index, .. } => {
                self.gen_expr(object);
                self.write("[");
                self.gen_expr(index);
                self.write("]");
            }

            Expr::Field { object, field, .. } => {
                self.gen_expr(object);
                self.write(&format!(".{}", field));
            }

            Expr::MethodCall {
                receiver,
                method,
                args,
                ..
            } => {
                // Special handling for array methods - translate to JavaScript equivalents
                match method.as_str() {
                    "len" => {
                        self.gen_expr(receiver);
                        self.write(".length");
                        return;
                    }
                    "is_empty" => {
                        self.gen_expr(receiver);
                        self.write(".length === 0");
                        return;
                    }
                    "first" => {
                        self.gen_expr(receiver);
                        self.write("[0]");
                        return;
                    }
                    "last" => {
                        self.write("(() => { const __arr = ");
                        self.gen_expr(receiver);
                        self.write("; return __arr[__arr.length - 1]; })()");
                        return;
                    }
                    "contains" => {
                        self.gen_expr(receiver);
                        self.write(".includes(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "push" => {
                        self.gen_expr(receiver);
                        self.write(".push(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "pop" => {
                        self.gen_expr(receiver);
                        self.write(".pop()");
                        return;
                    }
                    "clear" => {
                        self.gen_expr(receiver);
                        self.write(".length = 0");
                        return;
                    }
                    "to_string" | "to_owned" => {
                        self.write("String(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "to_uppercase" => {
                        self.gen_expr(receiver);
                        self.write(".toUpperCase()");
                        return;
                    }
                    "to_lowercase" => {
                        self.gen_expr(receiver);
                        self.write(".toLowerCase()");
                        return;
                    }
                    "trim" => {
                        self.gen_expr(receiver);
                        self.write(".trim()");
                        return;
                    }
                    "split" => {
                        self.gen_expr(receiver);
                        self.write(".split(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "join" => {
                        self.gen_expr(receiver);
                        self.write(".join(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "starts_with" => {
                        self.gen_expr(receiver);
                        self.write(".startsWith(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "ends_with" => {
                        self.gen_expr(receiver);
                        self.write(".endsWith(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "replace" => {
                        self.gen_expr(receiver);
                        self.write(".replaceAll(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "chars" | "bytes" => {
                        self.write("Array.from(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "map" => {
                        self.gen_expr(receiver);
                        self.write(".map(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "filter" => {
                        self.gen_expr(receiver);
                        self.write(".filter(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "filter_map" => {
                        self.gen_expr(receiver);
                        self.write(".flatMap(__x => { const __v = (");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")(__x); return __v != null ? [__v] : []; })");
                        return;
                    }
                    "reduce" | "fold" => {
                        self.gen_expr(receiver);
                        self.write(".reduce(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "find" => {
                        self.gen_expr(receiver);
                        self.write(".find(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(") ?? null");
                        return;
                    }
                    "any" => {
                        self.gen_expr(receiver);
                        self.write(".some(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "all" => {
                        self.gen_expr(receiver);
                        self.write(".every(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "enumerate" => {
                        self.gen_expr(receiver);
                        self.write(".map((__v, __i) => [__i, __v] as [number, typeof __v])");
                        return;
                    }
                    "zip" => {
                        self.write("(() => { const __a = ");
                        self.gen_expr(receiver);
                        self.write("; const __b = ");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write("; return __a.map((__v, __i) => [__v, __b[__i]]); })()");
                        return;
                    }
                    "flat_map" | "flatten" => {
                        self.gen_expr(receiver);
                        self.write(".flat()");
                        return;
                    }
                    "clamp" => {
                        self.write("Math.min(Math.max(");
                        self.gen_expr(receiver);
                        if let Some(min_arg) = args.first() {
                            self.write(", ");
                            self.gen_expr(&min_arg.value);
                        }
                        self.write("), ");
                        if let Some(max_arg) = args.get(1) {
                            self.gen_expr(&max_arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "abs" => {
                        self.write("Math.abs(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "sqrt" => {
                        self.write("Math.sqrt(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "floor" => {
                        self.write("Math.floor(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "ceil" => {
                        self.write("Math.ceil(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "round" => {
                        self.write("Math.round(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "min" => {
                        self.write("Math.min(");
                        self.gen_expr(receiver);
                        if let Some(arg) = args.first() {
                            self.write(", ");
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "max" => {
                        self.write("Math.max(");
                        self.gen_expr(receiver);
                        if let Some(arg) = args.first() {
                            self.write(", ");
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "unwrap" | "unwrap_or_default" => {
                        self.write("((");
                        self.gen_expr(receiver);
                        self.write(
                            ") ?? (() => { throw new Error('KAIN: unwrap on null/None'); })())",
                        );
                        return;
                    }
                    "unwrap_or" => {
                        self.write("((");
                        self.gen_expr(receiver);
                        self.write(") ?? ");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "ok" => {
                        // Option.ok() → wrap in result-like
                        self.write("(({ ok: true, value: ");
                        self.gen_expr(receiver);
                        self.write(" }))");
                        return;
                    }
                    "is_some" | "is_ok" => {
                        self.write("((");
                        self.gen_expr(receiver);
                        self.write(") != null)");
                        return;
                    }
                    "is_none" | "is_err" => {
                        self.write("((");
                        self.gen_expr(receiver);
                        self.write(") == null)");
                        return;
                    }
                    "sort" => {
                        self.write("[...");
                        self.gen_expr(receiver);
                        self.write("].sort()");
                        return;
                    }
                    "sort_by" => {
                        self.write("[...");
                        self.gen_expr(receiver);
                        self.write("].sort(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "reverse" => {
                        self.write("[...");
                        self.gen_expr(receiver);
                        self.write("].reverse()");
                        return;
                    }
                    "collect" => {
                        // In KAIN context, collect() just returns the iterator as an array
                        self.write("Array.from(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    "iter" | "into_iter" | "iter_mut" => {
                        // Iterators are just arrays in TS
                        self.gen_expr(receiver);
                        return;
                    }
                    "clone" | "to_vec" => {
                        self.write("[...");
                        self.gen_expr(receiver);
                        self.write("]");
                        return;
                    }
                    "get" => {
                        self.gen_expr(receiver);
                        self.write("[");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write("] ?? null");
                        return;
                    }
                    "insert" => {
                        // Map/Set insert — emit as assignment
                        self.gen_expr(receiver);
                        self.write(".set(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "remove" => {
                        self.gen_expr(receiver);
                        self.write(".delete(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "keys" => {
                        self.write("Array.from((");
                        self.gen_expr(receiver);
                        self.write(").keys())");
                        return;
                    }
                    "values" => {
                        self.write("Array.from((");
                        self.gen_expr(receiver);
                        self.write(").values())");
                        return;
                    }
                    "entries" => {
                        self.write("Array.from((");
                        self.gen_expr(receiver);
                        self.write(").entries())");
                        return;
                    }
                    "extend" => {
                        self.gen_expr(receiver);
                        self.write(".push(...");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write(")");
                        return;
                    }
                    "retain" => {
                        // arr.retain(|x| cond) → arr = arr.filter(cond)
                        self.write("(() => { const __recv = ");
                        self.gen_expr(receiver);
                        self.write("; const __kept = __recv.filter(");
                        if let Some(arg) = args.first() {
                            self.gen_expr(&arg.value);
                        }
                        self.write("); __recv.length = 0; __recv.push(...__kept); })()");
                        return;
                    }
                    "parse" => {
                        self.write("Number(");
                        self.gen_expr(receiver);
                        self.write(")");
                        return;
                    }
                    _ => {}
                }

                // Default method call handling
                self.gen_expr(receiver);
                self.write(&format!(".{}(", method));
                for (i, arg) in args.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(&arg.value);
                }
                self.write(")");
            }

            Expr::Struct { name, fields, .. } => {
                self.write(&format!("new {}(", name));
                for (i, (_, value)) in fields.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(value);
                }
                self.write(")");
            }

            Expr::If {
                condition,
                then_branch,
                else_branch,
                ..
            } => {
                // Emit as an IIFE so else-if chains and blocks work correctly
                self.write("(() => { if (");
                self.gen_expr(condition);
                self.write(") { return ");
                self.gen_block_as_expr(then_branch);
                self.write("; }");
                let mut current_else = else_branch.as_ref();
                while let Some(branch) = current_else {
                    match branch.as_ref() {
                        ElseBranch::Else(b) => {
                            self.write(" else { return ");
                            self.gen_block_as_expr(b);
                            self.write("; }");
                            current_else = None;
                        }
                        ElseBranch::ElseIf(cond, body, next) => {
                            self.write(" else if (");
                            self.gen_expr(cond);
                            self.write(") { return ");
                            self.gen_block_as_expr(body);
                            self.write("; }");
                            current_else = next.as_ref();
                        }
                    }
                }
                self.write(" return undefined; })()");
            }

            Expr::Match {
                scrutinee, arms, ..
            } => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.write("const __match = ");
                self.gen_expr(scrutinee);
                self.writeln(";");

                for (i, arm) in arms.iter().enumerate() {
                    if i == 0 {
                        self.write("if (");
                    } else {
                        self.write("else if (");
                    }
                    self.gen_pattern_match("__match", &arm.pattern);
                    self.writeln(") {");
                    self.indent();
                    self.gen_pattern_bindings("__match", &arm.pattern);
                    self.write("return ");
                    self.gen_expr(&arm.body);
                    self.writeln(";");
                    self.dedent();
                    self.write("} ");
                }
                self.writeln("");
                self.writeln("throw new Error('Non-exhaustive match');");
                self.dedent();
                self.write("})()");
            }

            Expr::Lambda { params, body, .. } => {
                let params = params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, self.type_to_ts(&p.ty)))
                    .collect::<Vec<_>>()
                    .join(", ");
                self.write(&format!("({}) => ", params));
                self.gen_expr(body);
            }

            Expr::Block(block, _) => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.gen_block(block);
                self.dedent();
                self.write("})()");
            }

            Expr::Assign { target, value, .. } => {
                self.gen_expr(target);
                self.write(" = ");
                self.gen_expr(value);
            }

            Expr::FString(parts, _) => {
                self.write("`");
                for part in parts {
                    match part {
                        Expr::String(s, _) => self.write(s),
                        _ => {
                            self.write("${");
                            self.gen_expr(part);
                            self.write("}");
                        }
                    }
                }
                self.write("`");
            }

            Expr::JSX(node, _) => self.gen_jsx(node),

            Expr::EnumVariant {
                enum_name,
                variant,
                fields,
                ..
            } => {
                self.write(&format!("{}.{}(", enum_name, variant));
                match fields {
                    EnumVariantFields::Unit => {}
                    EnumVariantFields::Tuple(exprs) => {
                        for (i, expr) in exprs.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(expr);
                        }
                    }
                    EnumVariantFields::Struct(named) => {
                        for (i, (_, expr)) in named.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(expr);
                        }
                    }
                }
                self.write(")");
            }

            // --- Parenthesized expressions ---
            Expr::Paren(inner, _) => {
                self.write("(");
                self.gen_expr(inner);
                self.write(")");
            }

            // --- Type cast: emit as value (TS handles types structurally) ---
            Expr::Cast { value, target, .. } => {
                self.write("(");
                self.gen_expr(value);
                self.write(" as unknown as ");
                self.write(&self.type_to_ts(target).clone());
                self.write(")");
            }

            // --- Error propagation: unwrap to throw in TS ---
            Expr::Try(inner, _) => {
                self.write("(() => { const __r = ");
                self.gen_expr(inner);
                self.write("; if (__r && __r.ok === false) throw __r.error; return __r && 'value' in __r ? __r.value : __r; })()");
            }

            // --- Async/await ---
            Expr::Await(inner, _) => {
                self.write("await ");
                self.gen_expr(inner);
            }

            // --- Range: emit as a lazy iterator helper ---
            Expr::Range {
                start,
                end,
                inclusive,
                ..
            } => {
                self.write("((__s, __e) => { const __a: number[] = []; for (let __i = __s; __i ");
                self.write(if *inclusive { "<= __e" } else { "< __e" });
                self.write("; __i++) __a.push(__i); return __a; })(");
                if let Some(s) = start {
                    self.gen_expr(s);
                } else {
                    self.write("0");
                }
                self.write(", ");
                if let Some(e) = end {
                    self.gen_expr(e);
                } else {
                    self.write("0");
                }
                self.write(")");
            }

            // --- Comptime: evaluate inline (values already folded by the time we codegen) ---
            Expr::Comptime(inner, _) => {
                self.gen_expr(inner);
            }

            // --- Return/Break/Continue as expressions (rare but valid in some positions) ---
            Expr::Return(Some(val), _) => {
                self.write("(() => { return ");
                self.gen_expr(val);
                self.write("; })()");
            }
            Expr::Return(None, _) => {
                self.write("(() => { return undefined; })()");
            }
            Expr::Break(Some(val), _) => {
                self.write("(() => { ");
                self.gen_expr(val);
                self.write("; })()");
            }
            Expr::Break(None, _) => self.write("undefined"),
            Expr::Continue(_) => self.write("undefined"),

            // --- Actor spawn: create an object representing the actor ---
            Expr::Spawn { actor, init, .. } => {
                self.write(&format!("new {}(", actor));
                for (i, (_, expr)) in init.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(expr);
                }
                self.write(")");
            }

            // --- Message send: emit as a method call convention ---
            Expr::SendMsg {
                target,
                message,
                data,
                ..
            } => {
                self.gen_expr(target);
                self.write(&format!(".{}(", message));
                for (i, (_, expr)) in data.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.gen_expr(expr);
                }
                self.write(")");
            }

            // --- Macro calls: translate common macros to JS equivalents ---
            Expr::MacroCall { name, args, .. } => {
                match name.as_str() {
                    "print" | "println" | "eprintln" => {
                        self.write("console.log(");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            match arg {
                                e => self.gen_expr(e),
                            }
                        }
                        self.write(")");
                    }
                    "assert" | "assert_eq" | "assert_ne" => {
                        self.write("(() => { const __ok = ");
                        if let Some(e) = args.first() {
                            self.gen_expr(e);
                        } else {
                            self.write("true");
                        }
                        self.write(&format!(
                            "; if (!__ok) throw new Error('KAIN assert failed: {}'); }})()",
                            name
                        ));
                    }
                    "vec" | "array" => {
                        self.write("[");
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.write("]");
                    }
                    "format" | "concat" => {
                        // Treat first arg as a template string base
                        self.write("`");
                        for arg in args {
                            self.write("${");
                            self.gen_expr(arg);
                            self.write("}");
                        }
                        self.write("`");
                    }
                    "todo" => {
                        self.write("(() => { throw new Error('TODO: not yet implemented'); })()")
                    }
                    "unreachable" => self
                        .write("(() => { throw new Error('KAIN: unreachable code reached'); })()"),
                    "panic" => {
                        self.write("(() => { throw new Error(");
                        if let Some(e) = args.first() {
                            self.gen_expr(e);
                        } else {
                            self.write("'panic'");
                        }
                        self.write("); })()");
                    }
                    _ => {
                        // Unknown macro: emit as a function call
                        self.write(&format!("{}__macro(", name));
                        for (i, arg) in args.iter().enumerate() {
                            if i > 0 {
                                self.write(", ");
                            }
                            self.gen_expr(arg);
                        }
                        self.write(")");
                    }
                }
            }

            _ => self.write("/* unsupported expr */"),
        }
    }

    fn gen_jsx(&mut self, node: &JSXNode) {
        match node {
            JSXNode::Element {
                tag,
                attributes,
                children,
                ..
            } => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.writeln(&format!("const __el = document.createElement('{}');", tag));

                for attr in attributes {
                    match &attr.value {
                        JSXAttrValue::String(s) => {
                            if attr.name == "class" {
                                self.writeln(&format!("__el.className = '{}';", s));
                            } else {
                                self.writeln(&format!(
                                    "__el.setAttribute('{}', '{}');",
                                    attr.name, s
                                ));
                            }
                        }
                        JSXAttrValue::Bool(b) => {
                            if *b {
                                self.writeln(&format!("__el.setAttribute('{}', '');", attr.name));
                            }
                        }
                        JSXAttrValue::Expr(expr) => {
                            if attr.name.starts_with("on_") {
                                let event = attr.name.trim_start_matches("on_");
                                self.write(&format!("__el.addEventListener('{}', ", event));
                                self.gen_expr(expr);
                                self.writeln(" as EventListener);");
                            } else if attr.name == "class" {
                                self.write("__el.className = String(");
                                self.gen_expr(expr);
                                self.writeln(");");
                            } else {
                                self.write(&format!("__el.setAttribute('{}', String(", attr.name));
                                self.gen_expr(expr);
                                self.writeln("));");
                            }
                        }
                    }
                }

                for child in children {
                    self.write("__el.appendChild(");
                    self.gen_jsx(child);
                    self.writeln(");");
                }

                self.writeln("return __el;");
                self.dedent();
                self.write("})()");
            }
            JSXNode::Text(text, _) => {
                // Proper JavaScript single-quote escaping for text nodes
                let escaped = text.replace('\\', "\\\\").replace('\'', "\\'");
                self.write(&format!("document.createTextNode('{}')", escaped))
            }
            JSXNode::Expression(expr) => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.write("const __val = ");
                self.gen_expr(expr);
                self.writeln(";");
                self.writeln("if (typeof __val === 'string' || typeof __val === 'number') {");
                self.indent();
                self.writeln("return document.createTextNode(String(__val));");
                self.dedent();
                self.writeln("} else if (__val instanceof Node) {");
                self.indent();
                self.writeln("return __val;");
                self.dedent();
                self.writeln("} else {");
                self.indent();
                self.writeln("return document.createTextNode('');");
                self.dedent();
                self.writeln("}");
                self.dedent();
                self.write("})()");
            }
            JSXNode::ComponentCall {
                name,
                props,
                children,
                ..
            } => {
                self.write(&format!("{}({{", name));
                for (i, prop) in props.iter().enumerate() {
                    if i > 0 {
                        self.write(", ");
                    }
                    self.write(&format!("{}: ", prop.name));
                    match &prop.value {
                        JSXAttrValue::String(s) => self.write(&format!("'{}'", s)),
                        JSXAttrValue::Bool(b) => self.write(&b.to_string()),
                        JSXAttrValue::Expr(e) => self.gen_expr(e),
                    }
                }
                if !children.is_empty() {
                    if !props.is_empty() {
                        self.write(", ");
                    }
                    self.write("children: [");
                    for (i, child) in children.iter().enumerate() {
                        if i > 0 {
                            self.write(", ");
                        }
                        self.gen_jsx(child);
                    }
                    self.write("]");
                }
                self.write("})");
            }
            JSXNode::Fragment(children, _) => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.writeln("const __frag = document.createDocumentFragment();");
                for child in children {
                    self.write("__frag.appendChild(");
                    self.gen_jsx(child);
                    self.writeln(");");
                }
                self.writeln("return __frag;");
                self.dedent();
                self.write("})()");
            }
            JSXNode::For {
                binding,
                iter,
                body,
                ..
            } => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.writeln("const __frag = document.createDocumentFragment();");
                self.write(&format!("for (const {} of ", binding));
                self.gen_expr(iter);
                self.writeln(") {");
                self.indent();
                self.write("__frag.appendChild(");
                self.gen_jsx(body);
                self.writeln(");");
                self.dedent();
                self.writeln("}");
                self.writeln("return __frag;");
                self.dedent();
                self.write("})()");
            }
            JSXNode::If {
                condition,
                then_branch,
                else_branch,
                ..
            } => {
                self.write("(() => {");
                self.indent();
                self.writeln("");
                self.write("if (");
                self.gen_expr(condition);
                self.writeln(") {");
                self.indent();
                self.write("return ");
                self.gen_jsx(then_branch);
                self.writeln(";");
                self.dedent();
                if let Some(else_node) = else_branch {
                    self.writeln("} else {");
                    self.indent();
                    self.write("return ");
                    self.gen_jsx(else_node);
                    self.writeln(";");
                    self.dedent();
                }
                self.writeln("}");
                self.writeln("return document.createTextNode('');");
                self.dedent();
                self.write("})()");
            }
        }
    }

    fn gen_block_as_expr(&mut self, block: &Block) {
        self.write("(() => {");
        self.indent();
        self.writeln("");
        self.gen_block(block);
        self.dedent();
        self.write("})()");
    }

    fn gen_pattern_match(&mut self, scrutinee: &str, pattern: &Pattern) {
        match pattern {
            Pattern::Wildcard(_) | Pattern::Binding { .. } => self.write("true"),
            Pattern::Literal(expr) => {
                self.write(&format!("{} === ", scrutinee));
                self.gen_expr(expr);
            }
            Pattern::Variant {
                enum_name,
                variant,
                fields,
                ..
            } => {
                if let Some(enum_name) = enum_name {
                    self.write(&format!(
                        "{}.type === '{}' && {}.tag === '{}'",
                        scrutinee, enum_name, scrutinee, variant
                    ));
                } else {
                    self.write(&format!("{}.tag === '{}'", scrutinee, variant));
                }

                if let VariantPatternFields::Tuple(patterns) = fields {
                    for (i, _) in patterns.iter().enumerate() {
                        self.write(&format!(" && typeof {}._{} !== 'undefined'", scrutinee, i));
                    }
                }
            }
            _ => self.write("false"),
        }
    }

    fn gen_pattern_bindings(&mut self, scrutinee: &str, pattern: &Pattern) {
        if let Pattern::Binding { name, .. } = pattern {
            self.writeln(&format!("const {} = {};", name, scrutinee));
        }
    }

    fn gen_binop(&self, op: BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Pow => "**",
            BinaryOp::Eq => "===",
            BinaryOp::Ne => "!==",
            BinaryOp::Lt => "<",
            BinaryOp::Le => "<=",
            BinaryOp::Gt => ">",
            BinaryOp::Ge => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::BitAnd => "&",
            BinaryOp::BitOr => "|",
            BinaryOp::BitXor => "^",
            BinaryOp::Shl => "<<",
            BinaryOp::Shr => ">>",
            BinaryOp::Assign => "=",
            BinaryOp::AddAssign => "+=",
            BinaryOp::SubAssign => "-=",
            BinaryOp::MulAssign => "*=",
            BinaryOp::DivAssign => "/=",
            BinaryOp::Range | BinaryOp::RangeInclusive => "/* range */",
        }
    }

    fn gen_unop(&self, op: UnaryOp) -> &'static str {
        match op {
            UnaryOp::Neg => "-",
            UnaryOp::Not => "!",
            UnaryOp::BitNot => "~",
            UnaryOp::Ref | UnaryOp::RefMut | UnaryOp::Deref => "",
        }
    }

    fn function_return_ts(&self, func: &TypedFunction) -> String {
        if let Some(ret) = &func.ast.return_type {
            return self.type_to_ts(ret);
        }

        if let ResolvedType::Function { ret, .. } = &func.resolved_type {
            return self.resolved_type_to_ts(ret);
        }

        "void".to_string()
    }

    fn type_to_ts(&self, ty: &Type) -> String {
        match ty {
            Type::Named { name, generics, .. } => {
                let base = match name.as_str() {
                    "Int" | "Float" | "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8"
                    | "u16" | "u32" | "u64" | "u128" | "usize" | "f32" | "f64" => {
                        "number".to_string()
                    }
                    "Bool" => "boolean".to_string(),
                    "String" | "str" | "Char" => "string".to_string(),
                    "Unit" => "void".to_string(),
                    "Vec2" => "[number, number]".to_string(),
                    "Vec3" => "[number, number, number]".to_string(),
                    _ => name.clone(),
                };

                if generics.is_empty() {
                    base
                } else {
                    let gs = generics
                        .iter()
                        .map(|g| self.type_to_ts(g))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{}<{}>", base, gs)
                }
            }
            Type::Tuple(types, _) => {
                let inner = types
                    .iter()
                    .map(|t| self.type_to_ts(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[{}]", inner)
            }
            Type::Array(inner, _, _) | Type::Slice(inner, _) => {
                format!("Array<{}>", self.type_to_ts(inner))
            }
            Type::Ref { inner, .. } => self.type_to_ts(inner),
            Type::Ptr { inner, .. } => self.type_to_ts(inner),
            Type::Function {
                params,
                return_type,
                ..
            } => {
                let params = params
                    .iter()
                    .enumerate()
                    .map(|(i, p)| format!("arg{}: {}", i, self.type_to_ts(p)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({}) => {}", params, self.type_to_ts(return_type))
            }
            Type::Option(inner, _) => format!("{} | null", self.type_to_ts(inner)),
            Type::Result(ok, err, _) => {
                let ok_t = self.type_to_ts(ok);
                let err_t = self.type_to_ts(err);
                format!(
                    "{{ ok: true; value: {} }} | {{ ok: false; error: {} }}",
                    ok_t, err_t
                )
            }
            Type::Infer(_) | Type::Impl { .. } => "unknown".to_string(),
            Type::Never(_) => "never".to_string(),
            Type::Unit(_) => "void".to_string(),
        }
    }

    fn resolved_type_to_ts(&self, ty: &ResolvedType) -> String {
        match ty {
            ResolvedType::Unit => "void".to_string(),
            ResolvedType::Bool => "boolean".to_string(),
            ResolvedType::Int(IntSize::I64)
            | ResolvedType::Int(IntSize::I32)
            | ResolvedType::Int(IntSize::I16)
            | ResolvedType::Int(IntSize::I8)
            | ResolvedType::Int(IntSize::I128)
            | ResolvedType::Int(IntSize::Isize)
            | ResolvedType::Int(IntSize::U64)
            | ResolvedType::Int(IntSize::U32)
            | ResolvedType::Int(IntSize::U16)
            | ResolvedType::Int(IntSize::U8)
            | ResolvedType::Int(IntSize::U128)
            | ResolvedType::Int(IntSize::Usize) => "number".to_string(),
            ResolvedType::Float(FloatSize::F32) | ResolvedType::Float(FloatSize::F64) => {
                "number".to_string()
            }
            ResolvedType::String | ResolvedType::Char => "string".to_string(),
            ResolvedType::Array(inner, _) | ResolvedType::Slice(inner) => {
                format!("Array<{}>", self.resolved_type_to_ts(inner))
            }
            ResolvedType::Tuple(inner) => {
                let s = inner
                    .iter()
                    .map(|t| self.resolved_type_to_ts(t))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[{}]", s)
            }
            ResolvedType::Option(inner) => format!("{} | null", self.resolved_type_to_ts(inner)),
            ResolvedType::Result(ok, err) => {
                let ok_t = self.resolved_type_to_ts(ok);
                let err_t = self.resolved_type_to_ts(err);
                format!(
                    "{{ ok: true; value: {} }} | {{ ok: false; error: {} }}",
                    ok_t, err_t
                )
            }
            ResolvedType::Ref { inner, .. } => self.resolved_type_to_ts(inner),
            ResolvedType::Ptr { inner, .. } => self.resolved_type_to_ts(inner),
            ResolvedType::Function { params, ret, .. } => {
                let ps = params
                    .iter()
                    .enumerate()
                    .map(|(i, p)| format!("arg{}: {}", i, self.resolved_type_to_ts(p)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({}) => {}", ps, self.resolved_type_to_ts(ret))
            }
            ResolvedType::Struct(name, _)
            | ResolvedType::Enum(name, _)
            | ResolvedType::Generic(name) => name.clone(),
            ResolvedType::Never => "never".to_string(),
            ResolvedType::Unknown => "unknown".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kain_core::ast::*;
    use kain_core::span::Span;
    use std::collections::HashMap;

    #[test]
    fn test_string_escaping() {
        let mut gen = TSGen::new();
        let expr = Expr::String("Hello\nWorld".to_string(), Span::default());
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, r#""Hello\nWorld""#);
    }

    #[test]
    fn test_string_with_quotes() {
        let mut gen = TSGen::new();
        let expr = Expr::String(r#"He said "hello""#.to_string(), Span::default());
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, r#""He said \"hello\"""#);
    }

    #[test]
    fn test_string_with_backslash() {
        let mut gen = TSGen::new();
        let expr = Expr::String(r"C:\path\to\file".to_string(), Span::default());
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, r#""C:\\path\\to\\file""#);
    }

    #[test]
    fn test_string_with_tabs() {
        let mut gen = TSGen::new();
        let expr = Expr::String("Hello\tWorld".to_string(), Span::default());
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, r#""Hello\tWorld""#);
    }

    #[test]
    fn test_jsx_text_with_apostrophe() {
        let mut gen = TSGen::new();
        let node = JSXNode::Text("It's working".to_string(), Span::default());
        gen.gen_jsx(&node);
        let output = gen.output.build();
        assert!(output.contains("It\\'s working"));
        assert!(!output.contains("It's working")); // Should be escaped
    }

    #[test]
    fn test_jsx_text_with_backslash() {
        let mut gen = TSGen::new();
        let node = JSXNode::Text(r"Path: C:\test".to_string(), Span::default());
        gen.gen_jsx(&node);
        let output = gen.output.build();
        assert!(output.contains("C:\\\\test"));
    }

    #[test]
    fn test_numeric_helpers_generated() {
        let program = TypedProgram { items: vec![] };
        let output = generate(&program).unwrap();
        assert!(output.contains("function u8(n: number)"));
        assert!(output.contains("function u16(n: number)"));
        assert!(output.contains("function u32(n: number)"));
        assert!(output.contains("function i8(n: number)"));
        assert!(output.contains("function i16(n: number)"));
        assert!(output.contains("function i32(n: number)"));
        assert!(output.contains("function f32(n: number)"));
        assert!(output.contains("function __kain_addr_of"));
        assert!(output.contains("function __kain_bind_local"));
        assert!(output.contains("function __kain_field_ptr"));
        assert!(output.contains("function __kain_index_ptr"));
        assert!(output.contains("function __kain_mem_load"));
    }

    #[test]
    fn test_array_len_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "len".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, "arr.length");
    }

    #[test]
    fn test_array_is_empty_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "is_empty".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, "arr.length === 0");
    }

    #[test]
    fn test_array_first_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "first".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, "arr[0]");
    }

    #[test]
    fn test_array_last_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "last".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert!(output.contains("__arr[__arr.length - 1]"));
    }

    #[test]
    fn test_array_contains_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let arg = CallArg {
            name: None,
            value: Expr::Int(42, Span::default()),
            span: Span::default(),
        };
        let expr = Expr::MethodCall {
            receiver,
            method: "contains".to_string(),
            args: vec![arg],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert!(output.contains("arr.includes(42)"));
    }

    #[test]
    fn test_array_push_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let arg = CallArg {
            name: None,
            value: Expr::Int(42, Span::default()),
            span: Span::default(),
        };
        let expr = Expr::MethodCall {
            receiver,
            method: "push".to_string(),
            args: vec![arg],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert!(output.contains("arr.push(42)"));
    }

    #[test]
    fn test_array_pop_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "pop".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, "arr.pop()");
    }

    #[test]
    fn test_array_clear_method() {
        let mut gen = TSGen::new();
        let receiver = Box::new(Expr::Ident("arr".to_string(), Span::default()));
        let expr = Expr::MethodCall {
            receiver,
            method: "clear".to_string(),
            args: vec![],
            span: Span::default(),
        };
        gen.gen_expr(&expr);
        let output = gen.output.build();
        assert_eq!(output, "arr.length = 0");
    }

    #[test]
    fn test_component_children_destructuring_with_props() {
        let mut gen = TSGen::new();
        let comp = TypedComponent {
            ast: kain_core::ast::Component {
                name: "TestComp".to_string(),
                props: vec![Param {
                    name: "title".to_string(),
                    ty: Type::Named {
                        name: "String".to_string(),
                        generics: vec![],
                        span: Span::default(),
                    },
                    mutable: false,
                    default: None,
                    span: Span::default(),
                }],
                state: vec![],
                methods: vec![],
                effects: vec![],
                body: JSXNode::Text("test".to_string(), Span::default()),
                visibility: Visibility::Public,
                attributes: vec![],
                span: Span::default(),
            },
            prop_types: Default::default(),
        };
        gen.gen_typed_component(&comp);
        let output = gen.output.build();
        assert!(output.contains("const { title, children = [] } = props;"));
    }

    #[test]
    fn test_component_children_destructuring_without_props() {
        let mut gen = TSGen::new();
        let comp = TypedComponent {
            ast: kain_core::ast::Component {
                name: "TestComp".to_string(),
                props: vec![],
                state: vec![],
                methods: vec![],
                effects: vec![],
                body: JSXNode::Text("test".to_string(), Span::default()),
                visibility: Visibility::Public,
                attributes: vec![],
                span: Span::default(),
            },
            prop_types: Default::default(),
        };
        gen.gen_typed_component(&comp);
        let output = gen.output.build();
        assert!(output.contains("const { children = [] } = props;"));
    }
}
