// Generated by KAIN-PRO - Module Registration
#include "AlphaGen.h"
#include "Modules/ModuleManager.h"

class FAlphaGenModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        // Module startup
    }

    virtual void ShutdownModule() override
    {
        // Module shutdown
    }
};

IMPLEMENT_MODULE(FAlphaGenModule, AlphaGen)
