// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "FilterPosterize.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

namespace {
    struct FShaderDirectoryRegistration {
        FShaderDirectoryRegistration() {
            static bool bRegistered = false;
            if (!bRegistered) {
                TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("AlphaGen"));
                if (Plugin.IsValid()) {
                    FString PluginShaderDir = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Shaders"));
                    AddShaderSourceDirectoryMapping(TEXT("/Plugin/AlphaGen"), PluginShaderDir);
                    bRegistered = true;
                } else {
                    UE_LOG(LogShaders, Error, TEXT("Failed to find plugin 'AlphaGen' for shader directory mapping"));
                }
            }
        }
    };
    static FShaderDirectoryRegistration GShaderDirReg_FilterPosterize;
}

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FFilterPosterizeShader, "/Plugin/AlphaGen/Shaders/FilterPosterize.usf", "FilterPosterizeCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FilterPosterize(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float steps,
    FRDGTextureRef input_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FFilterPosterizeShader::FParameters* Params = GraphBuilder.AllocParameters<FFilterPosterizeShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->steps = steps;
    // Bind Textures
    Params->input_texture = input_texture;
    Params->input_textureSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FFilterPosterizeShader::Exec(GraphBuilder, *Params, GroupCount);
}
