// Generated by KAIN compiler
// Target: JavaScript (ES6+)

const TokenKind = {
  Int: (_0) => ({
    type: 'TokenKind',
    tag: 'Int',
    _0: _0,
  }),
  Float: (_0) => ({
    type: 'TokenKind',
    tag: 'Float',
    _0: _0,
  }),
  String: (_0) => ({
    type: 'TokenKind',
    tag: 'String',
    _0: _0,
  }),
  Bool: (_0) => ({
    type: 'TokenKind',
    tag: 'Bool',
    _0: _0,
  }),
  Ident: (_0) => ({
    type: 'TokenKind',
    tag: 'Ident',
    _0: _0,
  }),
  Keyword: (_0) => ({
    type: 'TokenKind',
    tag: 'Keyword',
    _0: _0,
  }),
  Plus: { type: 'TokenKind', tag: 'Plus' },
  Minus: { type: 'TokenKind', tag: 'Minus' },
  Star: { type: 'TokenKind', tag: 'Star' },
  Slash: { type: 'TokenKind', tag: 'Slash' },
  Percent: { type: 'TokenKind', tag: 'Percent' },
  Eq: { type: 'TokenKind', tag: 'Eq' },
  EqEq: { type: 'TokenKind', tag: 'EqEq' },
  NotEq: { type: 'TokenKind', tag: 'NotEq' },
  Lt: { type: 'TokenKind', tag: 'Lt' },
  LtEq: { type: 'TokenKind', tag: 'LtEq' },
  Gt: { type: 'TokenKind', tag: 'Gt' },
  GtEq: { type: 'TokenKind', tag: 'GtEq' },
  And: { type: 'TokenKind', tag: 'And' },
  Or: { type: 'TokenKind', tag: 'Or' },
  Not: { type: 'TokenKind', tag: 'Not' },
  Arrow: { type: 'TokenKind', tag: 'Arrow' },
  FatArrow: { type: 'TokenKind', tag: 'FatArrow' },
  Dot: { type: 'TokenKind', tag: 'Dot' },
  DotDot: { type: 'TokenKind', tag: 'DotDot' },
  Colon: { type: 'TokenKind', tag: 'Colon' },
  ColonColon: { type: 'TokenKind', tag: 'ColonColon' },
  Comma: { type: 'TokenKind', tag: 'Comma' },
  Semicolon: { type: 'TokenKind', tag: 'Semicolon' },
  Pipe: { type: 'TokenKind', tag: 'Pipe' },
  Ampersand: { type: 'TokenKind', tag: 'Ampersand' },
  LParen: { type: 'TokenKind', tag: 'LParen' },
  RParen: { type: 'TokenKind', tag: 'RParen' },
  LBracket: { type: 'TokenKind', tag: 'LBracket' },
  RBracket: { type: 'TokenKind', tag: 'RBracket' },
  LBrace: { type: 'TokenKind', tag: 'LBrace' },
  RBrace: { type: 'TokenKind', tag: 'RBrace' },
  LAngle: { type: 'TokenKind', tag: 'LAngle' },
  RAngle: { type: 'TokenKind', tag: 'RAngle' },
  Newline: { type: 'TokenKind', tag: 'Newline' },
  Indent: { type: 'TokenKind', tag: 'Indent' },
  Dedent: { type: 'TokenKind', tag: 'Dedent' },
  Eof: { type: 'TokenKind', tag: 'Eof' },
  Error: (_0) => ({
    type: 'TokenKind',
    tag: 'Error',
    _0: _0,
  }),
};

class Token {
  constructor(kind, line, column, lexeme) {
    this.kind = kind;
    this.line = line;
    this.column = column;
    this.lexeme = lexeme;
  }
}

Token.new = function(kind, line, column, lexeme) {
return new Token(kind, line, column, lexeme)  ;
};
Token.prototype.is_keyword = function(kw) {
let keywords = ["fn", "let", "var", "if", "else", "while", "for", "in", "return", "match", "struct", "enum", "impl", "use", "pub", "async", "await", "spawn", "actor", "on", "send", "true", "false", "none", "self", "test", "comptime", "with", "break", "continue", "loop"]  ;
return ((self.lexeme === kw) && contains(keywords, self.lexeme))  ;
};
Token.prototype.is_ident = function() {
let keywords = ["fn", "let", "var", "if", "else", "while", "for", "in", "return", "match", "struct", "enum", "impl", "use", "pub", "async", "await", "spawn", "actor", "on", "send", "true", "false", "none", "self", "test", "comptime", "with", "break", "continue", "loop"]  ;
((len(self.lexeme) === 0) ? (() => {    
return false    ;
})() : null)  ;
let c = ord(self.lexeme)  ;
let is_alpha = ((/* unsupported expr */ || /* unsupported expr */) || (c === 95))  ;
return (is_alpha && (!contains(keywords, self.lexeme)))  ;
};
Token.prototype.is_error = function() {
return false  ;
};

class Lexer {
  constructor(source, chars, pos, line, column, indent_stack) {
    this.source = source;
    this.chars = chars;
    this.pos = pos;
    this.line = line;
    this.column = column;
    this.indent_stack = indent_stack;
  }
}

Lexer.new = function(source) {
let chars = split(source, "")  ;
return new Lexer(source, chars, 0, 1, 1, [0])  ;
};
Lexer.prototype.is_eof = function() {
return (self.pos >= array_len(self.chars))  ;
};
Lexer.prototype.peek = function() {
(self.is_eof() ? (() => {    
return ""    ;
})() : null)  ;
return self.chars[self.pos]  ;
};
Lexer.prototype.peek_n = function(n) {
let idx = (self.pos + n)  ;
((idx >= array_len(self.chars)) ? (() => {    
return ""    ;
})() : null)  ;
return self.chars[idx]  ;
};
Lexer.prototype.advance = function() {
(self.is_eof() ? (() => {    
return ""    ;
})() : null)  ;
let c = self.chars[self.pos]  ;
self.pos = (self.pos + 1)  ;
((c === "\n") ? (() => {    
self.line = (self.line + 1)    ;
self.column = 1    ;
})() : (() => {    
self.column = (self.column + 1)    ;
})())  ;
return c  ;
};
Lexer.prototype.skip_spaces = function() {
while ((!self.is_eof())  ) {
let c = self.peek()    ;
(((c === " ") || (c === "\r")) ? (() => {      
self.advance()      ;
})() : (() => {      
      break;
})())    ;
  }
};
Lexer.prototype.make_token = function(kind, lexeme) {
return Token.new(kind, self.line, self.column, lexeme)  ;
};
Lexer.prototype.lex_number = function() {
let start = self.pos  ;
let start_col = self.column  ;
while (((!self.is_eof()) && is_digit(self.peek()))  ) {
self.advance()    ;
  }
(((self.peek() === ".") && is_digit(self.peek_n(1))) ? (() => {    
self.advance()    ;
while (((!self.is_eof()) && is_digit(self.peek()))    ) {
self.advance()      ;
    }
let lexeme = substring_range(self.source, start, self.pos)    ;
return Token.new(TokenKind.Float(to_float(lexeme)), self.line, start_col, lexeme)    ;
})() : null)  ;
let lexeme = substring_range(self.source, start, self.pos)  ;
return Token.new(TokenKind.Int(to_int(lexeme)), self.line, start_col, lexeme)  ;
};
Lexer.prototype.lex_string = function() {
let start_col = self.column  ;
let quote = self.advance()  ;
let value = ""  ;
while (((!self.is_eof()) && (self.peek() !== quote))  ) {
let c = self.advance()    ;
((c === "\\") ? (() => {      
let next = self.advance()      ;
((next === "n") ? (() => {        
value = (value + "\n")        ;
})() : /* else-if */null)      ;
})() : (() => {      
value = (value + c)      ;
})())    ;
  }
self.advance()  ;
return Token.new(TokenKind.String(value), self.line, start_col, (("\"" + value) + "\""))  ;
};
Lexer.prototype.lex_ident = function() {
let start = self.pos  ;
let start_col = self.column  ;
while (((!self.is_eof()) && is_ident_char(self.peek()))  ) {
self.advance()    ;
  }
let lexeme = substring_range(self.source, start, self.pos)  ;
let keywords = ["fn", "let", "var", "if", "else", "while", "for", "in", "return", "match", "struct", "enum", "impl", "use", "pub", "async", "await", "spawn", "actor", "on", "send", "true", "false", "none", "self", "test", "comptime", "with"]  ;
(contains(keywords, lexeme) ? (() => {    
((lexeme === "true") ? (() => {      
return Token.new(TokenKind.Bool(true), self.line, start_col, lexeme)      ;
})() : /* else-if */null)    ;
return Token.new(TokenKind.Keyword(lexeme), self.line, start_col, lexeme)    ;
})() : null)  ;
return Token.new(TokenKind.Ident(lexeme), self.line, start_col, lexeme)  ;
};
Lexer.prototype.next_token = function() {
self.skip_spaces()  ;
(self.is_eof() ? (() => {    
return self.make_token(TokenKind.Eof(), "")    ;
})() : null)  ;
let c = self.peek()  ;
(((c === "#") || /* unsupported expr */) ? (() => {    
while (((!self.is_eof()) && (self.peek() !== "\n"))    ) {
self.advance()      ;
    }
return self.next_token()    ;
})() : null)  ;
((c === "\r") ? (() => {    
self.advance()    ;
return self.next_token()    ;
})() : null)  ;
((c === "\n") ? (() => {    
self.advance()    ;
return self.make_token(TokenKind.Newline(), "\n")    ;
})() : null)  ;
(is_digit(c) ? (() => {    
return self.lex_number()    ;
})() : null)  ;
(((c === "\"") || (c === "\'")) ? (() => {    
return self.lex_string()    ;
})() : null)  ;
(is_ident_start(c) ? (() => {    
return self.lex_ident()    ;
})() : null)  ;
self.advance()  ;
(() => {    
const __match = c    ;
if (__match === "+"    ) {
return /* unsupported expr */      ;
} else if (__match === "-"    ) {
return (() => {        
((self.peek() === ">") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.Arrow(), "->")          ;
})() : null)        ;
return self.make_token(TokenKind.Minus(), "-")        ;
})()      ;
} else if (__match === "*"    ) {
return /* unsupported expr */      ;
} else if (__match === "/"    ) {
return /* unsupported expr */      ;
} else if (__match === "%"    ) {
return /* unsupported expr */      ;
} else if (__match === "="    ) {
return (() => {        
((self.peek() === "=") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.EqEq(), "==")          ;
})() : null)        ;
((self.peek() === ">") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.FatArrow(), "=>")          ;
})() : null)        ;
return self.make_token(TokenKind.Eq(), "=")        ;
})()      ;
} else if (__match === "!"    ) {
return (() => {        
((self.peek() === "=") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.NotEq(), "!=")          ;
})() : null)        ;
return self.make_token(TokenKind.Not(), "!")        ;
})()      ;
} else if (__match === "<"    ) {
return (() => {        
((self.peek() === "=") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.LtEq(), "<=")          ;
})() : null)        ;
return self.make_token(TokenKind.Lt(), "<")        ;
})()      ;
} else if (__match === ">"    ) {
return (() => {        
((self.peek() === "=") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.GtEq(), ">=")          ;
})() : null)        ;
return self.make_token(TokenKind.Gt(), ">")        ;
})()      ;
} else if (__match === "&"    ) {
return (() => {        
((self.peek() === "&") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.And(), "&&")          ;
})() : null)        ;
return self.make_token(TokenKind.Ampersand(), "&")        ;
})()      ;
} else if (__match === "|"    ) {
return (() => {        
((self.peek() === "|") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.Or(), "||")          ;
})() : null)        ;
return self.make_token(TokenKind.Pipe(), "|")        ;
})()      ;
} else if (__match === "."    ) {
return (() => {        
((self.peek() === ".") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.DotDot(), "..")          ;
})() : null)        ;
return self.make_token(TokenKind.Dot(), ".")        ;
})()      ;
} else if (__match === ":"    ) {
return (() => {        
((self.peek() === ":") ? (() => {          
self.advance()          ;
return self.make_token(TokenKind.ColonColon(), "::")          ;
})() : null)        ;
return self.make_token(TokenKind.Colon(), ":")        ;
})()      ;
} else if (__match === ","    ) {
return /* unsupported expr */      ;
} else if (__match === ";"    ) {
return /* unsupported expr */      ;
} else if (__match === "("    ) {
return /* unsupported expr */      ;
} else if (__match === ")"    ) {
return /* unsupported expr */      ;
} else if (__match === "["    ) {
return /* unsupported expr */      ;
} else if (__match === "]"    ) {
return /* unsupported expr */      ;
} else if (__match === "{"    ) {
return /* unsupported expr */      ;
} else if (__match === "}"    ) {
return /* unsupported expr */      ;
} else if (true    ) {
return /* unsupported expr */      ;
}     
    throw new Error('Non-exhaustive match');
})()  ;
};
Lexer.prototype.tokenize = function() {
let tokens = []  ;
  while (true) {
let tok = self.next_token()    ;
push(tokens, tok)    ;
(self.is_eof() ? (() => {      
      break;
})() : null)    ;
  }
return tokens  ;
};

function is_digit(c) {
((len(c) === 0) ? (() => {    
return false    ;
})() : null)  ;
let code = ord(c)  ;
return ((code >= 48) && (code <= 57))  ;
}

function is_alpha(c) {
((len(c) === 0) ? (() => {    
return false    ;
})() : null)  ;
let code = ord(c)  ;
return (/* unsupported expr */ || /* unsupported expr */)  ;
}

function is_ident_start(c) {
return (is_alpha(c) || (c === "_"))  ;
}

function is_ident_char(c) {
return ((is_alpha(c) || is_digit(c)) || (c === "_"))  ;
}

function substring_range(s, start, end) {
let chars = split(s, "")  ;
let result = ""  ;
for (const i of range(start, end)  ) {
((i < len(chars)) ? (() => {      
result = (result + chars[i])      ;
})() : null)    ;
  }
return result  ;
}

function main() {
println("=== KAIN Bootstrap Lexer ===")  ;
let source = "fn main():\r\n    let x = 42\r\n    println(x)"  ;
println("Source:")  ;
println(source)  ;
println("")  ;
println("Tokens:")  ;
let lexer = Lexer.new(source)  ;
let tokens = lexer.tokenize()  ;
println(("Token count: " + str(len(tokens))))  ;
for (const tok of tokens  ) {
println(((((("  [" + str(tok.line)) + ":") + str(tok.column)) + "] ") + tok.lexeme))    ;
  }
println("")  ;
println(" Lexer complete!")  ;
}

