// Generated by KAIN - UE5 Editor Tools
#include "SSovereignDetailsPanel.h"
#include "SlateOptMacros.h"

BEGIN_SLATE_FUNCTION_BUILD_OPTIMIZATION
void SSovereignDetailsPanel::Construct(const FArguments& InArgs)
{
	ChildSlot
	[
		SNew(SVerticalBox)
	];
}
END_SLATE_FUNCTION_BUILD_OPTIMIZATION

