// Generated by KAIN compiler

#include "ActionNodeNodeData.h"
#include "CombatGraphGraphInstance.h"

const UCombatGraphGraphNodeData* UActionNodeNodeData::ExecuteNode(UCombatGraphGraphInstance* Instance) const
{
	if (!IsValid(Instance))
	{
		return nullptr;
	}

	// Default execution - pass through to next node

	// Select output pin based on execution result
	// Default: use first output pin
	int32 OutputPinIndex = 0;

	// Return next node via output pin
	return GetNextOutputNodeByPinIndex(OutputPinIndex);
}

bool UActionNodeNodeData::ValidateNode() const
{
	// Validate that all required properties are set

	// No validation required for this node
	return true;
}