// Generated by KAIN compiler

#include "CombatGraphGraphNodeData.h"
#include "CombatGraphPinData.h"

UCombatGraphGraphNodeData* UCombatGraphGraphNodeData::GetNextOutputNodeByPinIndex(int OutputPinIndex) const
{
	if (!OutputPins.IsValidIndex(OutputPinIndex))
	{
		return nullptr;
	}

	UCombatGraphPinData* OutputPin = OutputPins[OutputPinIndex];
	if (!IsValid(OutputPin) || OutputPin->ConnectToPins.Num() == 0)
	{
		return nullptr;
	}

	// Get the first connected pin's parent node
	UCombatGraphPinData* ConnectedPin = OutputPin->ConnectToPins[0];
	if (!IsValid(ConnectedPin))
	{
		return nullptr;
	}

	return ConnectedPin->Parent;
}

const UCombatGraphGraphNodeData* UCombatGraphGraphNodeData::ExecuteNode(UCombatGraphGraphInstance* Instance) const
{
	// Base implementation - return next node via first output pin
	return GetNextOutputNodeByPinIndex(0);
}