[package]
name = "vulkain"
version = "0.1.0"
description = "Pure Kain Vulkan renderer via include <vulkan/vulkan.h> as vk"

[build]
entry = "vulkan_window_demo.kn"
artifact_root = ".kain/out/llvm"
cache_root = ".kain/cache/build"
profile = "debug"

[c_ffi]
include_paths = [
  ".",
  "${env:VULKAN_SDK}/include",
]

[[c_ffi.libraries]]
name = "vulkan_bridge"
header = "vulkan_bridge.h"
sources = ["vulkan_bridge.c"]
include_paths = [
  ".",
  "${env:VULKAN_SDK}/include",
]
static_libs = [
  "${env:VULKAN_SDK}/Lib/vulkan-1.lib",
]
link_libs = ["user32", "gdi32", "shell32"]
