//! .ini File Generation
//!
//! This module generates .ini file sections for KAIN @config structs.
//! Follows UE5 .ini format: [/Script/PluginName.ClassName]

use crate::config_ir::{ConfigField, ConfigStruct};
use anyhow::Result;

/// Generate a .ini file section for a config struct
///
/// # Example Output
///
/// ```ini
/// [/Script/MyPlugin.VoxelSettings]
/// ChunkSize=100.0
/// MaxLod=4
/// DebugVis=False
/// ```
pub fn generate_ini_section(config: &ConfigStruct, plugin_name: &str) -> Result<String> {
    let mut lines = Vec::new();

    // Section header: [/Script/PluginName.ClassName]
    let section_name = config.get_ini_section(plugin_name);
    lines.push(format!("[{}]", section_name));

    // Generate field entries
    for field in &config.fields {
        let property_name = field.ue5_property_name();
        let value = format_ini_value(field)?;
        lines.push(format!("{}={}", property_name, value));
    }

    Ok(lines.join("\n"))
}

/// Format a field value for .ini file
///
/// CRITICAL: Bool values MUST be "True"/"False" (capital T/F), NOT "true"/"false"
fn format_ini_value(field: &ConfigField) -> Result<String> {
    use kain_core::ast::Expr;

    match &field.default {
        Some(Expr::Float(val, _)) => Ok(format!("{}", val)),
        Some(Expr::Int(val, _)) => Ok(val.to_string()),
        Some(Expr::Bool(val, _)) => {
            // CRITICAL: Capital T/F for UE5 .ini format
            Ok(if *val { "True" } else { "False" }.to_string())
        }
        Some(Expr::String(val, _)) => Ok(val.clone()),
        None => {
            // Use type-appropriate defaults
            match field.ty {
                kain_core::ast::Type::Named { ref name, .. } => match name.as_str() {
                    "Float" => Ok("0.0".to_string()),
                    "Int" => Ok("0".to_string()),
                    "Bool" => Ok("False".to_string()), // Capital F
                    "String" => Ok(String::new()),
                    _ => anyhow::bail!("Unsupported .ini type: {}", name),
                },
                _ => anyhow::bail!("Unsupported .ini type for field: {}", field.name),
            }
        }
        _ => anyhow::bail!(
            "Unsupported default value expression for field: {}",
            field.name
        ),
    }
}

/// Generate complete .ini file content with header comment
pub fn generate_ini_file(config: &ConfigStruct, plugin_name: &str) -> Result<String> {
    let mut content = String::new();

    // Add header comment
    content.push_str(&format!(
        "; Generated by KAIN compiler\n; Configuration for {}\n\n",
        config.get_display_name()
    ));

    // Add section
    content.push_str(&generate_ini_section(config, plugin_name)?);
    content.push('\n');

    Ok(content)
}

#[cfg(test)]
mod tests {
    use super::*;
    use kain_core::ast::{Expr, Field, Struct, Type, Visibility};
    use kain_core::span::Span;

    fn make_test_config() -> ConfigStruct {
        ConfigStruct {
            name: "VoxelSettings".to_string(),
            category: crate::config_ir::ConfigCategory::Game,
            ini_file: None,
            ini_section: None,
            display_name: None,
            fields: vec![],
            original_struct: Struct {
                name: "VoxelSettings".to_string(),
                generics: vec![],
                fields: vec![],
                methods: vec![],
                attributes: vec![],
                visibility: Visibility::Public,
                span: Span::default(),
            },
            span: Span::default(),
        }
    }

    fn make_test_field(name: &str, ty_name: &str, default: Option<Expr>) -> ConfigField {
        ConfigField {
            name: name.to_string(),
            ty: Type::Named {
                name: ty_name.to_string(),
                generics: vec![],
                span: Span::default(),
            },
            default,
            display_name: None,
            tooltip: None,
            cvar: None,
            blueprint: false,
            min: None,
            max: None,
            writable: false,
            original_field: Field {
                name: name.to_string(),
                ty: Type::Named {
                    name: ty_name.to_string(),
                    generics: vec![],
                    span: Span::default(),
                },
                attributes: vec![],
                visibility: Visibility::Public,
                default: None,
                weak: false,
                span: Span::default(),
            },
            span: Span::default(),
        }
    }

    #[test]
    fn test_generate_ini_section_basic() {
        let mut config = make_test_config();
        config.fields.push(make_test_field(
            "chunk_size",
            "Float",
            Some(Expr::Float(100.0, Span::default())),
        ));

        let section = generate_ini_section(&config, "MyPlugin").unwrap();
        assert!(section.contains("[/Script/MyPlugin.UVoxelSettings]"));
        assert!(section.contains("ChunkSize=100"));
    }

    #[test]
    fn test_generate_ini_section_multiple_fields() {
        let mut config = make_test_config();
        config.fields.push(make_test_field(
            "chunk_size",
            "Float",
            Some(Expr::Float(100.0, Span::default())),
        ));
        config.fields.push(make_test_field(
            "max_lod",
            "Int",
            Some(Expr::Int(4, Span::default())),
        ));
        config.fields.push(make_test_field(
            "debug_vis",
            "Bool",
            Some(Expr::Bool(false, Span::default())),
        ));

        let section = generate_ini_section(&config, "MyPlugin").unwrap();
        assert!(section.contains("[/Script/MyPlugin.UVoxelSettings]"));
        assert!(section.contains("ChunkSize=100"));
        assert!(section.contains("MaxLod=4"));
        assert!(section.contains("DebugVis=False")); // Capital F!
    }

    #[test]
    fn test_format_ini_value_float() {
        let field = make_test_field("test", "Float", Some(Expr::Float(123.45, Span::default())));
        assert_eq!(format_ini_value(&field).unwrap(), "123.45");
    }

    #[test]
    fn test_format_ini_value_int() {
        let field = make_test_field("test", "Int", Some(Expr::Int(42, Span::default())));
        assert_eq!(format_ini_value(&field).unwrap(), "42");
    }

    #[test]
    fn test_format_ini_value_bool_true() {
        let field = make_test_field("test", "Bool", Some(Expr::Bool(true, Span::default())));
        // CRITICAL: Must be capital T
        assert_eq!(format_ini_value(&field).unwrap(), "True");
    }

    #[test]
    fn test_format_ini_value_bool_false() {
        let field = make_test_field("test", "Bool", Some(Expr::Bool(false, Span::default())));
        // CRITICAL: Must be capital F
        assert_eq!(format_ini_value(&field).unwrap(), "False");
    }

    #[test]
    fn test_format_ini_value_string() {
        let field = make_test_field(
            "test",
            "String",
            Some(Expr::String("hello world".to_string(), Span::default())),
        );
        assert_eq!(format_ini_value(&field).unwrap(), "hello world");
    }

    #[test]
    fn test_format_ini_value_no_default() {
        let field = make_test_field("test", "Float", None);
        assert_eq!(format_ini_value(&field).unwrap(), "0.0");

        let field = make_test_field("test", "Int", None);
        assert_eq!(format_ini_value(&field).unwrap(), "0");

        let field = make_test_field("test", "Bool", None);
        assert_eq!(format_ini_value(&field).unwrap(), "False"); // Capital F
    }

    #[test]
    fn test_generate_ini_file() {
        let mut config = make_test_config();
        config.fields.push(make_test_field(
            "chunk_size",
            "Float",
            Some(Expr::Float(100.0, Span::default())),
        ));

        let content = generate_ini_file(&config, "MyPlugin").unwrap();
        assert!(content.contains("; Generated by KAIN compiler"));
        assert!(content.contains("[/Script/MyPlugin.UVoxelSettings]"));
        assert!(content.contains("ChunkSize=100"));
    }

    #[test]
    fn test_custom_ini_section() {
        let mut config = make_test_config();
        config.ini_section = Some("/Script/CustomPlugin.CustomSettings".to_string());
        config.fields.push(make_test_field(
            "test_field",
            "Int",
            Some(Expr::Int(42, Span::default())),
        ));

        let section = generate_ini_section(&config, "MyPlugin").unwrap();
        assert!(section.contains("[/Script/CustomPlugin.CustomSettings]"));
        assert!(section.contains("TestField=42"));
    }
}
