[package]
name = "kain-3d"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
kain-core = { path = "../kain-core" }
kain-host = { path = "../kain-host", default-features = false }
kain-reflect = { path = "../kain-reflect" }
naga = { version = "24.0.0", features = ["spv-in", "wgsl-out"] }
pollster = { workspace = true }
wgpu = { workspace = true }
