// Generated by KAIN Compiler
// Derived HLSL output from the KAIN shader artifact pipeline

cbuffer ShaderParams : register(b0)
{
    float4 query_embed;
    float4 index_matrix;
    float4 index_norms;
    float4 scores;
    float4 dim_data;
    float4 num_chunks_data;
    float4 query_norm_data;
};

[numthreads(8, 8, 1)]
void CSMain(uint3 dispatchThreadID : SV_DispatchThreadID,
            uint3 groupThreadID : SV_GroupThreadID,
            uint3 groupID : SV_GroupID,
            uint groupIndex : SV_GroupIndex)
{
    float dim = dim_data[0];
    float num_chunks = num_chunks_data[0];
    float query_norm = query_norm_data[0];
    float chunk_idx = id.x;
    if ((chunk_idx >= num_chunks))
    {
        return;
    }
    float dot = 0.000000;
    uint d = uint(0);
    float4 safe_dim = dim;
    while ((d < safe_dim))
    {
        dot = (dot + (query_embed[d] * index_matrix[((chunk_idx * safe_dim) + d)]));
        d = (d + uint(1));
    }
    float norm = index_norms[chunk_idx];
    float score = 0.000000;
    if ((query_norm > float(0.000000)))
    {
        if ((norm > float(0.000000)))
        {
            score = (dot / ((query_norm * norm)));
        }
    }
    scores[chunk_idx] = score;
}
