// Copyright 2026 Epic Games, Inc.. All Rights Reserved.
// Generated by KAIN-PRO - Editor Module Master Header
#pragma once

#include "CoreMinimal.h"
#include "KainCosmos.h"

// Editor module includes
#include "SCosmosDashboard.h"
#include "SSovereignDetailsPanel.h"
#include "FKainCosmosModule.h"
