@echo off
REM Stub tablegen for llvm-kain -- creates empty .inc file
REM Usage: stub-tablegen.cmd <output-file> <options...>
REM We need to figure out which .inc file to create from the options.
REM Look for -o <file> in the arguments or use %2 as output.

setlocal enabledelayedexpansion
set "outfile="
set "i=1"
:loop
if "%i%"=="%1" set "i=%1"
set "arg="
for /f "tokens=%i" %%a in ("%*") do set "arg=%%a"
if defined arg (
  if "!arg!"=="-o" (
    set /a i+=1
    for /f "tokens=!i!" %%b in ("%*") do set "outfile=%%b"
  )
  set /a i+=1
  goto loop
)

if not defined outfile set "outfile=%2"
if not defined outfile set "outfile=output.inc"

echo // Stub generated by llvm-kain stub-tablegen > "%outfile%"
echo. >> "%outfile%"
exit /b 0
