[package]
name = "kain-sys-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
kain-actor = { path = "../actor" }
kain-core = { path = "../core" }
kain-ownership = { path = "../ownership" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
inkwell = { workspace = true, optional = true }

[features]
default = []
llvm = ["dep:inkwell"]
