// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "AHyperFluidProbe.h"
#include "RenderGraph.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphResources.h"
#include "RenderGraphUtils.h"
#include "RenderTargetPool.h"
#include "Engine/TextureRenderTarget2D.h"
#include "LatticeBoltzmannCollision.h"
#include "LatticeBoltzmannStreaming.h"
#include "SmoothedParticleHydrodynamics.h"
#include "MagnetohydrodynamicsInduction.h"
#include "MagnetohydrodynamicsLorentz.h"
#include "QuantumFluidGrossPitaevskii.h"
#include "QuantumFluidVortices.h"
#include "MultiphasePhaseField.h"
#include "MultiphaseSurfaceTension.h"
#include "ThermalFluidConduction.h"
#include "ThermalFluidConvection.h"
#include "ReactiveFluidChemistry.h"
#include "ReactiveFluidCombustion.h"
#include "GranularFlowCollision.h"
#include "GranularFlowFriction.h"
#include "CosmicDustAccretion.h"
#include "CosmicDustRadiation.h"
#include "SuperfluidHelium4.h"
#include "SuperfluidVortexLattice.h"
#include "PlasmaTokamak.h"
#include "PlasmaFusion.h"
#include "ViscoelasticStress.h"
#include "ViscoelasticRelaxation.h"
#include "ImmersedBoundaryForce.h"
#include "ImmersedBoundaryVelocity.h"
#include "SpectralFourierTransform.h"
#include "SpectralTurbulence.h"
#include "VortexMethodCore.h"
#include "VortexMethodAdvection.h"
#include "FiniteVolumeFlux.h"
#include "FiniteVolumeGradient.h"
#include "FiniteElementStiffness.h"
#include "FiniteElementMass.h"
#include "FluidRaymarching.h"
#include "FluidSchlieren.h"
#include "FluidInterferometry.h"
#include "FluidHolography.h"
#include "FluidQuantumVisualization.h"
#include "AdvectVelocity.h"
#include "AdvectDensity.h"
#include "AdvectTemperature.h"
#include "ApplyExternalForces.h"
#include "ComputeDivergence.h"
#include "JacobiPressure.h"
#include "SubtractGradient.h"
#include "VOF_AdvectionPLIC.h"
#include "LevelSet_Reinitialization.h"
#include "PhaseChange_Evaporation.h"
#include "PhaseChange_Condensation.h"
#include "TurbulenceKEpsilon.h"
#include "TurbulenceKOmegaSST.h"
#include "TurbulenceSpalartAllmaras.h"
#include "LES_DynamicSmagorinsky.h"
#include "ParticleDrag.h"
#include "ParticleCollision.h"
#include "ParticleBreakup.h"
#include "ParticleEvaporation.h"
#include "AcousticWaveEquation.h"
#include "AcousticSourceTerm.h"
#include "DarcyFlow.h"
#include "Forchheimer.h"
#include "PoroElastic.h"
#include "FreeSurface_VOF.h"
#include "FreeSurface_LevelSet.h"
#include "SurfaceTension_CSF.h"
#include "AdvectionWENO5.h"
#include "SDFCollisionPass.h"
#include "ClearTexture.h"
#include "FluidRaymarching.h"
#include "FluidSchlieren.h"
#include "FluidInterferometry.h"
#include "FluidHolography.h"
#include "FluidQuantumVisualization.h"

AHyperFluidProbe::AHyperFluidProbe()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AHyperFluidProbe::BeginPlay()
{
	Super::BeginPlay();
	// Initialize Render Targets here (omitted for brevity, user must implemented or we gen helper)
	// Helper: KismetRenderingLibrary::CreateRenderTarget2D(this, 1024, 1024, RTF_RGBA32f);
}

void AHyperFluidProbe::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// Enqueue Simulation on Render Thread
	ENQUEUE_RENDER_COMMAND(SimulationTick)(
		[this, DeltaTime](FRHICommandListImmediate& RHICmdList) {
			FRDGBuilder GraphBuilder(RHICmdList);

			// 1. Register External Textures (Ping-Pong Logic)
			bool bOddFrame = GFrameNumberRenderThread % 2 != 0;
			if(!PositionRT_A || !PositionRT_B || !VelocityRT_A || !VelocityRT_B) return;
			auto CreateRenderTarget = [&](FRHICommandListImmediate& RHICmdList, UTextureRenderTarget2D* RT, const TCHAR* Name) -> TRefCountPtr<IPooledRenderTarget> {
				if (!RT || !RT->GetResource()) return nullptr;
				FTexture2DRHIRef TextureRHI = RT->GetResource()->GetTexture2DRHI();
				FPooledRenderTargetDesc Desc = FPooledRenderTargetDesc::Create2DDesc(
					FIntPoint(RT->SizeX, RT->SizeY),
					TextureRHI->GetFormat(),
					FClearValueBinding::None,
					TexCreate_None,
					TexCreate_ShaderResource | TexCreate_UAV | TexCreate_RenderTargetable,
					false
				);
				TRefCountPtr<IPooledRenderTarget> PooledRT;
				FSceneRenderTargetItem Item;
				Item.TargetableTexture = (FTextureRHIRef)TextureRHI;
				Item.ShaderResourceTexture = (FTextureRHIRef)TextureRHI;
				GRenderTargetPool.CreateUntrackedElement(Desc, PooledRT, Item);
				return PooledRT;
			};

			FRDGTextureRef PositionInput = GraphBuilder.RegisterExternalTexture(CreateRenderTarget(RHICmdList, bOddFrame ? PositionRT_A : PositionRT_B, TEXT("PosIn")));
			FRDGTextureRef PositionOutput = GraphBuilder.RegisterExternalTexture(CreateRenderTarget(RHICmdList, bOddFrame ? PositionRT_B : PositionRT_A, TEXT("PosOut")));
			FRDGTextureRef VelocityInput = GraphBuilder.RegisterExternalTexture(CreateRenderTarget(RHICmdList, bOddFrame ? VelocityRT_A : VelocityRT_B, TEXT("VelIn")));
			FRDGTextureRef VelocityOutput = GraphBuilder.RegisterExternalTexture(CreateRenderTarget(RHICmdList, bOddFrame ? VelocityRT_B : VelocityRT_A, TEXT("VelOut")));

			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTurbulenceComponentData turbulence_pod {};
			AddPass_LatticeBoltzmannCollision(GraphBuilder, physics_pod, turbulence_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTurbulenceComponentData turbulence_pod {};
			AddPass_LatticeBoltzmannStreaming(GraphBuilder, physics_pod, turbulence_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTurbulenceComponentData turbulence_pod {};
			AddPass_SmoothedParticleHydrodynamics(GraphBuilder, physics_pod, turbulence_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FElectroMagneticComponentData em_pod {};
			AddPass_MagnetohydrodynamicsInduction(GraphBuilder, em_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FElectroMagneticComponentData em_pod {};
			AddPass_MagnetohydrodynamicsLorentz(GraphBuilder, em_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FQuantumComponentData quantum_pod {};
			AddPass_QuantumFluidGrossPitaevskii(GraphBuilder, quantum_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FQuantumComponentData quantum_pod {};
			AddPass_QuantumFluidVortices(GraphBuilder, quantum_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_MultiphasePhaseField(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_MultiphaseSurfaceTension(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FThermalComponentData thermal_pod {};
			AddPass_ThermalFluidConduction(GraphBuilder, thermal_pod, ThermalRT, FIntVector(32, 32, 1));
			}
			{
			FThermalComponentData thermal_pod {};
			AddPass_ThermalFluidConvection(GraphBuilder, thermal_pod, ThermalRT, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ReactiveFluidChemistry(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ReactiveFluidCombustion(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FParticulateComponentData particles_pod {};
			AddPass_GranularFlowCollision(GraphBuilder, particles_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FParticulateComponentData particles_pod {};
			AddPass_GranularFlowFriction(GraphBuilder, particles_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_CosmicDustAccretion(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_CosmicDustRadiation(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FQuantumComponentData quantum_pod {};
			AddPass_SuperfluidHelium4(GraphBuilder, quantum_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FQuantumComponentData quantum_pod {};
			AddPass_SuperfluidVortexLattice(GraphBuilder, quantum_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FElectroMagneticComponentData em_pod {};
			AddPass_PlasmaTokamak(GraphBuilder, em_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FElectroMagneticComponentData em_pod {};
			AddPass_PlasmaFusion(GraphBuilder, em_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ViscoelasticStress(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ViscoelasticRelaxation(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ImmersedBoundaryForce(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ImmersedBoundaryVelocity(GraphBuilder, physics_pod, VelocityOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_SpectralFourierTransform(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTurbulenceComponentData turbulence_pod {};
			AddPass_SpectralTurbulence(GraphBuilder, physics_pod, turbulence_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_VortexMethodCore(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_VortexMethodAdvection(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_FiniteVolumeFlux(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_FiniteVolumeGradient(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_FiniteElementStiffness(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_FiniteElementMass(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidRaymarching(GraphBuilder, viz_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidSchlieren(GraphBuilder, viz_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidInterferometry(GraphBuilder, viz_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidHolography(GraphBuilder, viz_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidQuantumVisualization(GraphBuilder, viz_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTimeIntegrationComponentData time_pod {};
			AddPass_AdvectVelocity(GraphBuilder, physics_pod, time_pod, VelocityInput, VelocityOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTimeIntegrationComponentData time_pod {};
			AddPass_AdvectDensity(GraphBuilder, physics_pod, time_pod, VelocityInput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FTimeIntegrationComponentData time_pod {};
			AddPass_AdvectTemperature(GraphBuilder, physics_pod, time_pod, VelocityInput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FThermalComponentData thermal_pod {};
			FTimeIntegrationComponentData time_pod {};
			AddPass_ApplyExternalForces(GraphBuilder, physics_pod, thermal_pod, time_pod, VelocityInput, PositionOutput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ComputeDivergence(GraphBuilder, physics_pod, VelocityInput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_JacobiPressure(GraphBuilder, physics_pod, PositionOutput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_SubtractGradient(GraphBuilder, physics_pod, VelocityInput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_VOF_AdvectionPLIC(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_LevelSet_Reinitialization(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			FThermalComponentData thermal_pod {};
			AddPass_PhaseChange_Evaporation(GraphBuilder, multiphase_pod, thermal_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			FThermalComponentData thermal_pod {};
			AddPass_PhaseChange_Condensation(GraphBuilder, multiphase_pod, thermal_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FTurbulenceAdvancedComponentData turbulence_advanced_pod {};
			AddPass_TurbulenceKEpsilon(GraphBuilder, turbulence_advanced_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FTurbulenceAdvancedComponentData turbulence_advanced_pod {};
			AddPass_TurbulenceKOmegaSST(GraphBuilder, turbulence_advanced_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FTurbulenceAdvancedComponentData turbulence_advanced_pod {};
			AddPass_TurbulenceSpalartAllmaras(GraphBuilder, turbulence_advanced_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FTurbulenceAdvancedComponentData turbulence_advanced_pod {};
			AddPass_LES_DynamicSmagorinsky(GraphBuilder, turbulence_advanced_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FHyperFluidParticleSystemComponentData particle_system_pod {};
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_ParticleDrag(GraphBuilder, particle_system_pod, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FHyperFluidParticleSystemComponentData particle_system_pod {};
			AddPass_ParticleCollision(GraphBuilder, particle_system_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FHyperFluidParticleSystemComponentData particle_system_pod {};
			AddPass_ParticleBreakup(GraphBuilder, particle_system_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FHyperFluidParticleSystemComponentData particle_system_pod {};
			AddPass_ParticleEvaporation(GraphBuilder, particle_system_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FCouplingComponentData coupling_pod {};
			AddPass_AcousticWaveEquation(GraphBuilder, coupling_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FCouplingComponentData coupling_pod {};
			AddPass_AcousticSourceTerm(GraphBuilder, coupling_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FBoundaryConditionComponentData boundary_pod {};
			AddPass_DarcyFlow(GraphBuilder, physics_pod, boundary_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FBoundaryConditionComponentData boundary_pod {};
			AddPass_Forchheimer(GraphBuilder, physics_pod, boundary_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FBoundaryConditionComponentData boundary_pod {};
			AddPass_PoroElastic(GraphBuilder, physics_pod, boundary_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_FreeSurface_VOF(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_FreeSurface_LevelSet(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FMultiphaseComponentData multiphase_pod {};
			AddPass_SurfaceTension_CSF(GraphBuilder, multiphase_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			AddPass_AdvectionWENO5(GraphBuilder, physics_pod, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FPhysicalPropertiesComponentData physics_pod {};
			FCollisionComponentData collision_pod {};
			AddPass_SDFCollisionPass(GraphBuilder, physics_pod, collision_pod, VelocityInput, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			AddPass_ClearTexture(GraphBuilder, FVector4f(0.0f, 0.0f, 0.0f, 0.0f), PositionOutput, FIntVector(32, 32, 1));
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidRaymarching(GraphBuilder, viz_pod, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidSchlieren(GraphBuilder, viz_pod, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidInterferometry(GraphBuilder, viz_pod, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidHolography(GraphBuilder, viz_pod, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}
			{
			FVisualizationComponentData viz_pod {};
			AddPass_FluidQuantumVisualization(GraphBuilder, viz_pod, PositionOutput, PositionOutput, FIntVector(32, 32, 1));
			}

			GraphBuilder.Execute();
		}
	);
}

	void AHyperFluidProbe::Server_Sample_Implementation(const UHyperFluidSimulationCore* world)
	{
		buffer = hyperfluid_sample_field(world, sample_position, radius);
		Client_ReceiveSample(buffer);
	}

	bool AHyperFluidProbe::Server_Sample_Validate(const UHyperFluidSimulationCore* world)
	{
		return true; // Add validation logic here
	}

	void AHyperFluidProbe::Client_ReceiveSample_Implementation(const TArray<float>& data)
	{
		UE_LOG(LogTemp, Warning, TEXT("%s"), *(LexToString(((TEXT("Probe Data Received: ") + string(data.length)) + TEXT(" components")))));
	}

	void AHyperFluidProbe::Server_SampleVelocity_Implementation(const UHyperFluidSimulationCore* world)
	{
		const auto vel = hyperfluid_sample_velocity(world, sample_position);
		Client_ReceiveSample({vel.X, vel.Y, vel.Z});
	}

	bool AHyperFluidProbe::Server_SampleVelocity_Validate(const UHyperFluidSimulationCore* world)
	{
		return true; // Add validation logic here
	}

	void AHyperFluidProbe::Server_SamplePressure_Implementation(const UHyperFluidSimulationCore* world)
	{
		const auto p = hyperfluid_sample_pressure(world, sample_position);
		Client_ReceiveSample({p});
	}

	bool AHyperFluidProbe::Server_SamplePressure_Validate(const UHyperFluidSimulationCore* world)
	{
		return true; // Add validation logic here
	}

	void AHyperFluidProbe::Server_SampleTemperature_Implementation(const UHyperFluidSimulationCore* world)
	{
		const auto t = hyperfluid_sample_temperature(world, sample_position);
		Client_ReceiveSample({t});
	}

	bool AHyperFluidProbe::Server_SampleTemperature_Validate(const UHyperFluidSimulationCore* world)
	{
		return true; // Add validation logic here
	}

