// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "FluidInterferometry.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FFluidInterferometryShader, "/Plugin/FluidFlow/FluidInterferometry.usf", "FluidInterferometryCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FluidInterferometry(
    FRDGBuilder& GraphBuilder,
    FVisualizationComponentData viz,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FFluidInterferometryShader::FParameters* Params = GraphBuilder.AllocParameters<FFluidInterferometryShader::FParameters>();
    // Bind Scalars
    Params->viz = viz;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FFluidInterferometryShader::Exec(GraphBuilder, *Params, GroupCount);
}
