// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "SuperfluidVortexLattice.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FSuperfluidVortexLatticeShader, "/Plugin/FluidFlow/SuperfluidVortexLattice.usf", "SuperfluidVortexLatticeCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_SuperfluidVortexLattice(
    FRDGBuilder& GraphBuilder,
    FQuantumComponentData quantum,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FSuperfluidVortexLatticeShader::FParameters* Params = GraphBuilder.AllocParameters<FSuperfluidVortexLatticeShader::FParameters>();
    // Bind Scalars
    Params->quantum = quantum;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FSuperfluidVortexLatticeShader::Exec(GraphBuilder, *Params, GroupCount);
}
