// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "VortexMethodAdvection.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FVortexMethodAdvectionShader, "/Plugin/FluidFlow/VortexMethodAdvection.usf", "VortexMethodAdvectionCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_VortexMethodAdvection(
    FRDGBuilder& GraphBuilder,
    PhysicalPropertiesComponent physics,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FVortexMethodAdvectionShader::FParameters* Params = GraphBuilder.AllocParameters<FVortexMethodAdvectionShader::FParameters>();
    // Bind Scalars
    Params->physics = physics;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FVortexMethodAdvectionShader::Exec(GraphBuilder, *Params, GroupCount);
}
