// Compatibility umbrella for lean single-file builds.
// The live runtime stays vendor-free and keeps only Kain-owned runtime systems,
// raw Win32 host/input helpers, and passive UI/runtime bundle support.

#include "native/src/core/kain_runtime_core.c"
#include "native/src/core/kain_runtime_version.c"
#include "native/src/core/kain_runtime_diagnostics.c"
#include "native/src/core/kain_runtime_services.c"
#include "native/src/core/kain_runtime_contract.c"
#include "native/src/core/kain_runtime_entangle.c"
#include "native/src/core/kain_runtime_native_stdlib.c"
#include "native/src/core/kain_native_input_system.c"
#include "native/src/core/kain_native_net_system.c"
#include "native/src/core/kain_native_process_system.c"
#include "native/src/core/kain_native_graphics_system.c"
#include "native/src/core/kain_runtime_renderer_backend.c"
#include "native/src/core/kain_runtime_renderer_session.c"
#include "native/src/core/kain_runtime_scene.c"
#include "native/src/core/kain_runtime_reflection.c"
#include "native/src/core/kain_runtime_realtime.c"
#include "native/src/core/kain_runtime_async.c"
#include "native/src/core/kain_runtime_compatibility.c"
#include "native/src/core/kain_runtime_host_bridge.c"
#include "native/src/core/kain_runtime_memory.c"
#include "native/src/core/kain_runtime_ownership.c"
#include "native/src/core/kain_runtime_bitfield.c"
#include "native/src/core/kain_runtime_union.c"
#include "native/src/core/kain_runtime_actor.c"
#include "native/src/platform/kain_runtime_platform.c"
#include "native/src/platform/win32/kain_win32_app_host.c"
#include "native/src/platform/win32/kain_win32_input_host.c"
#include "native/src/platform/win32/kain_runtime_win32_shared.c"
#include "native/src/ui/kain_ui_compiled_bundle.c"
#include "native/src/ui/kain_native_ui_system.c"
#include "native/src/ui/kain_native_ui_host_adapter.c"
#include "native/src/ui/kain_ui_runtime.c"
#include "native/src/ui/kain_ui_hot_reload.c"
