// Compatibility umbrella for lean single-file builds.
// The live runtime stays vendor-free and keeps only Kain-owned runtime systems,
// raw Win32 host/input helpers, and passive UI/runtime bundle support.

#include "native/src/core/core.c"
#include "native/src/core/version.c"
#include "native/src/core/diagnostics.c"
#include "native/src/core/services.c"
#include "native/src/core/contract.c"
#include "native/src/core/entangle.c"
#include "native/src/core/stdlib_abi.c"
#include "native/src/core/input_system.c"
#include "native/src/core/net_system.c"
#include "native/src/core/process_system.c"
#include "native/src/core/graphics_system.c"
#include "native/src/core/renderer_backend.c"
#include "native/src/core/renderer_session.c"
#include "native/src/core/scene.c"
#include "native/src/core/reflection.c"
#include "native/src/core/realtime.c"
#include "native/src/core/async.c"
#include "native/src/core/compatibility.c"
#include "native/src/core/host_bridge.c"
#include "native/src/core/memory.c"
#include "native/src/core/ownership.c"
#include "native/src/core/bitfield.c"
#include "native/src/core/union.c"
#include "native/src/core/actor.c"
#include "native/src/platform/platform.c"
#include "native/src/platform/win32/kain_win32_app_host.c"
#include "native/src/platform/win32/kain_win32_input_host.c"
#include "native/src/platform/win32/win32_shared.c"
#include "native/src/ui/ui_compiled_bundle.c"
#include "native/src/ui/ui_system.c"
#include "native/src/ui/ui_host_adapter.c"
#include "native/src/ui/ui_runtime.c"
#include "native/src/ui/ui_hot_reload.c"
