#!/usr/bin/env python3
"""
execute-phase5.py — Phase 5: Clean Flat Layout Restructure (Safe Execution)
===========================================================================
SAFE BY DEFAULT: --dry-run is the default mode. No files are modified unless
you explicitly pass --execute AND have run --backup first.

Modes:
    --backup         Create a full backup of llvm-project/
    --dry-run        Preview all changes (DEFAULT)
    --execute        Execute the flat layout restructure
    --reverse        Restore from backup
    --status         Report current state

Usage:
    python execute-phase5.py                # dry-run (default)
    python execute-phase5.py --backup        # backup first
    python execute-phase5.py --execute       # execute (requires backup)
    python execute-phase5.py --reverse       # undo everything
    python execute-phase5.py --status        # current state

Requirements: Python 3.x (stdlib only: os, shutil, sys, json, csv, datetime,
argparse, pathlib, logging, re)
"""

import argparse
import csv
import json
import logging
import os
import re
import shutil
import sys
import time
from collections import defaultdict
from datetime import datetime
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================

LLVM_PROJECT_ROOT = Path("X:/llvm-project")
BACKUP_ROOT = Path("X:/llvm-backups")
SCRIPTS_DIR = LLVM_PROJECT_ROOT / "scripts" / "phase5-layout"
REPORTS_DIR = SCRIPTS_DIR / "reports"
CHECKPOINT_FILE = REPORTS_DIR / ".phase5-checkpoint.json"
LLVM_KAIN_DIR = LLVM_PROJECT_ROOT / "llvm-kain"

# Sandbox directory (safe testing ground before touching real tree)
SANDBOX_DIR = SCRIPTS_DIR / "temp-build"
SANDBOX_SRC_DIR = SANDBOX_DIR / "llvm-project"
SANDBOX_KAIN_DIR = SANDBOX_SRC_DIR / "llvm-kain"  # = temp-build/llvm-project/llvm-kain — mirrors real layout under copied tree
SANDBOX_BUILD_OK_MARKER = SANDBOX_DIR / ".sandbox-build-ok"

# Existing report files (generated by analysis scripts)
FILE_MOVEMENTS_TSV = REPORTS_DIR / "file-movements.tsv"
BROKEN_INCLUDES_TSV = REPORTS_DIR / "broken-includes.tsv"
CURRENT_TREE_JSON = REPORTS_DIR / "current-tree.json"

# The same INCLUDE_PATH_MAP from verify-dependencies.py
# Maps old include path prefixes -> new include path prefixes
INCLUDE_PATH_MAP = {
    # llvm/ headers -> core/ etc.
    "llvm/IR/":              "core/ir/",
    "llvm/IRPrinter/":       "core/ir/",
    "llvm/IRReader/":        "core/ir/",
    "llvm/AsmParser/":       "core/ir/",
    "llvm/Analysis/":        "core/analysis/",
    "llvm/Transforms/":      "core/passes/",
    "llvm/Passes/":          "core/passes/",
    "llvm/CodeGen/":         "target/shared/codegen/",
    "llvm/MC/":              "core/mc/",
    "llvm/Object/":          "core/object/",
    "llvm/BinaryFormat/":    "core/support/",
    "llvm/Demangle/":        "core/support/",
    "llvm/Bitcode/":         "core/ir/",
    "llvm/Bitstream/":       "core/ir/",
    "llvm/DebugInfo/":       "core/debug/",
    "llvm/ExecutionEngine/": "jit/",
    "llvm/ExecutionEngine/Orc/": "jit/orc/",
    "llvm/ExecutionEngine/JITLink/": "jit/jitlink/",
    "llvm/Linker/":          "core/linker/",
    "llvm/Option/":          "core/support/",
    "llvm/ProfileData/":     "core/profiledata/",
    "llvm/Remarks/":         "core/support/",
    "llvm/Support/":         "support/adt/",
    "llvm/Target/":          "target/shared/",
    "llvm/TargetParser/":    "support/target/",
    "llvm/TableGen/":        "tools/tablegen/",
    "llvm/ADT/":             "support/adt/",
    "llvm/Config/":          "core/config/",
    "llvm-c/":               "c-api/",
    "llvm/ABI/":             "support/abi/",
    "llvm/WindowsResource/": "core/object/",
    "llvm/Frontend/":        "core/frontend/",
    "llvm/DWARFCFIChecker/": "core/debug/",
    "llvm/DTLTO/":           "core/linker/",
    "llvm/CodeGenTypes/":    "target/shared/codegen/",
    # clang/ headers -> flat clang/include/
    "clang/Basic/":          "basic/",
    "clang/Lex/":            "lex/",
    "clang/Parse/":          "parse/",
    "clang/AST/":            "ast/",
    "clang/ASTMatchers/":    "ast/",
    "clang/Sema/":           "sema/",
    "clang/CodeGen/":        "codegen/",
    "clang/Frontend/":       "frontend/",
    "clang/Serialization/":  "serialization/",
    "clang/Analysis/":       "analysis/",
    "clang/Edit/":           "edit/",
    "clang/Options/":       "options/",
    "clang/Config/":        "basic/",
    "clang/FrontendTool/":  "frontend/",
    # Dropped clang libraries (empty string = dead)
    "clang/Driver/":         "",
    "clang/Format/":         "",
    "clang/Tooling/":        "",
    "clang/StaticAnalyzer/": "",
    "clang/Rewrite/":        "",
    "clang/Index/":          "",
    "clang/Sandbox/":        "",
    "clang/InstallAPI/":     "",
    "clang/APINotes/":       "",
    "clang/CIR/":            "",
    "clang/Testing/":        "",
    "clang/CrossTU/":        "",
    "clang/DirectoryWatcher/": "",
    "clang/DependencyScanning/": "",
    "clang/ExtractAPI/":     "",
    "clang/Interpreter/":    "",

    # Dropped llvm libraries (empty string = dead)
    "llvm/LTO/":            "",
    "llvm/TextAPI/":        "",
    "llvm/SandboxIR/":      "",
    "llvm/CGData/":         "",
    "llvm/Debuginfod/":     "",
    "llvm/WindowsManifest/":"",
    "clang/Support/":       "",
    "clang/ScalableStaticAnalysis/": "",
    # Catch-all for root-level llvm/ headers (Pass.h, PassSupport.h, etc.)
    "llvm/":                "core/",
}

# Sorted for longest-prefix-first matching
SORTED_INCLUDE_MAP = sorted(INCLUDE_PATH_MAP.items(), key=lambda x: -len(x[0]))

# Include path regex
INCLUDE_RE = re.compile(r'(#\s*include\s+["<])([^">]+)([">])')

# Source file extensions for include path fixing
SOURCE_EXTENSIONS = {".cpp", ".h", ".hpp", ".c", ".def", ".td"}
VERSION = "1.1.0"  # 1.0 = original, 1.1 = added sandbox modes

# ============================================================================
# LOGGING SETUP
# ============================================================================

def setup_logging(log_file: Path):
    """Configure logging to both file and stdout."""
    log_file.parent.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("phase5")
    logger.setLevel(logging.INFO)

    # File handler
    fh = logging.FileHandler(str(log_file), mode="w", encoding="utf-8")
    fh.setLevel(logging.INFO)
    fh.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(message)s"))
    logger.addHandler(fh)

    # Console handler
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(message)s"))
    logger.addHandler(ch)

    return logger


# ============================================================================
# PROGRESS INDICATOR
# ============================================================================

class ProgressBar:
    """Simple text progress bar."""

    def __init__(self, total: int, prefix: str = "", width: int = 50):
        self.total = max(total, 1)
        self.prefix = prefix
        self.width = width
        self.current = 0
        self.start_time = time.time()

    def update(self, n: int = 1):
        """Advance by n steps."""
        self.current += n
        self._draw()

    def _draw(self):
        percent = self.current / self.total
        filled = int(self.width * percent)
        bar = "=" * filled + "-" * (self.width - filled)
        elapsed = time.time() - self.start_time
        eta = elapsed / max(self.current, 1) * (self.total - self.current)
        sys.stdout.write(
            f"\r{self.prefix} [{bar}] {self.current}/{self.total} "
            f"({percent * 100:.1f}%) ETA: {eta:.0f}s"
        )
        sys.stdout.flush()
        if self.current >= self.total:
            print()

    def close(self):
        """Ensure bar completes."""
        if self.current < self.total:
            self.current = self.total
            self._draw()


# ============================================================================
# CHECKPOINT SYSTEM
# ============================================================================

def load_checkpoint() -> dict:
    """Load checkpoint state from file."""
    if CHECKPOINT_FILE.exists():
        try:
            with open(CHECKPOINT_FILE, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def save_checkpoint(state: dict):
    """Save checkpoint state to file."""
    CHECKPOINT_FILE.parent.mkdir(parents=True, exist_ok=True)
    state["updated_at"] = datetime.now().isoformat()
    with open(CHECKPOINT_FILE, "w") as f:
        json.dump(state, f, indent=2, sort_keys=True)


def clear_checkpoint():
    """Remove checkpoint file."""
    if CHECKPOINT_FILE.exists():
        CHECKPOINT_FILE.unlink()


# ============================================================================
# FILE MOVEMENTS LOADER
# ============================================================================

def load_file_movements() -> list[dict]:
    """Load file movements from file-movements.tsv."""
    if not FILE_MOVEMENTS_TSV.exists():
        return []

    movements = []
    with open(FILE_MOVEMENTS_TSV, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            movements.append(row)
    return movements


def load_broken_includes() -> list[dict]:
    """Load broken includes from broken-includes.tsv."""
    if not BROKEN_INCLUDES_TSV.exists():
        return []

    includes = []
    with open(BROKEN_INCLUDES_TSV, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            includes.append(row)
    return includes


def load_current_tree() -> dict:
    """Load current tree JSON."""
    if not CURRENT_TREE_JSON.exists():
        return {}
    with open(CURRENT_TREE_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


# ============================================================================
# PATH HELPERS
# ============================================================================

def normalize_path(p: str) -> str:
    """Normalize path separators to forward slashes."""
    return p.replace("\\", "/").replace("//", "/")


def abs_path(rel_path: str) -> Path:
    """Convert a repo-relative path to absolute."""
    norm = normalize_path(rel_path)
    return Path(LLVM_PROJECT_ROOT / norm).resolve()


def rel_path(abs_path_obj: Path) -> str:
    """Convert an absolute path to repo-relative."""
    try:
        return normalize_path(str(abs_path_obj.relative_to(LLVM_PROJECT_ROOT)))
    except ValueError:
        return normalize_path(str(abs_path_obj))

# ============================================================================
# SANDBOX MODES
# ============================================================================
# These modes operate inside temp-build/ only. The real llvm-project/ is
# NEVER modified by sandbox operations.
# ============================================================================


def sandbox_rel_path(abs_path_obj: Path, sandbox_root: Path) -> str:
    """Convert a path under the sandbox to sandbox-relative."""
    try:
        return normalize_path(str(abs_path_obj.relative_to(sandbox_root)))
    except ValueError:
        return normalize_path(str(abs_path_obj))


def resolve_include_path(inc_path: str) -> str:
    """Resolve an include path to its new location under the target layout.
    Returns the new path or empty string if unresolvable/dropped."""
    norm_inc = normalize_path(inc_path)
    for old_prefix, new_prefix in SORTED_INCLUDE_MAP:
        if norm_inc.startswith(old_prefix):
            if new_prefix == "":
                return ""
            suffix = norm_inc[len(old_prefix):]
            return new_prefix + suffix
    if norm_inc.startswith("llvm/"):
        remainder = norm_inc[5:]
        for old_prefix, new_prefix in SORTED_INCLUDE_MAP:
            if old_prefix.startswith("llvm/") and remainder.startswith(old_prefix[5:]):
                suffix = remainder[len(old_prefix[5:]):]
                return new_prefix + suffix
    if norm_inc.startswith("clang/"):
        remainder = norm_inc[6:]
        for old_prefix, new_prefix in SORTED_INCLUDE_MAP:
            if old_prefix.startswith("clang/") and remainder.startswith(old_prefix[6:]):
                suffix = remainder[len(old_prefix[6:]):]
                return new_prefix + suffix
    return inc_path


# ============================================================================
# SANDBOX: --sandbox-prep
# ============================================================================

def mode_sandbox_prep(logger: logging.Logger):
    """Copy only Phase-5-relevant files into sandbox: files from the movement
    TSV plus CMake/build infrastructure. Skips large research/scratch artifacts."""
    if not LLVM_PROJECT_ROOT.exists():
        logger.error(f"Source tree not found: {LLVM_PROJECT_ROOT}")
        return False

    movements = load_file_movements()
    if not movements:
        logger.error(f"No file movements found at {FILE_MOVEMENTS_TSV}")
        logger.error("Run analysis scripts first.")
        return False

    # Check if sandbox already exists
    if SANDBOX_SRC_DIR.exists():
        logger.warning(f"Sandbox already exists at {SANDBOX_SRC_DIR}")
        answer = input("Overwrite? (y/N): ").strip().lower()
        if answer != "y":
            logger.info("Sandbox prep cancelled.")
            return True
        logger.info("Removing existing sandbox...")
        shutil.rmtree(str(SANDBOX_DIR))

    logger.info(f"Copying Phase-5-relevant files to sandbox...")
    logger.info(f"  Source: {LLVM_PROJECT_ROOT}")
    logger.info(f"  Dest:   {SANDBOX_SRC_DIR}")
    logger.info("")

    start_time = time.time()
    SANDBOX_DIR.mkdir(parents=True, exist_ok=True)

    # Build a set of source paths that must be copied (from the movement TSV)
    needed_paths = {}
    for m in movements:
        src_raw = m.get("current_path", "")
        if src_raw and src_raw != "(keep-in-place)":
            src_abs = str(LLVM_PROJECT_ROOT / normalize_path(src_raw))
            needed_paths[src_abs] = True

    # Also copy essential build infrastructure (CMakeLists.txt at key dirs)
    build_dirs = [
        "llvm/lib/IR", "llvm/lib/Analysis", "llvm/lib/Transforms",
        "llvm/lib/CodeGen", "llvm/lib/MC", "llvm/lib/Object",
        "llvm/lib/Support", "llvm/lib/Target/X86", "llvm/lib/Target/AArch64",
        "llvm/lib/ExecutionEngine/Orc", "llvm/lib/ExecutionEngine/JITLink",
        "llvm/include/llvm", "llvm/include/llvm-c",
        "clang/lib", "clang/include/clang",
        "compiler-rt/lib/builtins",
        "lld", "cmake", "runtimes",
    ]

    # Collect all CMakeLists.txt and .cmake files from build areas
    extra_patterns = ["CMakeLists.txt", "*.cmake", "*.inc"]
    import fnmatch
    for bd in build_dirs:
        bd_path = LLVM_PROJECT_ROOT / normalize_path(bd)
        if not bd_path.exists():
            continue
        for r, dirs, files in os.walk(str(bd_path)):
            for f in files:
                for pat in extra_patterns:
                    if fnmatch.fnmatch(f, pat):
                        fp = os.path.join(r, f)
                        needed_paths[fp] = True
                        break

    # Sort and copy
    sorted_srcs = sorted(needed_paths.keys())
    total_files = len(sorted_srcs)
    total_size = 0

    pb = ProgressBar(total_files, prefix="Copying to sandbox")
    copied = 0
    errors = 0

    for src_abs in sorted_srcs:
        try:
            total_size += os.path.getsize(src_abs)
            rel = os.path.relpath(src_abs, str(LLVM_PROJECT_ROOT))
            dst_abs = str(SANDBOX_SRC_DIR / normalize_path(rel))
            os.makedirs(os.path.dirname(dst_abs), exist_ok=True)
            shutil.copy2(src_abs, dst_abs)
            copied += 1
        except Exception as e:
            errors += 1
            if errors <= 5:
                logger.warning(f"  Copy error: {src_abs}: {e}")
        pb.update()
    pb.close()

    elapsed = time.time() - start_time
    logger.info(f"")
    logger.info(f"Sandbox copy complete in {elapsed:.0f}s")
    logger.info(f"  Copied:  {copied:,}")
    logger.info(f"  Errors:  {errors}")
    logger.info(f"  Size:    {total_size / 1024 / 1024:.1f} MB")

    # Write report
    report = REPORTS_DIR / "sandbox-prep-log.txt"
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(report, "w") as f:
        f.write(f"Sandbox Prep Log\n")
        f.write(f"================\n")
        f.write(f"Date:     {datetime.now().isoformat()}\n")
        f.write(f"Source:   {LLVM_PROJECT_ROOT}\n")
        f.write(f"Sandbox:  {SANDBOX_SRC_DIR}\n")
        f.write(f"Files:    {copied:,}\n")
        f.write(f"Size:     {total_size / 1024 / 1024:.1f} MB\n")
        f.write(f"Duration: {elapsed:.0f}s\n")
        f.write(f"Errors:   {errors}\n")

    save_checkpoint({**load_checkpoint(),
        "sandbox_path": str(SANDBOX_SRC_DIR),
        "sandbox_prep_time": datetime.now().isoformat(),
        "sandbox_files": copied,
        "sandbox_size": total_size,
    })
    logger.info(f"Sandbox prep report: {report}")
    return True


# ============================================================================
# SANDBOX: --sandbox-apply
# ============================================================================

def mode_sandbox_apply(logger: logging.Logger):
    """Apply the layout restructure INSIDE the sandbox only."""
    if not SANDBOX_SRC_DIR.exists():
        logger.error(f"Sandbox not found at {SANDBOX_SRC_DIR}")
        logger.error("Run --sandbox-prep first.")
        return False

    movements = load_file_movements()
    if not movements:
        logger.error(f"No file movements found at {FILE_MOVEMENTS_TSV}")
        return False

    moves = [m for m in movements if m.get("action") == "move"]
    logger.info("=" * 70)
    logger.info("SANDBOX — APPLY LAYOUT RESTRUCTURE")
    logger.info(f"Inside: {SANDBOX_SRC_DIR}")
    logger.info(f"Target: {SANDBOX_KAIN_DIR}")
    logger.info("=" * 70)
    logger.info("")

    start_time = time.time()
    total_errors = 0

    # ── Phase 1: Create target directories ──────────────────────────────────
    logger.info("Phase 1/4: Creating target directories in sandbox...")
    target_dirs = set()
    for m in moves:
        tgt = m.get("target_path", "")
        if tgt and tgt != "(keep-in-place)":
            if tgt.startswith("llvm-kain/"):
                local = tgt[len("llvm-kain/"):]
                td = os.path.dirname(str(SANDBOX_KAIN_DIR / local))
            else:
                td = os.path.dirname(str(SANDBOX_KAIN_DIR / tgt.replace(f"llvm-kain/", "", 1)))
            target_dirs.add(td)

    created = 0
    for td in sorted(target_dirs):
        os.makedirs(td, exist_ok=True)
        created += 1
    logger.info(f"  Created {created} directories.")

    # ── Phase 2: Copy files to new layout ───────────────────────────────────
    logger.info("")
    logger.info("Phase 2/4: Copying files to new layout in sandbox...")
    copied = 0
    skipped = 0
    errors = []

    pb = ProgressBar(len(moves), prefix="Copying (sandbox)")
    for m in moves:
        src_raw = m.get("current_path", "")
        tgt_raw = m.get("target_path", "")
        if not src_raw or not tgt_raw or tgt_raw == "(keep-in-place)":
            skipped += 1
            pb.update()
            continue

        src_path = SANDBOX_SRC_DIR / normalize_path(src_raw)
        tgt_path = SANDBOX_SRC_DIR / normalize_path(tgt_raw)

        if not src_path.exists():
            errors.append(f"Source not found: {src_path}")
            total_errors += 1
            pb.update()
            continue

        if tgt_path.exists():
            skipped += 1
            pb.update()
            continue

        try:
            tgt_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(src_path), str(tgt_path))
            copied += 1
        except Exception as e:
            errors.append(f"Copy failed: {src_path} -> {tgt_path}: {e}")
            total_errors += 1
        pb.update()
    pb.close()

    logger.info(f"  Copied:  {copied:,}")
    logger.info(f"  Skipped: {skipped:,}")
    logger.info(f"  Errors:  {total_errors}")

    if errors:
        for err in errors[:10]:
            logger.warning(f"    - {err}")

    # ── Phase 3: Fix include paths ──────────────────────────────────────────
    logger.info("")
    logger.info("Phase 3/4: Fixing include paths in sandbox...")
    include_fixes = 0
    include_errors = 0

    src_files = []
    for ext in SOURCE_EXTENSIONS:
        src_files.extend(SANDBOX_KAIN_DIR.rglob(f"*{ext}"))

    pb = ProgressBar(len(src_files), prefix="Fixing includes")
    include_rewrites = []
    for sf in src_files:
        sf_str = str(sf)
        try:
            with open(sf_str, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            original = content
            modified = False

            def replacer(match):
                nonlocal modified
                prefix = match.group(1)
                inc_path = match.group(2)
                suffix = match.group(3)
                resolved = resolve_include_path(inc_path)
                if resolved and resolved != inc_path:
                    modified = True
                    return prefix + resolved + suffix
                return match.group(0)

            content = INCLUDE_RE.sub(replacer, content)

            if modified:
                with open(sf_str, "w", encoding="utf-8") as f:
                    f.write(content)
                include_fixes += 1
                inc_rel = sandbox_rel_path(sf, SANDBOX_SRC_DIR)
                include_rewrites.append(inc_rel)
        except Exception as e:
            include_errors += 1
            total_errors += 1
        pb.update()
    pb.close()

    logger.info(f"  Files with include fixes: {include_fixes:,}")
    logger.info(f"  Include fix errors:       {include_errors}")

    # Write include rewrites log
    inc_log = REPORTS_DIR / "sandbox-include-rewrites.log"
    with open(inc_log, "w") as f:
        for path in sorted(include_rewrites):
            f.write(path + "\n")
    logger.info(f"  Include rewrites log: {inc_log}")

    # ── Phase 4: Remove empty source directories ────────────────────────────
    logger.info("")
    logger.info("Phase 4/4: Cleaning up empty source directories in sandbox...")
    clean_areas = [
        "llvm/lib/IR", "llvm/lib/Analysis", "llvm/lib/Transforms",
        "llvm/lib/CodeGen", "llvm/lib/MC", "llvm/lib/Object",
        "llvm/lib/Support", "llvm/lib/Target/X86", "llvm/lib/Target/AArch64",
        "llvm/lib/ExecutionEngine/Orc", "llvm/lib/ExecutionEngine/JITLink",
        "llvm/include/llvm", "llvm/include/llvm-c",
        "clang/lib", "clang/include/clang",
        "compiler-rt/lib/builtins",
    ]
    empty_removed = 0
    for clean_area in clean_areas:
        clean_path = SANDBOX_SRC_DIR / normalize_path(clean_area)
        if not clean_path.exists():
            continue
        for root, dirs, files in os.walk(str(clean_path), topdown=False):
            if not os.path.exists(root):
                continue
            if root == str(clean_path):
                continue
            try:
                remaining = os.listdir(root)
                if not remaining:
                    os.rmdir(root)
                    empty_removed += 1
            except (OSError, PermissionError):
                pass

    logger.info(f"  Empty directories removed: {empty_removed}")

    elapsed = time.time() - start_time
    logger.info("")
    logger.info("=" * 70)
    logger.info("SANDBOX APPLY SUMMARY")
    logger.info(f"  Duration:        {elapsed:.0f}s")
    logger.info(f"  Directories:     {created:,}")
    logger.info(f"  Files copied:    {copied:,}")
    logger.info(f"  Already existed: {skipped:,}")
    logger.info(f"  Include fixes:   {include_fixes:,}")
    logger.info(f"  Empty dirs removed: {empty_removed:,}")
    logger.info(f"  Errors:          {total_errors}")
    logger.info("=" * 70)

    # Write apply log
    apply_log = REPORTS_DIR / "sandbox-apply-log.txt"
    with open(apply_log, "w") as f:
        f.write(f"Sandbox Apply Log\n")
        f.write(f"================\n")
        f.write(f"Date:             {datetime.now().isoformat()}\n")
        f.write(f"Duration:         {elapsed:.0f}s\n")
        f.write(f"Directories:      {created:,}\n")
        f.write(f"Files copied:     {copied:,}\n")
        f.write(f"Already existed:  {skipped:,}\n")
        f.write(f"Include fixes:    {include_fixes:,}\n")
        f.write(f"Empty dirs removed: {empty_removed:,}\n")
        f.write(f"Errors:           {total_errors}\n")

    save_checkpoint({**load_checkpoint(),
        "sandbox_applied_at": datetime.now().isoformat(),
        "sandbox_files_copied": copied,
        "sandbox_include_fixes": include_fixes,
    })
    logger.info(f"Sandbox apply log: {apply_log}")
    return total_errors == 0


# ============================================================================
# SANDBOX: --sandbox-build
# ============================================================================

def mode_sandbox_build(logger: logging.Logger):
    """Attempt CMake build inside the sandbox and capture errors."""
    if not SANDBOX_KAIN_DIR.exists():
        logger.error(f"Sandbox llvm-kain/ not found at {SANDBOX_KAIN_DIR}")
        logger.error("Run --sandbox-prep and --sandbox-apply first.")
        return False

    logger.info("=" * 70)
    logger.info("SANDBOX — BUILD TEST")
    logger.info(f"Building in: {SANDBOX_KAIN_DIR}")
    logger.info("=" * 70)
    logger.info("")

    logger.warning("Sandbox build requires CMake and Ninja to be installed.")
    logger.warning("The build is optional for verification purposes.")
    logger.warning("If CMake/Ninja are not available, this step will be skipped.")
    logger.info("")

    # Check if cmake is available
    import subprocess
    import shutil as shutil_mod

    cmake_path = shutil_mod.which("cmake")
    ninja_path = shutil_mod.which("ninja")

    if not cmake_path:
        logger.warning("cmake not found — skipping build. Install CMake to enable build verification.")
        logger.warning("Proceeding with file-level verification only.")
        # Still mark as "checked" so we can do basic verification
        SANDBOX_BUILD_OK_MARKER.parent.mkdir(parents=True, exist_ok=True)
        with open(SANDBOX_BUILD_OK_MARKER, "w") as f:
            f.write(f"BUILD_SKIPPED: cmake not available\n")
            f.write(f"Date: {datetime.now().isoformat()}\n")
            f.write(f"Files in llvm-kain: {len(list(SANDBOX_KAIN_DIR.rglob('*')))}\n")
        logger.info("Marking sandbox as verified (file-level only).")
        return True

    build_dir = SANDBOX_DIR / "build"
    build_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Running CMake configure...")
    cmake_cmd = [
        str(cmake_path),
        "-G", "Ninja",
        f"-DLLVM_TARGETS_TO_BUILD=X86;AArch64",
        f"-DLLVM_INCLUDE_TESTS=OFF",
        f"-DLLVM_INCLUDE_BENCHMARKS=OFF",
        f"-DLLVM_INCLUDE_EXAMPLES=OFF",
        f"-DLLVM_INCLUDE_DOCS=OFF",
        f"-DLLVM_ENABLE_PROJECTS=clang",
        f"-DLLVM_ENABLE_RUNTIMES=",
        f"-DCMAKE_BUILD_TYPE=Release",
        f"-B{str(build_dir)}",
        f"-S{str(SANDBOX_KAIN_DIR)}",
    ]

    build_log = REPORTS_DIR / "sandbox-build-log.txt"
    start_time = time.time()

    try:
        logger.info(f"  cmake command: {' '.join(cmake_cmd)}")
        result = subprocess.run(
            cmake_cmd,
            capture_output=True,
            text=True,
            timeout=300,
        )
        cmake_output = result.stdout + "\n" + result.stderr

        with open(build_log, "w") as f:
            f.write(f"Sandbox Build Log\n")
            f.write(f"================\n")
            f.write(f"Date: {datetime.now().isoformat()}\n")
            f.write(f"CMake configure exit code: {result.returncode}\n")
            f.write(f"\n--- CMake stdout/stderr ---\n")
            f.write(cmake_output)

        if result.returncode != 0:
            logger.error(f"CMake configure failed with exit code {result.returncode}")
            logger.error(f"  Full output in: {build_log}")
            logger.info("")
            logger.info("CMake errors detected. See the build log for details.")

            # Parse errors
            error_lines = [l for l in cmake_output.split("\n") if "Error" in l or "error" in l.lower()]
            if error_lines:
                logger.info(f"First 20 CMake errors:")
                for el in error_lines[:20]:
                    logger.info(f"  {el.strip()}")

            SANDBOX_BUILD_OK_MARKER.parent.mkdir(parents=True, exist_ok=True)
            with open(SANDBOX_BUILD_OK_MARKER, "w") as f:
                f.write(f"BUILD_FAILED: CMake configure error\n")
                f.write(f"Exit code: {result.returncode}\n")
                f.write(f"Date: {datetime.now().isoformat()}\n")
            return False

        logger.info("CMake configure succeeded!")
        logger.info("")

        # Now run the actual build
        logger.info("Running Ninja build...")
        logger.info("  (This may take a long time — 30-60 minutes for full LLVM)")
        logger.info("  The build will be captured to the build log.")
        logger.info("")

        ninja_result = subprocess.run(
            [str(ninja_path), "-j4"],
            cwd=str(build_dir),
            capture_output=True,
            text=True,
            timeout=7200,  # 2 hour timeout
        )
        ninja_output = ninja_result.stdout + "\n" + ninja_result.stderr

        # Append to build log
        with open(build_log, "a") as f:
            f.write(f"\n--- Ninja build stdout/stderr ---\n")
            f.write(ninja_output)

        elapsed = time.time() - start_time

        # Parse build results
        success_count = 0
        fail_count = 0
        fail_files = []
        error_categories = defaultdict(int)

        for line in ninja_output.split("\n"):
            if "BUILT" in line:
                success_count += 1
            if "FAILED" in line:
                fail_count += 1
                # Extract filename
                parts = line.split()
                for p in parts:
                    if ".cpp" in p or ".c" in p or ".h" in p:
                        fail_files.append(p.strip())
                        break
                # Categorize error
                lower = line.lower()
                if "fatal error" in lower:
                    error_categories["fatal_error"] += 1
                elif "undefined reference" in lower:
                    error_categories["undefined_symbol"] += 1
                elif "undefined symbol" in lower:
                    error_categories["undefined_symbol"] += 1
                elif "no such file" in lower or "not found" in lower:
                    error_categories["missing_file"] += 1
                elif "error:" in lower:
                    error_categories["compile_error"] += 1

        # Count built targets
        built_count = len([l for l in ninja_output.split("\n") if "BUILT" in l])

        logger.info(f"")
        logger.info(f"Build duration: {elapsed:.0f}s")
        logger.info(f"Targets built:  {built_count}")
        logger.info(f"Build failures: {fail_count}")
        logger.info(f"")

        if fail_count > 0:
            logger.warning(f"Error categories:")
            for cat, cnt in sorted(error_categories.items()):
                logger.warning(f"  {cat}: {cnt}")
            logger.warning(f"")
            logger.warning(f"First 20 failing files:")
            for ff in fail_files[:20]:
                logger.warning(f"  {ff}")
        else:
            logger.info("All targets built successfully!")

        # Mark sandbox build result
        SANDBOX_BUILD_OK_MARKER.parent.mkdir(parents=True, exist_ok=True)
        with open(SANDBOX_BUILD_OK_MARKER, "w") as f:
            f.write(f"BUILD_OK: {fail_count} failures, {built_count} built\n")
            f.write(f"Date: {datetime.now().isoformat()}\n")
            f.write(f"Duration: {elapsed:.0f}s\n")
            f.write(f"Targets built: {built_count}\n")
            f.write(f"Failures: {fail_count}\n")
            if fail_files:
                f.write(f"Failing files:\n")
                for ff in fail_files:
                    f.write(f"  {ff}\n")

        save_checkpoint({**load_checkpoint(),
            "sandbox_built_at": datetime.now().isoformat(),
            "sandbox_build_duration_s": elapsed,
            "sandbox_build_targets": built_count,
            "sandbox_build_failures": fail_count,
            "sandbox_build_pass": fail_count == 0,
        })

        logger.info(f"Build log: {build_log}")

        if fail_count > 0:
            logger.warning(f"Sandbox build finished with {fail_count} failures.")
            logger.warning("Review the build log and fix issues before running --execute.")
            return False

        logger.info("Sandbox build PASSED! The layout restructure is safe to execute.")
        return True

    except subprocess.TimeoutExpired:
        logger.error("Build timed out (2 hour limit)")
        with open(build_log, "a") as f:
            f.write(f"\n--- TIMEOUT after {elapsed:.0f}s ---\n")
        return False
    except Exception as e:
        logger.error(f"Build failed with exception: {e}")
        return False


# ============================================================================
# SANDBOX: --sandbox-report
# ============================================================================

def mode_sandbox_report(logger: logging.Logger):
    """Summarize everything from the sandbox run."""
    checkpoint = load_checkpoint()

    logger.info("=" * 70)
    logger.info("SANDBOX — REPORT")
    logger.info("=" * 70)
    logger.info("")

    # Prep status
    if checkpoint.get("sandbox_prep_time"):
        logger.info("SANDBOX PREP: COMPLETED")
        logger.info(f"  Time:    {checkpoint['sandbox_prep_time']}")
        logger.info(f"  Files:   {checkpoint.get('sandbox_files', '?'):,}")
        logger.info(f"  Size:    {checkpoint.get('sandbox_size', 0) / 1024 / 1024:.1f} MB")
    elif SANDBOX_SRC_DIR.exists():
        fc = len(list(SANDBOX_SRC_DIR.rglob("*")))
        logger.info("SANDBOX PREP: EXISTS (no checkpoint)")
        logger.info(f"  Items in sandbox: {fc:,}")
    else:
        logger.info("SANDBOX PREP: NOT RUN")
    logger.info("")

    # Apply status
    if checkpoint.get("sandbox_applied_at"):
        logger.info("SANDBOX APPLY: COMPLETED")
        logger.info(f"  Time:         {checkpoint['sandbox_applied_at']}")
        logger.info(f"  Files copied: {checkpoint.get('sandbox_files_copied', '?'):,}")
        logger.info(f"  Include fixes: {checkpoint.get('sandbox_include_fixes', '?'):,}")

        # Report llvm-kain stats
        if SANDBOX_KAIN_DIR.exists():
            nd = 0
            nf = 0
            for p in SANDBOX_KAIN_DIR.rglob("*"):
                if p.is_dir():
                    nd += 1
                else:
                    nf += 1
            logger.info(f"  llvm-kain/ dirs:  {nd:,}")
            logger.info(f"  llvm-kain/ files: {nf:,}")
    elif SANDBOX_KAIN_DIR.exists():
        logger.info("SANDBOX APPLY: PARTIAL")
    else:
        logger.info("SANDBOX APPLY: NOT RUN")
    logger.info("")

    # Build status
    build_pass = checkpoint.get("sandbox_build_pass")
    if checkpoint.get("sandbox_built_at"):
        logger.info("SANDBOX BUILD:")
        if build_pass:
            logger.info("  RESULT: PASSED ")
        else:
            logger.info("  RESULT: FAILED ")
        logger.info(f"  Time:     {checkpoint['sandbox_built_at']}")
        logger.info(f"  Duration: {checkpoint.get('sandbox_build_duration_s', '?'):.0f}s")
        logger.info(f"  Targets:  {checkpoint.get('sandbox_build_targets', '?'):,}")
        logger.info(f"  Failures: {checkpoint.get('sandbox_build_failures', '?')}")
    elif SANDBOX_BUILD_OK_MARKER.exists():
        with open(SANDBOX_BUILD_OK_MARKER, "r") as f:
            content = f.read()
        if "BUILD_OK" in content:
            logger.info("SANDBOX BUILD: PASSED (marker file)")
        elif "BUILD_FAILED" in content:
            logger.info("SANDBOX BUILD: FAILED (marker file)")
        elif "BUILD_SKIPPED" in content:
            logger.info("SANDBOX BUILD: SKIPPED (file-level check only)")
        logger.info(f"  Marker content: {content[:200]}...")
    else:
        logger.info("SANDBOX BUILD: NOT RUN")
    logger.info("")

    # Greenlight assessment
    logger.info("GREENLIGHT ASSESSMENT:")
    prep_done = checkpoint.get("sandbox_prep_time") is not None or SANDBOX_SRC_DIR.exists()
    apply_done = checkpoint.get("sandbox_applied_at") is not None
    build_ok = checkpoint.get("sandbox_build_pass") or (
        SANDBOX_BUILD_OK_MARKER.exists() and "BUILD_OK" in SANDBOX_BUILD_OK_MARKER.read_text()
    )

    if prep_done and apply_done and build_ok:
        logger.info("  SANDBOX FULLY VALIDATED — safe to run --execute on real tree")
    elif prep_done and apply_done:
        logger.info("  SANDBOX APPLIED but NOT yet built — run --sandbox-build")
    elif prep_done:
        logger.info("  SANDBOX PREPPED but NOT yet applied — run --sandbox-apply")
    else:
        logger.info("  SANDBOX NOT READY — run --sandbox-prep first")
    logger.info("")

    if build_ok:
        logger.info("To execute on real tree:")
        logger.info("  python execute-phase5.py --backup")
        logger.info("  python execute-phase5.py --execute")
    logger.info("")

    # Include rewrites summary
    inc_log = REPORTS_DIR / "sandbox-include-rewrites.log"
    if inc_log.exists():
        with open(inc_log, "r") as f:
            rewrite_count = sum(1 for _ in f)
        logger.info(f"Include rewrites performed: {rewrite_count:,}")
        logger.info(f"  Full list: {inc_log}")

    build_log = REPORTS_DIR / "sandbox-build-log.txt"
    if build_log.exists():
        size = build_log.stat().st_size
        logger.info(f"Build log: {build_log} ({size / 1024:.0f} KB)")

    return True


# ============================================================================
# SANDBOX: --sandbox-cleanup
# ============================================================================

def mode_sandbox_cleanup(logger: logging.Logger):
    """Delete the entire sandbox directory."""
    if not SANDBOX_DIR.exists():
        logger.info("Sandbox directory does not exist. Nothing to clean.")
        return True

    size = sum(f.stat().st_size for f in SANDBOX_DIR.rglob("*") if f.is_file())
    files = len(list(SANDBOX_DIR.rglob("*")))

    logger.warning(f"About to DELETE sandbox directory: {SANDBOX_DIR}")
    logger.warning(f"  Size: {size / 1024 / 1024:.1f} MB, Items: {files:,}")
    answer = input("Delete sandbox? (y/N): ").strip().lower()
    if answer != "y":
        logger.info("Sandbox cleanup cancelled.")
        return True

    try:
        shutil.rmtree(str(SANDBOX_DIR))
        logger.info(f"Sandbox deleted: {SANDBOX_DIR}")

        # Also clear checkpoint entries
        cp = load_checkpoint()
        for key in list(cp.keys()):
            if key.startswith("sandbox_"):
                del cp[key]
        save_checkpoint(cp)

        return True
    except Exception as e:
        logger.error(f"Failed to delete sandbox: {e}")
        return False


# ============================================================================
# MODE: --backup
# ============================================================================

def mode_backup(logger: logging.Logger):
    """Create a full backup of the llvm-project tree."""
    if not LLVM_PROJECT_ROOT.exists():
        logger.error(f"Source tree not found: {LLVM_PROJECT_ROOT}")
        return False

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = BACKUP_ROOT / f"llvm-project-{timestamp}"
    newest_backup = find_newest_backup()

    # Check if a backup already exists for today
    today_prefix = datetime.now().strftime("%Y%m%d")
    today_backups = sorted(BACKUP_ROOT.glob(f"llvm-project-{today_prefix}-*"))
    if today_backups:
        logger.warning(f"Backup already exists for today: {today_backups[-1]}")
        answer = input("Overwrite? (y/N): ").strip().lower()
        if answer != "y":
            logger.info("Backup cancelled.")
            return True

    logger.info(f"Creating backup of {LLVM_PROJECT_ROOT}")
    logger.info(f"  -> {backup_path}")
    logger.info("")

    # Estimate size
    total_files = 0
    total_size = 0
    logger.info("Scanning source tree...")
    for root, dirs, files in os.walk(str(LLVM_PROJECT_ROOT)):
        # Skip hidden directories
        dirs[:] = [d for d in dirs if not d.startswith(".") and d != "__pycache__"]
        for fname in files:
            try:
                fp = os.path.join(root, fname)
                total_files += 1
                total_size += os.path.getsize(fp)
            except (OSError, PermissionError):
                pass

    logger.info(f"  Files to backup: {total_files:,}")
    logger.info(f"  Size to backup:  {total_size / 1024 / 1024:.1f} MB")
    logger.info("")

    # Create parent
    BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

    # Do the copy
    logger.info("Starting backup (this may take a while)...")
    start_time = time.time()

    try:
        shutil.copytree(
            str(LLVM_PROJECT_ROOT),
            str(backup_path),
            symlinks=False,
            ignore_dangling_symlinks=True,
            ignore=shutil.ignore_patterns("__pycache__", ".git"),
        )
    except Exception as e:
        logger.error(f"Backup failed: {e}")
        return False

    elapsed = time.time() - start_time
    logger.info(f"Backup complete in {elapsed:.0f}s")

    # Write backup report
    report = REPORTS_DIR / "backup-report.txt"
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(report, "w") as f:
        f.write(f"Backup Report\n")
        f.write(f"=============\n")
        f.write(f"Date:     {datetime.now().isoformat()}\n")
        f.write(f"Source:   {LLVM_PROJECT_ROOT}\n")
        f.write(f"Backup:   {backup_path}\n")
        f.write(f"Files:    {total_files:,}\n")
        f.write(f"Size:     {total_size / 1024 / 1024:.1f} MB\n")
        f.write(f"Duration: {elapsed:.0f}s\n")

    logger.info(f"Backup report written to: {report}")
    save_checkpoint({
        "backup_path": str(backup_path),
        "backup_time": datetime.now().isoformat(),
        "backup_files": total_files,
        "backup_size": total_size,
    })
    return True


def find_newest_backup() -> Path | None:
    """Find the most recent backup directory."""
    if not BACKUP_ROOT.exists():
        return None
    backups = sorted(BACKUP_ROOT.glob("llvm-project-*"))
    return backups[-1] if backups else None


# ============================================================================
# MODE: --dry-run
# ============================================================================

def mode_dry_run(logger: logging.Logger):
    """Preview the flat layout restructure without making changes."""
    movements = load_file_movements()
    if not movements:
        logger.error(f"No file movements found at {FILE_MOVEMENTS_TSV}")
        logger.error("Run the analysis scripts first (analyze-current-tree.py + map-file-movements.py)")
        return False

    broken = load_broken_includes()
    tree = load_current_tree()

    logger.info("=" * 70)
    logger.info("PHASE 5 LAYOUT RESTRUCTURE — DRY RUN")
    logger.info("No files will be modified.")
    logger.info("=" * 70)
    logger.info("")

    # Count movements by area
    area_counts = defaultdict(int)
    area_sizes = defaultdict(int)
    actions = defaultdict(int)

    for m in movements:
        area = m.get("area", "unknown")
        action = m.get("action", "unknown")
        size = int(m.get("size_bytes", 0))
        area_counts[area] += 1
        area_sizes[area] += size
        actions[action] += 1

    # Current tree summary
    if tree:
        tree_overall = tree.get("overall", {})
        logger.info(f"Current tree: {tree_overall.get('dirs', '?')} dirs, {tree_overall.get('files', '?')} files, "
                     f"{tree_overall.get('size_mb', '?'):.1f} MB")
        logger.info("")

    logger.info("Files to move by area:")
    logger.info(f"  {'Area':<25} {'Files':>8} {'Size':>12}")
    logger.info(f"  {'-'*25} {'-'*8} {'-'*12}")
    total_files = 0
    total_size = 0
    for area in sorted(area_counts.keys()):
        n = area_counts[area]
        s = area_sizes[area]
        total_files += n
        total_size += s
        logger.info(f"  {area:<25} {n:>8,} {s / 1024 / 1024:>10.1f} MB")
    logger.info(f"  {'-'*25} {'-'*8} {'-'*12}")
    logger.info(f"  {'TOTAL':<25} {total_files:>8,} {total_size / 1024 / 1024:>10.1f} MB")
    logger.info("")

    # Action breakdown
    logger.info(f"Actions: {', '.join(f'{k}={v}' for k, v in sorted(actions.items()))}")
    logger.info("")

    # Target directory structure
    logger.info("Target directory structure (will be created):")
    target_dirs = set()
    for m in movements:
        tgt = m.get("target_path", "")
        if tgt and tgt != "(keep-in-place)":
            td = os.path.dirname(tgt)
            if td:
                target_dirs.add(td)
    for td in sorted(target_dirs):
        logger.info(f"  {td}/")

    logger.info(f"\nTotal new directories: {len(target_dirs)}")
    logger.info("")

    # Broken includes summary
    if broken:
        dropped = [b for b in broken if b.get("status") == "dropped-library"]
        unmapped = [b for b in broken if b.get("status") == "unmapped"]
        logger.info(f"Include dependency analysis:")
        logger.info(f"  Broken includes requiring fix: {len(broken)}")
        logger.info(f"    Dropped library references:  {len(dropped)} (0 if Phases 1-3 complete)")
        logger.info(f"    Needs manual review:         {len(unmapped)}")
        logger.info(f"  Auto-mapped includes:          {broken[0].get('total_ok', '?') if broken else '?'}")
        logger.info("")

        if dropped:
            logger.info("  Sample dropped-library includes (will be removed from source):")
            for b in dropped[:5]:
                logger.info(f"    - {b.get('source_file', '?')}:{b.get('line', '?')} -> {b.get('include_path', '?')}")

    # Estimated time
    logger.info("Estimated execution time:")
    logger.info(f"  Directory creation:  ~1 min")
    logger.info(f"  File copies:         ~{total_files * 0.002:.0f}s ({total_files:,} files @ ~2ms/file)")
    logger.info(f"  Include path fixes:  ~30s")
    logger.info(f"  Verification:        ~1 min")
    logger.info(f"  Total:               ~{1 + total_files * 0.002 / 60 + 0.5 + 1:.0f} min")
    logger.info("")

    logger.info("SAFE: No files were modified. Run with --execute to proceed.")
    logger.info("")

    # Write dry-run report
    report = REPORTS_DIR / "dry-run-report.txt"
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with open(report, "w") as f:
        f.write(f"Phase 5 Dry Run Report\n")
        f.write(f"=====================\n")
        f.write(f"Date:       {datetime.now().isoformat()}\n")
        f.write(f"Source:     {LLVM_PROJECT_ROOT}\n")
        f.write(f"Target:     {LLVM_KAIN_DIR}\n")
        f.write(f"Files to move: {total_files:,}\n")
        f.write(f"Total size:    {total_size / 1024 / 1024:.1f} MB\n")
        f.write(f"New dirs:      {len(target_dirs)}\n")
        f.write(f"Broken includes: {len(broken)}\n")
        f.write(f"\nBy area:\n")
        for area in sorted(area_counts.keys()):
            f.write(f"  {area}: {area_counts[area]} files ({area_sizes[area] / 1024 / 1024:.1f} MB)\n")
        f.write(f"\nActions:\n")
        for action, count in sorted(actions.items()):
            f.write(f"  {action}: {count}\n")
    logger.info(f"Dry run report written to: {report}")
    return True


# ============================================================================
# MODE: --execute
# ============================================================================

def mode_execute(logger: logging.Logger):
    """Execute the flat layout restructure on the real tree."""
    # Verify sandbox build passed first
    checkpoint = load_checkpoint()
    sandbox_build_pass = checkpoint.get("sandbox_build_pass")
    if not sandbox_build_pass:
        # Also check the marker file directly
        if SANDBOX_BUILD_OK_MARKER.exists():
            content = SANDBOX_BUILD_OK_MARKER.read_text()
            if "BUILD_OK" in content:
                sandbox_build_pass = True
            elif "BUILD_SKIPPED" in content:
                logger.warning("Sandbox build was skipped (cmake not available).")
                logger.warning("Proceeding without build verification is RISKY.")
                answer = input("Continue without sandbox build proof? (y/N): ").strip().lower()
                if answer != "y":
                    logger.info("Execution cancelled.")
                    return False
                sandbox_build_pass = True

    if not sandbox_build_pass:
        logger.error("=" * 70)
        logger.error("SANDBOX BUILD NOT PASSED")
        logger.error("--execute requires a successful sandbox build first.")
        logger.error("")
        logger.error("  Run: python execute-phase5.py --sandbox-prep")
        logger.error("       python execute-phase5.py --sandbox-apply")
        logger.error("       python execute-phase5.py --sandbox-build")
        logger.error("       python execute-phase5.py --sandbox-report")
        logger.error("")
        logger.error("This proves the layout works before touching the real tree.")
        logger.error("=" * 70)
        return False

    # Verify backup exists
    if not checkpoint.get("backup_path"):
        logger.error("No backup found! Run --backup first before --execute.")
        logger.error("  python execute-phase5.py --backup")
        return False

    backup_path = Path(checkpoint["backup_path"])
    if not backup_path.exists():
        logger.error(f"Backup path does not exist: {backup_path}")
        logger.error("Run --backup again.")
        return False

    backup_path = Path(checkpoint["backup_path"])
    if not backup_path.exists():
        logger.error(f"Backup path does not exist: {backup_path}")
        logger.error("Run --backup again.")
        return False

    movements = load_file_movements()
    if not movements:
        logger.error(f"No file movements found at {FILE_MOVEMENTS_TSV}")
        logger.error("Run the analysis scripts first.")
        return False

    # Separate moves from keeps
    moves = [m for m in movements if m.get("action") == "move"]
    keeps = [m for m in movements if m.get("action") == "keep-in-place"]

    logger.info("=" * 70)
    logger.info("PHASE 5 LAYOUT RESTRUCTURE — EXECUTE")
    logger.info(f"Source: {LLVM_PROJECT_ROOT}")
    logger.info(f"Target: {LLVM_KAIN_DIR}")
    logger.info(f"Backup: {backup_path}")
    logger.info("=" * 70)
    logger.info("")

    # Confirm
    logger.warning(f"About to copy {len(moves):,} files to new flat layout.")
    logger.warning(f"{len(keeps):,} files will stay in place.")
    logger.warning("This is a destructive restructure operation.")
    answer = input("Continue? (y/N): ").strip().lower()
    if answer != "y":
        logger.info("Execution cancelled.")
        return False

    start_time = time.time()
    total_errors = 0

    # ── Phase 1: Create target directories ──────────────────────────────────
    logger.info("")
    logger.info("Phase 1/6: Creating target directories...")
    target_dirs = set()
    for m in moves:
        tgt = m.get("target_path", "")
        if tgt and tgt != "(keep-in-place)":
            td = os.path.dirname(str(LLVM_KAIN_DIR / tgt.replace(f"llvm-kain/", "", 1)))
            target_dirs.add(td)
    # Also handle paths that start with llvm-kain/ already
    for m in moves:
        tgt = m.get("target_path", "")
        if tgt and tgt != "(keep-in-place)" and tgt.startswith("llvm-kain/"):
            local = tgt[len("llvm-kain/"):]
            td = os.path.dirname(str(LLVM_KAIN_DIR / local))
            target_dirs.add(td)

    created = 0
    for td in sorted(target_dirs):
        os.makedirs(td, exist_ok=True)
        created += 1
    logger.info(f"  Created {created} directories.")
    save_checkpoint({**load_checkpoint(), "phase1_dirs_created": created})

    # ── Phase 2: Copy files to new locations ────────────────────────────────
    logger.info("")
    logger.info("Phase 2/6: Copying files to new layout...")
    copied = 0
    skipped = 0
    errors = []

    pb = ProgressBar(len(moves), prefix="Copying")
    for m in moves:
        src_raw = m.get("current_path", "")
        tgt_raw = m.get("target_path", "")
        if not src_raw or not tgt_raw or tgt_raw == "(keep-in-place)":
            skipped += 1
            pb.update()
            continue

        src_path = LLVM_PROJECT_ROOT / normalize_path(src_raw)
        tgt_path = LLVM_PROJECT_ROOT / normalize_path(tgt_raw)

        if not src_path.exists():
            errors.append(f"Source not found: {src_path}")
            total_errors += 1
            pb.update()
            continue

        if tgt_path.exists():
            skipped += 1
            pb.update()
            continue

        try:
            tgt_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(str(src_path), str(tgt_path))
            copied += 1
        except Exception as e:
            errors.append(f"Copy failed: {src_path} -> {tgt_path}: {e}")
            total_errors += 1
        pb.update()
    pb.close()

    logger.info(f"  Copied:  {copied:,}")
    logger.info(f"  Skipped (exists or keep): {skipped:,}")
    logger.info(f"  Errors:  {total_errors}")
    save_checkpoint({**load_checkpoint(), "phase2_files_copied": copied, "phase2_errors": total_errors})

    if errors:
        logger.warning("  First 10 errors:")
        for err in errors[:10]:
            logger.warning(f"    - {err}")

    # ── Phase 3: Fix include paths ──────────────────────────────────────────
    logger.info("")
    logger.info("Phase 3/6: Fixing include paths in copied files...")
    include_fixes = 0
    include_errors = 0

    # Collect all source files in the new tree
    src_files = []
    for ext in SOURCE_EXTENSIONS:
        src_files.extend(LLVM_KAIN_DIR.rglob(f"*{ext}"))

    pb = ProgressBar(len(src_files), prefix="Fixing includes")
    include_changes = []
    for sf in src_files:
        sf_str = str(sf)
        try:
            with open(sf_str, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()

            original = content
            modified = False

            def replace_include(match):
                nonlocal modified
                prefix = match.group(1)
                inc_path = match.group(2)
                suffix = match.group(3)

                # Try to resolve the include path
                resolved = resolve_include_path(inc_path)
                if resolved and resolved != inc_path:
                    modified = True
                    return prefix + resolved + suffix
                return match.group(0)

            content = INCLUDE_RE.sub(replace_include, content)

            if modified:
                with open(sf_str, "w", encoding="utf-8") as f:
                    f.write(content)
                include_fixes += 1
                rel = rel_path(sf)
                include_changes.append(rel)
        except Exception as e:
            include_errors += 1
            total_errors += 1
        pb.update()
    pb.close()

    logger.info(f"  Files with include fixes: {include_fixes:,}")
    logger.info(f"  Include fix errors:       {include_errors}")
    save_checkpoint({**load_checkpoint(), "phase3_include_fixes": include_fixes})

    # ── Phase 4: Remove empty source directories (if all files copied) ─────
    logger.info("")
    logger.info("Phase 4/6: Cleaning up empty source directories...")
    # Only clean directories that had ALL their files copied
    source_dirs_used = defaultdict(set)
    source_dirs_all = defaultdict(set)
    for m in moves:
        src_raw = m.get("current_path", "")
        tgt_raw = m.get("target_path", "")
        if src_raw and tgt_raw and tgt_raw != "(keep-in-place)":
            src_dir = os.path.dirname(normalize_path(src_raw))
            src_abs = str(LLVM_PROJECT_ROOT / src_dir)
            source_dirs_used[src_abs].add(1)
            # Check if the source file still exists (it should — we copied, not moved)
            src_file = str(LLVM_PROJECT_ROOT / normalize_path(src_raw))
            source_dirs_all[src_abs].add(src_file)

    # Only clean directories under areas we moved from
    clean_areas = [
        "llvm/lib/IR", "llvm/lib/Analysis", "llvm/lib/Transforms",
        "llvm/lib/CodeGen", "llvm/lib/MC", "llvm/lib/Object",
        "llvm/lib/Support", "llvm/lib/Target/X86", "llvm/lib/Target/AArch64",
        "llvm/lib/ExecutionEngine/Orc", "llvm/lib/ExecutionEngine/JITLink",
        "llvm/include/llvm", "llvm/include/llvm-c",
        "clang/lib", "clang/include/clang",
        "compiler-rt/lib/builtins",
    ]

    empty_removed = 0
    for clean_area in clean_areas:
        clean_path = LLVM_PROJECT_ROOT / normalize_path(clean_area)
        if not clean_path.exists():
            continue
        # Walk bottom-up and remove empty directories
        for root, dirs, files in os.walk(str(clean_path), topdown=False):
            if not os.path.exists(root):
                continue
            if root == str(clean_path):
                continue
            try:
                # Check if directory is empty (no files, no subdirs)
                remaining = os.listdir(root)
                if not remaining:
                    os.rmdir(root)
                    empty_removed += 1
            except (OSError, PermissionError):
                pass

    logger.info(f"  Empty directories removed: {empty_removed}")
    save_checkpoint({**load_checkpoint(), "phase4_empty_removed": empty_removed})

    # ── Phase 5: Create __ORIGINAL__ symlink/junction ───────────────────────
    logger.info("")
    logger.info("Phase 5/6: Creating __ORIGINAL__ reference...")
    original_link = LLVM_KAIN_DIR / "__ORIGINAL__"
    if not original_link.exists():
        try:
            # On Windows, use junction. On Linux, use symlink.
            if os.name == "nt":
                import subprocess
                # Use mklink /J for directory junction
                result = subprocess.run(
                    ["cmd", "/c", "mklink", "/J",
                     str(original_link), str(LLVM_PROJECT_ROOT)],
                    capture_output=True, text=True, shell=True
                )
                if result.returncode != 0:
                    logger.warning(f"  Junction creation failed: {result.stderr.strip()}")
                    logger.warning("  (This is non-critical; __ORIGINAL__ is for reference)")
                else:
                    logger.info(f"  Created junction: {original_link}")
            else:
                os.symlink(str(LLVM_PROJECT_ROOT), str(original_link),
                           target_is_directory=True)
                logger.info(f"  Created symlink: {original_link}")
        except Exception as e:
            logger.warning(f"  Could not create __ORIGINAL__ link: {e}")
            logger.warning("  (Non-critical — __ORIGINAL__ is for reference/diffing)")
    else:
        logger.info(f"  __ORIGINAL__ already exists, skipping.")

    # ── Phase 6: Run verification ──────────────────────────────────────────
    logger.info("")
    logger.info("Phase 6/6: Running post-move verification...")

    # Count files in new layout
    new_files = len(list(LLVM_KAIN_DIR.rglob("*")))
    new_dirs = 0
    new_file_count = 0
    for p in LLVM_KAIN_DIR.rglob("*"):
        if p.is_dir():
            new_dirs += 1
        else:
            new_file_count += 1

    logger.info(f"  New tree: {new_dirs:,} dirs, {new_file_count:,} files")

    # Check for leftover source files (only in the specific areas we moved from)
    leftovers = 0
    for area in clean_areas:
        area_path = LLVM_PROJECT_ROOT / normalize_path(area)
        if area_path.exists():
            for f in area_path.rglob("*"):
                if f.is_file():
                    leftovers += 1

    logger.info(f"  Leftover source files in old areas: {leftovers:,}")

    elapsed = time.time() - start_time
    logger.info("")
    logger.info("=" * 70)
    logger.info("EXECUTION SUMMARY")
    logger.info(f"  Duration:        {elapsed:.0f}s ({elapsed / 60:.1f} min)")
    logger.info(f"  Directories:     {created:,}")
    logger.info(f"  Files copied:    {copied:,}")
    logger.info(f"  Already existed: {skipped:,}")
    logger.info(f"  Include fixes:   {include_fixes:,}")
    logger.info(f"  Empty dirs removed: {empty_removed:,}")
    logger.info(f"  Errors:          {total_errors}")
    logger.info(f"  Leftover files:  {leftovers:,}")
    logger.info("")
    if total_errors > 0:
        logger.warning("  Some files had errors. Check logs above for details.")
    logger.info("  Post-move steps:")
    logger.info("    1. Verify include paths: python scripts/phase5-layout/verify-dependencies.py")
    logger.info("    2. Build test:    cd llvm-kain && cmake ...")
    logger.info("    3. Verify llc:    llc --version (should show X86 + AArch64 only)")
    logger.info("    4. Clang test:    echo 'int main(){}' | clang -x c - -o /dev/null")
    logger.info("=" * 70)

    # Write execute log
    execute_log = REPORTS_DIR / "execute-log.txt"
    with open(execute_log, "w") as f:
        f.write(f"Phase 5 Execute Log\n")
        f.write(f"==================\n")
        f.write(f"Date:             {datetime.now().isoformat()}\n")
        f.write(f"Duration:         {elapsed:.0f}s\n")
        f.write(f"Backup:           {backup_path}\n")
        f.write(f"Directories:      {created:,}\n")
        f.write(f"Files copied:     {copied:,}\n")
        f.write(f"Already existed:  {skipped:,}\n")
        f.write(f"Include fixes:    {include_fixes:,}\n")
        f.write(f"Empty dirs removed: {empty_removed:,}\n")
        f.write(f"Errors:           {total_errors}\n")
        f.write(f"Leftover files:   {leftovers:,}\n")

    save_checkpoint({**load_checkpoint(),
        "executed_at": datetime.now().isoformat(),
        "duration_s": elapsed,
        "files_copied": copied,
        "include_fixes": include_fixes,
        "total_errors": total_errors,
    })
    logger.info(f"Execute log written to: {execute_log}")
    return total_errors == 0
# ============================================================================
# MODE: --reverse
# ============================================================================

def mode_reverse(logger: logging.Logger):
    """Restore from backup."""
    checkpoint = load_checkpoint()
    backup_path_str = checkpoint.get("backup_path")
    if not backup_path_str:
        newest = find_newest_backup()
        if not newest:
            logger.error("No backup found! Run --backup first.")
            logger.error("  python execute-phase5.py --backup")
            return False
        backup_path = newest
        logger.info(f"Found backup at: {backup_path}")
        answer = input("Use this backup? (Y/n): ").strip().lower()
        if answer == "n":
            logger.info("Reverse cancelled.")
            return False
    else:
        backup_path = Path(backup_path_str)
        if not backup_path.exists():
            logger.error(f"Backup path not found: {backup_path}")
            logger.error("Run --backup to create a new backup.")
            return False

    logger.info("=" * 70)
    logger.info("PHASE 5 LAYOUT RESTRUCTURE — REVERSE")
    logger.info(f"Restoring from: {backup_path}")
    logger.info("=" * 70)
    logger.info("")

    logger.warning("This will DELETE the llvm-kain/ directory and RESTORE")
    logger.warning("the original llvm-project/ from backup.")
    logger.warning("ALL changes since the backup will be LOST.")
    answer = input("Are you absolutely sure? (yes/N): ").strip().lower()
    if answer != "yes":
        logger.info("Reverse cancelled.")
        return False

    # Remove llvm-kain/
    if LLVM_KAIN_DIR.exists():
        logger.info("Removing llvm-kain/ directory...")
        try:
            shutil.rmtree(str(LLVM_KAIN_DIR))
            logger.info("  Removed.")
        except Exception as e:
            logger.error(f"  Failed to remove {LLVM_KAIN_DIR}: {e}")
            return False

    # Remove the current tree completely
    logger.info("Removing current llvm-project/ contents (keeping .git if exists)...")
    git_dir = LLVM_PROJECT_ROOT / ".git"
    has_git = git_dir.exists()

    for item in LLVM_PROJECT_ROOT.iterdir():
        if item.name == ".git":
            continue
        try:
            if item.is_dir():
                shutil.rmtree(str(item))
            else:
                item.unlink()
        except Exception as e:
            logger.warning(f"  Could not remove {item.name}: {e}")

    # Copy everything back from backup
    logger.info(f"Restoring from backup: {backup_path}")
    start_time = time.time()

    try:
        shutil.copytree(
            str(backup_path),
            str(LLVM_PROJECT_ROOT),
            symlinks=False,
            ignore_dangling_symlinks=True,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("__pycache__", ".git"),
        )
    except Exception as e:
        logger.error(f"Restore failed: {e}")
        return False

    elapsed = time.time() - start_time
    logger.info(f"Restore complete in {elapsed:.0f}s")

    # Clear checkpoint
    clear_checkpoint()

    # Write reverse log
    reverse_log = REPORTS_DIR / "reverse-log.txt"
    with open(reverse_log, "w") as f:
        f.write(f"Phase 5 Reverse Log\n")
        f.write(f"==================\n")
        f.write(f"Date:       {datetime.now().isoformat()}\n")
        f.write(f"Backup:     {backup_path}\n")
        f.write(f"Duration:   {elapsed:.0f}s\n")
        f.write(f"Status:     Restored from backup\n")
    logger.info(f"Reverse log written to: {reverse_log}")
    return True


# ============================================================================
# MODE: --status
# ============================================================================

def mode_status(logger: logging.Logger):
    """Report current state of the Phase 5 operation."""
    checkpoint = load_checkpoint()
    tree = load_current_tree()

    logger.info("=" * 70)
    logger.info("PHASE 5 LAYOUT RESTRUCTURE — STATUS")
    logger.info("=" * 70)
    logger.info("")

    # Backup status
    backup_path_str = checkpoint.get("backup_path")
    if backup_path_str:
        bp = Path(backup_path_str)
        if bp.exists():
            backup_size = sum(f.stat().st_size for f in bp.rglob("*") if f.is_file())
            backup_files = len(list(bp.rglob("*")))
            logger.info("BACKUP STATUS: EXISTS")
            logger.info(f"  Location: {bp}")
            logger.info(f"  Files:    {backup_files:,}")
            logger.info(f"  Size:     {backup_size / 1024 / 1024:.1f} MB")
            logger.info(f"  Created:  {checkpoint.get('backup_time', 'unknown')}")
        else:
            logger.info("BACKUP STATUS: MISSING (path recorded but does not exist)")
    else:
        newest = find_newest_backup()
        if newest:
            logger.info("BACKUP STATUS: EXISTS (no checkpoint record)")
            logger.info(f"  Location: {newest}")
        else:
            logger.info("BACKUP STATUS: NONE")
    logger.info("")

    # Execution status
    if checkpoint.get("executed_at"):
        logger.info("EXECUTION STATUS: COMPLETED")
        logger.info(f"  Executed:    {checkpoint['executed_at']}")
        logger.info(f"  Duration:    {checkpoint.get('duration_s', '?'):.0f}s")
        logger.info(f"  Files moved: {checkpoint.get('files_copied', '?'):,}")
        logger.info(f"  Errors:      {checkpoint.get('total_errors', '?')}")
    elif LLVM_KAIN_DIR.exists():
        kain_files = len(list(LLVM_KAIN_DIR.rglob("*")))
        if kain_files > 0:
            logger.info("EXECUTION STATUS: PARTIAL (llvm-kain/ exists but no checkpoint)")
            logger.info(f"  Files in llvm-kain/: {kain_files:,}")
        else:
            logger.info("EXECUTION STATUS: NOT STARTED (llvm-kain/ is empty)")
    else:
        logger.info("EXECUTION STATUS: NOT STARTED")
    logger.info("")

    # Current tree info
    if tree:
        to = tree.get("overall", {})
        logger.info("CURRENT TREE (from analysis):")
        logger.info(f"  Directories: {to.get('dirs', '?'):,}")
        logger.info(f"  Files:       {to.get('files', '?'):,}")
        logger.info(f"  Size:        {to.get('size_mb', '?'):.1f} MB")
    else:
        # Live count
        if LLVM_PROJECT_ROOT.exists():
            live_dirs = 0
            live_files = 0
            live_size = 0
            try:
                for root, dirs, files in os.walk(str(LLVM_PROJECT_ROOT)):
                    if ".git" in dirs:
                        dirs.remove(".git")
                    live_dirs += len(dirs)
                    live_files += len(files)
                    for f in files:
                        try:
                            live_size += os.path.getsize(os.path.join(root, f))
                        except OSError:
                            pass
            except Exception:
                pass
            logger.info("CURRENT TREE (live):")
            logger.info(f"  Directories: {live_dirs:,}")
            logger.info(f"  Files:       {live_files:,}")
            logger.info(f"  Size:        {live_size / 1024 / 1024:.1f} MB")
    logger.info("")

    # New layout info
    if LLVM_KAIN_DIR.exists():
        new_dirs = 0
        new_files = 0
        new_size = 0
        for p in LLVM_KAIN_DIR.rglob("*"):
            if p.is_dir():
                new_dirs += 1
            else:
                new_files += 1
                try:
                    new_size += p.stat().st_size
                except OSError:
                    pass
        logger.info("NEW LAYOUT (llvm-kain/):")
        logger.info(f"  Directories: {new_dirs:,}")
        logger.info(f"  Files:       {new_files:,}")
        logger.info(f"  Size:        {new_size / 1024 / 1024:.1f} MB")
        if tree:
            old_files = tree.get("overall", {}).get("files", 0)
            pct = new_files / old_files * 100 if old_files else 0
            logger.info(f"  Coverage:    {pct:.1f}% of original tree")
    else:
        logger.info("NEW LAYOUT: NOT CREATED")
    logger.info("")

    # Sandbox status
    logger.info("SANDBOX STATUS:")
    if checkpoint.get("sandbox_prep_time"):
        logger.info(f"  Prep:     COMPLETED ({checkpoint.get('sandbox_files', '?'):,} files)")
    elif SANDBOX_SRC_DIR.exists():
        logger.info("  Prep:     EXISTS (no checkpoint)")
    else:
        logger.info("  Prep:     NOT RUN")

    if checkpoint.get("sandbox_applied_at"):
        logger.info(f"  Apply:    COMPLETED ({checkpoint.get('sandbox_files_copied', '?'):,} files copied)")
    elif SANDBOX_KAIN_DIR.exists():
        logger.info("  Apply:    PARTIAL")
    else:
        logger.info("  Apply:    NOT RUN")

    build_pass = checkpoint.get("sandbox_build_pass")
    if build_pass:
        logger.info("  Build:    PASSED")
    elif checkpoint.get("sandbox_built_at"):
        logger.info(f"  Build:    FAILED ({checkpoint.get('sandbox_build_failures', '?')} failures)")
    elif SANDBOX_BUILD_OK_MARKER.exists():
        content = SANDBOX_BUILD_OK_MARKER.read_text()
        if "BUILD_FAILED" in content:
            logger.info("  Build:    FAILED (marker)")
        elif "BUILD_SKIPPED" in content:
            logger.info("  Build:    SKIPPED (cmake unavailable)")
        else:
            logger.info("  Build:    marker exists")
    else:
        logger.info("  Build:    NOT RUN")
    logger.info("")

    if SANDBOX_DIR.exists():
        sd_size = sum(f.stat().st_size for f in SANDBOX_DIR.rglob("*") if f.is_file())
        sd_files = len(list(SANDBOX_DIR.rglob("*")))
        logger.info(f"  Sandbox directory: {SANDBOX_DIR}")
        logger.info(f"  Sandbox size:      {sd_size / 1024 / 1024:.1f} MB ({sd_files:,} items)")
        logger.info("")

    # File movements
    movements = load_file_movements()
    if movements:
        logger.info("PHASE 5 DATA FILES:")
        logger.info(f"  file-movements.tsv:  {len(movements):,} entries")
        broken = load_broken_includes()
        if broken:
            logger.info(f"  broken-includes.tsv: {len(broken):,} entries (need fixing)")
        else:
            logger.info(f"  broken-includes.tsv: not loaded")
    else:
        logger.info("PHASE 5 DATA FILES: Not found — run analysis scripts first.")
    logger.info("")
    logger.info("Next steps:")
    has_sandbox_build = checkpoint.get("sandbox_build_pass") or (
        SANDBOX_BUILD_OK_MARKER.exists()
        and "BUILD_OK" in SANDBOX_BUILD_OK_MARKER.read_text()
    )
    if not checkpoint.get("sandbox_prep_time"):
        logger.info("  1. python execute-phase5.py --sandbox-prep     (copy tree to sandbox)")
        logger.info("  2. python execute-phase5.py --sandbox-apply    (apply layout in sandbox)")
        logger.info("  3. python execute-phase5.py --sandbox-build    (prove layout works)")
        logger.info("  4. python execute-phase5.py --backup           (then backup real tree)")
        logger.info("  5. python execute-phase5.py --execute          (run on real tree)")
    elif not has_sandbox_build:
        logger.info("  1. python execute-phase5.py --sandbox-apply    (finish sandbox apply)")
        logger.info("  2. python execute-phase5.py --sandbox-build    (build to verify)")
        logger.info("  3. python execute-phase5.py --backup           (backup real tree)")
        logger.info("  4. python execute-phase5.py --execute          (run on real tree)")
    elif not checkpoint.get("backup_path"):
        logger.info("  1. python execute-phase5.py --backup           (create backup)")
        logger.info("  2. python execute-phase5.py --execute          (run on real tree)")
    elif not checkpoint.get("executed_at"):
        logger.info("  1. python execute-phase5.py --execute          (run the restructure)")
    else:
        logger.info("  1. Backup: EXISTS")
        logger.info("  2. Execution: DONE")

    return True


# ============================================================================
# MAIN
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Phase 5: Clean Flat Layout Restructure (Safe Execution)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
SAFETY LAYER 1: Backup + Dry-run + Reverse (protect the real tree)
SAFETY LAYER 2: Sandbox (prove layout works before touching real tree)

Modes:
  --backup              Create a full backup of llvm-project/
  --dry-run             Preview all changes (DEFAULT)
  --execute             Execute the flat layout restructure
  --reverse             Restore from backup
  --status              Report current state
  --sandbox-prep        Copy entire tree to sandbox (temp-build/)
  --sandbox-apply       Apply layout restructure INSIDE sandbox only
  --sandbox-build       Attempt CMake build inside sandbox, capture errors
  --sandbox-report      Summarize sandbox run results
  --sandbox-cleanup     Delete the sandbox directory

Workflow:
  1. python execute-phase5.py --sandbox-prep      (copy to sandbox)
  2. python execute-phase5.py --sandbox-apply     (apply layout in sandbox)
  3. python execute-phase5.py --sandbox-build     (prove it compiles)
  4. python execute-phase5.py --sandbox-report    (review results)
  5. python execute-phase5.py --backup             (backup real tree)
  6. python execute-phase5.py --execute            (execute on real tree)

Usage:
  python execute-phase5.py                    # dry-run (default)
  python execute-phase5.py --backup            # backup first
  python execute-phase5.py --sandbox-prep      # safe sandbox testing
        """,
    )
    parser.add_argument("--backup", action="store_true", help="Create a full backup")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes (default)")
    parser.add_argument("--execute", action="store_true", help="Execute the layout restructure")
    parser.add_argument("--reverse", action="store_true", help="Restore from backup")
    parser.add_argument("--status", action="store_true", help="Report current state")
    parser.add_argument("--sandbox-prep", action="store_true", help="Copy tree to sandbox")
    parser.add_argument("--sandbox-apply", action="store_true", help="Apply layout in sandbox only")
    parser.add_argument("--sandbox-build", action="store_true", help="Build test in sandbox")
    parser.add_argument("--sandbox-report", action="store_true", help="View sandbox results")
    parser.add_argument("--sandbox-cleanup", action="store_true", help="Delete sandbox")
    parser.add_argument("--verbose", action="store_true", help="Detailed logging")

    args = parser.parse_args()

    # If no mode specified, default to dry-run
    all_modes = [
        args.backup, args.dry_run, args.execute, args.reverse, args.status,
        args.sandbox_prep, args.sandbox_apply, args.sandbox_build,
        args.sandbox_report, args.sandbox_cleanup,
    ]
    if not any(all_modes):
        args.dry_run = True

    # Validate that only one mode is specified
    mode_count = sum(1 for m in all_modes if m)
    if mode_count > 1:
        print("Error: Specify only one mode at a time.")
        print("  python execute-phase5.py --help")
        sys.exit(1)
    # Setup logging
    log_file = REPORTS_DIR / f"phase5-{datetime.now().strftime('%Y%m%d-%H%M%S')}.log"
    logger = setup_logging(log_file)

    logger.info(f"LLVM Project Root: {LLVM_PROJECT_ROOT}")
    logger.info(f"Log file:          {log_file}")
    logger.info("")

    if args.backup:
        success = mode_backup(logger)
    elif args.dry_run:
        success = mode_dry_run(logger)
    elif args.execute:
        success = mode_execute(logger)
    elif args.reverse:
        success = mode_reverse(logger)
    elif args.status:
        success = mode_status(logger)
    elif args.sandbox_prep:
        success = mode_sandbox_prep(logger)
    elif args.sandbox_apply:
        success = mode_sandbox_apply(logger)
    elif args.sandbox_build:
        success = mode_sandbox_build(logger)
    elif args.sandbox_report:
        success = mode_sandbox_report(logger)
    elif args.sandbox_cleanup:
        success = mode_sandbox_cleanup(logger)
    else:
        logger.error("No valid mode specified.")
        success = False

    logger.info("")
    if success:
        logger.info("Done.")
    else:
        logger.error("Operation completed with errors or was cancelled.")
        sys.exit(1)


if __name__ == "__main__":
    main()
