#!/usr/bin/env python3
"""Generate the first-party Kain Rust Bazel workspace overlay."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import sync_rust_builds as legacy


IGNORED_TOP_LEVEL = {
    ".git",
    ".kain",
    "$RECYCLE.BIN",
    "System Volume Information",
    "bazel-bin",
    "bazel-out",
    "bazel-testlogs",
    "target",
}
IGNORED_FILENAMES = {
    "BUILD",
    "BUILD.bazel",
    "MODULE.bazel",
    "MODULE.bazel.lock",
    "WORKSPACE",
    "WORKSPACE.bazel",
}
EXTERNAL_ROOT_BUILD = """# @generated by tools/bazel/kain_rust_workspace_generator.py
load("@@//tools/bazel:kain_public_targets.bzl", "declare_kain_public_targets")

package(default_visibility = ["//visibility:public"])

declare_kain_public_targets()
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-repo-root", required=True)
    parser.add_argument("--output-root", required=True)
    parser.add_argument("--repo-name", default="kain_workspace_rust")
    parser.add_argument("--cargo-bin", default="cargo")
    parser.add_argument("--write-watch-file")
    args = parser.parse_args()

    source_repo_root = Path(args.source_repo_root).resolve()
    output_root = Path(args.output_root).resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    clear_output_root(output_root)

    packages = legacy.load_workspace_packages(source_repo_root, cargo_bin=args.cargo_bin)
    package_dirs = {
        package.directory.relative_to(source_repo_root).as_posix()
        for package in packages
    }

    mirror_workspace_overlay(source_repo_root, output_root, package_dirs)
    write_generated_workspace(
        source_repo_root=source_repo_root,
        output_root=output_root,
        repo_name=args.repo_name,
        packages=packages,
    )

    if args.write_watch_file:
        watch_file = Path(args.write_watch_file)
        watch_payload = sorted(
            {
                str(source_repo_root / "Cargo.toml"),
                str(source_repo_root / "Cargo.lock"),
                str(source_repo_root / "tools" / "bazel" / "kain_rust_workspace_generator.py"),
                str(source_repo_root / "tools" / "bazel" / "sync_rust_builds.py"),
                *[str(package.directory) for package in packages],
            }
        )
        watch_file.write_text(json.dumps(watch_payload, indent=2), encoding="utf-8")

    print(f"generated first-party Rust workspace overlay for {len(packages)} packages")
    return 0


def write_generated_workspace(
    *,
    source_repo_root: Path,
    output_root: Path,
    repo_name: str,
    packages: list[legacy.Package],
) -> None:
    workspace_labels = legacy.workspace_package_labels(packages, source_repo_root)
    workspace_features = legacy.workspace_package_features(packages)
    proc_macro_packages = {
        package.name
        for package in packages
        if any("proc-macro" in target.crate_types for target in package.targets)
    }

    for package in packages:
        relative_directory = package.directory.relative_to(source_repo_root)
        build_path = output_root / relative_directory / "BUILD.bazel"
        build_path.parent.mkdir(parents=True, exist_ok=True)
        build_path.write_text(
            legacy.render_build_file(
                package,
                workspace_labels,
                workspace_features,
                proc_macro_packages,
            ),
            encoding="utf-8",
        )

    (output_root / "WORKSPACE.bazel").write_text(
        f'workspace(name = "{repo_name}")\n',
        encoding="utf-8",
    )
    (output_root / "BUILD.bazel").write_text(EXTERNAL_ROOT_BUILD, encoding="utf-8")


def mirror_workspace_overlay(source_root: Path, output_root: Path, package_dirs: set[str]) -> None:
    package_ancestors = {
        ancestor
        for package_dir in package_dirs
        for ancestor in ancestors_of(package_dir)
    }

    for child in sorted(source_root.iterdir(), key=lambda entry: entry.name.lower()):
        if child.name in IGNORED_TOP_LEVEL:
            continue
        mirror_entry(
            source_path=child,
            source_root=source_root,
            output_root=output_root,
            package_dirs=package_dirs,
            package_ancestors=package_ancestors,
        )


def clear_output_root(output_root: Path) -> None:
    for child in output_root.iterdir():
        if child.is_symlink() or child.is_file():
            child.unlink()
        else:
            shutil.rmtree(child)


def mirror_entry(
    *,
    source_path: Path,
    source_root: Path,
    output_root: Path,
    package_dirs: set[str],
    package_ancestors: set[str],
) -> None:
    relative = source_path.relative_to(source_root)
    relative_posix = relative.as_posix()
    destination = output_root / relative

    if source_path.name in IGNORED_FILENAMES:
        return

    if source_path.is_dir():
        if relative_posix in package_dirs:
            destination.mkdir(parents=True, exist_ok=True)
            for child in sorted(source_path.iterdir(), key=lambda entry: entry.name.lower()):
                if child.name in IGNORED_FILENAMES:
                    continue
                link_or_copy(child, destination / child.name)
            return

        if relative_posix in package_ancestors:
            destination.mkdir(parents=True, exist_ok=True)
            for child in sorted(source_path.iterdir(), key=lambda entry: entry.name.lower()):
                mirror_entry(
                    source_path=child,
                    source_root=source_root,
                    output_root=output_root,
                    package_dirs=package_dirs,
                    package_ancestors=package_ancestors,
                )
            return

    link_or_copy(source_path, destination)


def ancestors_of(path_text: str) -> list[str]:
    parts = path_text.split("/")
    ancestors = []
    for index in range(1, len(parts)):
        ancestors.append("/".join(parts[:index]))
    return ancestors


def link_or_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.is_symlink() or destination.is_file():
        destination.unlink()
    elif destination.is_dir():
        shutil.rmtree(destination)
    try:
        if source.is_dir():
            os.symlink(source, destination, target_is_directory=True)
        else:
            os.symlink(source, destination, target_is_directory=False)
        return
    except OSError:
        pass

    if source.is_dir():
        if destination.exists():
            return
        shutil.copytree(source, destination)
    else:
        shutil.copy2(source, destination)


if __name__ == "__main__":
    raise SystemExit(main())
