#!/usr/bin/env python3
"""Generate Bazel manifest data for the native runtime C/C++ bundle."""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
RUNTIME_DIR = REPO_ROOT / "runtime"
OUTPUT_PATH = RUNTIME_DIR / "runtime_manifest_data.bzl"
HEADER = """# @generated by tools/bazel/sync_native_runtime_builds.py
# Do not edit by hand; update runtime/*.toml and rerun the generator.
"""
HEADER_EXTENSIONS = (".h", ".hpp", ".hh", ".hxx", ".inc", ".inl")
CPP_EXTENSIONS = {".cc", ".cpp", ".cxx", ".mm"}
WINDOWS_LINKOPT_PREFIX = "/DEFAULTLIB:"


@dataclass(frozen=True)
class RuntimeManifestSpec:
    symbol_name: str
    manifest_path: Path


MANIFEST_SPECS = (
    RuntimeManifestSpec(
        symbol_name="NATIVE_CORE_RUNTIME",
        manifest_path=RUNTIME_DIR / "native_core_runtime.toml",
    ),
    RuntimeManifestSpec(
        symbol_name="NATIVE_RUNTIME",
        manifest_path=RUNTIME_DIR / "native_runtime.toml",
    ),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if runtime_manifest_data.bzl is missing or stale",
    )
    args = parser.parse_args()

    rendered = render_output()
    if args.check:
        existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
        if existing != rendered:
            print(f"stale: {OUTPUT_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("Run: py -3 tools/bazel/sync_native_runtime_builds.py", file=sys.stderr)
            return 1
        print("checked native runtime Bazel manifest data")
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"generated {OUTPUT_PATH.relative_to(REPO_ROOT)}")
    return 0


def render_output() -> str:
    lines: list[str] = [HEADER.rstrip(), ""]
    for spec in MANIFEST_SPECS:
        manifest = parse_runtime_manifest(spec.manifest_path)
        lines.extend(render_manifest(spec.symbol_name, manifest))
    lines.append("NATIVE_RUNTIME_ACTOR_TESTS = [")
    lines.append('    "native/tests/test_actor_monitor_link.c",')
    lines.append('    "native/tests/test_actor_supervision.c",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def render_manifest(symbol_name: str, manifest: dict[str, object]) -> list[str]:
    lines = [f"{symbol_name} = {{"]
    field_order = [
        "name",
        "includes",
        "header_globs",
        "common_c_srcs",
        "common_cpp_srcs",
        "windows_c_srcs",
        "windows_cpp_srcs",
        "linux_c_srcs",
        "linux_cpp_srcs",
        "macos_c_srcs",
        "macos_cpp_srcs",
        "common_defines",
        "windows_defines",
        "linux_defines",
        "macos_defines",
        "windows_linkopts",
        "linux_linkopts",
        "macos_linkopts",
        "has_cpp_sources",
    ]
    for key in field_order:
        value = manifest[key]
        if isinstance(value, list):
            lines.append(f'    "{key}": [')
            for item in value:
                lines.append(f"        {item!r},")
            lines.append("    ],")
        else:
            lines.append(f'    "{key}": {value!r},')
    lines.append("}")
    lines.append("")
    return lines


def parse_runtime_manifest(path: Path) -> dict[str, object]:
    arrays: dict[tuple[str | None, str], list[str]] = {}
    scalars: dict[tuple[str | None, str], object] = {}
    section_name: str | None = None
    lines = path.read_text(encoding="utf-8").splitlines()
    line_index = 0
    while line_index < len(lines):
        cleaned_line = strip_comments(lines[line_index]).strip()
        if not cleaned_line:
            line_index += 1
            continue
        if cleaned_line.startswith("[[") and cleaned_line.endswith("]]"):
            section_name = cleaned_line[2:-2].strip()
            line_index += 1
            continue
        if cleaned_line.startswith("[") and cleaned_line.endswith("]"):
            section_name = cleaned_line[1:-1].strip()
            line_index += 1
            continue
        if "=" not in cleaned_line:
            line_index += 1
            continue

        key, raw_value = [part.strip() for part in cleaned_line.split("=", 1)]
        if raw_value.startswith("["):
            array_text = raw_value
            while "]" not in array_text:
                line_index += 1
                if line_index >= len(lines):
                    raise ValueError(f"unterminated array for {key} in {path}")
                next_line = strip_comments(lines[line_index]).strip()
                if next_line:
                    array_text = f"{array_text} {next_line}"
            arrays[(section_name, key)] = parse_string_array(array_text)
        else:
            scalars[(section_name, key)] = ast.literal_eval(raw_value)
        line_index += 1

    common_sources = arrays.get((None, "sources"), [])
    windows_sources = arrays.get((None, "windows_sources"), [])
    linux_sources = arrays.get((None, "linux_sources"), [])
    macos_sources = arrays.get((None, "macos_sources"), [])
    common_c_srcs, common_cpp_srcs = split_sources(common_sources)
    windows_c_srcs, windows_cpp_srcs = split_sources(windows_sources)
    linux_c_srcs, linux_cpp_srcs = split_sources(linux_sources)
    macos_c_srcs, macos_cpp_srcs = split_sources(macos_sources)
    include_dirs = arrays.get((None, "include_dirs"), [])
    windows_link_libraries = arrays.get(("link", "windows"), [])
    linux_link_libraries = arrays.get(("link", "linux"), [])
    macos_link_libraries = arrays.get(("link", "macos"), [])

    return {
        "name": scalars.get((None, "name"), path.stem),
        "includes": include_dirs,
        "header_globs": build_header_globs(include_dirs),
        "common_c_srcs": common_c_srcs,
        "common_cpp_srcs": common_cpp_srcs,
        "windows_c_srcs": windows_c_srcs,
        "windows_cpp_srcs": windows_cpp_srcs,
        "linux_c_srcs": linux_c_srcs,
        "linux_cpp_srcs": linux_cpp_srcs,
        "macos_c_srcs": macos_c_srcs,
        "macos_cpp_srcs": macos_cpp_srcs,
        "common_defines": arrays.get((None, "defines"), []),
        "windows_defines": arrays.get((None, "windows_defines"), []),
        "linux_defines": arrays.get((None, "linux_defines"), []),
        "macos_defines": arrays.get((None, "macos_defines"), []),
        "windows_linkopts": [format_windows_linkopt(library) for library in windows_link_libraries],
        "linux_linkopts": [format_posix_linkopt(library) for library in linux_link_libraries],
        "macos_linkopts": [format_posix_linkopt(library) for library in macos_link_libraries],
        "has_cpp_sources": bool(
            common_cpp_srcs or windows_cpp_srcs or linux_cpp_srcs or macos_cpp_srcs
        ),
    }


def strip_comments(line: str) -> str:
    result: list[str] = []
    in_string = False
    escape_active = False
    for char in line:
        if escape_active:
            result.append(char)
            escape_active = False
            continue
        if char == "\\":
            result.append(char)
            escape_active = True
            continue
        if char == '"':
            result.append(char)
            in_string = not in_string
            continue
        if char == "#" and not in_string:
            break
        result.append(char)
    return "".join(result)


def parse_string_array(value: str) -> list[str]:
    parsed = ast.literal_eval(value)
    if not isinstance(parsed, list):
        raise TypeError(f"expected list literal, got {type(parsed).__name__}")
    result: list[str] = []
    for item in parsed:
        if not isinstance(item, str):
            raise TypeError(f"expected string list item, got {type(item).__name__}")
        result.append(item)
    return result


def split_sources(sources: list[str]) -> tuple[list[str], list[str]]:
    c_sources: list[str] = []
    cpp_sources: list[str] = []
    for source in sources:
        extension = Path(source).suffix.lower()
        if extension in CPP_EXTENSIONS:
            cpp_sources.append(source)
        else:
            c_sources.append(source)
    return c_sources, cpp_sources


def build_header_globs(include_dirs: list[str]) -> list[str]:
    patterns: list[str] = []
    for include_dir in include_dirs:
        normalized = include_dir.strip("/")
        for extension in HEADER_EXTENSIONS:
            patterns.append(f"{normalized}/*{extension}")
            patterns.append(f"{normalized}/**/*{extension}")
    return sorted(dict.fromkeys(patterns))


def format_windows_linkopt(library_name: str) -> str:
    if library_name.lower().endswith(".lib"):
        return f"{WINDOWS_LINKOPT_PREFIX}{library_name}"
    return f"{WINDOWS_LINKOPT_PREFIX}{library_name}.lib"


def format_posix_linkopt(library_name: str) -> str:
    if library_name.startswith("-l"):
        return library_name
    return f"-l{library_name}"


if __name__ == "__main__":
    raise SystemExit(main())
