//! Experimental C code generation for KAIN native targets.
//!
//! This backend intentionally supports a smaller, explicit subset than LLVM.
//! Unsupported constructs fail with codegen errors instead of emitting invalid C.

use kain_core::ast::{
    BinaryOp, Block, ConvergeDef, ElseBranch, Enum, EnumVariantFields, Expr, Function, LawDef,
    OrchestrateDef, Param, PatchDef, Pattern, Stmt, Struct, Type, UnaryOp, VariantFields, WorldDef,
};
use kain_core::error::{KainError, KainResult};
use kain_core::span::Span;
use kain_core::types::{TypedItem, TypedProgram};
use kain_core::{lower_typed_program_memory_for_target, CompileTarget};
use std::collections::{HashMap, HashSet};

pub fn generate(program: &TypedProgram) -> KainResult<String> {
    let lowered = lower_typed_program_memory_for_target(program, CompileTarget::C)?;
    let mut gen = CGen::new();
    gen.gen_program(&lowered)
}

struct StringBuilder {
    lines: Vec<String>,
}

impl StringBuilder {
    fn new() -> Self {
        Self { lines: Vec::new() }
    }

    fn push_line(&mut self, text: &str) {
        self.lines.push(format!("{text}\n"));
    }

    fn build(self) -> String {
        self.lines.join("")
    }
}

struct CGen {
    output: StringBuilder,
    indent: usize,
    world_names: HashSet<String>,
    local_types: HashMap<String, String>,
    function_return_types: HashMap<String, String>,
    has_entanglements: bool,
}

impl CGen {
    fn new() -> Self {
        Self {
            output: StringBuilder::new(),
            indent: 0,
            world_names: HashSet::new(),
            local_types: HashMap::new(),
            function_return_types: HashMap::new(),
            has_entanglements: false,
        }
    }

    fn gen_program(&mut self, program: &TypedProgram) -> KainResult<String> {
        self.collect_world_names(program);
        self.collect_callable_return_types(program)?;

        self.write_line("/* Generated by the KAIN Compiler. */");
        self.write_line(
            "/* Experimental C backend: unsupported constructs fail during codegen. */",
        );
        self.write_blank();
        self.write_line("#include <stdbool.h>");
        self.write_line("#include <stddef.h>");
        self.write_line("#include <stdint.h>");
        self.write_line("#include <stdio.h>");
        self.write_line("#include <string.h>");
        self.write_blank();
        self.write_line("typedef void* Any;");
        self.write_blank();
        self.write_print_helpers();
        self.write_blank();

        for item in &program.items {
            match item {
                TypedItem::Struct(st) => {
                    self.write_line(&format!("typedef struct {} {};", st.ast.name, st.ast.name));
                }
                TypedItem::World(world) => {
                    self.write_line(&format!(
                        "typedef struct {} {};",
                        world.ast.name, world.ast.name
                    ));
                }
                _ => {}
            }
        }
        if program
            .items
            .iter()
            .any(|item| matches!(item, TypedItem::Struct(_) | TypedItem::World(_)))
        {
            self.write_blank();
        }

        for item in &program.items {
            match item {
                TypedItem::Struct(st) => self.gen_struct_decl(&st.ast)?,
                TypedItem::World(world) => self.gen_world_decl(&world.ast)?,
                TypedItem::Enum(en) => self.gen_enum_decl(&en.ast)?,
                _ => {}
            }
        }
        if program.items.iter().any(|item| {
            matches!(
                item,
                TypedItem::Struct(_) | TypedItem::World(_) | TypedItem::Enum(_)
            )
        }) {
            self.write_blank();
        }

        self.gen_entangle_metadata(program)?;
        if program
            .items
            .iter()
            .any(|item| matches!(item, TypedItem::Entangle(_)))
        {
            self.write_blank();
        }

        for item in &program.items {
            if let Some(signature) = self.callable_item_signature(item)? {
                self.write_line(&format!("{signature};"));
            }
        }
        if program.items.iter().any(Self::item_is_c_callable) {
            self.write_blank();
        }

        for item in &program.items {
            match item {
                TypedItem::Function(function) => {
                    if !Self::function_is_extern(&function.ast) {
                        self.gen_function(&function.ast)?;
                        self.write_blank();
                    }
                }
                TypedItem::Patch(patch) => {
                    self.gen_patch(&patch.ast)?;
                    self.write_blank();
                }
                TypedItem::Law(law) => {
                    self.gen_law(&law.ast)?;
                    self.write_blank();
                }
                TypedItem::Converge(converge) => {
                    self.gen_converge(&converge.ast)?;
                    self.write_blank();
                }
                TypedItem::Orchestrate(orchestrate) => {
                    self.gen_orchestrate(&orchestrate.ast)?;
                    self.write_blank();
                }
                TypedItem::Struct(st) => {
                    for method in &st.ast.methods {
                        if !Self::function_is_extern(method) {
                            self.gen_function(method)?;
                            self.write_blank();
                        }
                    }
                }
                TypedItem::Impl(imp) => {
                    for method in &imp.ast.methods {
                        if !Self::function_is_extern(method) {
                            self.gen_function(method)?;
                            self.write_blank();
                        }
                    }
                }
                TypedItem::Const(_)
                | TypedItem::TypeAlias(_)
                | TypedItem::Shader(_)
                | TypedItem::Actor(_)
                | TypedItem::Component(_)
                | TypedItem::Enum(_)
                | TypedItem::World(_)
                | TypedItem::Entangle(_)
                | TypedItem::Mod(_) => {}
                _ => {}
            }
        }

        Ok(std::mem::replace(&mut self.output, StringBuilder::new()).build())
    }

    fn collect_world_names(&mut self, program: &TypedProgram) {
        for item in &program.items {
            if let TypedItem::World(world) = item {
                self.world_names.insert(world.ast.name.clone());
            }
        }
    }

    fn collect_callable_return_types(&mut self, program: &TypedProgram) -> KainResult<()> {
        for item in &program.items {
            match item {
                TypedItem::Function(function) => {
                    self.function_return_types.insert(
                        function.ast.name.clone(),
                        self.callable_return_type(
                            &function.ast.name,
                            function.ast.return_type.as_ref(),
                        )?,
                    );
                }
                TypedItem::Patch(patch) => {
                    self.function_return_types.insert(
                        patch.ast.name.clone(),
                        self.callable_return_type(&patch.ast.name, patch.ast.return_type.as_ref())?,
                    );
                }
                TypedItem::Law(law) => {
                    self.function_return_types.insert(
                        law.ast.name.clone(),
                        self.callable_return_type(&law.ast.name, Some(&law.ast.return_type))?,
                    );
                }
                TypedItem::Converge(converge) => {
                    self.function_return_types.insert(
                        converge.ast.name.clone(),
                        self.callable_return_type(
                            &converge.ast.name,
                            converge.ast.return_type.as_ref(),
                        )?,
                    );
                }
                TypedItem::Orchestrate(orchestrate) => {
                    self.function_return_types.insert(
                        orchestrate.ast.name.clone(),
                        self.callable_return_type(
                            &orchestrate.ast.name,
                            orchestrate.ast.return_type.as_ref(),
                        )?,
                    );
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn item_is_c_callable(item: &TypedItem) -> bool {
        matches!(
            item,
            TypedItem::Function(_)
                | TypedItem::Patch(_)
                | TypedItem::Law(_)
                | TypedItem::Converge(_)
                | TypedItem::Orchestrate(_)
        )
    }

    fn function_is_extern(function: &Function) -> bool {
        function
            .attributes
            .iter()
            .any(|attribute| attribute.name == "extern")
    }

    fn callable_item_signature(&self, item: &TypedItem) -> KainResult<Option<String>> {
        match item {
            TypedItem::Function(function) => Ok(Some(self.function_signature(&function.ast)?)),
            TypedItem::Patch(patch) => Ok(Some(self.callable_signature_parts(
                &patch.ast.name,
                &patch.ast.params,
                patch.ast.return_type.as_ref(),
            )?)),
            TypedItem::Law(law) => Ok(Some(self.callable_signature_parts(
                &law.ast.name,
                &law.ast.params,
                Some(&law.ast.return_type),
            )?)),
            TypedItem::Converge(converge) => Ok(Some(self.callable_signature_parts(
                &converge.ast.name,
                &converge.ast.params,
                converge.ast.return_type.as_ref(),
            )?)),
            TypedItem::Orchestrate(orchestrate) => Ok(Some(self.callable_signature_parts(
                &orchestrate.ast.name,
                &orchestrate.ast.params,
                orchestrate.ast.return_type.as_ref(),
            )?)),
            _ => Ok(None),
        }
    }

    fn gen_entangle_metadata(&mut self, program: &TypedProgram) -> KainResult<()> {
        let entanglements = program
            .items
            .iter()
            .filter_map(|item| match item {
                TypedItem::Entangle(entangle) => Some(entangle),
                _ => None,
            })
            .collect::<Vec<_>>();

        if entanglements.is_empty() {
            return Ok(());
        }
        self.has_entanglements = true;

        self.write_line(
            "int64_t abi_entangle_register(const char * authority, const char * mirror, const char * policy, const char * type_name);",
        );
        self.write_line("typedef struct KainCEntangleBinding {");
        self.push_indent();
        self.write_line("const char *authority;");
        self.write_line("const char *mirror;");
        self.write_line("const char *policy;");
        self.write_line("const char *type_name;");
        self.pop_indent();
        self.write_line("} KainCEntangleBinding;");
        self.write_line("static const KainCEntangleBinding __kain_entanglements[] = {");
        self.push_indent();
        for entangle in entanglements {
            self.write_line(&format!(
                "{{ \"{}\", \"{}\", \"{}\", \"{}\" }},",
                self.escape_string(&entangle.ast.left.authored_path()),
                self.escape_string(&entangle.ast.right.authored_path()),
                self.escape_string(entangle.ast.policy.as_str()),
                self.escape_string(&entangle.endpoint_type_name)
            ));
        }
        self.pop_indent();
        self.write_line("};");
        self.write_line(
            "static const size_t __kain_entanglement_count = sizeof(__kain_entanglements) / sizeof(__kain_entanglements[0]);",
        );
        self.write_line("static void __kain_register_entanglements(void) {");
        self.push_indent();
        self.write_line("for (size_t index = 0; index < __kain_entanglement_count; index++) {");
        self.push_indent();
        self.write_line("const KainCEntangleBinding *binding = &__kain_entanglements[index];");
        self.write_line("(void)abi_entangle_register(binding->authority, binding->mirror, binding->policy, binding->type_name);");
        self.pop_indent();
        self.write_line("}");
        self.pop_indent();
        self.write_line("}");
        Ok(())
    }

    fn write_print_helpers(&mut self) {
        self.write_line("static void __kain_write_cstr(const char *value) { fputs(value ? value : \"\", stdout); }");
        self.write_line("static void __kain_write_bool(bool value) { fputs(value ? \"true\" : \"false\", stdout); }");
        self.write_line(
            "static void __kain_write_i64(int64_t value) { printf(\"%lld\", (long long)value); }",
        );
        self.write_line("static void __kain_write_f64(double value) { printf(\"%f\", value); }");
        self.write_line("static void __kain_write_unsupported_ptr(const void *value) { (void)value; fputs(\"<unsupported>\", stdout); }");
        self.write_line("#define __KAIN_WRITE_VALUE(value) _Generic((value), \\");
        self.write_line("    const char *: __kain_write_cstr, \\");
        self.write_line("    char *: __kain_write_cstr, \\");
        self.write_line("    bool: __kain_write_bool, \\");
        self.write_line("    int: __kain_write_i64, \\");
        self.write_line("    long: __kain_write_i64, \\");
        self.write_line("    long long: __kain_write_i64, \\");
        self.write_line("    int64_t: __kain_write_i64, \\");
        self.write_line("    double: __kain_write_f64, \\");
        self.write_line("    default: __kain_write_unsupported_ptr \\");
        self.write_line(")(value)");
    }

    fn gen_struct_decl(&mut self, struct_def: &Struct) -> KainResult<()> {
        self.write_line(&format!("struct {} {{", struct_def.name));
        self.push_indent();
        for field in &struct_def.fields {
            self.write_line(&format!("{} {};", self.map_type(&field.ty)?, field.name));
        }
        self.pop_indent();
        self.write_line("};");
        Ok(())
    }

    fn gen_world_decl(&mut self, world: &WorldDef) -> KainResult<()> {
        self.write_line(&format!("struct {} {{", world.name));
        self.push_indent();
        for state in &world.states {
            self.write_line(&format!("{} {};", self.map_type(&state.ty)?, state.name));
        }
        self.pop_indent();
        self.write_line("};");

        let rendered_states = world
            .states
            .iter()
            .map(|state| {
                Ok(format!(
                    ".{} = {}",
                    state.name,
                    self.gen_expr(&state.initial)?
                ))
            })
            .collect::<KainResult<Vec<_>>>()?;
        self.write_line(&format!(
            "static {} __kain_world_{} = {{{}}};",
            world.name,
            world.name,
            rendered_states.join(", ")
        ));
        Ok(())
    }

    fn gen_enum_decl(&mut self, enum_def: &Enum) -> KainResult<()> {
        if !enum_def
            .variants
            .iter()
            .all(|variant| matches!(variant.fields, VariantFields::Unit))
        {
            return Err(self.unsupported(
                format!(
                    "C backend currently only supports unit enums; enum '{}' has payload variants",
                    enum_def.name
                ),
                Span::default(),
            ));
        }

        self.write_line(&format!("typedef enum {} {{", enum_def.name));
        self.push_indent();
        for variant in &enum_def.variants {
            self.write_line(&format!("{}_{} ,", enum_def.name, variant.name));
        }
        self.pop_indent();
        self.write_line(&format!("}} {};", enum_def.name));
        Ok(())
    }

    fn gen_function(&mut self, function: &Function) -> KainResult<()> {
        self.begin_function_scope(&function.params)?;
        self.write_line(&format!("{} {{", self.function_signature(function)?));
        self.push_indent();
        if function.name == "main" && self.has_entanglements {
            self.write_line("__kain_register_entanglements();");
        }
        let needs_implicit_return = function.return_type.is_some();
        self.gen_block_with_implicit_return(&function.body, needs_implicit_return)?;
        if function.name == "main" && function.return_type.is_none() {
            self.write_line("return 0;");
        }
        self.pop_indent();
        self.write_line("}");
        Ok(())
    }

    fn gen_patch(&mut self, patch: &PatchDef) -> KainResult<()> {
        self.gen_named_callable(
            &patch.name,
            &patch.params,
            patch.return_type.as_ref(),
            &patch.body,
        )
    }

    fn gen_law(&mut self, law: &LawDef) -> KainResult<()> {
        self.gen_named_callable(&law.name, &law.params, Some(&law.return_type), &law.body)
    }

    fn gen_converge(&mut self, converge: &ConvergeDef) -> KainResult<()> {
        self.gen_named_callable(
            &converge.name,
            &converge.params,
            converge.return_type.as_ref(),
            &converge.spec_lane.body,
        )
    }

    fn gen_orchestrate(&mut self, orchestrate: &OrchestrateDef) -> KainResult<()> {
        self.gen_named_callable(
            &orchestrate.name,
            &orchestrate.params,
            orchestrate.return_type.as_ref(),
            &orchestrate.body,
        )
    }

    fn gen_named_callable(
        &mut self,
        name: &str,
        params: &[Param],
        return_type: Option<&Type>,
        body: &Block,
    ) -> KainResult<()> {
        self.begin_function_scope(params)?;
        self.write_line(&format!(
            "{} {{",
            self.callable_signature_parts(name, params, return_type)?
        ));
        self.push_indent();
        self.gen_block_with_implicit_return(body, return_type.is_some())?;
        self.pop_indent();
        self.write_line("}");
        Ok(())
    }

    fn begin_function_scope(&mut self, params: &[Param]) -> KainResult<()> {
        self.local_types.clear();
        for param in params {
            self.local_types
                .insert(param.name.clone(), self.map_type(&param.ty)?);
        }
        Ok(())
    }

    fn function_signature(&self, function: &Function) -> KainResult<String> {
        self.callable_signature_parts(
            &function.name,
            &function.params,
            function.return_type.as_ref(),
        )
    }

    fn callable_signature_parts(
        &self,
        name: &str,
        params: &[Param],
        return_type: Option<&Type>,
    ) -> KainResult<String> {
        let return_type = self.callable_return_type(name, return_type)?;
        let params = self.gen_params(params)?;
        Ok(format!("{return_type} {name}({params})"))
    }

    fn callable_return_type(&self, name: &str, return_type: Option<&Type>) -> KainResult<String> {
        if name == "main" {
            Ok("int".to_string())
        } else if let Some(return_type) = return_type {
            self.map_type(return_type)
        } else {
            Ok("void".to_string())
        }
    }

    fn gen_params(&self, params: &[Param]) -> KainResult<String> {
        if params.is_empty() {
            return Ok("void".to_string());
        }
        let mut rendered = Vec::with_capacity(params.len());
        for param in params {
            rendered.push(format!("{} {}", self.map_type(&param.ty)?, param.name));
        }
        Ok(rendered.join(", "))
    }

    fn gen_block_with_implicit_return(
        &mut self,
        block: &Block,
        implicit_return: bool,
    ) -> KainResult<()> {
        let last_index = block.stmts.len().saturating_sub(1);
        for (index, stmt) in block.stmts.iter().enumerate() {
            if implicit_return && index == last_index {
                if let Stmt::Expr(expr) = stmt {
                    if !matches!(
                        expr,
                        Expr::Return(_, _) | Expr::Break(_, _) | Expr::Continue(_)
                    ) {
                        self.write_line(&format!("return {};", self.gen_expr(expr)?));
                        continue;
                    }
                }
            }
            self.gen_stmt(stmt)?;
        }
        Ok(())
    }

    fn gen_block(&mut self, block: &Block) -> KainResult<()> {
        for stmt in &block.stmts {
            self.gen_stmt(stmt)?;
        }
        Ok(())
    }

    fn gen_stmt(&mut self, stmt: &Stmt) -> KainResult<()> {
        match stmt {
            Stmt::Let {
                pattern, ty, value, ..
            } => {
                let Pattern::Binding { name, .. } = pattern else {
                    return Err(self.unsupported(
                        "C backend only supports simple let bindings".to_string(),
                        Span::default(),
                    ));
                };
                let type_name = if let Some(explicit_type) = ty {
                    self.map_type(explicit_type)?
                } else if let Some(value) = value {
                    self.infer_expr_type(value)?
                } else {
                    return Err(self.unsupported(
                        format!("C backend cannot infer an uninitialized local '{name}'"),
                        Span::default(),
                    ));
                };
                if let Some(value) = value {
                    self.write_line(&format!("{type_name} {name} = {};", self.gen_expr(value)?));
                } else {
                    self.write_line(&format!("{type_name} {name};"));
                }
                self.local_types.insert(name.clone(), type_name);
            }
            Stmt::Return(expr, _) => {
                if let Some(expr) = expr {
                    self.write_line(&format!("return {};", self.gen_expr(expr)?));
                } else {
                    self.write_line("return;");
                }
            }
            Stmt::Break(_, _) => self.write_line("break;"),
            Stmt::Continue(_) => self.write_line("continue;"),
            Stmt::For { .. } => {
                return Err(self.unsupported(
                    "C backend does not yet support KAIN for-loops".to_string(),
                    Span::default(),
                ));
            }
            Stmt::While {
                condition, body, ..
            } => {
                self.write_line(&format!("while ({}) {{", self.gen_expr(condition)?));
                self.push_indent();
                self.gen_block(body)?;
                self.pop_indent();
                self.write_line("}");
            }
            Stmt::Loop { body, .. } => {
                self.write_line("while (true) {");
                self.push_indent();
                self.gen_block(body)?;
                self.pop_indent();
                self.write_line("}");
            }
            Stmt::Expr(expr) => match expr {
                Expr::If {
                    condition,
                    then_branch,
                    else_branch,
                    ..
                } => self.gen_if_stmt(condition, then_branch, else_branch)?,
                Expr::Assign { target, value, .. } => {
                    self.write_line(&format!(
                        "{} = {};",
                        self.gen_expr(target)?,
                        self.gen_expr(value)?
                    ));
                }
                _ => {
                    let expr = self.gen_expr(expr)?;
                    if !expr.is_empty() {
                        self.write_line(&format!("{expr};"));
                    }
                }
            },
            Stmt::Item(_) => {}
        }
        Ok(())
    }

    fn gen_if_stmt(
        &mut self,
        condition: &Expr,
        then_branch: &Block,
        else_branch: &Option<Box<ElseBranch>>,
    ) -> KainResult<()> {
        self.write_line(&format!("if ({}) {{", self.gen_expr(condition)?));
        self.push_indent();
        self.gen_block(then_branch)?;
        self.pop_indent();

        if let Some(else_branch) = else_branch {
            self.gen_else_branch_continuation(else_branch)?;
        } else {
            self.write_line("}");
        }
        Ok(())
    }

    fn gen_else_branch_continuation(&mut self, branch: &ElseBranch) -> KainResult<()> {
        match branch {
            ElseBranch::Else(block) => {
                self.write_line("} else {");
                self.push_indent();
                self.gen_block(block)?;
                self.pop_indent();
                self.write_line("}");
            }
            ElseBranch::ElseIf(condition, block, next_else) => {
                self.write_line(&format!("}} else if ({}) {{", self.gen_expr(condition)?));
                self.push_indent();
                self.gen_block(block)?;
                self.pop_indent();
                if let Some(next_else) = next_else {
                    self.gen_else_branch_continuation(next_else)?;
                } else {
                    self.write_line("}");
                }
            }
        }
        Ok(())
    }

    fn gen_expr(&self, expr: &Expr) -> KainResult<String> {
        match expr {
            Expr::Int(value, _) => Ok(value.to_string()),
            Expr::Float(value, _) => Ok(format!("{value:.6}")),
            Expr::String(value, _) => Ok(format!("\"{}\"", self.escape_string(value))),
            Expr::Bool(value, _) => Ok(if *value { "true" } else { "false" }.to_string()),
            Expr::Ident(name, _) if self.world_names.contains(name) => {
                Ok(format!("(&__kain_world_{name})"))
            }
            Expr::Ident(name, _) => Ok(name.clone()),
            Expr::None(_) => Ok("NULL".to_string()),
            Expr::Binary {
                left, op, right, ..
            } => {
                if matches!(op, BinaryOp::Eq | BinaryOp::Ne) {
                    let left_ty = self.infer_expr_type(left).ok();
                    let right_ty = self.infer_expr_type(right).ok();
                    if left_ty.as_deref() == Some("const char *")
                        || right_ty.as_deref() == Some("const char *")
                    {
                        let comparison = if matches!(op, BinaryOp::Eq) {
                            "== 0"
                        } else {
                            "!= 0"
                        };
                        return Ok(format!(
                            "(strcmp({}, {}) {})",
                            self.gen_expr(left)?,
                            self.gen_expr(right)?,
                            comparison
                        ));
                    }
                }
                Ok(format!(
                    "({} {} {})",
                    self.gen_expr(left)?,
                    self.map_binop(op)?,
                    self.gen_expr(right)?
                ))
            }
            Expr::Unary { op, operand, .. } => Ok(format!(
                "({}{})",
                self.map_unaryop(op),
                self.gen_expr(operand)?
            )),
            Expr::Call { callee, args, .. } => {
                let callee_name = self.gen_expr(callee)?;
                if callee_name == "print" || callee_name == "println" {
                    return self.gen_print_call(callee_name == "println", args);
                }
                let rendered_args = args
                    .iter()
                    .map(|arg| self.gen_expr(&arg.value))
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!("{callee_name}({})", rendered_args.join(", ")))
            }
            Expr::StageCall {
                runtime,
                function,
                args,
                ..
            } => {
                let rendered_args = args
                    .iter()
                    .map(|arg| self.gen_expr(&arg.value))
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!(
                    "/* orchestrate stage {} */ {}({})",
                    runtime.as_str(),
                    function,
                    rendered_args.join(", ")
                ))
            }
            Expr::MethodCall {
                receiver,
                method,
                args,
                ..
            } => {
                let rendered_args = args
                    .iter()
                    .map(|arg| self.gen_expr(&arg.value))
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!(
                    "{}.{}({})",
                    self.gen_expr(receiver)?,
                    method,
                    rendered_args.join(", ")
                ))
            }
            Expr::Spawn { actor, init, .. } => Ok(format!(
                "abi_actor_spawn(\"{}\", \"{}\")",
                self.escape_string(actor),
                self.escape_string(&self.render_actor_payload_pairs(init)?)
            )),
            Expr::SendMsg {
                target,
                message,
                data,
                ..
            } => Ok(format!(
                "abi_actor_send({}, \"{}\", \"{}\")",
                self.gen_expr(target)?,
                self.escape_string(message),
                self.escape_string(&self.render_actor_payload_pairs(data)?)
            )),
            Expr::Field { object, field, .. } => self.gen_field_access(object, field),
            Expr::Index { object, index, .. } => Ok(format!(
                "{}[{}]",
                self.gen_expr(object)?,
                self.gen_expr(index)?
            )),
            Expr::Struct { name, fields, .. } => {
                let rendered_fields = fields
                    .iter()
                    .map(|(field_name, value)| {
                        Ok(format!(".{field_name} = {}", self.gen_expr(value)?))
                    })
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!("({name}){{{}}}", rendered_fields.join(", ")))
            }
            Expr::EnumVariant {
                enum_name,
                variant,
                fields,
                ..
            } => match fields {
                EnumVariantFields::Unit => Ok(format!("{enum_name}_{variant}")),
                EnumVariantFields::Tuple(_) | EnumVariantFields::Struct(_) => Err(self
                    .unsupported(
                        format!(
                            "C backend only supports unit enum variants; '{}::{}' carries data",
                            enum_name, variant
                        ),
                        Span::default(),
                    )),
            },
            Expr::If {
                condition,
                then_branch,
                else_branch,
                ..
            } => self.gen_if_expr(condition, then_branch, else_branch),
            Expr::Ref { value, .. } => Ok(format!("&{}", self.gen_expr(value)?)),
            Expr::Deref(value, _) => Ok(format!("*{}", self.gen_expr(value)?)),
            Expr::Cast { value, target, .. } => Ok(format!(
                "(({}) {})",
                self.map_type(target)?,
                self.gen_expr(value)?
            )),
            Expr::Teleport { value, .. } => self.gen_expr(value),
            Expr::Paren(inner, _) => Ok(format!("({})", self.gen_expr(inner)?)),
            Expr::Return(expr, _) => {
                if let Some(expr) = expr {
                    Ok(format!("return {}", self.gen_expr(expr)?))
                } else {
                    Ok("return".to_string())
                }
            }
            Expr::Break(_, _) => Ok("break".to_string()),
            Expr::Continue(_) => Ok("continue".to_string()),
            Expr::Array(_, _)
            | Expr::Tuple(_, _)
            | Expr::Match { .. }
            | Expr::Lambda { .. }
            | Expr::Range { .. }
            | Expr::Block(_, _)
            | Expr::FString(_, _)
            | Expr::Assign { .. } => Err(self.unsupported(
                format!("C backend does not yet support expression form '{expr:?}'"),
                Span::default(),
            )),
            _ => Err(self.unsupported(
                format!("C backend does not yet support expression form '{expr:?}'"),
                Span::default(),
            )),
        }
    }

    fn gen_field_access(&self, object: &Expr, field: &str) -> KainResult<String> {
        if let Expr::Ident(name, _) = object {
            if self.world_names.contains(name) {
                return Ok(format!("(&__kain_world_{name})->{field}"));
            }
            if self
                .local_types
                .get(name)
                .map(|ty| ty.trim_end().ends_with('*'))
                .unwrap_or(false)
            {
                return Ok(format!("{name}->{field}"));
            }
        }

        Ok(format!("{}.{}", self.gen_expr(object)?, field))
    }

    fn gen_print_call(
        &self,
        newline: bool,
        args: &[kain_core::ast::CallArg],
    ) -> KainResult<String> {
        let mut parts = Vec::new();
        for (index, arg) in args.iter().enumerate() {
            if index > 0 {
                parts.push("fputs(\" \", stdout)".to_string());
            }
            parts.push(format!(
                "__KAIN_WRITE_VALUE({})",
                self.gen_expr(&arg.value)?
            ));
        }
        if newline {
            parts.push("fputc('\\n', stdout)".to_string());
        }
        if parts.is_empty() {
            Ok(if newline {
                "fputc('\\n', stdout)".to_string()
            } else {
                String::new()
            })
        } else if parts.len() == 1 {
            Ok(parts.remove(0))
        } else {
            Ok(format!("({})", parts.join(", ")))
        }
    }

    fn gen_if_expr(
        &self,
        condition: &Expr,
        then_branch: &Block,
        else_branch: &Option<Box<ElseBranch>>,
    ) -> KainResult<String> {
        let Some(ElseBranch::Else(else_block)) = else_branch.as_deref() else {
            return Err(self.unsupported(
                "C backend only supports if-expressions with a concrete else block".to_string(),
                Span::default(),
            ));
        };
        if then_branch.stmts.len() != 1 || else_block.stmts.len() != 1 {
            return Err(self.unsupported(
                "C backend only supports single-expression if-expressions".to_string(),
                Span::default(),
            ));
        }
        let Stmt::Expr(then_expr) = &then_branch.stmts[0] else {
            return Err(self.unsupported(
                "C backend if-expression then-branch must end with an expression".to_string(),
                Span::default(),
            ));
        };
        let Stmt::Expr(else_expr) = &else_block.stmts[0] else {
            return Err(self.unsupported(
                "C backend if-expression else-branch must end with an expression".to_string(),
                Span::default(),
            ));
        };
        Ok(format!(
            "({} ? {} : {})",
            self.gen_expr(condition)?,
            self.gen_expr(then_expr)?,
            self.gen_expr(else_expr)?
        ))
    }

    fn infer_expr_type(&self, expr: &Expr) -> KainResult<String> {
        match expr {
            Expr::Int(_, _) => Ok("int64_t".to_string()),
            Expr::Float(_, _) => Ok("double".to_string()),
            Expr::String(_, _) => Ok("const char *".to_string()),
            Expr::Bool(_, _) => Ok("bool".to_string()),
            Expr::Ident(name, _) if self.world_names.contains(name) => Ok(format!("{name}*")),
            Expr::Struct { name, .. } => Ok(name.clone()),
            Expr::Teleport { value, .. } => self.infer_expr_type(value),
            Expr::Spawn { .. } | Expr::SendMsg { .. } => Ok("int64_t".to_string()),
            Expr::Call { callee, .. } => {
                if let Expr::Ident(name, _) = callee.as_ref() {
                    if let Some(return_type) = self.function_return_types.get(name) {
                        return Ok(return_type.clone());
                    }
                }
                Err(self.unsupported(
                    format!("C backend cannot infer the local type for call expression '{expr:?}'"),
                    Span::default(),
                ))
            }
            Expr::Binary { left, op, .. } => match op {
                BinaryOp::And
                | BinaryOp::Or
                | BinaryOp::Eq
                | BinaryOp::Ne
                | BinaryOp::Lt
                | BinaryOp::Le
                | BinaryOp::Gt
                | BinaryOp::Ge => Ok("bool".to_string()),
                BinaryOp::Add
                | BinaryOp::Sub
                | BinaryOp::Mul
                | BinaryOp::Div
                | BinaryOp::Mod
                | BinaryOp::BitAnd
                | BinaryOp::BitOr
                | BinaryOp::BitXor
                | BinaryOp::Shl
                | BinaryOp::Shr => self.infer_expr_type(left),
                BinaryOp::Assign
                | BinaryOp::AddAssign
                | BinaryOp::SubAssign
                | BinaryOp::MulAssign
                | BinaryOp::DivAssign
                | BinaryOp::Pow
                | BinaryOp::Range
                | BinaryOp::RangeInclusive => Err(self.unsupported(
                    format!("C backend cannot infer the local type for binary op '{op:?}'"),
                    Span::default(),
                )),
            },
            Expr::StageCall { function, .. } => self
                .function_return_types
                .get(function)
                .cloned()
                .ok_or_else(|| {
                    self.unsupported(
                        format!(
                            "C backend cannot infer the local type for stage call '{}'",
                            function
                        ),
                        Span::default(),
                    )
                }),
            _ => Err(self.unsupported(
                format!("C backend cannot infer the local type for expression '{expr:?}'"),
                Span::default(),
            )),
        }
    }

    fn render_actor_payload_pairs(&self, pairs: &[(String, Expr)]) -> KainResult<String> {
        let rendered = pairs
            .iter()
            .map(|(name, value)| {
                Ok(format!(
                    "{}={}",
                    name,
                    self.render_actor_payload_value(value)?
                ))
            })
            .collect::<KainResult<Vec<_>>>()?;
        Ok(rendered.join(";"))
    }

    fn render_actor_payload_value(&self, value: &Expr) -> KainResult<String> {
        match value {
            Expr::Int(value, _) => Ok(value.to_string()),
            Expr::Float(value, _) => Ok(format!("{value:.6}")),
            Expr::String(value, _) => Ok(value.clone()),
            Expr::Bool(value, _) => Ok(if *value { "true" } else { "false" }.to_string()),
            Expr::Ident(name, _) => Ok(format!("${name}")),
            _ => Ok(format!("<{}>", self.gen_expr(value)?)),
        }
    }

    fn map_type(&self, ty: &Type) -> KainResult<String> {
        match ty {
            Type::Named { name, generics, .. } => {
                if !generics.is_empty() {
                    return Err(self.unsupported(
                        format!("C backend does not yet support generic type '{name}'"),
                        Span::default(),
                    ));
                }
                Ok(match name.as_str() {
                    "Int" | "isize" | "i64" => "int64_t",
                    "UInt" | "usize" | "u64" => "uint64_t",
                    "i32" => "int32_t",
                    "u32" => "uint32_t",
                    "i16" => "int16_t",
                    "u16" => "uint16_t",
                    "i8" => "int8_t",
                    "u8" => "uint8_t",
                    "Float" => "double",
                    "Bool" => "bool",
                    "String" => "const char *",
                    "Char" => "char",
                    "Unit" | "()" => "void",
                    _ if self.world_names.contains(name) => return Ok(format!("{name}*")),
                    _ => name,
                }
                .to_string())
            }
            Type::Ref { inner, .. } | Type::Ptr { inner, .. } => {
                Ok(format!("{}*", self.map_type(inner)?))
            }
            Type::Unit(_) => Ok("void".to_string()),
            Type::Function { .. } => Ok("void*".to_string()),
            Type::Infer(_) => Err(self.unsupported(
                "C backend requires concrete types after type checking".to_string(),
                Span::default(),
            )),
            Type::Tuple(_, _)
            | Type::Array(_, _, _)
            | Type::Slice(_, _)
            | Type::Option(_, _)
            | Type::Result(_, _, _)
            | Type::Never(_)
            | Type::Impl { .. } => Err(self.unsupported(
                format!("C backend does not yet support type '{ty:?}'"),
                Span::default(),
            )),
        }
    }

    fn map_binop(&self, op: &BinaryOp) -> KainResult<&'static str> {
        match op {
            BinaryOp::Add => Ok("+"),
            BinaryOp::Sub => Ok("-"),
            BinaryOp::Mul => Ok("*"),
            BinaryOp::Div => Ok("/"),
            BinaryOp::Mod => Ok("%"),
            BinaryOp::And => Ok("&&"),
            BinaryOp::Or => Ok("||"),
            BinaryOp::Eq => Ok("=="),
            BinaryOp::Ne => Ok("!="),
            BinaryOp::Lt => Ok("<"),
            BinaryOp::Le => Ok("<="),
            BinaryOp::Gt => Ok(">"),
            BinaryOp::Ge => Ok(">="),
            BinaryOp::BitAnd => Ok("&"),
            BinaryOp::BitOr => Ok("|"),
            BinaryOp::BitXor => Ok("^"),
            BinaryOp::Shl => Ok("<<"),
            BinaryOp::Shr => Ok(">>"),
            BinaryOp::Assign
            | BinaryOp::AddAssign
            | BinaryOp::SubAssign
            | BinaryOp::MulAssign
            | BinaryOp::DivAssign
            | BinaryOp::Pow
            | BinaryOp::Range
            | BinaryOp::RangeInclusive => Err(self.unsupported(
                format!(
                    "C backend does not support binary operator '{op:?}' in expression context"
                ),
                Span::default(),
            )),
        }
    }

    fn map_unaryop(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::Ref | UnaryOp::RefMut => "&",
            UnaryOp::BitNot => "~",
            UnaryOp::Deref => "*",
        }
    }

    fn escape_string(&self, value: &str) -> String {
        let mut escaped = String::new();
        for ch in value.chars() {
            match ch {
                '\n' => escaped.push_str("\\n"),
                '\t' => escaped.push_str("\\t"),
                '\\' => escaped.push_str("\\\\"),
                '"' => escaped.push_str("\\\""),
                _ => escaped.push(ch),
            }
        }
        escaped
    }

    fn unsupported(&self, message: String, span: Span) -> KainError {
        KainError::codegen(message, span)
    }

    fn write_line(&mut self, line: &str) {
        self.output
            .push_line(&format!("{}{}", "    ".repeat(self.indent), line));
    }

    fn write_blank(&mut self) {
        self.output.push_line("");
    }

    fn push_indent(&mut self) {
        self.indent += 1;
    }

    fn pop_indent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }
}
