//! Experimental C code generation for KAIN native targets.
//!
//! This backend intentionally supports a smaller, explicit subset than LLVM.
//! Unsupported constructs fail with codegen errors instead of emitting invalid C.

use kain_core::ast::{
    BinaryOp, Block, ElseBranch, Enum, EnumVariantFields, Expr, Function, Param, Pattern, Stmt,
    Struct, Type, UnaryOp, VariantFields,
};
use kain_core::error::{KainError, KainResult};
use kain_core::span::Span;
use kain_core::types::{TypedItem, TypedProgram};
use kain_core::{lower_typed_program_memory_for_target, CompileTarget};

pub fn generate(program: &TypedProgram) -> KainResult<String> {
    let lowered = lower_typed_program_memory_for_target(program, CompileTarget::C)?;
    let mut gen = CGen::new();
    gen.gen_program(&lowered)
}

struct StringBuilder {
    lines: Vec<String>,
}

impl StringBuilder {
    fn new() -> Self {
        Self { lines: Vec::new() }
    }

    fn push_line(&mut self, text: &str) {
        self.lines.push(format!("{text}\n"));
    }

    fn build(self) -> String {
        self.lines.join("")
    }
}

struct CGen {
    output: StringBuilder,
    indent: usize,
}

impl CGen {
    fn new() -> Self {
        Self {
            output: StringBuilder::new(),
            indent: 0,
        }
    }

    fn gen_program(&mut self, program: &TypedProgram) -> KainResult<String> {
        self.write_line("/* Generated by the KAIN Compiler. */");
        self.write_line(
            "/* Experimental C backend: unsupported constructs fail during codegen. */",
        );
        self.write_blank();
        self.write_line("#include <stdbool.h>");
        self.write_line("#include <stddef.h>");
        self.write_line("#include <stdint.h>");
        self.write_line("#include <stdio.h>");
        self.write_blank();
        self.write_print_helpers();
        self.write_blank();

        for item in &program.items {
            if let TypedItem::Struct(st) = item {
                self.write_line(&format!("typedef struct {} {};", st.ast.name, st.ast.name));
            }
        }
        if program
            .items
            .iter()
            .any(|item| matches!(item, TypedItem::Struct(_)))
        {
            self.write_blank();
        }

        for item in &program.items {
            match item {
                TypedItem::Struct(st) => self.gen_struct_decl(&st.ast)?,
                TypedItem::Enum(en) => self.gen_enum_decl(&en.ast)?,
                _ => {}
            }
        }
        if program
            .items
            .iter()
            .any(|item| matches!(item, TypedItem::Struct(_) | TypedItem::Enum(_)))
        {
            self.write_blank();
        }

        for item in &program.items {
            if let TypedItem::Function(function) = item {
                self.write_line(&format!("{};", self.function_signature(&function.ast)?));
            }
        }
        if program
            .items
            .iter()
            .any(|item| matches!(item, TypedItem::Function(_)))
        {
            self.write_blank();
        }

        for item in &program.items {
            match item {
                TypedItem::Function(function) => {
                    self.gen_function(&function.ast)?;
                    self.write_blank();
                }
                TypedItem::Struct(st) => {
                    for method in &st.ast.methods {
                        self.gen_function(method)?;
                        self.write_blank();
                    }
                }
                TypedItem::Impl(imp) => {
                    for method in &imp.ast.methods {
                        self.gen_function(method)?;
                        self.write_blank();
                    }
                }
                TypedItem::Const(_)
                | TypedItem::TypeAlias(_)
                | TypedItem::Shader(_)
                | TypedItem::Actor(_)
                | TypedItem::Component(_)
                | TypedItem::Enum(_)
                | TypedItem::Mod(_) => {}
                _ => {}
            }
        }

        Ok(std::mem::replace(&mut self.output, StringBuilder::new()).build())
    }

    fn write_print_helpers(&mut self) {
        self.write_line("static void __kain_write_cstr(const char *value) { fputs(value ? value : \"\", stdout); }");
        self.write_line("static void __kain_write_bool(bool value) { fputs(value ? \"true\" : \"false\", stdout); }");
        self.write_line(
            "static void __kain_write_i64(int64_t value) { printf(\"%lld\", (long long)value); }",
        );
        self.write_line("static void __kain_write_f64(double value) { printf(\"%f\", value); }");
        self.write_line("static void __kain_write_unsupported_ptr(const void *value) { (void)value; fputs(\"<unsupported>\", stdout); }");
        self.write_line("#define __KAIN_WRITE_VALUE(value) _Generic((value), \\");
        self.write_line("    const char *: __kain_write_cstr, \\");
        self.write_line("    char *: __kain_write_cstr, \\");
        self.write_line("    bool: __kain_write_bool, \\");
        self.write_line("    int: __kain_write_i64, \\");
        self.write_line("    long: __kain_write_i64, \\");
        self.write_line("    long long: __kain_write_i64, \\");
        self.write_line("    int64_t: __kain_write_i64, \\");
        self.write_line("    double: __kain_write_f64, \\");
        self.write_line("    default: __kain_write_unsupported_ptr \\");
        self.write_line(")(value)");
    }

    fn gen_struct_decl(&mut self, struct_def: &Struct) -> KainResult<()> {
        self.write_line(&format!("struct {} {{", struct_def.name));
        self.push_indent();
        for field in &struct_def.fields {
            self.write_line(&format!("{} {};", self.map_type(&field.ty)?, field.name));
        }
        self.pop_indent();
        self.write_line("};");
        Ok(())
    }

    fn gen_enum_decl(&mut self, enum_def: &Enum) -> KainResult<()> {
        if !enum_def
            .variants
            .iter()
            .all(|variant| matches!(variant.fields, VariantFields::Unit))
        {
            return Err(self.unsupported(
                format!(
                    "C backend currently only supports unit enums; enum '{}' has payload variants",
                    enum_def.name
                ),
                Span::default(),
            ));
        }

        self.write_line(&format!("typedef enum {} {{", enum_def.name));
        self.push_indent();
        for variant in &enum_def.variants {
            self.write_line(&format!("{}_{} ,", enum_def.name, variant.name));
        }
        self.pop_indent();
        self.write_line(&format!("}} {};", enum_def.name));
        Ok(())
    }

    fn gen_function(&mut self, function: &Function) -> KainResult<()> {
        self.write_line(&format!("{} {{", self.function_signature(function)?));
        self.push_indent();
        let needs_implicit_return = function.return_type.is_some();
        self.gen_block_with_implicit_return(&function.body, needs_implicit_return)?;
        if function.name == "main" && function.return_type.is_none() {
            self.write_line("return 0;");
        }
        self.pop_indent();
        self.write_line("}");
        Ok(())
    }

    fn function_signature(&self, function: &Function) -> KainResult<String> {
        let return_type = if function.name == "main" && function.return_type.is_none() {
            "int".to_string()
        } else if let Some(return_type) = &function.return_type {
            self.map_type(return_type)?
        } else {
            "void".to_string()
        };
        let params = self.gen_params(&function.params)?;
        Ok(format!("{return_type} {}({params})", function.name))
    }

    fn gen_params(&self, params: &[Param]) -> KainResult<String> {
        if params.is_empty() {
            return Ok("void".to_string());
        }
        let mut rendered = Vec::with_capacity(params.len());
        for param in params {
            rendered.push(format!("{} {}", self.map_type(&param.ty)?, param.name));
        }
        Ok(rendered.join(", "))
    }

    fn gen_block_with_implicit_return(
        &mut self,
        block: &Block,
        implicit_return: bool,
    ) -> KainResult<()> {
        let last_index = block.stmts.len().saturating_sub(1);
        for (index, stmt) in block.stmts.iter().enumerate() {
            if implicit_return && index == last_index {
                if let Stmt::Expr(expr) = stmt {
                    if !matches!(
                        expr,
                        Expr::Return(_, _) | Expr::Break(_, _) | Expr::Continue(_)
                    ) {
                        self.write_line(&format!("return {};", self.gen_expr(expr)?));
                        continue;
                    }
                }
            }
            self.gen_stmt(stmt)?;
        }
        Ok(())
    }

    fn gen_block(&mut self, block: &Block) -> KainResult<()> {
        for stmt in &block.stmts {
            self.gen_stmt(stmt)?;
        }
        Ok(())
    }

    fn gen_stmt(&mut self, stmt: &Stmt) -> KainResult<()> {
        match stmt {
            Stmt::Let {
                pattern, ty, value, ..
            } => {
                let Pattern::Binding { name, .. } = pattern else {
                    return Err(self.unsupported(
                        "C backend only supports simple let bindings".to_string(),
                        Span::default(),
                    ));
                };
                let type_name = if let Some(explicit_type) = ty {
                    self.map_type(explicit_type)?
                } else if let Some(value) = value {
                    self.infer_expr_type(value)?
                } else {
                    return Err(self.unsupported(
                        format!("C backend cannot infer an uninitialized local '{name}'"),
                        Span::default(),
                    ));
                };
                if let Some(value) = value {
                    self.write_line(&format!("{type_name} {name} = {};", self.gen_expr(value)?));
                } else {
                    self.write_line(&format!("{type_name} {name};"));
                }
            }
            Stmt::Return(expr, _) => {
                if let Some(expr) = expr {
                    self.write_line(&format!("return {};", self.gen_expr(expr)?));
                } else {
                    self.write_line("return;");
                }
            }
            Stmt::Break(_, _) => self.write_line("break;"),
            Stmt::Continue(_) => self.write_line("continue;"),
            Stmt::For { .. } => {
                return Err(self.unsupported(
                    "C backend does not yet support KAIN for-loops".to_string(),
                    Span::default(),
                ));
            }
            Stmt::While {
                condition, body, ..
            } => {
                self.write_line(&format!("while ({}) {{", self.gen_expr(condition)?));
                self.push_indent();
                self.gen_block(body)?;
                self.pop_indent();
                self.write_line("}");
            }
            Stmt::Loop { body, .. } => {
                self.write_line("while (true) {");
                self.push_indent();
                self.gen_block(body)?;
                self.pop_indent();
                self.write_line("}");
            }
            Stmt::Expr(expr) => match expr {
                Expr::If {
                    condition,
                    then_branch,
                    else_branch,
                    ..
                } => self.gen_if_stmt(condition, then_branch, else_branch)?,
                Expr::Assign { target, value, .. } => {
                    self.write_line(&format!(
                        "{} = {};",
                        self.gen_expr(target)?,
                        self.gen_expr(value)?
                    ));
                }
                _ => {
                    let expr = self.gen_expr(expr)?;
                    if !expr.is_empty() {
                        self.write_line(&format!("{expr};"));
                    }
                }
            },
            Stmt::Item(_) => {}
        }
        Ok(())
    }

    fn gen_if_stmt(
        &mut self,
        condition: &Expr,
        then_branch: &Block,
        else_branch: &Option<Box<ElseBranch>>,
    ) -> KainResult<()> {
        self.write_line(&format!("if ({}) {{", self.gen_expr(condition)?));
        self.push_indent();
        self.gen_block(then_branch)?;
        self.pop_indent();

        if let Some(else_branch) = else_branch {
            self.gen_else_branch_continuation(else_branch)?;
        } else {
            self.write_line("}");
        }
        Ok(())
    }

    fn gen_else_branch_continuation(&mut self, branch: &ElseBranch) -> KainResult<()> {
        match branch {
            ElseBranch::Else(block) => {
                self.write_line("} else {");
                self.push_indent();
                self.gen_block(block)?;
                self.pop_indent();
                self.write_line("}");
            }
            ElseBranch::ElseIf(condition, block, next_else) => {
                self.write_line(&format!("}} else if ({}) {{", self.gen_expr(condition)?));
                self.push_indent();
                self.gen_block(block)?;
                self.pop_indent();
                if let Some(next_else) = next_else {
                    self.gen_else_branch_continuation(next_else)?;
                } else {
                    self.write_line("}");
                }
            }
        }
        Ok(())
    }

    fn gen_expr(&self, expr: &Expr) -> KainResult<String> {
        match expr {
            Expr::Int(value, _) => Ok(value.to_string()),
            Expr::Float(value, _) => Ok(format!("{value:.6}")),
            Expr::String(value, _) => Ok(format!("\"{}\"", self.escape_string(value))),
            Expr::Bool(value, _) => Ok(if *value { "true" } else { "false" }.to_string()),
            Expr::Ident(name, _) => Ok(name.clone()),
            Expr::None(_) => Ok("NULL".to_string()),
            Expr::Binary {
                left, op, right, ..
            } => Ok(format!(
                "({} {} {})",
                self.gen_expr(left)?,
                self.map_binop(op)?,
                self.gen_expr(right)?
            )),
            Expr::Unary { op, operand, .. } => Ok(format!(
                "({}{})",
                self.map_unaryop(op),
                self.gen_expr(operand)?
            )),
            Expr::Call { callee, args, .. } => {
                let callee_name = self.gen_expr(callee)?;
                if callee_name == "print" || callee_name == "println" {
                    return self.gen_print_call(callee_name == "println", args);
                }
                let rendered_args = args
                    .iter()
                    .map(|arg| self.gen_expr(&arg.value))
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!("{callee_name}({})", rendered_args.join(", ")))
            }
            Expr::MethodCall {
                receiver,
                method,
                args,
                ..
            } => {
                let rendered_args = args
                    .iter()
                    .map(|arg| self.gen_expr(&arg.value))
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!(
                    "{}.{}({})",
                    self.gen_expr(receiver)?,
                    method,
                    rendered_args.join(", ")
                ))
            }
            Expr::Field { object, field, .. } => {
                Ok(format!("{}.{}", self.gen_expr(object)?, field))
            }
            Expr::Index { object, index, .. } => Ok(format!(
                "{}[{}]",
                self.gen_expr(object)?,
                self.gen_expr(index)?
            )),
            Expr::Struct { name, fields, .. } => {
                let rendered_fields = fields
                    .iter()
                    .map(|(field_name, value)| {
                        Ok(format!(".{field_name} = {}", self.gen_expr(value)?))
                    })
                    .collect::<KainResult<Vec<_>>>()?;
                Ok(format!("({name}){{{}}}", rendered_fields.join(", ")))
            }
            Expr::EnumVariant {
                enum_name,
                variant,
                fields,
                ..
            } => match fields {
                EnumVariantFields::Unit => Ok(format!("{enum_name}_{variant}")),
                EnumVariantFields::Tuple(_) | EnumVariantFields::Struct(_) => Err(self
                    .unsupported(
                        format!(
                            "C backend only supports unit enum variants; '{}::{}' carries data",
                            enum_name, variant
                        ),
                        Span::default(),
                    )),
            },
            Expr::If {
                condition,
                then_branch,
                else_branch,
                ..
            } => self.gen_if_expr(condition, then_branch, else_branch),
            Expr::Ref { value, .. } => Ok(format!("&{}", self.gen_expr(value)?)),
            Expr::Deref(value, _) => Ok(format!("*{}", self.gen_expr(value)?)),
            Expr::Cast { value, target, .. } => Ok(format!(
                "(({}) {})",
                self.map_type(target)?,
                self.gen_expr(value)?
            )),
            Expr::Paren(inner, _) => Ok(format!("({})", self.gen_expr(inner)?)),
            Expr::Return(expr, _) => {
                if let Some(expr) = expr {
                    Ok(format!("return {}", self.gen_expr(expr)?))
                } else {
                    Ok("return".to_string())
                }
            }
            Expr::Break(_, _) => Ok("break".to_string()),
            Expr::Continue(_) => Ok("continue".to_string()),
            Expr::Array(_, _)
            | Expr::Tuple(_, _)
            | Expr::Match { .. }
            | Expr::Lambda { .. }
            | Expr::Range { .. }
            | Expr::Block(_, _)
            | Expr::FString(_, _)
            | Expr::Assign { .. } => Err(self.unsupported(
                format!("C backend does not yet support expression form '{expr:?}'"),
                Span::default(),
            )),
            _ => Err(self.unsupported(
                format!("C backend does not yet support expression form '{expr:?}'"),
                Span::default(),
            )),
        }
    }

    fn gen_print_call(
        &self,
        newline: bool,
        args: &[kain_core::ast::CallArg],
    ) -> KainResult<String> {
        let mut parts = Vec::new();
        for (index, arg) in args.iter().enumerate() {
            if index > 0 {
                parts.push("fputs(\" \", stdout)".to_string());
            }
            parts.push(format!(
                "__KAIN_WRITE_VALUE({})",
                self.gen_expr(&arg.value)?
            ));
        }
        if newline {
            parts.push("fputc('\\n', stdout)".to_string());
        }
        if parts.is_empty() {
            Ok(if newline {
                "fputc('\\n', stdout)".to_string()
            } else {
                String::new()
            })
        } else if parts.len() == 1 {
            Ok(parts.remove(0))
        } else {
            Ok(format!("({})", parts.join(", ")))
        }
    }

    fn gen_if_expr(
        &self,
        condition: &Expr,
        then_branch: &Block,
        else_branch: &Option<Box<ElseBranch>>,
    ) -> KainResult<String> {
        let Some(ElseBranch::Else(else_block)) = else_branch.as_deref() else {
            return Err(self.unsupported(
                "C backend only supports if-expressions with a concrete else block".to_string(),
                Span::default(),
            ));
        };
        if then_branch.stmts.len() != 1 || else_block.stmts.len() != 1 {
            return Err(self.unsupported(
                "C backend only supports single-expression if-expressions".to_string(),
                Span::default(),
            ));
        }
        let Stmt::Expr(then_expr) = &then_branch.stmts[0] else {
            return Err(self.unsupported(
                "C backend if-expression then-branch must end with an expression".to_string(),
                Span::default(),
            ));
        };
        let Stmt::Expr(else_expr) = &else_block.stmts[0] else {
            return Err(self.unsupported(
                "C backend if-expression else-branch must end with an expression".to_string(),
                Span::default(),
            ));
        };
        Ok(format!(
            "({} ? {} : {})",
            self.gen_expr(condition)?,
            self.gen_expr(then_expr)?,
            self.gen_expr(else_expr)?
        ))
    }

    fn infer_expr_type(&self, expr: &Expr) -> KainResult<String> {
        match expr {
            Expr::Int(_, _) => Ok("int64_t".to_string()),
            Expr::Float(_, _) => Ok("double".to_string()),
            Expr::String(_, _) => Ok("const char *".to_string()),
            Expr::Bool(_, _) => Ok("bool".to_string()),
            Expr::Struct { name, .. } => Ok(name.clone()),
            _ => Err(self.unsupported(
                format!("C backend cannot infer the local type for expression '{expr:?}'"),
                Span::default(),
            )),
        }
    }

    fn map_type(&self, ty: &Type) -> KainResult<String> {
        match ty {
            Type::Named { name, generics, .. } => {
                if !generics.is_empty() {
                    return Err(self.unsupported(
                        format!("C backend does not yet support generic type '{name}'"),
                        Span::default(),
                    ));
                }
                Ok(match name.as_str() {
                    "Int" | "isize" | "usize" => "int64_t",
                    "Float" => "double",
                    "Bool" => "bool",
                    "String" => "const char *",
                    "Char" => "char",
                    "Unit" | "()" => "void",
                    _ => name,
                }
                .to_string())
            }
            Type::Ref { inner, .. } | Type::Ptr { inner, .. } => {
                Ok(format!("{}*", self.map_type(inner)?))
            }
            Type::Unit(_) => Ok("void".to_string()),
            Type::Infer(_) => Err(self.unsupported(
                "C backend requires concrete types after type checking".to_string(),
                Span::default(),
            )),
            Type::Tuple(_, _)
            | Type::Array(_, _, _)
            | Type::Slice(_, _)
            | Type::Function { .. }
            | Type::Option(_, _)
            | Type::Result(_, _, _)
            | Type::Never(_)
            | Type::Impl { .. } => Err(self.unsupported(
                format!("C backend does not yet support type '{ty:?}'"),
                Span::default(),
            )),
        }
    }

    fn map_binop(&self, op: &BinaryOp) -> KainResult<&'static str> {
        match op {
            BinaryOp::Add => Ok("+"),
            BinaryOp::Sub => Ok("-"),
            BinaryOp::Mul => Ok("*"),
            BinaryOp::Div => Ok("/"),
            BinaryOp::Mod => Ok("%"),
            BinaryOp::And => Ok("&&"),
            BinaryOp::Or => Ok("||"),
            BinaryOp::Eq => Ok("=="),
            BinaryOp::Ne => Ok("!="),
            BinaryOp::Lt => Ok("<"),
            BinaryOp::Le => Ok("<="),
            BinaryOp::Gt => Ok(">"),
            BinaryOp::Ge => Ok(">="),
            BinaryOp::BitAnd => Ok("&"),
            BinaryOp::BitOr => Ok("|"),
            BinaryOp::BitXor => Ok("^"),
            BinaryOp::Shl => Ok("<<"),
            BinaryOp::Shr => Ok(">>"),
            BinaryOp::Assign
            | BinaryOp::AddAssign
            | BinaryOp::SubAssign
            | BinaryOp::MulAssign
            | BinaryOp::DivAssign
            | BinaryOp::Pow
            | BinaryOp::Range
            | BinaryOp::RangeInclusive => Err(self.unsupported(
                format!(
                    "C backend does not support binary operator '{op:?}' in expression context"
                ),
                Span::default(),
            )),
        }
    }

    fn map_unaryop(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::Ref | UnaryOp::RefMut => "&",
            UnaryOp::BitNot => "~",
            UnaryOp::Deref => "*",
        }
    }

    fn escape_string(&self, value: &str) -> String {
        let mut escaped = String::new();
        for ch in value.chars() {
            match ch {
                '\n' => escaped.push_str("\\n"),
                '\t' => escaped.push_str("\\t"),
                '\\' => escaped.push_str("\\\\"),
                '"' => escaped.push_str("\\\""),
                _ => escaped.push(ch),
            }
        }
        escaped
    }

    fn unsupported(&self, message: String, span: Span) -> KainError {
        KainError::codegen(message, span)
    }

    fn write_line(&mut self, line: &str) {
        self.output
            .push_line(&format!("{}{}", "    ".repeat(self.indent), line));
    }

    fn write_blank(&mut self) {
        self.output.push_line("");
    }

    fn push_indent(&mut self) {
        self.indent += 1;
    }

    fn pop_indent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }
}
