// Generated by KAIN compiler

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "CombatGraphPinData.generated.h"

class UCombatGraphGraphNodeData;

UCLASS()
class GRAPHRUNTIMETEST_API UCombatGraphPinData
	: public UObject
{
	GENERATED_BODY()

public:
	UPROPERTY()
	FName PinName;

	UPROPERTY()
	FGuid PinId;

	UPROPERTY()
	TArray<UCombatGraphPinData*> ConnectToPins;

	UPROPERTY()
	UCombatGraphGraphNodeData* Parent = nullptr;
};