"""pykain.buffer — normalized buffer crossing for Kain↔Python.

Handles raw byte buffers, shared memory contracts, and future backends.
Returns host objects for buffers, dicts for info, ints for signatures.
"""

from __future__ import annotations

import json
from typing import Any

import numpy as np

from . import _native_loader


def _plan(plan_text: str) -> dict[str, Any]:
    return json.loads(plan_text)


# ═══════════════════════════════════════════════════════════════════════════
#  Buffer creation
# ═══════════════════════════════════════════════════════════════════════════

def grid(plan_text: str, seed: int) -> np.ndarray:
    """Create a test byte grid. Always returns contiguous uint8 numpy array.

    Kain uses python_shared_buffer() on the result.
    """
    plan = _plan(plan_text)
    rows = int(plan.get("tensor_rows", 3))
    cols = int(plan.get("tensor_cols", 4))
    total = rows * cols
    base = np.arange(total, dtype=np.uint8).reshape(rows, cols)
    return np.ascontiguousarray(base + np.uint8(int(seed) % 251))


def grid_signature(plan_text: str, seed: int) -> int:
    return signature(grid(plan_text, seed))


def grid_byte_length(plan_text: str, seed: int) -> int:
    return int(info(grid(plan_text, seed)).get("byte_length", 0))


def grid_contract(plan_text: str, seed: int) -> int:
    """Return 0 when the generated byte grid matches the plan-level buffer contract."""
    try:
        plan = _plan(plan_text)
        rows = int(plan.get("tensor_rows", 3))
        cols = int(plan.get("tensor_cols", 4))
        meta = info(grid(plan_text, seed))
        if not meta.get("valid", False):
            return 1
        shape = meta.get("shape", [])
        if len(shape) != 2 or int(shape[0]) != rows or int(shape[1]) != cols:
            return 2
        if str(meta.get("element_type", "")) != "uint8":
            return 3
        if int(meta.get("element_size", 0)) != 1:
            return 4
        if int(meta.get("byte_length", 0)) != rows * cols:
            return 5
        if str(meta.get("contract", "")) != "kain.shared.buffer":
            return 6
        return 0
    except Exception:
        return 9


def grid_ok(plan_text: str, seed: int) -> bool:
    """Bool-shaped Kain-facing contract probe for current host-object semantics."""
    return grid_contract(plan_text, seed) == 0


def from_bytes(data: bytes, shape: list[int] | None = None) -> np.ndarray:
    """Create a buffer from raw bytes with optional reshape.

    Kain passes python_call_raw("bytes", [kain_array]) to create the bytes,
    then passes them here for normalization into a contiguous numpy array.
    """
    arr = np.frombuffer(data, dtype=np.uint8)
    if shape:
        arr = arr.reshape(tuple(shape))
    return np.ascontiguousarray(arr)


def patterned(size: int, seed: int) -> np.ndarray:
    """Create a patterned byte buffer for testing. Returns 1D uint8 array."""
    return np.ascontiguousarray(
        np.array([(seed + (i * 13)) % 256 for i in range(size)], dtype=np.uint8)
    )


# ═══════════════════════════════════════════════════════════════════════════
#  Info — structured metadata
# ═══════════════════════════════════════════════════════════════════════════

def info(buffer: Any) -> dict[str, Any]:
    """Return normalized buffer metadata as a dict.

    Keys: shape, element_type, element_size, byte_length, element_count,
          backend, contract, is_contiguous, valid.
    """
    try:
        native_info = _native_loader.inspect_object(buffer, kind="buffer")
        if native_info.get("valid"):
            native_info.update({
                "backend": native_info.get("backend", "python"),
                "contract": "kain.shared.buffer",
                "source_backend": native_info.get("backend", "python"),
                "mime_type": native_info.get("mime_type", "application/octet-stream"),
            })
            return native_info

        arr = np.asarray(buffer)
        result: dict[str, Any] = {"valid": False}
        result.update({
            "shape": list(arr.shape),
            "element_type": str(arr.dtype),
            "dtype": str(arr.dtype),
            "element_size": int(arr.dtype.itemsize),
            "byte_length": int(arr.nbytes),
            "element_count": int(arr.size),
            "backend": "numpy",
            "source_runtime": "python",
            "source_backend": "numpy",
            "ownership": "python-borrowed",
            "contract": "kain.shared.buffer",
            "contract_version": 1,
            "is_contiguous": bool(arr.flags["C_CONTIGUOUS"]),
            "is_writeable": bool(arr.flags["WRITEABLE"]),
            "valid": True,
        })
        return result
    except Exception as exc:
        result: dict[str, Any] = {"valid": False}
        result["error"] = str(exc)
        return result


def info_json(buffer: Any) -> str:
    return json.dumps(info(buffer), default=str, separators=(",", ":"))


def signature(buffer: Any) -> int:
    """Checksum: sum of all bytes modulo 1000000007."""
    try:
        return _native_loader.signature(buffer)
    except Exception:
        arr = np.asarray(buffer, dtype=np.uint8)
        return int(arr.sum(dtype=np.int64)) % 1000000007


# ═══════════════════════════════════════════════════════════════════════════
#  Validation
# ═══════════════════════════════════════════════════════════════════════════

def validate(buffer: Any, expected_shape: list[int] | None = None,
             expected_type: str = "", expected_size: int = 0) -> dict[str, Any]:
    """Full validation with optional expected params."""
    result = info(buffer)
    if expected_shape and result.get("shape") != expected_shape:
        result["valid"] = False
        result["error"] = f"shape mismatch: {result.get('shape')} vs {expected_shape}"
    if expected_type and result.get("element_type", "") != expected_type:
        result["valid"] = False
        result["error"] = f"type mismatch: {result.get('element_type')} vs {expected_type}"
    if expected_size > 0 and result.get("element_size", 0) != expected_size:
        result["valid"] = False
        result["error"] = f"elem size mismatch: {result.get('element_size')} vs {expected_size}"
    return result
