// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342332
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"

#include "ASketchfabImportManager.generated.h"

UCLASS()
class SKETCHFAB_API ASketchfabImportManager : public AActor
{
	GENERATED_BODY()

	public:
		ASketchfabImportManager();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		TArray<FString> current_downloads;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		TArray<FString> import_queue;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		int32 max_concurrent_downloads;
		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_StartDownload")
		void Server_StartDownload(const FString& model_uid, const FString& api_token);

		bool Server_StartDownload_Validate(const FString& model_uid, const FString& api_token);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_CancelDownload")
		void Server_CancelDownload(const FString& model_uid);

		bool Server_CancelDownload_Validate(const FString& model_uid);

		UFUNCTION(Client, Reliable, BlueprintCallable, Category = "Client_UpdateProgress")
		void Client_UpdateProgress(const FString& model_uid, const float progress);

		UFUNCTION(NetMulticast, Reliable, BlueprintCallable, Category = "Multicast_NotifyDownloadStarted")
		void Multicast_NotifyDownloadStarted(const FString& model_uid);

		UFUNCTION(NetMulticast, Reliable, BlueprintCallable, Category = "Multicast_NotifyDownloadComplete")
		void Multicast_NotifyDownloadComplete(const FString& model_uid, const bool success);

		UFUNCTION(NetMulticast, Reliable, BlueprintCallable, Category = "Multicast_NotifyDownloadCancelled")
		void Multicast_NotifyDownloadCancelled(const FString& model_uid);

	};

