// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342332
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "ESketchfabSortMode.generated.h"

UENUM(BlueprintType)
enum class ESketchfabSortMode : uint8
{
	Relevance UMETA(DisplayName = "Relevance"),
	LikeCount UMETA(DisplayName = "LikeCount"),
	ViewCount UMETA(DisplayName = "ViewCount"),
	PublishedDate UMETA(DisplayName = "PublishedDate"),
	CreatedDate UMETA(DisplayName = "CreatedDate"),
};

