// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342332
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "FSketchfabDownloadResult.generated.h"

USTRUCT(BlueprintType)
struct SKETCHFAB_API FSketchfabDownloadResult
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabDownloadResult")
	bool success;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabDownloadResult")
	FString download_url;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabDownloadResult")
	FString format;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabDownloadResult")
	FString error_message;

};

