// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342332
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"

#include "FSketchfabModel.generated.h"

USTRUCT(BlueprintType)
struct SKETCHFAB_API FSketchfabModel : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString uid;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString description;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString thumbnail_url;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString author_name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString author_username;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	FString viewer_url;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	int32 like_count;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SketchfabModel")
	int32 view_count;

};

