// Generated by KAIN-PRO Compiler — Data-Driven Module
using UnrealBuildTool;
using System.IO;

public class Materialize : ModuleRules
{
	public Materialize(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"AssetRegistry",
				"Core",
				"CoreUObject",
				"DeveloperSettings",
				"Engine",
				"ImageWrapper",
				"InputCore",
				"Projects",
				"RHI",
				"RenderCore",
				"Renderer"
			}
		);

		PrivateDependencyModuleNames.AddRange(
			new string[]
			{

			}
		);
	}
}
