// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771578113
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"

#include "ATestActor.generated.h"



UCLASS()
class KAIN_API ATestActor : public AActor
{
	GENERATED_BODY()

	public:
		ATestActor();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float health;
		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_TakeDamage")
		void Server_TakeDamage(const float amount);

		bool Server_TakeDamage_Validate(const float amount);

	};


