#!/usr/bin/env python3
"""Generate RuntimeLibcalls.inc from actual RTLIB:: references in source files."""

import subprocess
import os

LLVM_KAIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def get_rtlib_refs():
    """Extract all RTLIB::Xxx references from .cpp and .h files under src/ and include/."""
    exclude_dirs = ["include/core/ir/RuntimeLibcalls.inc"]
    
    result = subprocess.run(
        ["grep", "-rnh", "RTLIB::", "src/", "include/", "--include=*.cpp", "--include=*.h"],
        capture_output=True, text=True, cwd=LLVM_KAIN
    )
    symbols = set()
    for line in result.stdout.splitlines():
        # Skip the .inc file itself
        if ".inc" in line:
            continue
        parts = line.split("RTLIB::")
        for part in parts[1:]:
            sym = ""
            for c in part:
                if c.isalnum() or c == '_':
                    sym += c
                else:
                    break
            # Filter: skip empty, skip 'libcalls' (iteration ref), skip short artifacts
            if sym and sym != "libcalls" and len(sym) > 1:
                # Skip function calls (getXxx), sentinels, and values from other enum
                if sym.startswith("get"):
                    continue
                if sym in ("Libcall", "LibcallImpl", "NumLibcallImpls", "NumLibcallIds", "RuntimeLibcallsInfo", "libcall_impls", "libcalls"):
                    continue
                symbols.add(sym)
    return sorted(symbols)

def main():
    symbols = get_rtlib_refs()
    
    # Separate into Libcall and LibcallImpl
    libcall_impl_symbols = sorted([s for s in symbols if s.startswith("impl_")])
    libcall_symbols = sorted([s for s in symbols if not s.startswith("impl_")])
    
    # Remove sentinels and cross-contamination
    libcall_symbols = [s for s in libcall_symbols if s not in ("Unsupported", "UNKNOWN_LIBCALL", "NumLibcallIds", "NumLibcallImpls")]
    
    lines = []
    lines.append("//===- RuntimeLibcalls.inc - Runtime Library Calls enum -------------------===//")
    lines.append("//")
    lines.append("// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.")
    lines.append("// See https://llvm.org/LICENSE.txt for license information.")
    lines.append("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    lines.append("//")
    lines.append("//===----------------------------------------------------------------------===//")
    lines.append("// Auto-generated by gen-rtlibcalls-inc.py")
    lines.append("//===----------------------------------------------------------------------===//")
    lines.append("")
    lines.append("#if defined(GET_RUNTIME_LIBCALL_ENUM) && !defined(RUNTIME_LIBCALL_ENUM_ALREADY_DEFINED)")
    lines.append("#define RUNTIME_LIBCALL_ENUM_ALREADY_DEFINED")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace llvm {")
    lines.append("namespace RTLIB {")
    lines.append("")
    lines.append("enum Libcall : unsigned {")
    lines.append("  UNKNOWN_LIBCALL = 0,")
    for sym in libcall_symbols:
        lines.append(f"  {sym},")
    lines.append(f"  NumLibcallIds = {len(libcall_symbols) + 1}")
    lines.append("};")
    lines.append("")
    lines.append("enum LibcallImpl : unsigned {")
    lines.append("  Unsupported = 0,")
    for sym in libcall_impl_symbols:
        lines.append(f"  {sym},")
    lines.append(f"  NumLibcallImpls = {len(libcall_impl_symbols) + 1}")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace RTLIB")
    lines.append("} // namespace llvm")
    lines.append("")
    lines.append("#endif // GET_RUNTIME_LIBCALL_ENUM")
    lines.append("")
    lines.append("#ifdef GET_RUNTIME_LIBCALLS_INFO")
    lines.append("// Stub: no runtime libcall info tables.")
    lines.append("#endif")
    lines.append("")
    lines.append("#ifdef GET_INIT_RUNTIME_LIBCALL_NAMES")
    lines.append("// Stub: no runtime libcall name initialization.")
    lines.append("#endif")
    lines.append("")
    lines.append("#ifdef GET_SET_TARGET_RUNTIME_LIBCALL_SETS")
    lines.append("// Stub: no target-specific runtime libcall sets.")
    lines.append("#endif")
    lines.append("")
    lines.append("#ifdef DEFINE_GET_LOOKUP_LIBCALL_IMPL_NAME")
    lines.append("// Stub: empty lookup function.")
    lines.append("iota_range<RTLIB::LibcallImpl> RuntimeLibcallsInfo::lookupLibcallImplNameImpl(StringRef Name) {")
    lines.append("  (void)Name;")
    lines.append("  return libcallImplNameHit(0, 0);")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#ifdef GET_LOOKUP_LIBCALL_IMPL_NAME_BODY")
    lines.append("return iota_range<RTLIB::LibcallImpl>(static_cast<RTLIB::LibcallImpl>(0), static_cast<RTLIB::LibcallImpl>(0), true);")
    lines.append("#undef GET_LOOKUP_LIBCALL_IMPL_NAME_BODY")
    lines.append("#endif // GET_LOOKUP_LIBCALL_IMPL_NAME_BODY")
    
    output_path = os.path.join(LLVM_KAIN, "include", "core", "ir", "RuntimeLibcalls.inc")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    
    print(f"Generated {output_path}")
    print(f"  Libcall enum: {len(libcall_symbols) + 1} values (incl UNKNOWN_LIBCALL)")
    print(f"  LibcallImpl enum: {len(libcall_impl_symbols) + 1} values (incl Unsupported)")

if __name__ == "__main__":
    main()
