//! USF Code Generation - KAIN to Unreal Shader Format
//! Generates UE5-compatible .usf/.ush files for compute and pixel shaders
//! 
//! Key UE5 patterns supported:
//! - #include "/Engine/Public/Platform.ush" headers
//! - RWTexture2D UAV bindings for compute outputs
//! - [numthreads] compute dispatch
//! - SHADER_PARAMETER_STRUCT compatible parameter layout

use kain_core::types::{TypedProgram, TypedItem, TypedShader};
use kain_core::error::{KainResult, KainError};
use kain_core::ast::{Type, ShaderStage, Expr, Stmt, Block, BinaryOp, Pattern};
use std::collections::HashMap;
use crate::shader_knowledge::ShaderKnowledge;

/// Pre-computed component mirror structs.
/// Compute once from a [`TypedProgram`] and reuse across the `_cached` generation
/// functions to avoid redundant AST traversals when building all three shader
/// artifacts (header, implementation, USF) for the same program.
pub struct CachedMirrors(pub(crate) HashMap<String, crate::pod_mirror::PodMirrorStruct>);

impl CachedMirrors {
    /// Build from a typed program, using an empty map on error.
    pub fn from_program(program: &TypedProgram) -> Self {
        CachedMirrors(
            crate::pod_mirror::collect_component_mirrors(program).unwrap_or_default()
        )
    }
}

/// Generate C++ reflection header for UE5 shader parameter binding.
/// Creates a .h file with SHADER_PARAMETER_STRUCT compatible bindings.
pub fn generate_cpp_header(program: &TypedProgram, shader_name: &str) -> String {
    generate_cpp_header_cached(program, shader_name, "", &CachedMirrors::from_program(program))
}

fn generate_cpp_header_cached(program: &TypedProgram, shader_name: &str, plugin_name: &str, mirrors: &CachedMirrors) -> String {
    let mut output = String::new();
    
    output.push_str("// Generated by KAIN Compiler - UE5 Shader Parameter Reflection\n");
    output.push_str("// This file provides C++ bindings for shader parameters\n\n");
    output.push_str("#pragma once\n\n");
    output.push_str("#include \"CoreMinimal.h\"\n");
    output.push_str("#include \"GlobalShader.h\"\n");
    output.push_str("#include \"ShaderParameters.h\"\n");
    output.push_str("#include \"ShaderParameterStruct.h\"\n");
    output.push_str("#include \"ShaderParameterUtils.h\"\n");
    output.push_str("#include \"RenderGraphResources.h\"\n");
    output.push_str("#include \"RenderGraphBuilder.h\"\n");
    output.push_str("#include \"RenderGraphUtils.h\"\n"); // Fixed: Needed for FComputeShaderUtils
    output.push_str("#include \"ShaderCompilerCore.h\"\n");
    output.push_str("#include \"RHIStaticStates.h\"\n\n");
    
    // Detect shader stage
    let (is_compute, is_vertex) = program.items.iter()
        .find_map(|item| {
            if let TypedItem::Shader(shader) = item {
                let normalized_ast_name = shader.ast.name.replace("_", "");
                let normalized_shader_name = shader_name.replace("_", "");
                if normalized_ast_name.eq_ignore_ascii_case(&normalized_shader_name) {
                    return Some((
                        matches!(shader.ast.stage, ShaderStage::Compute),
                        matches!(shader.ast.stage, ShaderStage::Vertex),
                    ));
                }
            }
            None
        })
        .unwrap_or((false, false));
    
    // Collect uniforms ONLY from the shader matching shader_name
    let mut all_scalar_params: Vec<(String, String, u32)> = Vec::new();
    let mut all_texture_inputs: Vec<(String, String, u32)> = Vec::new();
    let mut all_uav_outputs: Vec<(String, String, u32)> = Vec::new();
    
    // Also collect permutations
    let mut permissions: Vec<String> = Vec::new();

    for item in &program.items {
        if let TypedItem::Shader(shader) = item {
            // Only collect uniforms from the shader that matches our output name
            // Normalize both names by removing underscores for comparison
            let normalized_ast_name = shader.ast.name.replace("_", "");
            let normalized_shader_name = shader_name.replace("_", "");
            if !normalized_ast_name.eq_ignore_ascii_case(&normalized_shader_name) {
                continue;
            }
            
            // Find permutations by scanning the AST for identifiers used in preprocessor-like ways
            // For now, we'll scan uniforms that match the permutation pattern
            for uniform in &shader.ast.uniforms {
                if is_permutation_param(&uniform.name) {
                    if !permissions.contains(&uniform.name) {
                        permissions.push(uniform.name.clone());
                    }
                    continue; // Permutations are not regular parameters
                }
                
                let usf_type = map_type_to_usf(&uniform.ty);
                let entry = (uniform.name.clone(), usf_type.clone(), uniform.binding);
                
                if usf_type.starts_with("RWTexture") || usf_type.starts_with("RWBuffer") || usf_type.starts_with("RWStructuredBuffer") {
                    all_uav_outputs.push(entry);
                } else if usf_type.contains("Texture") {
                    all_texture_inputs.push(entry);
                } else {
                    all_scalar_params.push(entry);
                }
            }
            
            // For compute shaders, allow explicitly named "OutputTexture" if referenced in logic but not in inputs
            if is_compute && all_uav_outputs.is_empty() {
                // We'll inject a default output UAV called "OutputTexture"
                 all_uav_outputs.push(("OutputTexture".to_string(), "RWTexture2D<float4>".to_string(), 0));
            }
            
            break; // Found our shader, stop looking
        }
    }
    
    let component_mirrors = &mirrors.0;

    // Determine which mirrors are actually referenced by THIS shader's scalar params.
    let mut used_mirror_names: Vec<String> = Vec::new();
    for (_, usf_type, _) in &all_scalar_params {
        if component_mirrors.contains_key(usf_type.as_str()) && !used_mirror_names.contains(usf_type) {
            used_mirror_names.push(usf_type.clone());
        }
    }

    // Emit POD struct definitions before the shader class.
    for comp_name in &used_mirror_names {
        if let Some(mirror) = component_mirrors.get(comp_name.as_str()) {
            output.push_str(&mirror.generate_cpp_struct());
        }
    }

    let class_name = if is_vertex {
        format!("F{}VS", capitalize_first(shader_name))
    } else {
        format!("F{}Shader", capitalize_first(shader_name))
    };
    
    output.push_str(&format!("class {} : public FGlobalShader\n{{\n", class_name));
    output.push_str(&format!("    DECLARE_GLOBAL_SHADER({});\n", class_name));
    output.push_str(&format!("    SHADER_USE_PARAMETER_STRUCT({}, FGlobalShader);\n\n", class_name));
    
    // Permutation Domain
    if !permissions.is_empty() {
        output.push_str("    // Permutation Domain\n");
        for perm in &permissions {
            output.push_str(&format!("    class {} : SHADER_PERMUTATION_BOOL(\"{}\");\n", perm, perm));
        }
        
        output.push_str("    using FPermutationDomain = TShaderPermutationDomain<");
        for (i, perm) in permissions.iter().enumerate() {
            if i > 0 { output.push_str(", "); }
            output.push_str(perm);
        }
        output.push_str(">;\n\n");
    }
    // NOTE: When no permutations, we intentionally omit FPermutationDomain typedef
    // (matches Niagara pattern — only declare when needed)

    output.push_str("    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )\n");
    
    // Emit scalar parameters
    for (name, ty, _) in &all_scalar_params {
        if is_permutation_param(name) { continue; } // Skip permutations in struct
        // If the USF type is a known component, use its POD mirror struct name.
        let cpp_type = if let Some(mirror) = component_mirrors.get(ty.as_str()) {
            mirror.pod_struct_name.clone()
        } else {
            map_usf_type_to_cpp(ty)
        };
        output.push_str(&format!("        SHADER_PARAMETER({}, {})\n", cpp_type, name));
    }
    
    // Emit texture parameters
    for (name, ty, _) in &all_texture_inputs {
        let texture_type = if ty.contains("Texture2D") {
            "Texture2D"
        } else if ty.contains("Texture3D") {
            "Texture3D"
        } else if ty.contains("TextureCube") {
            "TextureCube"
        } else {
            "Texture2D"
        };
        // Use RDG texture parameters for graph correctness
        output.push_str(&format!("        SHADER_PARAMETER_RDG_TEXTURE({}, {})\n", texture_type, name));
        output.push_str(&format!("        SHADER_PARAMETER_SAMPLER(SamplerState, {}Sampler)\n", name));
    }
    
    // Emit UAV parameters
    for (name, ty, _) in &all_uav_outputs {
        let uav_type = if ty.contains("RWTexture2D") {
            "RWTexture2D<float4>"
        } else if ty.contains("RWTexture3D") {
            "RWTexture3D<float4>"
        } else if ty.contains("RWStructuredBuffer") {
            "RWStructuredBuffer<float4>"
        } else {
            "RWTexture2D<float4>" // Default to float4 texture
        };
        // CRITICAL FIX: Use SHADER_PARAMETER_RDG_TEXTURE_UAV instead of generic UAV
        output.push_str(&format!("        SHADER_PARAMETER_RDG_TEXTURE_UAV({}, {})\n", uav_type, name));
    }
    
    output.push_str("    END_SHADER_PARAMETER_STRUCT()\n\n");
    
    // Static execution function for easy RDG setup
    if is_compute {
        output.push_str("    // Automatically generates RDG compute pass\n");
        output.push_str("    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount");
    } else if is_vertex {
        output.push_str("    // Vertex shader: bind with a mesh draw call (NOT AddFullscreenPass)\n");
        output.push_str("    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters");
    } else {
        output.push_str("    // Automatically generates RDG pixel shader pass\n");
        output.push_str("    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters");
    }
    
    // Add permutation arguments to Exec
    for perm in &permissions {
        output.push_str(&format!(", bool b{}", perm));
    }
    
    output.push_str(")\n    {\n");
    
    // Build permutation vector BEFORE creating TShaderMapRef (required by UE5)
    if !permissions.is_empty() {
        output.push_str("        FPermutationDomain PermutationVector;\n");
        for perm in &permissions {
            output.push_str(&format!("        PermutationVector.Set<{}>(b{});\n", perm, perm));
        }
        output.push_str("\n");
    }
    
    if is_compute {
        if permissions.is_empty() {
            output.push_str(&format!("        TShaderMapRef<{}> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));\n\n", class_name));
        } else {
            output.push_str(&format!("        TShaderMapRef<{}> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel), PermutationVector);\n\n", class_name));
        }
    } else if is_vertex {
        if permissions.is_empty() {
            output.push_str(&format!("        TShaderMapRef<{}> VertexShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));\n\n", class_name));
        } else {
            output.push_str(&format!("        TShaderMapRef<{}> VertexShader(GetGlobalShaderMap(GMaxRHIFeatureLevel), PermutationVector);\n\n", class_name));
        }
    } else {
        if permissions.is_empty() {
            output.push_str(&format!("        TShaderMapRef<{}> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));\n\n", class_name));
        } else {
            output.push_str(&format!("        TShaderMapRef<{}> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel), PermutationVector);\n\n", class_name));
        }
    }
        
    output.push_str("        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();\n");
    output.push_str("        *PassParameters = Parameters;\n\n");
    
    if is_compute {
        output.push_str(&format!("        FComputeShaderUtils::AddPass(\n"));
        output.push_str(&format!("            GraphBuilder,\n"));
        output.push_str(&format!("            RDG_EVENT_NAME(\"{} Dispatch\"),\n", shader_name));
        output.push_str("            ComputeShader,\n");
        output.push_str("            PassParameters,\n");
        output.push_str("            GroupCount\n");
        output.push_str("        );\n");
    } else if is_vertex {
        output.push_str("        // Vertex shaders require geometry submission via FMeshPassProcessor\n");
        output.push_str("        // or a custom FRenderPass — AddFullscreenPass is not valid here.\n");
        output.push_str(&format!("        // Bind VertexShader in your draw call setup for {}.\n", shader_name));
    } else {
        output.push_str("        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry\n");
        output.push_str("        // This is a simplified example - adapt to your rendering pipeline\n");
        output.push_str(&format!("        // Use AddDrawPass or integrate with your post-process pipeline\n"));
    }
    
    output.push_str("    }\n");
    
    output.push_str("};\n\n");
    
    // Add implementation macro hint
    let effective_plugin = if plugin_name.is_empty() { "YourPlugin" } else { plugin_name };
    output.push_str(&format!("// In your .cpp file, add:\n"));
    if is_compute {
        output.push_str(&format!("// IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}CS\", SF_Compute);\n",
            class_name, effective_plugin, shader_name, capitalize_first(shader_name)));
    } else if is_vertex {
        output.push_str(&format!("// IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}VS\", SF_Vertex);\n",
            class_name, effective_plugin, shader_name, capitalize_first(shader_name)));
    } else {
        output.push_str(&format!("// IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}PS\", SF_Pixel);\n",
            class_name, effective_plugin, shader_name, capitalize_first(shader_name)));
    }
    
    // Add forward declaration for AddPass helper function
    output.push_str(&format!("\n// Helper function to add pass to render graph\n"));
    output.push_str(&format!("void AddPass_{}(\n", capitalize_first(shader_name)));
    output.push_str("    FRDGBuilder& GraphBuilder");
    
    // Add parameter declarations
    let mut args = Vec::new();
    
    // 1. Scalars
    for (name, ty, _) in &all_scalar_params {
        let cpp_type = if let Some(mirror) = component_mirrors.get(ty.as_str()) {
            mirror.pod_struct_name.clone()
        } else {
            map_usf_type_to_cpp(ty)
        };
        args.push(format!("    {} {}", cpp_type, name));
    }
    
    // 2. Textures
    for (name, _, _) in &all_texture_inputs {
        args.push(format!("    FRDGTextureRef {}", name));
    }
    
    // 3. UAVs
    for (name, _, _) in &all_uav_outputs {
        args.push(format!("    FRDGTextureRef {}", name));
    }
    
    // 4. GroupCount
    if is_compute {
        args.push("    FIntVector GroupCount = FIntVector(32, 32, 1)".to_string());
    }
    
    // 5. Permutation bools (must match .cpp signature)
    for perm in &permissions {
        args.push(format!("    bool b{} = false", perm));
    }
    
    // Only add comma and newline if there are additional args
    if !args.is_empty() {
        output.push_str(",\n");
        output.push_str(&args.join(",\n"));
    }
    output.push_str("\n);\n");
    
    output
}

/// Generate C++ implementation file for shader registration and dispatch.
/// Creates a .cpp file with IMPLEMENT_GLOBAL_SHADER and helper functions.
pub fn generate_cpp_implementation(program: &TypedProgram, shader_name: &str, plugin_name: &str) -> String {
    generate_cpp_implementation_cached(program, shader_name, plugin_name, &CachedMirrors::from_program(program))
}

fn generate_cpp_implementation_cached(program: &TypedProgram, shader_name: &str, plugin_name: &str, mirrors: &CachedMirrors) -> String {
    let mut output = String::new();
    
    output.push_str("// Generated by KAIN Compiler - UE5 Shader Implementation\n");
    output.push_str("// Shader registration and dispatch helpers\n\n");
    output.push_str(&format!("#include \"{}.h\"\n", shader_name));
    output.push_str("#include \"RenderGraphBuilder.h\"\n");
    output.push_str("#include \"RenderGraphUtils.h\"\n");
    output.push_str("#include \"ShaderParameterUtils.h\"\n");
    output.push_str("#include \"GlobalShader.h\"\n");
    output.push_str("\n");
    // NOTE: Shader directory mapping is handled by the plugin module's StartupModule()
    // (same pattern as Niagara's NiagaraShaderModule.cpp)
    
    // Detect shader stage
    let (is_compute, is_vertex) = program.items.iter()
        .find_map(|item| {
            if let TypedItem::Shader(shader) = item {
                let normalized_ast_name = shader.ast.name.replace("_", "");
                let normalized_shader_name = shader_name.replace("_", "");
                if normalized_ast_name.eq_ignore_ascii_case(&normalized_shader_name) {
                    return Some((
                        matches!(shader.ast.stage, ShaderStage::Compute),
                        matches!(shader.ast.stage, ShaderStage::Vertex),
                    ));
                }
            }
            None
        })
        .unwrap_or((false, false));

    let class_name = if is_vertex {
        format!("F{}VS", capitalize_first(shader_name))
    } else {
        format!("F{}Shader", capitalize_first(shader_name))
    };
    
    // Shader registration
    output.push_str(&format!("// Register shader with UE5\n"));
    if is_compute {
        output.push_str(&format!("IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}CS\", SF_Compute);\n\n",
            class_name, plugin_name, shader_name, capitalize_first(shader_name)));
    } else if is_vertex {
        output.push_str(&format!("IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}VS\", SF_Vertex);\n\n",
            class_name, plugin_name, shader_name, capitalize_first(shader_name)));
    } else {
        output.push_str(&format!("IMPLEMENT_GLOBAL_SHADER({}, \"/Plugin/{}/{}.usf\", \"{}PS\", SF_Pixel);\n\n",
            class_name, plugin_name, shader_name, capitalize_first(shader_name)));
    }
    
    // Collect shader parameters and permutations
    let mut all_scalar_params: Vec<(String, String, u32)> = Vec::new();
    let mut all_texture_inputs: Vec<(String, String, u32)> = Vec::new();
    let mut all_uav_outputs: Vec<(String, String, u32)> = Vec::new();
    let mut permutations: Vec<String> = Vec::new();

    // Find the matching shader and collect its uniforms
    for item in &program.items {
        if let TypedItem::Shader(shader) = item {
            // Normalize both names by removing underscores for comparison
            let normalized_ast_name = shader.ast.name.replace("_", "");
            let normalized_shader_name = shader_name.replace("_", "");
            if !normalized_ast_name.eq_ignore_ascii_case(&normalized_shader_name) {
                continue;
            }
            
            for uniform in &shader.ast.uniforms {
                if is_permutation_param(&uniform.name) {
                    permutations.push(uniform.name.clone());
                    continue;
                }
                
                let usf_type = map_type_to_usf(&uniform.ty);
                let entry = (uniform.name.clone(), usf_type.clone(), uniform.binding);
                
                if usf_type.starts_with("RWTexture") || usf_type.starts_with("RWBuffer") || usf_type.starts_with("RWStructuredBuffer") {
                    all_uav_outputs.push(entry);
                } else if usf_type.contains("Texture") || usf_type.contains("Sampler") {
                    all_texture_inputs.push(entry);
                } else {
                    all_scalar_params.push(entry);
                }
            }
            
            // Inject default OutputTexture if needed for compute
            if is_compute && all_uav_outputs.is_empty() {
                 all_uav_outputs.push(("OutputTexture".to_string(), "RWTexture2D<float4>".to_string(), 0));
            }
            break; 
        }
    }
    
    let component_mirrors_impl = &mirrors.0;

    // Generate helper function
    output.push_str(&format!("// Helper function to add pass to render graph\n"));
    output.push_str(&format!("void AddPass_{}(\n", capitalize_first(shader_name)));
    output.push_str("    FRDGBuilder& GraphBuilder");
    
    // --- Arguments Generation ---
    let mut args = Vec::new();
    
    // 1. Scalars
    for (name, ty, _) in &all_scalar_params {
        let cpp_type = if let Some(mirror) = component_mirrors_impl.get(ty.as_str()) {
            mirror.pod_struct_name.clone()
        } else {
            map_usf_type_to_cpp(ty)
        };
        args.push(format!("    {} {}", cpp_type, name));
    }
    
    // 2. Textures
    for (name, _, _) in &all_texture_inputs {
         args.push(format!("    FRDGTextureRef {}", name));
    }
    
    // 3. UAVs
    for (name, _, _) in &all_uav_outputs {
         args.push(format!("    FRDGTextureRef {}", name));
    }
    
    // 4. GroupCount (Compute only)
    if is_compute {
        args.push("    FIntVector GroupCount".to_string());
    }
    
    // 5. Permutation bools (must match Exec signature)
    for perm in &permutations {
        args.push(format!("    bool b{}", perm));
    }
    
    // Only add comma and newline if there are additional args
    if !args.is_empty() {
        output.push_str(",\n");
        output.push_str(&args.join(",\n"));
    }
    output.push_str("\n)\n{\n");
    
    // No ENQUEUE_RENDER_COMMAND here - assume we are inside one
    // output.push_str(&format!("    ENQUEUE_RENDER_COMMAND({}Render)([=](FRHICommandListImmediate& RHICmdList) {{\n", capitalize_first(shader_name)));
    // output.push_str("        FRDGBuilder GraphBuilder(RHICmdList);\n\n");
    
    output.push_str(&format!("    {}::FParameters* Params = GraphBuilder.AllocParameters<{}::FParameters>();\n", 
        class_name, class_name));
    
    // Bind Scalars
    if !all_scalar_params.is_empty() {
        output.push_str("    // Bind Scalars\n");
        for (name, _, _) in &all_scalar_params {
            output.push_str(&format!("    Params->{} = {};\n", name, name));
        }
    }
    
    // Bind Textures
    if !all_texture_inputs.is_empty() {
        output.push_str("    // Bind Textures\n");
        for (name, _, _) in &all_texture_inputs {
             output.push_str(&format!("    Params->{} = {};\n", name, name));
             output.push_str(&format!("    Params->{}Sampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();\n", name));
        }
    }
    
    // Bind UAVs
    if !all_uav_outputs.is_empty() {
        output.push_str("    // Bind UAVs\n");
        for (name, ty, _) in &all_uav_outputs {
            // Check if we need to create UAV from texture before binding
            // But usually for Compute Shader helper, we expect FRDGTextureUAVRef
            // However, our signature takes FRDGTextureRef for simplicity.
            // So we MUST create the UAV here using GraphBuilder.CreateUAV(...)
            output.push_str(&format!("    Params->{} = GraphBuilder.CreateUAV({});\n", name, name));
        }
    }
    
    output.push_str("\n");
    
    // Execute — forward all args including permutation bools
    let perm_args: String = permutations.iter()
        .map(|p| format!(", b{}", p))
        .collect();
    if is_compute {
         output.push_str(&format!("    {}::Exec(GraphBuilder, *Params, GroupCount{});\n", class_name, perm_args));
    } else {
         output.push_str(&format!("    {}::Exec(GraphBuilder, *Params{});\n", class_name, perm_args));
    }
    
    output.push_str("}\n");
    
    output
}

/// Map USF/HLSL types to UE5 C++ types
fn map_usf_type_to_cpp(usf_type: &str) -> String {
    match usf_type {
        "float" => "float".to_string(),
        "float2" => "FVector2f".to_string(),
        "float3" => "FVector3f".to_string(),
        "float4" => "FVector4f".to_string(),
        "int" => "int32".to_string(),
        "int2" => "FIntPoint".to_string(),
        "int3" => "FIntVector".to_string(),
        "int4" => "FIntVector4".to_string(),
        "uint" => "uint32".to_string(),
        "uint2" => "FUintVector2".to_string(),
        "uint3" => "FUintVector".to_string(),
        "uint4" => "FUintVector4".to_string(),
        "float4x4" => "FMatrix44f".to_string(),
        "float3x3" => "FMatrix33f".to_string(),
        _ => usf_type.to_string(),
    }
}

/// Generate USF code from typed KAIN program.
/// Uses two-pass generation: first collect all uniforms, then emit code.
pub fn generate(program: &TypedProgram) -> KainResult<String> {
    generate_cached(program, &CachedMirrors::from_program(program))
}

fn generate_cached(program: &TypedProgram, mirrors: &CachedMirrors) -> KainResult<String> {
    let mut output = String::new();
    
    // Pass 1: Collect all uniforms from all shaders to deduplicate
    let mut all_texture_inputs: Vec<(String, String, u32)> = Vec::new();
    let mut all_uav_outputs: Vec<(String, String, u32)> = Vec::new();
    let mut all_scalar_params: Vec<(String, String, u32)> = Vec::new();
    
    // Detect if we have any compute shaders
    let has_compute = program.items.iter().any(|item| 
        if let TypedItem::Shader(s) = item { matches!(s.ast.stage, ShaderStage::Compute) } else { false }
    );
    
    for item in &program.items {
        if let TypedItem::Shader(shader) = item {
            for uniform in &shader.ast.uniforms {
                // Skip permutation parameters (handled via preprocessor)
                if is_permutation_param(&uniform.name) {
                    continue;
                }

                let usf_type = map_type_to_usf(&uniform.ty);
                let entry = (uniform.name.clone(), usf_type.clone(), uniform.binding);
                
                if usf_type.starts_with("RWTexture") || usf_type.starts_with("RWBuffer") || usf_type.starts_with("RWStructuredBuffer") {
                    if !all_uav_outputs.iter().any(|(n, _, _)| n == &uniform.name) {
                        all_uav_outputs.push(entry);
                    }
                } else if usf_type.contains("Texture") {
                    if !all_texture_inputs.iter().any(|(n, _, _)| n == &uniform.name) {
                        all_texture_inputs.push(entry);
                    }
                } else {
                    if !all_scalar_params.iter().any(|(n, _, _)| n == &uniform.name) {
                        all_scalar_params.push(entry);
                    }
                }
            }
        }
    }
    
    // For compute shaders, check if we need to inject the OutputTexture UAV
    if has_compute && all_uav_outputs.is_empty() {
        all_uav_outputs.push(("OutputTexture".to_string(), "RWTexture2D<float4>".to_string(), 0));
    }
    
    // UE5 header
    output.push_str("// Generated by KAIN Compiler - Unreal Shader Format\n");
    output.push_str("// Compatible with UE5 SHADER_PARAMETER_STRUCT bindings\n\n");
    output.push_str("#include \"/Engine/Public/Platform.ush\"\n\n");

    let usf_mirrors = &mirrors.0;

    // Emit HLSL struct definitions for component uniforms (deduplicated).
    {
        let mut emitted_structs: std::collections::HashSet<String> = std::collections::HashSet::new();
        for (_, usf_type, _) in &all_scalar_params {
            if let Some(mirror) = usf_mirrors.get(usf_type.as_str()) {
                if emitted_structs.insert(mirror.pod_struct_name.clone()) {
                    output.push_str(&mirror.generate_hlsl_struct());
                }
            }
        }
    }

    // Emit ALL scalar parameters once (deduplicated)
    if !all_scalar_params.is_empty() {
        output.push_str("// Scalar Parameters - Bind via SHADER_PARAMETER_STRUCT\n");
        for (name, ty, _) in &all_scalar_params {
            // Replace component types with their POD mirror struct name.
            let hlsl_type = if let Some(mirror) = usf_mirrors.get(ty.as_str()) {
                mirror.pod_struct_name.clone()
            } else {
                ty.clone()
            };
            output.push_str(&format!("{} {};\n", hlsl_type, name));
        }
        output.push_str("\n");
    }
    
    // Emit ALL texture inputs once (deduplicated)
    if !all_texture_inputs.is_empty() {
        output.push_str("// Texture Inputs\n");
        for (name, ty, binding) in &all_texture_inputs {
            output.push_str(&format!("{} {} : register(t{});\n", ty, name, binding));
            output.push_str(&format!("SamplerState {}Sampler : register(s{});\n", name, binding));
        }
        output.push_str("\n");
    }
    
    // Emit ALL UAV outputs once (deduplicated)
    if !all_uav_outputs.is_empty() {
        output.push_str("// UAV Outputs\n");
        for (name, ty, binding) in &all_uav_outputs {
            output.push_str(&format!("{} {} : register(u{});\n", ty, name, binding));
        }
        output.push_str("\n");
    }
    
    // Pass 2: Emit each shader's entry point (no declarations, just the function)
    for item in &program.items {
        if let TypedItem::Shader(shader) = item {
            output.push_str(&emit_shader_body(shader)?);
        }
    }
    
    Ok(output)
}

struct USFContext {
    // Maps variable name -> (code, type) for proper type tracking
    vars: HashMap<String, (String, String)>,
    indent_level: usize,
    uniform_bindings: Vec<(String, String, u32)>,
    packer: Option<InterpolatorPacker>,
    is_vertex_shader: bool,
    is_compute_shader: bool,
    // Data-driven shader knowledge (intrinsics, includes, permutations)
    shader_knowledge: Option<ShaderKnowledge>,
}

/// Tracks interpolator packing allocations for optimal GPU bandwidth usage
#[derive(Debug, Clone)]
struct InterpolatorPacker {
    /// Maps variable name -> (register_index, swizzle_mask)
    allocations: HashMap<String, (usize, String)>,
    /// Available registers with their usage
    registers: Vec<PackedRegister>,
}

#[derive(Debug, Clone)]
struct PackedRegister {
    index: usize,              // TEXCOORD index (0, 1, 2, ...)
    components_used: usize,    // How many components used (0-4)
    variables: Vec<PackedVar>, // What's stored here
}

#[derive(Debug, Clone)]
struct PackedVar {
    name: String,
    ty: String,      // USF type string
    swizzle: String, // "x", "xy", "xyz", "xyzw", "zw", etc.
}

impl USFContext {
    fn new() -> Self {
        Self {
            vars: HashMap::new(),
            indent_level: 0,
            uniform_bindings: Vec::new(),
            packer: None,
            is_vertex_shader: false,
            is_compute_shader: false,
            shader_knowledge: None,
        }
    }

    fn with_knowledge(mut self, sk: ShaderKnowledge) -> Self {
        self.shader_knowledge = Some(sk);
        self
    }
    
    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }
    
    fn push_indent(&mut self) {
        self.indent_level += 1;
    }
    
    fn pop_indent(&mut self) {
        if self.indent_level > 0 {
            self.indent_level -= 1;
        }
    }
}

impl InterpolatorPacker {
    fn new() -> Self {
        Self {
            allocations: HashMap::new(),
            registers: Vec::new(),
        }
    }
    
    /// Allocate space for a variable, returns (register_index, swizzle)
    fn allocate(&mut self, name: String, ty: String) -> (usize, String) {
        let components_needed = type_component_count(&ty);
        
        // Try to fit in existing register
        for reg in &mut self.registers {
            if reg.components_used + components_needed <= 4 {
                let swizzle = generate_swizzle(reg.components_used, components_needed);
                reg.variables.push(PackedVar {
                    name: name.clone(),
                    ty: ty.clone(),
                    swizzle: swizzle.clone(),
                });
                reg.components_used += components_needed;
                self.allocations.insert(name, (reg.index, swizzle.clone()));
                return (reg.index, swizzle);
            }
        }
        
        // Need new register
        let new_index = self.registers.len();
        let swizzle = generate_swizzle(0, components_needed);
        self.registers.push(PackedRegister {
            index: new_index,
            components_used: components_needed,
            variables: vec![PackedVar {
                name: name.clone(),
                ty,
                swizzle: swizzle.clone(),
            }],
        });
        self.allocations.insert(name, (new_index, swizzle.clone()));
        (new_index, swizzle)
    }
    
    /// Get allocation for a variable
    fn get_allocation(&self, name: &str) -> Option<(usize, String)> {
        self.allocations.get(name).cloned()
    }
}

/// Count components needed for a type
fn type_component_count(ty: &str) -> usize {
    match ty {
        "float" | "int" | "uint" | "bool" => 1,
        "float2" | "int2" | "uint2" => 2,
        "float3" | "int3" | "uint3" => 3,
        "float4" | "int4" | "uint4" => 4,
        _ => 4, // Default to float4 for unknown types
    }
}

/// Generate swizzle mask for component range
fn generate_swizzle(start: usize, count: usize) -> String {
    let components = ['x', 'y', 'z', 'w'];
    if start + count > 4 {
        // Overflow case - just use what we can
        return components[start..4].iter().collect::<String>();
    }
    components[start..start + count]
        .iter()
        .collect::<String>()
}

/// Emit just the shader entry point function (no declarations - those are now global)
fn emit_shader_body(shader: &TypedShader) -> KainResult<String> {
    let mut output = String::new();
    let mut ctx = USFContext::new();
    
    // Load shader knowledge for data-driven intrinsic resolution
    let metadata_dir = std::path::Path::new("unreal/metadata");
    if metadata_dir.exists() {
        let sk_path = metadata_dir.join("shader_knowledge.json");
        if sk_path.exists() {
            if let Ok(data) = std::fs::read_to_string(&sk_path) {
                let mut sk = ShaderKnowledge::new();
                if sk.load(&data).is_ok() {
                    ctx.shader_knowledge = Some(sk);
                }
            }
        }
    }
    
    // Seed context with uniform types so emit_expr can resolve them correctly
    // Without this, uniforms like status_color (float3) would fall through to
    // the unknown-ident default of float4, causing wrong type declarations.
    for uniform in &shader.ast.uniforms {
        if is_permutation_param(&uniform.name) {
            continue; // Permutations are compile-time, not runtime variables
        }
        let usf_type = map_type_to_usf(&uniform.ty);
        ctx.vars.insert(uniform.name.clone(), (uniform.name.clone(), usf_type));
    }
    
    match shader.ast.stage {
        ShaderStage::Compute => {
            // Check for @compute(x,y,z) attribute
            let mut threads = (32, 32, 1); // Default to decent 2D workgroup size
            /* 
            // Attributes not yet supported on Shader AST node
            for attr in &shader.ast.attributes {
                if attr.name == "compute" && attr.args.len() == 3 {
                    // Simple parsing - assumes literal integers
                     if let (Expr::Int(lx, _), Expr::Int(ly, _), Expr::Int(lz, _)) = (&attr.args[0], &attr.args[1], &attr.args[2]) {
                        threads = (*lx as u32, *ly as u32, *lz as u32);
                    }
                }
            }
            */
            
            output.push_str(&format!("[numthreads({}, {}, {})]\n", threads.0, threads.1, threads.2));
            output.push_str(&format!("void {}CS(uint3 ThreadId : SV_DispatchThreadID)\n{{\n", 
                capitalize_first(&shader.ast.name)));
            ctx.push_indent();
            
            // UE5 convention: early-out for out-of-bounds threads
            // For texture loads, we don't strictly need this if we clamp, but good practice
            output.push_str(&format!("{}// Safe Texture Load Pattern\n", ctx.indent()));
            output.push_str(&format!("{}int3 TexCoord = int3(ThreadId.xy, 0);\n", ctx.indent()));
            
            // Add compute builtins to context with proper types
            // Map all common parameter names to ThreadId
            ctx.vars.insert("thread_id".to_string(), ("ThreadId".to_string(), "uint3".to_string()));
            ctx.vars.insert("dispatch_thread_id".to_string(), ("ThreadId".to_string(), "uint3".to_string()));
            ctx.vars.insert("id".to_string(), ("ThreadId".to_string(), "uint3".to_string())); // FIX: Map 'id' parameter to ThreadId
            ctx.is_compute_shader = true;
            
            let body_code = emit_block(&mut ctx, &shader.ast.body)?;
            
            // Rewrite texture Lookups to use Load() if they look like simple samples
            // This is "Smart Codegen" attempt #1 -> Improved to handle ALL texture inputs
            let mut body_fixed = body_code;
            
            // Auto-convert .Sample(sampler, uv) -> .Load(TexCoord) for all texture inputs
            // This ensures 1:1 pixel mapping for simulation shaders
            for param in &shader.ast.inputs {
                if let Type::Named { name, .. } = &param.ty {
                    if name == "Texture2D" || name == "Sampler2D" {
                         let sampler_name = format!("{}_textureSampler", param.name);
                         let search = format!("{}.Sample({}, uv)", param.name, sampler_name); // Heuristic
                         // Also handle cases where param name already includes _texture suffix if manual
                         let search2 = format!("{}.Sample({}, uv)", param.name, format!("{}Sampler", param.name));
                         
                         body_fixed = body_fixed.replace(&search, &format!("{}.Load(TexCoord)", param.name));
                         body_fixed = body_fixed.replace(&search2, &format!("{}.Load(TexCoord)", param.name));
                    }
                }
            }

            // Also check uniforms!
            for uniform in &shader.ast.uniforms {
                if let Type::Named { name, .. } = &uniform.ty {
                    if name == "Texture2D" || name == "Sampler2D" {
                         let sampler_name = format!("{}_textureSampler", uniform.name);
                         let search = format!("{}.Sample({}, uv)", uniform.name, sampler_name); 
                         let search2 = format!("{}.Sample({}, uv)", uniform.name, format!("{}Sampler", uniform.name));
                         
                         body_fixed = body_fixed.replace(&search, &format!("{}.Load(TexCoord)", uniform.name));
                         body_fixed = body_fixed.replace(&search2, &format!("{}.Load(TexCoord)", uniform.name));
                    }
                }
            }

            // Also map KAIN scalar returns to OutputTexture writes handled in emit_stmt, 
            // but if there are any stray FPSOutput refs, clean them (should be none now)
            
            output.push_str(&body_fixed);

            ctx.pop_indent();
            output.push_str("}\n");
        },
        ShaderStage::Surface => {
            // UE5 Material Interface - generates CalcPixelMaterialInputs function
            output.push_str("// --- UE5 Material Interface ---\n");
            output.push_str("#define NUM_MATERIAL_TEXCOORDS_VERTEX 0\n");
            output.push_str("#define NUM_CUSTOM_VERTEX_INTERPOLATORS 0\n");
            output.push_str("#include \"/Engine/Generated/Material.ush\"\n\n");

            // The magic UE5 function signature that the material system expects
            output.push_str("void CalcPixelMaterialInputs(in out FMaterialPixelParameters Parameters, in out FPixelMaterialInputs PixelMaterialInputs)\n{\n");
            ctx.push_indent();

            // 1. Setup default values (UE5 crashes if you don't initialize these)
            output.push_str(&format!("{}// Initialize default material values\n", ctx.indent()));
            output.push_str(&format!("{}PixelMaterialInputs.BaseColor = float3(0,0,0);\n", ctx.indent()));
            output.push_str(&format!("{}PixelMaterialInputs.Roughness = 0.5;\n", ctx.indent()));
            output.push_str(&format!("{}PixelMaterialInputs.Metallic = 0.0;\n", ctx.indent()));
            output.push_str(&format!("{}PixelMaterialInputs.Normal = float3(0,0,1);\n\n", ctx.indent()));

            // 2. Map standard inputs from UE5 Parameters structure to shader variables
            output.push_str(&format!("{}// Map UE5 material parameters to shader inputs\n", ctx.indent()));
            ctx.vars.insert("uv".to_string(), ("Parameters.TexCoords[0]".to_string(), "float2".to_string()));
            ctx.vars.insert("world_pos".to_string(), ("Parameters.AbsoluteWorldPosition".to_string(), "float3".to_string()));
            ctx.vars.insert("view_dir".to_string(), ("Parameters.CameraVector".to_string(), "float3".to_string()));
            ctx.vars.insert("world_normal".to_string(), ("Parameters.WorldNormal".to_string(), "float3".to_string()));
            ctx.vars.insert("world_tangent".to_string(), ("Parameters.TangentToWorld[2]".to_string(), "float3".to_string()));

            // 3. Emit the shader logic
            let body_code = emit_block(&mut ctx, &shader.ast.body)?;
            output.push_str(&body_code);

            ctx.pop_indent();
            output.push_str("}\n");
        },
        ShaderStage::Fragment => {
            // Create packer matching vertex shader layout
            // In a real implementation, this would be loaded from metadata
            // For now, we recreate it based on shader inputs
            let mut packer = InterpolatorPacker::new();
            for param in &shader.ast.inputs {
                let usf_type = map_type_to_usf(&param.ty);
                packer.allocate(param.name.clone(), usf_type);
            }
            
            // Generate input struct with PACKED interpolators
            output.push_str("struct FPSInput\n{\n");
            
            // Emit packed TEXCOORD registers
            for reg in &packer.registers {
                output.push_str(&format!("    float4 TexCoord{} : TEXCOORD{};\n", 
                    reg.index, reg.index));
            }
            output.push_str("};\n\n");
            
            // Output struct
            let out_type = map_type_to_usf(&shader.ast.outputs);
            output.push_str("struct FPSOutput\n{\n");
            output.push_str(&format!("    {} Color : SV_Target0;\n", out_type));
            output.push_str("};\n\n");
            
            // Main function
            output.push_str(&format!("FPSOutput {}PS(FPSInput Input)\n{{\n", 
                capitalize_first(&shader.ast.name)));
            ctx.push_indent();
            
            // Unpack interpolators and map to variables
            output.push_str(&format!("{}// Unpack interpolators\n", ctx.indent()));
            for param in &shader.ast.inputs {
                if let Some((reg_idx, swizzle)) = packer.get_allocation(&param.name) {
                    let param_type = map_type_to_usf(&param.ty);
                    let packed_access = format!("Input.TexCoord{}.{}", reg_idx, swizzle);
                    
                    // Declare unpacked variable
                    output.push_str(&format!("{}{} {} = {};\n",
                        ctx.indent(), param_type, param.name, packed_access));
                    
                    // Store in context
                    ctx.vars.insert(param.name.clone(), (param.name.clone(), param_type));
                }
            }
            output.push_str("\n");
            
            let body_code = emit_block(&mut ctx, &shader.ast.body)?;
            output.push_str(&body_code);
            
            ctx.pop_indent();
            output.push_str("}\n");
        },
        ShaderStage::Vertex => {
            // Create packer for interpolator optimization
            let mut packer = InterpolatorPacker::new();
            
            // Analyze shader inputs to determine what needs to be packed
            // We'll pack all inputs as they become interpolators for the fragment shader
            for param in &shader.ast.inputs {
                let usf_type = map_type_to_usf(&param.ty);
                packer.allocate(param.name.clone(), usf_type);
            }
            
            // Generate input struct
            output.push_str("struct FVSInput\n{\n");
            for (i, param) in shader.ast.inputs.iter().enumerate() {
                let usf_type = map_type_to_usf(&param.ty);
                let semantic = match param.name.as_str() {
                    "position" => "POSITION",
                    "normal" => "NORMAL",
                    "tangent" => "TANGENT",
                    "color" => "COLOR",
                    _ => "TEXCOORD",
                };
                let idx = if semantic == "TEXCOORD" { i.to_string() } else { String::new() };
                output.push_str(&format!("    {} {} : {}{};\n", usf_type, param.name, semantic, idx));
            }
            output.push_str("};\n\n");
            
            // Generate output struct with PACKED interpolators
            output.push_str("struct FVSOutput\n{\n");
            output.push_str("    float4 Position : SV_Position;\n");
            
            // Emit packed TEXCOORD registers
            for reg in &packer.registers {
                output.push_str(&format!("    float4 TexCoord{} : TEXCOORD{};\n", 
                    reg.index, reg.index));
            }
            output.push_str("};\n\n");
            
            // Main function
            output.push_str(&format!("FVSOutput {}VS(FVSInput Input)\n{{\n", 
                capitalize_first(&shader.ast.name)));
            ctx.push_indent();
            
            // Initialize output
            output.push_str(&format!("{}FVSOutput Output;\n", ctx.indent()));
            
            // Store packer in context for use during code generation
            ctx.packer = Some(packer.clone());
            ctx.is_vertex_shader = true;
            
            // Map input parameters
            for param in &shader.ast.inputs {
                let param_type = map_type_to_usf(&param.ty);
                ctx.vars.insert(param.name.clone(), (format!("Input.{}", param.name), param_type));
            }
            
            // Emit body
            let body_code = emit_block(&mut ctx, &shader.ast.body)?;
            output.push_str(&body_code);
            
            // Pack outputs into interpolators
            output.push_str(&format!("\n{}// Pack interpolators\n", ctx.indent()));
            for param in &shader.ast.inputs {
                if let Some((reg_idx, swizzle)) = packer.get_allocation(&param.name) {
                    output.push_str(&format!("{}Output.TexCoord{}.{} = Input.{};\n",
                        ctx.indent(), reg_idx, swizzle, param.name));
                }
            }
            
            output.push_str(&format!("\n{}return Output;\n", ctx.indent()));
            ctx.pop_indent();
            output.push_str("}\n");
        },
    }
    
    Ok(output)
}

fn emit_block(ctx: &mut USFContext, block: &Block) -> KainResult<String> {
    let mut output = String::new();
    for stmt in &block.stmts {
        output.push_str(&emit_stmt(ctx, stmt)?);
    }
    Ok(output)
}

fn emit_stmt(ctx: &mut USFContext, stmt: &Stmt) -> KainResult<String> {
    let mut output = String::new();
    
    match stmt {
        Stmt::Let { pattern, value, .. } => {
            if let Some(value) = value {
                if let Pattern::Binding { name, mutable, .. } = pattern {
                    let (expr_code, expr_type) = emit_expr(ctx, value)?;
                    // Both let and var use same declaration in HLSL/USF
                    output.push_str(&format!("{}{} {} = {};\n", ctx.indent(), expr_type, name, expr_code));
                    // Store both the code and the type for proper type propagation
                    ctx.vars.insert(name.clone(), (name.clone(), expr_type.clone()));
                    // Mark mutable vars so we know they can be reassigned
                    if *mutable {
                        ctx.vars.insert(format!("__mutable_{}", name), ("true".to_string(), "bool".to_string()));
                    }
                }
            }
        },
        Stmt::Return(Some(expr), _) => {
            let (expr_code, _) = emit_expr(ctx, expr)?;
            
            if ctx.is_vertex_shader {
                // Wrap clip-space transform: vertex return is world-space Vec4
                output.push_str(&format!("{}Output.Position = mul({}, View.WorldToClip);\n", ctx.indent(), expr_code));
            } else if ctx.is_compute_shader {
                // For compute shaders, write to UAV directly
                // We assume the return value matches OutputTexture format (usually float4 for simulation)
                // If it's a vector, we write it. If it's scalar, we might need casting?
                output.push_str(&format!("{}OutputTexture[ThreadId.xy] = {};\n", ctx.indent(), expr_code));
                output.push_str(&format!("{}return;\n", ctx.indent()));
            } else {
                // For fragment shaders, return immediately
                output.push_str(&format!("{}FPSOutput _Result;\n", ctx.indent()));
                output.push_str(&format!("{}_Result.Color = {};\n", ctx.indent(), expr_code));
                output.push_str(&format!("{}return _Result;\n", ctx.indent()));
            }
        },
        Stmt::Return(None, _) => {
            if !ctx.is_vertex_shader {
                output.push_str(&format!("{}return;\n", ctx.indent()));
            }
            // For vertex shaders, ignore empty returns (packing happens after)
        },
        Stmt::Expr(expr) => {
            // Handle if expressions as statements
            if let Expr::If { condition, then_branch, else_branch, .. } = expr {
                output.push_str(&emit_if_statement(ctx, condition, then_branch, else_branch)?);
            } else {
                let (expr_code, _) = emit_expr(ctx, expr)?;
                // Skip empty expressions
                if !expr_code.is_empty() {
                    output.push_str(&format!("{}{};\n", ctx.indent(), expr_code));
                }
            }
        },
        Stmt::While { condition, body, .. } => {
            let (cond_code, _) = emit_expr(ctx, condition)?;
            output.push_str(&format!("{}while ({})\n", ctx.indent(), cond_code));
            output.push_str(&format!("{}{{\n", ctx.indent()));
            ctx.push_indent();
            output.push_str(&emit_block(ctx, body)?);
            ctx.pop_indent();
            output.push_str(&format!("{}}}\n", ctx.indent()));
        },
        Stmt::For { binding, iter, body, .. } => {
            if let Pattern::Binding { name, .. } = binding {
                // Extract loop bound from iterator expression
                // Common patterns: range(n), range(start, end)
                let bound = if let Expr::Call { callee, args, .. } = iter {
                    if let Expr::Ident(fn_name, _) = callee.as_ref() {
                        if fn_name == "range" && !args.is_empty() {
                            let (code, _) = emit_expr(ctx, &args[0].value)?;
                            code
                        } else {
                            let (code, _) = emit_expr(ctx, iter)?;
                            code
                        }
                    } else {
                        let (code, _) = emit_expr(ctx, iter)?;
                        code
                    }
                } else {
                    let (code, _) = emit_expr(ctx, iter)?;
                    code
                };
                output.push_str(&format!("{}for (int {} = 0; {} < {}; {}++)\n", 
                    ctx.indent(), name, name, bound, name));
                output.push_str(&format!("{}{{\n", ctx.indent()));
                ctx.push_indent();
                ctx.vars.insert(name.clone(), (name.clone(), "int".to_string()));
                output.push_str(&emit_block(ctx, body)?);
                ctx.pop_indent();
                output.push_str(&format!("{}}}\n", ctx.indent()));
            }
        },
        Stmt::Loop { body, .. } => {
            // Infinite loop - use while(true)
            output.push_str(&format!("{}while (true)\n", ctx.indent()));
            output.push_str(&format!("{}{{\n", ctx.indent()));
            ctx.push_indent();
            output.push_str(&emit_block(ctx, body)?);
            ctx.pop_indent();
            output.push_str(&format!("{}}}\n", ctx.indent()));
        },
        Stmt::Break(_, _) => {
            output.push_str(&format!("{}break;\n", ctx.indent()));
        },
        Stmt::Continue(_) => {
            output.push_str(&format!("{}continue;\n", ctx.indent()));
        },
        Stmt::Item(_) => {
            // Nested items not supported in shader body
        },
    }
    
    Ok(output)
}

// Helper to check if a variable name is a permutation parameter (compile-time constant)
fn is_permutation_param(name: &str) -> bool {
    // Check for common UE5 permutation prefixes (always permutations)
    if name.starts_with("CFG_") || 
       name.starts_with("ENABLE_") ||
       name.starts_with("USE_") ||
       name.starts_with("WITH_") ||
       name.starts_with("HAS_") ||
       name.starts_with("ALLOW_") ||
       name.starts_with("SUPPORT_") {
        return true;
    }
    
    // Check for SCREAMING_SNAKE_CASE but ONLY if it contains at least one underscore
    // and is at least 4 chars. This prevents false positives on short all-caps names
    // like UV, ID, N, RGB which are common shader variable names, NOT permutations.
    if name.len() >= 4 
       && name.contains('_') 
       && name.chars().all(|c| c.is_uppercase() || c == '_' || c.is_numeric()) 
    {
        return true;
    }
    
    false
}

// Helper to emit if statements with proper else-if chains
// Supports both runtime if statements and compile-time permutation directives
fn emit_if_statement(ctx: &mut USFContext, condition: &Expr, then_branch: &Block, else_branch: &Option<Box<kain_core::ast::ElseBranch>>) -> KainResult<String> {
    let mut output = String::new();
    
    // Check if this is a static permutation (compile-time branching)
    if let Expr::Ident(name, _) = condition {
        if is_permutation_param(name) {
            // Emit preprocessor directive for compile-time branching
            output.push_str(&format!("{}#ifdef {}\n", ctx.indent(), name));
            
            // Emit then branch (no indentation change for preprocessor)
            output.push_str(&emit_block(ctx, then_branch)?);
            
            if let Some(else_br) = else_branch {
                match else_br.as_ref() {
                    kain_core::ast::ElseBranch::Else(block) => {
                        output.push_str(&format!("{}#else\n", ctx.indent()));
                        output.push_str(&emit_block(ctx, block)?);
                    },
                    kain_core::ast::ElseBranch::ElseIf(cond, block, next_else) => {
                        // Check if the else-if condition is also a permutation
                        if let Expr::Ident(elif_name, _) = cond.as_ref() {
                            if is_permutation_param(elif_name) {
                                output.push_str(&format!("{}#elif defined({})\n", ctx.indent(), elif_name));
                                output.push_str(&emit_block(ctx, block)?);
                                
                                // Handle remaining else chain
                                if let Some(next) = next_else {
                                    // Recursively handle the rest
                                    output.push_str(&emit_else_branch_preprocessor(ctx, next)?);
                                }
                            } else {
                                // Mixed permutation/runtime - fallback to runtime
                                output.push_str(&format!("{}#else\n", ctx.indent()));
                                output.push_str(&emit_if_statement(ctx, cond, block, next_else)?);
                            }
                        } else {
                            // Complex condition - fallback to runtime in else block
                            output.push_str(&format!("{}#else\n", ctx.indent()));
                            output.push_str(&emit_if_statement(ctx, cond, block, next_else)?);
                        }
                    },
                }
            }
            
            output.push_str(&format!("{}#endif\n", ctx.indent()));
            return Ok(output);
        }
    }
    
    // Fallback to standard runtime if statement
    let (cond_code, _) = emit_expr(ctx, condition)?;
    
    output.push_str(&format!("{}if ({})\n", ctx.indent(), cond_code));
    output.push_str(&format!("{}{{\n", ctx.indent()));
    ctx.push_indent();
    output.push_str(&emit_block(ctx, then_branch)?);
    ctx.pop_indent();
    output.push_str(&format!("{}}}", ctx.indent()));
    
    if let Some(else_br) = else_branch {
        match else_br.as_ref() {
            kain_core::ast::ElseBranch::Else(block) => {
                output.push_str("\n");
                output.push_str(&format!("{}else\n", ctx.indent()));
                output.push_str(&format!("{}{{\n", ctx.indent()));
                ctx.push_indent();
                output.push_str(&emit_block(ctx, block)?);
                ctx.pop_indent();
                output.push_str(&format!("{}}}\n", ctx.indent()));
            },
            kain_core::ast::ElseBranch::ElseIf(cond, block, next_else) => {
                output.push_str("\n");
                output.push_str(&format!("{}else ", ctx.indent()));
                output.push_str(&emit_if_statement(ctx, cond, block, next_else)?);
            },
        }
    } else {
        output.push_str("\n");
    }
    
    Ok(output)
}

// Helper to emit remaining else branches in preprocessor mode
fn emit_else_branch_preprocessor(ctx: &mut USFContext, else_branch: &kain_core::ast::ElseBranch) -> KainResult<String> {
    let mut output = String::new();
    
    match else_branch {
        kain_core::ast::ElseBranch::Else(block) => {
            output.push_str(&format!("{}#else\n", ctx.indent()));
            output.push_str(&emit_block(ctx, block)?);
        },
        kain_core::ast::ElseBranch::ElseIf(cond, block, next_else) => {
            if let Expr::Ident(name, _) = cond.as_ref() {
                if is_permutation_param(name) {
                    output.push_str(&format!("{}#elif defined({})\n", ctx.indent(), name));
                    output.push_str(&emit_block(ctx, block)?);
                    
                    if let Some(next) = next_else {
                        output.push_str(&emit_else_branch_preprocessor(ctx, next)?);
                    }
                } else {
                    output.push_str(&format!("{}#else\n", ctx.indent()));
                    output.push_str(&emit_if_statement(ctx, cond, block, next_else)?);
                }
            } else {
                output.push_str(&format!("{}#else\n", ctx.indent()));
                output.push_str(&emit_if_statement(ctx, cond, block, next_else)?);
            }
        },
    }
    
    Ok(output)
}

fn emit_expr(ctx: &mut USFContext, expr: &Expr) -> KainResult<(String, String)> {
    match expr {
        Expr::Ident(name, _) => {
            if let Some((code, ty)) = ctx.vars.get(name) {
                // Return the stored type for proper type propagation
                Ok((code.clone(), ty.clone()))
            } else {
                // Unknown identifier - default to float4 (common for uniforms)
                Ok((name.clone(), "float4".to_string()))
            }
        },
        Expr::Float(f, _) => {
            Ok((format!("{:.6}", f), "float".to_string()))
        },
        Expr::Int(i, _) => {
            Ok((format!("{}", i), "int".to_string()))
        },
        Expr::Bool(b, _) => {
            Ok((format!("{}", b), "bool".to_string()))
        },
        Expr::String(s, _) => {
            Ok((format!("\"{}\"", s), "string".to_string()))
        },
        Expr::Binary { left, op, right, .. } => {
            let (left_code, left_ty) = emit_expr(ctx, left)?;
            let (right_code, _) = emit_expr(ctx, right)?;
            
            let op_str = match op {
                BinaryOp::Add => "+",
                BinaryOp::Sub => "-",
                BinaryOp::Mul => "*",
                BinaryOp::Div => "/",
                BinaryOp::Mod => "%",
                BinaryOp::Eq => "==",
                BinaryOp::Ne => "!=",
                BinaryOp::Lt => "<",
                BinaryOp::Le => "<=",
                BinaryOp::Gt => ">",
                BinaryOp::Ge => ">=",
                BinaryOp::And => "&&",
                BinaryOp::Or => "||",
                BinaryOp::BitAnd => "&",
                BinaryOp::BitOr => "|",
                BinaryOp::BitXor => "^",
                BinaryOp::Shl => "<<",
                BinaryOp::Shr => ">>",
                _ => return Err(KainError::codegen("Unsupported binary op in USF", expr.span())),
            };
            
            let result_ty = match op {
                BinaryOp::Eq | BinaryOp::Ne | BinaryOp::Lt | BinaryOp::Le | 
                BinaryOp::Gt | BinaryOp::Ge | BinaryOp::And | BinaryOp::Or => "bool".to_string(),
                _ => left_ty,
            };
            
            Ok((format!("({} {} {})", left_code, op_str, right_code), result_ty))
        },
        Expr::Unary { op, operand, .. } => {
            let (operand_code, ty) = emit_expr(ctx, operand)?;
            let op_str = match op {
                kain_core::ast::UnaryOp::Neg => "-",
                kain_core::ast::UnaryOp::Not => "!",
                kain_core::ast::UnaryOp::BitNot => "~",
                kain_core::ast::UnaryOp::Ref | kain_core::ast::UnaryOp::RefMut => {
                    return Ok((operand_code, ty));
                },
                kain_core::ast::UnaryOp::Deref => {
                    return Ok((operand_code, ty));
                },
            };
            Ok((format!("({}{})", op_str, operand_code), ty))
        },
        Expr::Call { callee, args, .. } => {
            if let Expr::Ident(name, _) = &**callee {
                emit_function_call(ctx, name, args)
            } else {
                Err(KainError::codegen("Complex callee not supported in USF", expr.span()))
            }
        },
        Expr::Field { object, field, .. } => {
            let (obj_code, _) = emit_expr(ctx, object)?;
            Ok((format!("{}.{}", obj_code, field), infer_swizzle_type(field)))
        },
        Expr::Index { object, index, .. } => {
            let (obj_code, obj_ty) = emit_expr(ctx, object)?;
            let (idx_code, _) = emit_expr(ctx, index)?;
            let elem_ty = if obj_ty.starts_with("float") { "float".to_string() } else { obj_ty };
            Ok((format!("{}[{}]", obj_code, idx_code), elem_ty))
        },
        Expr::Assign { target, value, .. } => {
            let (target_code, _) = emit_expr(ctx, target)?;
            let (value_code, ty) = emit_expr(ctx, value)?;
            Ok((format!("{} = {}", target_code, value_code), ty))
        },
        Expr::If { condition, then_branch, else_branch, .. } => {
            let (cond_code, _) = emit_expr(ctx, condition)?;
            
            // Try to emit as ternary if simple enough
            if then_branch.stmts.len() == 1 && else_branch.is_some() {
                if let Stmt::Expr(then_expr) = &then_branch.stmts[0] {
                    let (then_code, then_ty) = emit_expr(ctx, then_expr)?;
                    
                    if let Some(kain_core::ast::ElseBranch::Else(else_block)) = else_branch.as_ref().map(|b| b.as_ref()) {
                        if else_block.stmts.len() == 1 {
                            if let Stmt::Expr(else_expr) = &else_block.stmts[0] {
                                let (else_code, _) = emit_expr(ctx, else_expr)?;
                                return Ok((format!("({} ? {} : {})", cond_code, then_code, else_code), then_ty));
                            }
                        }
                    }
                }
            }
            
            // For complex if expressions used as values, we need a temp variable
            // For now, return empty - these should be handled as statements
            Ok(("".to_string(), "void".to_string()))
        },
        Expr::Paren(inner, _) => {
            let (inner_code, ty) = emit_expr(ctx, inner)?;
            Ok((format!("({})", inner_code), ty))
        },
        _ => Err(KainError::codegen("Unsupported expression in USF", expr.span())),
    }
}

fn emit_function_call(ctx: &mut USFContext, name: &str, args: &[kain_core::ast::CallArg]) -> KainResult<(String, String)> {
    match name {
        // Vector constructors
        "vec2" | "Vec2" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float2({})", arg_codes.join(", ")), "float2".to_string()))
        },
        "vec3" | "Vec3" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float3({})", arg_codes.join(", ")), "float3".to_string()))
        },
        "vec4" | "Vec4" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float4({})", arg_codes.join(", ")), "float4".to_string()))
        },
        
        // Math intrinsics - direct pass-through
        "sin" | "cos" | "tan" | "asin" | "acos" | "atan" | 
        "abs" | "floor" | "ceil" | "round" | "trunc" | "sqrt" | "rsqrt" |
        "exp" | "exp2" | "log" | "log2" | "log10" | "sign" | "saturate" => {
            let (arg_code, ty) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("{}({})", name, arg_code), ty))
        },
        "fract" => {
            let (arg_code, ty) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("frac({})", arg_code), ty))
        },
        
        // Two-arg math
        "pow" | "min" | "max" | "fmod" | "step" | "atan2" | "distance" => {
            let (arg1, ty) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            let ret_ty = if name == "distance" { "float".to_string() } else { ty };
            Ok((format!("{}({}, {})", name, arg1, arg2), ret_ty))
        },
        
        // Three-arg math
        "clamp" | "smoothstep" | "mad" => {
            let (arg1, ty) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            let (arg3, _) = emit_expr(ctx, &args[2].value)?;
            Ok((format!("{}({}, {}, {})", name, arg1, arg2, arg3), ty))
        },
        "mix" | "lerp" => {
            let (arg1, ty) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            let (arg3, _) = emit_expr(ctx, &args[2].value)?;
            Ok((format!("lerp({}, {}, {})", arg1, arg2, arg3), ty))
        },
        
        // Vector ops
        "length" => {
            let (arg_code, _) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("length({})", arg_code), "float".to_string()))
        },
        "normalize" => {
            let (arg_code, ty) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("normalize({})", arg_code), ty))
        },
        "dot" => {
            let (arg1, _) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("dot({}, {})", arg1, arg2), "float".to_string()))
        },
        "cross" => {
            let (arg1, ty) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("cross({}, {})", arg1, arg2), ty))
        },
        "reflect" | "refract" => {
            let (arg1, ty) = emit_expr(ctx, &args[0].value)?;
            let (arg2, _) = emit_expr(ctx, &args[1].value)?;
            if name == "refract" && args.len() > 2 {
                let (arg3, _) = emit_expr(ctx, &args[2].value)?;
                Ok((format!("refract({}, {}, {})", arg1, arg2, arg3), ty))
            } else {
                Ok((format!("{}({}, {})", name, arg1, arg2), ty))
            }
        },
        
        // Texture sampling - UE5 style with separate sampler
        "sample" => {
            let (texture, _) = emit_expr(ctx, &args[0].value)?;
            let (coords, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("{}.Sample({}Sampler, {})", texture, texture, coords), "float4".to_string()))
        },
        "sample_lod" | "SampleLevel" => {
            let (texture, _) = emit_expr(ctx, &args[0].value)?;
            let (coords, _) = emit_expr(ctx, &args[1].value)?;
            let (lod, _) = emit_expr(ctx, &args[2].value)?;
            Ok((format!("{}.SampleLevel({}Sampler, {}, {})", texture, texture, coords, lod), "float4".to_string()))
        },
        "load" | "Load" => {
            let (texture, _) = emit_expr(ctx, &args[0].value)?;
            let (location, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("{}.Load(int3({}, 0))", texture, location), "float4".to_string()))
        },
        
        // UAV store operations (compute shaders)
        "store" => {
            let (uav, _) = emit_expr(ctx, &args[0].value)?;
            let (coord, _) = emit_expr(ctx, &args[1].value)?;
            let (value, _) = emit_expr(ctx, &args[2].value)?;
            Ok((format!("{}[{}] = {}", uav, coord, value), "void".to_string()))
        },
        
        // Atomics for compute
        "atomic_add" => {
            let (uav, _) = emit_expr(ctx, &args[0].value)?;
            let (value, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("InterlockedAdd({}, {})", uav, value), "void".to_string()))
        },
        "atomic_min" | "atomic_max" => {
            let hlsl_name = if name == "atomic_min" { "InterlockedMin" } else { "InterlockedMax" };
            let (uav, _) = emit_expr(ctx, &args[0].value)?;
            let (value, _) = emit_expr(ctx, &args[1].value)?;
            Ok((format!("{}({}, {})", hlsl_name, uav, value), "void".to_string()))
        },
        
        // Barrier for compute
        "barrier" | "GroupMemoryBarrierWithGroupSync" => {
            Ok(("GroupMemoryBarrierWithGroupSync()".to_string(), "void".to_string()))
        },
        "device_barrier" | "DeviceMemoryBarrier" => {
            Ok(("DeviceMemoryBarrier()".to_string(), "void".to_string()))
        },
        
        // UE5 luminance helper
        "GetLuminance" | "luminance" => {
            let (arg_code, _) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("dot({}, float3(0.299, 0.587, 0.114))", arg_code), "float".to_string()))
        },
        
        // Type constructors/casts - return proper types
        "int" => {
            let (arg_code, _) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("int({})", arg_code), "int".to_string()))
        },
        "float" => {
            let (arg_code, _) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("float({})", arg_code), "float".to_string()))
        },
        "uint" => {
            let (arg_code, _) = emit_expr(ctx, &args[0].value)?;
            Ok((format!("uint({})", arg_code), "uint".to_string()))
        },
        "int2" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("int2({})", arg_codes.join(", ")), "int2".to_string()))
        },
        "int3" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("int3({})", arg_codes.join(", ")), "int3".to_string()))
        },
        "int4" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("int4({})", arg_codes.join(", ")), "int4".to_string()))
        },
        "uint2" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("uint2({})", arg_codes.join(", ")), "uint2".to_string()))
        },
        "uint3" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("uint3({})", arg_codes.join(", ")), "uint3".to_string()))
        },
        "uint4" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("uint4({})", arg_codes.join(", ")), "uint4".to_string()))
        },
        "float2" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float2({})", arg_codes.join(", ")), "float2".to_string()))
        },
        "float3" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float3({})", arg_codes.join(", ")), "float3".to_string()))
        },
        "float4" => {
            let mut arg_codes = Vec::new();
            for arg in args {
                let (code, _) = emit_expr(ctx, &arg.value)?;
                arg_codes.push(code);
            }
            Ok((format!("float4({})", arg_codes.join(", ")), "float4".to_string()))
        },
        
        // Data-driven fallback: query ShaderKnowledge for known intrinsics/UE5 functions
        _ => {
            let mut arg_codes = Vec::new();
            let mut first_arg_type = "float4".to_string();
            for (i, arg) in args.iter().enumerate() {
                let (code, ty) = emit_expr(ctx, &arg.value)?;
                if i == 0 { first_arg_type = ty; }
                arg_codes.push(code);
            }

            // Infer return type from ShaderKnowledge
            let return_type = if let Some(ref sk) = ctx.shader_knowledge {
                let inferred = sk.infer_return_type(name);
                match inferred {
                    "passthrough" => first_arg_type.clone(),
                    "unknown" => {
                        // Check if it's at least a known function
                        if sk.is_known_function(name) {
                            // Known UE5/HLSL function but no type info — use first arg type
                            first_arg_type.clone()
                        } else {
                            "float4".to_string()
                        }
                    }
                    other => other.to_string(),
                }
            } else {
                "float4".to_string()
            };

            Ok((format!("{}({})", name, arg_codes.join(", ")), return_type))
        },
    }
}

fn map_type_to_usf(ty: &Type) -> String {
    match ty {
        Type::Named { name, .. } => match name.as_str() {
            "Float" | "f32" => "float".to_string(),
            "Double" | "f64" => "double".to_string(),
            "Int" | "i32" => "int".to_string(),
            "UInt" | "u32" => "uint".to_string(),
            "Bool" => "bool".to_string(),
            "Vec2" => "float2".to_string(),
            "Vec3" => "float3".to_string(),
            "Vec4" => "float4".to_string(),
            "IVec2" => "int2".to_string(),
            "IVec3" => "int3".to_string(),
            "IVec4" => "int4".to_string(),
            "UVec2" => "uint2".to_string(),
            "UVec3" => "uint3".to_string(),
            "UVec4" => "uint4".to_string(),
            "Mat2" => "float2x2".to_string(),
            "Mat3" => "float3x3".to_string(),
            "Mat4" => "float4x4".to_string(),
            "Sampler2D" => "Texture2D<float4>".to_string(),
            "Sampler3D" => "Texture3D<float4>".to_string(),
            "SamplerCube" => "TextureCube<float4>".to_string(),
            "Image2D" => "RWTexture2D<float4>".to_string(),
            "Image3D" => "RWTexture3D<float4>".to_string(),
            "RWTexture2D" => "RWTexture2D<float4>".to_string(),
            "RWTexture2D_Float" => "RWTexture2D<float>".to_string(),
            "RWTexture2D_Float2" => "RWTexture2D<float2>".to_string(),
            "RWTexture2D_Float3" => "RWTexture2D<float3>".to_string(),
            "RWTexture2D_Int" => "RWTexture2D<int>".to_string(),
            "RWTexture2D_UInt" => "RWTexture2D<uint>".to_string(),
            "StructuredBuffer" => "StructuredBuffer<float4>".to_string(),
            "RWStructuredBuffer" => "RWStructuredBuffer<float4>".to_string(),
            _ => name.clone(),
        },
        _ => "float4".to_string(),
    }
}

fn infer_swizzle_type(swizzle: &str) -> String {
    match swizzle.len() {
        1 => "float".to_string(),
        2 => "float2".to_string(),
        3 => "float3".to_string(),
        4 => "float4".to_string(),
        _ => "float".to_string(),
    }
}

fn capitalize_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
    }
}

/// Generate a single USF string from a program (public API).
/// This generates ONLY the shader specified by shader_name, not all shaders.
pub fn generate_single_usf_from_program(program: &TypedProgram, shader_name: &str) -> KainResult<String> {
    generate_single_usf_cached(program, shader_name, &CachedMirrors::from_program(program))
}

fn generate_single_usf_cached(program: &TypedProgram, shader_name: &str, mirrors: &CachedMirrors) -> KainResult<String> {
    // Filter to only the shader we want
    let mut filtered_program = TypedProgram {
        items: Vec::new(),
    };
    
    // Always include all struct and enum definitions so that collect_component_mirrors
    // can find @component structs and enum names when generating POD mirror types.
    for item in &program.items {
        match item {
            TypedItem::Struct(_) | TypedItem::Enum(_) => {
                filtered_program.items.push(item.clone());
            }
            _ => {}
        }
    }

    // Then find and append only the matching shader.
    for item in &program.items {
        if let TypedItem::Shader(shader) = item {
            // Normalize both names for comparison (case-insensitive, ignore underscores)
            let normalized_ast_name = shader.ast.name.replace("_", "").to_lowercase();
            let normalized_shader_name = shader_name.replace("_", "").to_lowercase();
            
            if normalized_ast_name == normalized_shader_name {
                filtered_program.items.push(item.clone());
                break; // Found it, stop looking
            }
        }
    }
    
    if filtered_program.items.is_empty() {
        return Err(KainError::codegen(
            &format!("Shader '{}' not found in program", shader_name),
            kain_core::span::Span::default()
        ));
    }
    
    generate_cached(&filtered_program, mirrors)
}

/// All three shader artifacts (header, implementation, USF) generated in a single
/// pass — mirrors are computed once from the program and reused across all three.
pub struct ShaderArtifacts {
    pub header: String,
    pub cpp: String,
    pub usf: String,
}

/// Compile all shader artifacts for a single shader in one call.
/// This computes component mirrors **once** from the full program and passes the
/// result to each generator, avoiding the 3× per-shader mirror traversal that
/// occurs when calling the individual functions separately.
pub fn compile_shader_artifacts(
    program: &TypedProgram,
    shader_name: &str,
    plugin_name: &str,
) -> KainResult<ShaderArtifacts> {
    let mirrors = CachedMirrors::from_program(program);
    Ok(ShaderArtifacts {
        header: generate_cpp_header_cached(program, shader_name, plugin_name, &mirrors),
        cpp:    generate_cpp_implementation_cached(program, shader_name, plugin_name, &mirrors),
        usf:    generate_single_usf_cached(program, shader_name, &mirrors)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use kain_core::ast::{Shader, Uniform, Param, ShaderStage, Block};
    use kain_core::types::{TypedShader, TypedProgram, TypedItem, ResolvedType};
    use kain_core::span::Span;

    fn make_named_type(name: &str) -> Type {
        Type::Named { name: name.to_string(), generics: vec![], span: Span::default() }
    }

    fn make_uniform(name: &str, ty: &str, binding: u32) -> Uniform {
        Uniform { name: name.to_string(), ty: make_named_type(ty), binding, span: Span::default() }
    }

    fn make_param(name: &str, ty: &str) -> Param {
        Param { name: name.to_string(), ty: make_named_type(ty), mutable: false, default: None, span: Span::default() }
    }

    fn make_fragment_shader(name: &str, uniforms: Vec<Uniform>, inputs: Vec<Param>) -> TypedProgram {
        let body = Block {
            stmts: vec![
                Stmt::Return(Some(Expr::Call {
                    callee: Box::new(Expr::Ident("vec4".to_string(), Span::default())),
                    args: vec![
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(0.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(0.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                    ],
                    span: Span::default(),
                }), Span::default()),
            ],
            span: Span::default(),
        };

        let shader = TypedShader {
            ast: Shader {
                name: name.to_string(),
                stage: ShaderStage::Fragment,
                inputs,
                outputs: make_named_type("Vec4"),
                uniforms,
                body,
                span: Span::default(),
            },
            input_types: vec![],
            output_type: ResolvedType::Unknown,
        };

        TypedProgram { items: vec![TypedItem::Shader(shader)] }
    }

    fn make_compute_shader(name: &str, uniforms: Vec<Uniform>) -> TypedProgram {
        let body = Block {
            stmts: vec![
                Stmt::Return(Some(Expr::Call {
                    callee: Box::new(Expr::Ident("vec4".to_string(), Span::default())),
                    args: vec![
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                        kain_core::ast::CallArg { name: None, value: Expr::Float(1.0, Span::default()), span: Span::default() },
                    ],
                    span: Span::default(),
                }), Span::default()),
            ],
            span: Span::default(),
        };

        let shader = TypedShader {
            ast: Shader {
                name: name.to_string(),
                stage: ShaderStage::Compute,
                inputs: vec![make_param("thread_id", "Vec3")],
                outputs: make_named_type("Vec4"),
                uniforms,
                body,
                span: Span::default(),
            },
            input_types: vec![],
            output_type: ResolvedType::Unknown,
        };

        TypedProgram { items: vec![TypedItem::Shader(shader)] }
    }

    // ========================================================================
    // BUG 1 REGRESSION: is_permutation_param false positives
    // Short all-caps names like UV, ID, N must NOT be treated as permutations
    // ========================================================================
    #[test]
    fn test_permutation_detection_no_false_positives() {
        // These should NOT be permutations
        assert!(!is_permutation_param("UV"));
        assert!(!is_permutation_param("ID"));
        assert!(!is_permutation_param("N"));
        assert!(!is_permutation_param("RGB"));
        assert!(!is_permutation_param("XY"));
        assert!(!is_permutation_param("color"));
        assert!(!is_permutation_param("time"));

        // These SHOULD be permutations
        assert!(is_permutation_param("CFG_HIGH_QUALITY"));
        assert!(is_permutation_param("ENABLE_SHADOWS"));
        assert!(is_permutation_param("USE_NORMAL_MAP"));
        assert!(is_permutation_param("WITH_ALPHA"));
        assert!(is_permutation_param("HAS_TEXTURE"));
        assert!(is_permutation_param("ALLOW_MSAA"));
        assert!(is_permutation_param("SUPPORT_HDR"));
        // Generic SCREAMING_SNAKE_CASE with underscore + 4+ chars
        assert!(is_permutation_param("MY_CUSTOM_FLAG"));
        assert!(is_permutation_param("GENMIPS_SRGB"));
    }

    // ========================================================================
    // BUG 2 REGRESSION: Empty TShaderPermutationDomain<>
    // When no permutations, header must NOT contain FPermutationDomain typedef
    // ========================================================================
    #[test]
    fn test_no_empty_permutation_domain() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("color", "Vec3", 0),
            make_uniform("time", "Float", 1),
        ], vec![make_param("uv", "Vec2")]);

        let header = generate_cpp_header(&program, "TestShader");
        assert!(!header.contains("TShaderPermutationDomain<>"),
            "Empty TShaderPermutationDomain<> should not be emitted");
        assert!(!header.contains("FPermutationDomain"),
            "FPermutationDomain should not appear when no permutations exist");
    }

    #[test]
    fn test_permutation_domain_emitted_when_present() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("CFG_HIGH_QUALITY", "Float", 0),
            make_uniform("color", "Vec3", 1),
        ], vec![make_param("uv", "Vec2")]);

        let header = generate_cpp_header(&program, "TestShader");
        assert!(header.contains("SHADER_PERMUTATION_BOOL(\"CFG_HIGH_QUALITY\")"),
            "Permutation bool should be declared");
        assert!(header.contains("TShaderPermutationDomain<CFG_HIGH_QUALITY>"),
            "Permutation domain should include the permutation");
    }

    // ========================================================================
    // BUG 3 REGRESSION: Header forward decl must include permutation bools
    // ========================================================================
    #[test]
    fn test_header_forward_decl_includes_permutation_args() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("CFG_HIGH_QUALITY", "Float", 0),
            make_uniform("color", "Vec3", 1),
        ], vec![make_param("uv", "Vec2")]);

        let header = generate_cpp_header(&program, "TestShader");
        // The forward declaration must include the permutation bool
        assert!(header.contains("bool bCFG_HIGH_QUALITY"),
            "Forward declaration must include permutation bool parameter");
    }

    #[test]
    fn test_header_forward_decl_no_permutation_args_when_none() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("color", "Vec3", 0),
        ], vec![make_param("uv", "Vec2")]);

        let header = generate_cpp_header(&program, "TestShader");
        assert!(!header.contains("bool b"),
            "No permutation bool args when no permutations exist");
    }

    // ========================================================================
    // BUG 4 REGRESSION: Uniform type inference
    // Uniforms must be seeded in ctx.vars so type propagation is correct
    // ========================================================================
    #[test]
    fn test_uniform_type_in_usf_output() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("status_color", "Vec3", 0),
            make_uniform("time", "Float", 1),
            make_uniform("size", "Vec2", 2),
        ], vec![make_param("uv", "Vec2")]);

        let usf = generate(&program).unwrap();
        // Uniforms must be declared with correct HLSL types
        assert!(usf.contains("float3 status_color;"), "Vec3 uniform should be float3, got:\n{}", usf);
        assert!(usf.contains("float time;"), "Float uniform should be float");
        assert!(usf.contains("float2 size;"), "Vec2 uniform should be float2");
    }

    // ========================================================================
    // BUG 5 REGRESSION: map_usf_type_to_cpp int2 -> FIntPoint
    // ========================================================================
    #[test]
    fn test_int2_maps_to_fintpoint() {
        assert_eq!(map_usf_type_to_cpp("int2"), "FIntPoint");
        // Other int types should still work
        assert_eq!(map_usf_type_to_cpp("int"), "int32");
        assert_eq!(map_usf_type_to_cpp("int3"), "FIntVector");
        assert_eq!(map_usf_type_to_cpp("uint"), "uint32");
        assert_eq!(map_usf_type_to_cpp("float2"), "FVector2f");
        assert_eq!(map_usf_type_to_cpp("float3"), "FVector3f");
        assert_eq!(map_usf_type_to_cpp("float4"), "FVector4f");
    }

    // ========================================================================
    // BUG 6 REGRESSION: IMPLEMENT_GLOBAL_SHADER virtual path
    // Must be /Plugin/{PluginName}/{ShaderName}.usf (no /Shaders/)
    // ========================================================================
    #[test]
    fn test_implement_global_shader_virtual_path() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("color", "Vec3", 0),
        ], vec![make_param("uv", "Vec2")]);

        let cpp = generate_cpp_implementation(&program, "TestShader", "MyPlugin");
        assert!(cpp.contains("/Plugin/MyPlugin/TestShader.usf"),
            "Virtual path must be /Plugin/PluginName/ShaderName.usf");
        assert!(!cpp.contains("/Shaders/"),
            "Virtual path must NOT contain /Shaders/");
    }

    // ========================================================================
    // Compute shader: SF_Compute in IMPLEMENT_GLOBAL_SHADER
    // ========================================================================
    #[test]
    fn test_compute_shader_stage_detection() {
        let program = make_compute_shader("MyCompute", vec![
            make_uniform("color", "Vec3", 0),
        ]);

        let cpp = generate_cpp_implementation(&program, "MyCompute", "TestPlugin");
        assert!(cpp.contains("SF_Compute"), "Compute shader must use SF_Compute");
        assert!(cpp.contains("CS\""), "Compute entry point must end with CS");
    }

    #[test]
    fn test_fragment_shader_stage_detection() {
        let program = make_fragment_shader("MyPixel", vec![
            make_uniform("color", "Vec3", 0),
        ], vec![make_param("uv", "Vec2")]);

        let cpp = generate_cpp_implementation(&program, "MyPixel", "TestPlugin");
        assert!(cpp.contains("SF_Pixel"), "Fragment shader must use SF_Pixel");
        assert!(cpp.contains("PS\""), "Fragment entry point must end with PS");
    }

    // ========================================================================
    // Permutation params must NOT appear in SHADER_PARAMETER_STRUCT
    // ========================================================================
    #[test]
    fn test_permutations_excluded_from_parameter_struct() {
        let program = make_fragment_shader("TestShader", vec![
            make_uniform("CFG_HIGH_QUALITY", "Float", 0),
            make_uniform("ENABLE_SHADOWS", "Float", 1),
            make_uniform("color", "Vec3", 2),
            make_uniform("time", "Float", 3),
        ], vec![make_param("uv", "Vec2")]);

        let header = generate_cpp_header(&program, "TestShader");
        // Permutations should NOT be in the parameter struct
        assert!(!header.contains("SHADER_PARAMETER(float, CFG_HIGH_QUALITY)"),
            "Permutation CFG_HIGH_QUALITY must not be in SHADER_PARAMETER_STRUCT");
        assert!(!header.contains("SHADER_PARAMETER(float, ENABLE_SHADOWS)"),
            "Permutation ENABLE_SHADOWS must not be in SHADER_PARAMETER_STRUCT");
        // Regular params should be there
        assert!(header.contains("SHADER_PARAMETER(FVector3f, color)"),
            "Regular uniform 'color' must be in SHADER_PARAMETER_STRUCT");
        assert!(header.contains("SHADER_PARAMETER(float, time)"),
            "Regular uniform 'time' must be in SHADER_PARAMETER_STRUCT");
    }
}
