[package]
name = "kain_crate_ffi_bridge_sample_cli_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kain-core = { path = "M:\\Code\\Kain\\crates\\kain-core" }
kain-host = { path = "M:\\Code\\Kain\\crates\\kain-host", default-features = false }
sample_cli_ffi = { package = "sample_cli_ffi", path = "\\\\?\\C:\\Users\\Admin\\AppData\\Local\\Temp\\kain_cli_crateffi_5d5028c225a4425cb2bf9654176cd8ca\\sample_cli_ffi" }

[profile.dev]
debug = 0
panic = "unwind"

[workspace]
resolver = "2"
