// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771787931
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/ActorComponent.h"
#include "Kismet/BlueprintFunctionLibrary.h"

#include "TestComponentAccess.generated.h"



UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class TESTCOMPONENTACCESS_API UHealthComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UHealthComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Component")
		float current_health;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Component")
		float max_health;

};


UCLASS(HideCategories=(Input, Collision, LOD))
class TESTCOMPONENTACCESS_API ATestActor : public AActor
{
	GENERATED_BODY()

	public:
		ATestActor();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		UHealthComponent* health_comp;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		TArray<int64> items;
		void tick(const auto self, const float dt);

	};


