[package]
name = "kain_crate_ffi_bridge_cargo_node_weave"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kain-core = { path = "M:\\Code\\Kain\\crates\\kain-core" }
kain-host = { path = "M:\\Code\\Kain\\crates\\kain-host", default-features = false }
cargo_node_weave = { package = "cargo_node_weave", path = "\\\\?\\M:\\Code\\Kain\\smoketest\\cargo_node\\signal_workbench\\local_crate" }

[profile.dev]
debug = 0
panic = "unwind"

[workspace]
resolver = "2"
