//! C++ Code Generation - Transpiles KAIN AST to modern C++17 source code
//!
//! Generic C++ output for non-engine targets. Use `-t ue5` for Unreal Engine.
//! Generated code uses C++17 features: structured bindings, optional, variant.

use kain_core::types::{TypedProgram, TypedItem};
use kain_core::error::KainResult;
use kain_core::ast::{
    Type, Expr, Stmt, Block, BinaryOp, UnaryOp, Pattern, Function, Struct, Enum,
    VariantFields, Impl, Param, ElseBranch, EnumVariantFields,
};


/// Generate C++ source code from a typed program
pub fn generate(program: &TypedProgram) -> KainResult<String> {
    let mut gen = CppGen::new();
    Ok(gen.gen_program(program))
}

struct StringBuilder {
    lines: Vec<String>,
}

impl StringBuilder {
    fn new() -> Self {
        Self { lines: Vec::new() }
    }

    fn push(&mut self, text: &str) {
        self.lines.push(text.to_string());
    }

    fn push_line(&mut self, text: &str) {
        self.lines.push(format!("{}\n", text));
    }

    fn build(&self) -> String {
        self.lines.join("")
    }
}

struct CppGen {
    output: StringBuilder,
    indent: usize,
}

impl CppGen {
    fn new() -> Self {
        Self {
            output: StringBuilder::new(),
            indent: 0,
        }
    }

    fn push_indent(&mut self) {
        self.indent += 1;
    }

    fn pop_indent(&mut self) {
        if self.indent > 0 {
            self.indent -= 1;
        }
    }

    fn indent_str(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn write_line(&mut self, line: &str) {
        let indented = format!("{}{}", self.indent_str(), line);
        self.output.push_line(&indented);
    }

    fn write_blank(&mut self) {
        self.output.push_line("");
    }

    fn gen_program(&mut self, program: &TypedProgram) -> String {
        // Header comment
        self.write_line("// Generated by KAIN Compiler");
        self.write_line("// Do not edit - regenerate from .kn source");
        self.write_blank();

        // Standard headers
        self.write_line("#include <cstdint>");
        self.write_line("#include <string>");
        self.write_line("#include <vector>");
        self.write_line("#include <optional>");
        self.write_line("#include <variant>");
        self.write_line("#include <memory>");
        self.write_line("#include <iostream>");
        self.write_blank();

        // Forward declarations for structs
        for item in &program.items {
            if let TypedItem::Struct(st) = item {
                self.write_line(&format!("struct {};", st.ast.name));
            }
        }
        if program.items.iter().any(|i| matches!(i, TypedItem::Struct(_))) {
            self.write_blank();
        }

        // Generate each item
        for item in &program.items {
            self.gen_item(item);
            self.write_blank();
        }

        self.output.build()
    }

    fn gen_item(&mut self, item: &TypedItem) {
        match item {
            TypedItem::Function(fn_typed) => self.gen_function(&fn_typed.ast),
            TypedItem::Struct(st) => self.gen_struct(&st.ast),
            TypedItem::Enum(en) => self.gen_enum(&en.ast),
            TypedItem::Impl(im) => self.gen_impl(&im.ast),
            _ => {} // Skip shaders, actors, components for generic C++
        }
    }

    fn gen_function(&mut self, func: &Function) {
        let params = self.gen_params(&func.params);

        let ret = if let Some(ty) = &func.return_type {
            self.map_type(ty)
        } else {
            "void".to_string()
        };

        let has_return_type = func.return_type.is_some();

        // Function signature
        self.write_line(&format!("{} {}({}) {{", ret, func.name, params));
        self.push_indent();

        // Use implicit return for non-void functions
        self.gen_block_with_implicit_return(&func.body, has_return_type);

        self.pop_indent();
        self.write_line("}");
    }


    fn gen_params(&self, params: &[Param]) -> String {
        let parts: Vec<String> = params
            .iter()
            .map(|p| {
                let ty_str = self.map_type(&p.ty);
                if p.mutable {
                    format!("{} {}", ty_str, p.name)
                } else {
                    format!("const {} {}", ty_str, p.name)
                }
            })
            .collect();
        parts.join(", ")
    }

    fn gen_struct(&mut self, struct_def: &Struct) {
        self.write_line(&format!("struct {} {{", struct_def.name));
        self.push_indent();

        for field in &struct_def.fields {
            self.write_line(&format!("{} {};", self.map_type(&field.ty), field.name));
        }

        self.pop_indent();
        self.write_line("};");
    }

    fn gen_enum(&mut self, enum_def: &Enum) {
        // Check if this is a simple C-style enum (all Unit variants)
        let is_simple = enum_def.variants.iter().all(|v| matches!(v.fields, VariantFields::Unit));

        if is_simple {
            self.write_line(&format!("enum class {} {{", enum_def.name));
            self.push_indent();
            for variant in &enum_def.variants {
                self.write_line(&format!("{},", variant.name));
            }
            self.pop_indent();
            self.write_line("};");
        } else {
            // Tagged union via std::variant
            self.write_line(&format!("// Tagged union: {}", enum_def.name));
            
            // Generate variant structs
            for variant in &enum_def.variants {
                match &variant.fields {
                    VariantFields::Unit => {
                        self.write_line(&format!("struct {}_{} {{}};", enum_def.name, variant.name));
                    }
                    VariantFields::Tuple(types) => {
                        self.write_line(&format!("struct {}_{} {{", enum_def.name, variant.name));
                        self.push_indent();
                        for (i, ty) in types.iter().enumerate() {
                            self.write_line(&format!("{} _{};", self.map_type(ty), i));
                        }
                        self.pop_indent();
                        self.write_line("};");
                    }
                    VariantFields::Struct(fields) => {
                        self.write_line(&format!("struct {}_{} {{", enum_def.name, variant.name));
                        self.push_indent();
                        for f in fields {
                            self.write_line(&format!("{} {};", self.map_type(&f.ty), f.name));
                        }
                        self.pop_indent();
                        self.write_line("};");
                    }
                }
            }

            // Generate the variant typedef
            let variant_types: Vec<String> = enum_def.variants
                .iter()
                .map(|v| format!("{}_{}", enum_def.name, v.name))
                .collect();
            self.write_line(&format!("using {} = std::variant<{}>;", 
                enum_def.name, variant_types.join(", ")));
        }
    }

    fn gen_impl(&mut self, impl_def: &Impl) {
        // C++ doesn't have impl blocks - generate free functions or methods
        // For now, generate as member functions via class extension pattern
        let target = self.map_type(&impl_def.target_type);
        
        self.write_line(&format!("// Methods for {}", target));
        for method in &impl_def.methods {
            // Add self parameter handling here if needed
            self.gen_function(method);
            self.write_blank();
        }
    }

    fn gen_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.gen_stmt(stmt);
        }
    }

    /// Generate block with implicit return for the last statement
    /// KAIN functions without explicit return use last expression as return value
    fn gen_block_with_implicit_return(&mut self, block: &Block, implicit_return: bool) {
        let len = block.stmts.len();
        for (i, stmt) in block.stmts.iter().enumerate() {
            let is_last = i == len - 1;
            if is_last && implicit_return {
                // Handle implicit return for last statement
                if let Stmt::Expr(expr) = stmt {
                    // Skip explicit returns and control flow
                    if !matches!(expr, Expr::Return(_, _) | Expr::Break(_, _) | Expr::Continue(_)) {
                        let expr_str = self.gen_expr(expr);
                        self.write_line(&format!("return {};", expr_str));
                        continue;
                    }
                }
            }
            self.gen_stmt(stmt);
        }
    }


    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { pattern, ty, value, .. } => {
                if let Pattern::Binding { name, mutable, .. } = pattern {
                    let ty_str = ty.as_ref()
                        .map(|t| self.map_type(t))
                        .unwrap_or_else(|| "auto".to_string());
                    
                    if let Some(val) = value {
                        if *mutable {
                            self.write_line(&format!("{} {} = {};", ty_str, name, self.gen_expr(val)));
                        } else {
                            self.write_line(&format!("const {} {} = {};", ty_str, name, self.gen_expr(val)));
                        }
                    } else {
                        self.write_line(&format!("{} {};", ty_str, name));
                    }
                }
            }

            Stmt::Return(maybe_expr, _) => {
                if let Some(expr) = maybe_expr {
                    self.write_line(&format!("return {};", self.gen_expr(expr)));
                } else {
                    self.write_line("return;");
                }
            }

            Stmt::Break(_, _) => {
                self.write_line("break;");
            }

            Stmt::Continue(_) => {
                self.write_line("continue;");
            }

            Stmt::For { binding, iter, body, .. } => {
                if let Pattern::Binding { name, .. } = binding {
                    self.write_line(&format!("for (auto {} : {}) {{", name, self.gen_expr(iter)));
                    self.push_indent();
                    self.gen_block(body);
                    self.pop_indent();
                    self.write_line("}");
                }
            }

            Stmt::While { condition, body, .. } => {
                self.write_line(&format!("while ({}) {{", self.gen_expr(condition)));
                self.push_indent();
                self.gen_block(body);
                self.pop_indent();
                self.write_line("}");
            }

            Stmt::Loop { body, .. } => {
                self.write_line("while (true) {");
                self.push_indent();
                self.gen_block(body);
                self.pop_indent();
                self.write_line("}");
            }

            Stmt::Expr(expr) => {
                if let Expr::If { condition, then_branch, else_branch, .. } = expr {
                    self.gen_if_stmt(condition, then_branch, else_branch);
                } else if let Expr::Assign { target, value, .. } = expr {
                    self.write_line(&format!("{} = {};", self.gen_expr(target), self.gen_expr(value)));
                } else {
                    let expr_str = self.gen_expr(expr);
                    if !expr_str.is_empty() {
                        self.write_line(&format!("{};", expr_str));
                    }
                }
            }

            Stmt::Item(_) => {
                // Nested items not common in generated C++
            }
        }
    }

    fn gen_if_stmt(&mut self, condition: &Expr, then_branch: &Block, else_branch: &Option<Box<ElseBranch>>) {
        self.write_line(&format!("if ({}) {{", self.gen_expr(condition)));
        self.push_indent();
        self.gen_block(then_branch);
        self.pop_indent();
        
        if let Some(else_br) = else_branch {
            match else_br.as_ref() {
                ElseBranch::Else(block) => {
                    self.write_line("} else {");
                    self.push_indent();
                    self.gen_block(block);
                    self.pop_indent();
                    self.write_line("}");
                }
                ElseBranch::ElseIf(cond, block, next_else) => {
                    self.write_line(&format!("}} else if ({}) {{", self.gen_expr(cond)));
                    self.push_indent();
                    self.gen_block(block);
                    self.pop_indent();
                    if let Some(next) = next_else {
                        self.gen_else_branch_continuation(next);
                    } else {
                        self.write_line("}");
                    }
                }
            }
        } else {
            self.write_line("}");
        }
    }

    fn gen_else_branch_continuation(&mut self, branch: &ElseBranch) {
        match branch {
            ElseBranch::Else(block) => {
                self.write_line("} else {");
                self.push_indent();
                self.gen_block(block);
                self.pop_indent();
                self.write_line("}");
            }
            ElseBranch::ElseIf(cond, block, next_else) => {
                self.write_line(&format!("}} else if ({}) {{", self.gen_expr(cond)));
                self.push_indent();
                self.gen_block(block);
                self.pop_indent();
                if let Some(next) = next_else {
                    self.gen_else_branch_continuation(next);
                } else {
                    self.write_line("}");
                }
            }
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Int(n, _) => n.to_string(),
            Expr::Float(f, _) => format!("{:.6}", f),
            Expr::String(s, _) => format!("std::string(\"{}\")", self.escape_string(s)),
            Expr::Bool(b, _) => if *b { "true".to_string() } else { "false".to_string() },
            Expr::None(_) => "std::nullopt".to_string(),
            Expr::Ident(name, _) => name.clone(),

            Expr::Binary { left, op, right, .. } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                let cpp_op = self.map_binop(op);
                format!("({} {} {})", l, cpp_op, r)
            }

            Expr::Unary { op, operand, .. } => {
                let o = self.gen_expr(operand);
                let cpp_op = self.map_unaryop(op);
                format!("({}{})", cpp_op, o)
            }

            Expr::Call { callee, args, .. } => {
                let fn_name = self.gen_expr(callee);

                // Handle KAIN builtins
                if fn_name == "println" || fn_name == "print" {
                    let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expr(&a.value)).collect();
                    if fn_name == "println" {
                        return format!("std::cout << {} << std::endl", arg_strs.join(" << \" \" << "));
                    } else {
                        return format!("std::cout << {}", arg_strs.join(" << \" \" << "));
                    }
                }

                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expr(&a.value)).collect();
                format!("{}({})", fn_name, arg_strs.join(", "))
            }

            Expr::MethodCall { receiver, method, args, .. } => {
                let recv = self.gen_expr(receiver);
                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expr(&a.value)).collect();
                format!("{}.{}({})", recv, method, arg_strs.join(", "))
            }

            Expr::Field { object, field, .. } => {
                format!("{}.{}", self.gen_expr(object), field)
            }

            Expr::Index { object, index, .. } => {
                format!("{}[{}]", self.gen_expr(object), self.gen_expr(index))
            }

            Expr::Array(elements, _) => {
                let elems: Vec<String> = elements.iter().map(|e| self.gen_expr(e)).collect();
                format!("std::vector{{{}}}", elems.join(", "))
            }

            Expr::Tuple(elements, _) => {
                let elems: Vec<String> = elements.iter().map(|e| self.gen_expr(e)).collect();
                format!("std::make_tuple({})", elems.join(", "))
            }

            Expr::Struct { name, fields, .. } => {
                let field_strs: Vec<String> = fields
                    .iter()
                    .map(|(_, fval)| self.gen_expr(fval))
                    .collect();
                format!("{}{{{}}}", name, field_strs.join(", "))
            }

            Expr::EnumVariant { enum_name, variant, fields, .. } => {
                match fields {
                    EnumVariantFields::Unit => format!("{}::{}", enum_name, variant),
                    EnumVariantFields::Tuple(args) => {
                        let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                        format!("{}_{}{{ {} }}", enum_name, variant, arg_strs.join(", "))
                    }
                    EnumVariantFields::Struct(fields) => {
                        let field_strs: Vec<String> = fields
                            .iter()
                            .map(|(n, v)| format!(".{} = {}", n, self.gen_expr(v)))
                            .collect();
                        format!("{}_{}{{ {} }}", enum_name, variant, field_strs.join(", "))
                    }
                }
            }

            Expr::If { condition, then_branch, else_branch, .. } => {
                // Ternary for simple cases
                if then_branch.stmts.len() == 1 && else_branch.is_some() {
                    if let Stmt::Expr(then_expr) = &then_branch.stmts[0] {
                        if let Some(ElseBranch::Else(else_block)) = else_branch.as_ref().map(|b| b.as_ref()) {
                            if else_block.stmts.len() == 1 {
                                if let Stmt::Expr(else_expr) = &else_block.stmts[0] {
                                    let cond = self.gen_expr(condition);
                                    let then_code = self.gen_expr(then_expr);
                                    let else_code = self.gen_expr(else_expr);
                                    return format!("({} ? {} : {})", cond, then_code, else_code);
                                }
                            }
                        }
                    }
                }
                "/* complex if expr */".to_string()
            }

            Expr::Match { scrutinee, arms, .. } => {
                // C++ doesn't have pattern matching - use std::visit for variants
                let scrut = self.gen_expr(scrutinee);
                format!("/* match {} */", scrut)
            }

            Expr::Lambda { params, body, .. } => {
                let param_strs: Vec<String> = params.iter().map(|p| format!("auto {}", p.name)).collect();
                format!("[&]({}){{{}}}", param_strs.join(", "), self.gen_expr(body))
            }

            Expr::Ref { mutable, value, .. } => {
                if *mutable {
                    format!("&{}", self.gen_expr(value))
                } else {
                    format!("&{}", self.gen_expr(value))
                }
            }

            Expr::Deref(inner, _) => {
                format!("*{}", self.gen_expr(inner))
            }

            Expr::Cast { value, target, .. } => {
                format!("static_cast<{}>({})", self.map_type(target), self.gen_expr(value))
            }

            Expr::Range { start, end, inclusive, .. } => {
                // C++ doesn't have native ranges - this would need a range library
                let s = start.as_ref().map(|e| self.gen_expr(e)).unwrap_or_default();
                let e = end.as_ref().map(|e| self.gen_expr(e)).unwrap_or_default();
                format!("/* range {}..{}{} */", s, if *inclusive { "=" } else { "" }, e)
            }

            Expr::Block(block, _) => {
                // Immediately invoked lambda for block expressions
                format!("[&](){{ /* block */ }}()")
            }

            Expr::Paren(inner, _) => {
                format!("({})", self.gen_expr(inner))
            }

            Expr::Return(maybe_expr, _) => {
                if let Some(expr) = maybe_expr {
                    format!("return {}", self.gen_expr(expr))
                } else {
                    "return".to_string()
                }
            }

            Expr::Break(_, _) => "break".to_string(),
            Expr::Continue(_) => "continue".to_string(),

            Expr::FString(parts, _) => {
                // Build concatenated string
                let mut result = String::from("std::string()");
                for part in parts {
                    if let Expr::String(s, _) = part {
                        result.push_str(&format!(" + \"{}\"", s));
                    } else {
                        result.push_str(&format!(" + std::to_string({})", self.gen_expr(part)));
                    }
                }
                result
            }

            _ => "/* unhandled expr */".to_string(),
        }
    }

    fn map_type(&self, ty: &Type) -> String {
        match ty {
            Type::Named { name, generics, .. } => {
                let cpp_name = match name.as_str() {
                    "Int" => "int64_t",
                    "Float" => "double",
                    "Bool" => "bool",
                    "String" => "std::string",
                    "Unit" | "()" => "void",
                    "Array" => "std::vector",
                    "Option" => "std::optional",
                    _ => name,
                };

                if generics.is_empty() {
                    cpp_name.to_string()
                } else {
                    let gen_strs: Vec<String> = generics.iter().map(|g| self.map_type(g)).collect();
                    format!("{}<{}>", cpp_name, gen_strs.join(", "))
                }
            }
            Type::Tuple(types, _) => {
                let type_strs: Vec<String> = types.iter().map(|t| self.map_type(t)).collect();
                format!("std::tuple<{}>", type_strs.join(", "))
            }
            Type::Array(inner, size, _) => {
                format!("std::array<{}, {}>", self.map_type(inner), size)
            }
            Type::Slice(inner, _) => {
                format!("std::span<{}>", self.map_type(inner))
            }
            Type::Ref { mutable, inner, .. } => {
                if *mutable {
                    format!("{}&", self.map_type(inner))
                } else {
                    format!("const {}&", self.map_type(inner))
                }
            }
            Type::Ptr { inner, .. } => {
                format!("{}*", self.map_type(inner))
            }
            Type::Function { params, return_type, .. } => {
                let param_strs: Vec<String> = params.iter().map(|p| self.map_type(p)).collect();
                format!("std::function<{}({})>", self.map_type(return_type), param_strs.join(", "))
            }
            Type::Option(inner, _) => {
                format!("std::optional<{}>", self.map_type(inner))
            }
            Type::Result(ok, err, _) => {
                format!("std::variant<{}, {}>", self.map_type(ok), self.map_type(err))
            }
            Type::Infer(_) => "auto".to_string(),
            Type::Never(_) => "[[noreturn]] void".to_string(),
            Type::Unit(_) => "void".to_string(),
            Type::Impl { trait_name, generics, .. } => {
                if generics.is_empty() {
                    format!("/* impl {} */", trait_name)
                } else {
                    let gen_strs: Vec<String> = generics.iter().map(|g| self.map_type(g)).collect();
                    format!("/* impl {}<{}> */", trait_name, gen_strs.join(", "))
                }
            }
        }
    }

    fn map_binop(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Pow => "/* pow */",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::Eq => "==",
            BinaryOp::Ne => "!=",
            BinaryOp::Lt => "<",
            BinaryOp::Le => "<=",
            BinaryOp::Gt => ">",
            BinaryOp::Ge => ">=",
            BinaryOp::BitAnd => "&",
            BinaryOp::BitOr => "|",
            BinaryOp::BitXor => "^",
            BinaryOp::Shl => "<<",
            BinaryOp::Shr => ">>",
            BinaryOp::Assign => "=",
            BinaryOp::AddAssign => "+=",
            BinaryOp::SubAssign => "-=",
            BinaryOp::MulAssign => "*=",
            BinaryOp::DivAssign => "/=",
            BinaryOp::Range => "..",
            BinaryOp::RangeInclusive => "..=",
        }
    }

    fn map_unaryop(&self, op: &UnaryOp) -> &'static str {
        match op {
            UnaryOp::Not => "!",
            UnaryOp::Neg => "-",
            UnaryOp::Ref => "&",
            UnaryOp::RefMut => "&",
            UnaryOp::BitNot => "~",
            UnaryOp::Deref => "*",
        }
    }

    fn escape_string(&self, s: &str) -> String {
        let mut result = String::new();
        for c in s.chars() {
            match c {
                '\n' => result.push_str("\\n"),
                '\t' => result.push_str("\\t"),
                '\\' => result.push_str("\\\\"),
                '"' => result.push_str("\\\""),
                _ => result.push(c),
            }
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kain_core::span::Span;


    #[test]
    fn test_type_mapping() {
        let gen = CppGen::new();
        let int_ty = Type::Named {
            name: "Int".to_string(),
            generics: vec![],
            span: Span::default(),
        };
        assert_eq!(gen.map_type(&int_ty), "int64_t");
    }
}
