use super::config::Ue5ModuleConfig;

/// Generate a .uplugin file with correct module type(s) and loading phase(s)
/// 
/// # Parameters
/// - `plugin_name`: Name of the plugin
/// - `description`: Optional description text
/// - `has_editor_items`: Whether the plugin contains editor-only items
/// - `needs_split`: Whether to generate two modules (Runtime + Editor)
/// - `has_shaders`: Whether the plugin contains shaders (requires CanContainContent: true)
pub fn generate_uplugin_file(plugin_name: &str, description: &Option<String>, has_editor_items: bool, needs_split: bool, has_shaders: bool) -> String {
    let desc = description.as_ref()
        .map(|s| s.as_str())
        .unwrap_or("Generated by KAIN-PRO");
    
    let modules_json = if needs_split {
        // Two modules: Runtime + Editor
        format!(r#"    {{
      "Name": "{}",
      "Type": "Runtime",
      "LoadingPhase": "PostConfigInit"
    }},
    {{
      "Name": "{}Editor",
      "Type": "Editor",
      "LoadingPhase": "PostEngineInit"
    }}"#, plugin_name, plugin_name)
    } else {
        // Single module
        let (module_type, loading_phase) = if has_editor_items {
            ("Editor", "PostEngineInit")
        } else {
            ("Runtime", "PostConfigInit")
        };
        format!(r#"    {{
      "Name": "{}",
      "Type": "{}",
      "LoadingPhase": "{}"
    }}"#, plugin_name, module_type, loading_phase)
    };
    
    // When shaders are present, the plugin must have CanContainContent: true
    // This allows UE5 to load .usf files from the Shaders/ directory.
    let can_contain_content = if has_shaders { "true" } else { "false" };

    format!(r#"{{
  "FileVersion": 3,
  "Version": 1,
  "VersionName": "1.0.0",
  "FriendlyName": "{}",
  "Description": "{}",
  "Category": "KAIN-PRO",
  "CreatedBy": "KAIN-PRO Compiler",
  "CreatedByURL": "",
  "DocsURL": "",
  "MarketplaceURL": "",
  "SupportURL": "",
  "CanContainContent": {},
  "IsBetaVersion": false,
  "IsExperimentalVersion": false,
  "Installed": false,
  "Modules": [
{}
  ]
}}
"#, plugin_name, desc, can_contain_content, modules_json)
}

/// Generate a .uplugin file from an explicit, data-driven module list.
pub fn generate_uplugin_file_from_modules(
    plugin_name: &str,
    description: &Option<String>,
    has_shaders: bool,
    modules: &[Ue5ModuleConfig],
) -> String {
    let desc = description
        .as_ref()
        .map(|s| s.as_str())
        .unwrap_or("Generated by KAIN-PRO");

    let modules_json = modules
        .iter()
        .map(|m| {
            format!(
                r#"    {{
      "Name": "{}",
      "Type": "{}",
      "LoadingPhase": "{}"
    }}"#,
                m.name,
                m.module_type.as_uplugin_type(),
                m.loading_phase
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");

    let can_contain_content = if has_shaders { "true" } else { "false" };

    format!(
        r#"{{
  "FileVersion": 3,
  "Version": 1,
  "VersionName": "1.0.0",
  "FriendlyName": "{}",
  "Description": "{}",
  "Category": "KAIN-PRO",
  "CreatedBy": "KAIN-PRO Compiler",
  "CreatedByURL": "",
  "DocsURL": "",
  "MarketplaceURL": "",
  "SupportURL": "",
  "CanContainContent": {},
  "IsBetaVersion": false,
  "IsExperimentalVersion": false,
  "Installed": false,
  "Modules": [
{}
  ]
}}
"#,
        plugin_name, desc, can_contain_content, modules_json
    )
}
