// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "AtmosphericScattering.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FAtmosphericScatteringShader, "/Plugin/UltimateVFX/AtmosphericScattering.usf", "AtmosphericScatteringPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_AtmosphericScattering(
    FRDGBuilder& GraphBuilder,
    FVector3f rayleigh_coefficient,
    float rayleigh_scale_height,
    float mie_coefficient,
    float mie_scale_height,
    float mie_direction,
    float sun_intensity,
    FVector3f sun_direction,
    FVector3f sun_color,
    float planet_radius,
    float atmosphere_radius,
    float sample_count
)
{
    FAtmosphericScatteringShader::FParameters* Params = GraphBuilder.AllocParameters<FAtmosphericScatteringShader::FParameters>();
    // Bind Scalars
    Params->rayleigh_coefficient = rayleigh_coefficient;
    Params->rayleigh_scale_height = rayleigh_scale_height;
    Params->mie_coefficient = mie_coefficient;
    Params->mie_scale_height = mie_scale_height;
    Params->mie_direction = mie_direction;
    Params->sun_intensity = sun_intensity;
    Params->sun_direction = sun_direction;
    Params->sun_color = sun_color;
    Params->planet_radius = planet_radius;
    Params->atmosphere_radius = atmosphere_radius;
    Params->sample_count = sample_count;

    FAtmosphericScatteringShader::Exec(GraphBuilder, *Params);
}
