// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "RainDrops.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FRainDropsShader, "/Plugin/UltimateVFX/RainDrops.usf", "RainDropsPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_RainDrops(
    FRDGBuilder& GraphBuilder,
    float rain_intensity,
    float drop_size,
    float drop_speed,
    float drop_density,
    float ripple_strength,
    float blur_strength
)
{
    FRainDropsShader::FParameters* Params = GraphBuilder.AllocParameters<FRainDropsShader::FParameters>();
    // Bind Scalars
    Params->rain_intensity = rain_intensity;
    Params->drop_size = drop_size;
    Params->drop_speed = drop_speed;
    Params->drop_density = drop_density;
    Params->ripple_strength = ripple_strength;
    Params->blur_strength = blur_strength;

    FRainDropsShader::Exec(GraphBuilder, *Params);
}
