// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "ScreenSpaceReflections.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FScreenSpaceReflectionsShader, "/Plugin/UltimateVFX/ScreenSpaceReflections.usf", "ScreenSpaceReflectionsPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_ScreenSpaceReflections(
    FRDGBuilder& GraphBuilder,
    float ssr_intensity,
    float max_ray_distance,
    float stride,
    float thickness,
    float jitter,
    float max_steps,
    float binary_search_steps,
    float fade_start,
    float fade_end
)
{
    FScreenSpaceReflectionsShader::FParameters* Params = GraphBuilder.AllocParameters<FScreenSpaceReflectionsShader::FParameters>();
    // Bind Scalars
    Params->ssr_intensity = ssr_intensity;
    Params->max_ray_distance = max_ray_distance;
    Params->stride = stride;
    Params->thickness = thickness;
    Params->jitter = jitter;
    Params->max_steps = max_steps;
    Params->binary_search_steps = binary_search_steps;
    Params->fade_start = fade_start;
    Params->fade_end = fade_end;

    FScreenSpaceReflectionsShader::Exec(GraphBuilder, *Params);
}
