// Generated by KAIN Compiler - UE5 C++ Codegen
// Do not edit - regenerate from .kn source

#include "UltimateVFX.h"
#include "RenderGraph.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphResources.h"
#include "RenderGraphUtils.h"
#include "RenderTargetPool.h"
#include "Engine/TextureRenderTarget2D.h"

AAtmosphericScatteringActor::AAtmosphericScatteringActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AAtmosphericScatteringActor::BeginPlay()
{
	Super::BeginPlay();
	UE_LOG(LogTemp, Warning, TEXT("Atmospheric scattering initialized"));
}

void AAtmosphericScatteringActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

	void AAtmosphericScatteringActor::Server_SetTimeOfDay_Implementation(const ETimeOfDay time)
	{
		if (time == ETimeOfDay::Dawn) { sun_direction = FVector(0.800000f, 0.300000f, 0.500000f); }else if (time == ETimeOfDay::Noon) { sun_direction = FVector(0.000000f, 1.000000f, 0.000000f); }else if (time == ETimeOfDay::Dusk) { sun_direction = FVector((-0.800000f), 0.300000f, 0.500000f); }else if (time == ETimeOfDay::Night) { sun_direction = FVector(0.000000f, (-0.500000f), 0.000000f); } else { sun_direction = FVector(0.000000f, 0.700000f, 0.700000f); };
	}

	bool AAtmosphericScatteringActor::Server_SetTimeOfDay_Validate(const ETimeOfDay time)
	{
		return true; // Add validation logic here
	}

AVolumetricCloudsActor::AVolumetricCloudsActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AVolumetricCloudsActor::BeginPlay()
{
	Super::BeginPlay();
}

void AVolumetricCloudsActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

		void AVolumetricCloudsActor::Server_SetWeather_Implementation(const EWeatherType weather)
		{
			if (weather == EWeatherType::Clear) { cloud_coverage = 0.200000f; }else if (weather == EWeatherType::Cloudy) { cloud_coverage = 0.600000f; }else if (weather == EWeatherType::Overcast) { cloud_coverage = 0.900000f; }else if (weather == EWeatherType::Storm) { cloud_coverage = 1.000000f; } else { cloud_coverage = 0.500000f; };
		}

		bool AVolumetricCloudsActor::Server_SetWeather_Validate(const EWeatherType weather)
		{
			return true; // Add validation logic here
		}

AOceanRenderingActor::AOceanRenderingActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AOceanRenderingActor::BeginPlay()
{
	Super::BeginPlay();
			UE_LOG(LogTemp, Warning, TEXT("Ocean rendering initialized"));
}

void AOceanRenderingActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AVolumetricFogActor::AVolumetricFogActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AVolumetricFogActor::BeginPlay()
{
	Super::BeginPlay();
}

void AVolumetricFogActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AGodRaysActor::AGodRaysActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AGodRaysActor::BeginPlay()
{
	Super::BeginPlay();
}

void AGodRaysActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

ABloomLensFlareActor::ABloomLensFlareActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void ABloomLensFlareActor::BeginPlay()
{
	Super::BeginPlay();
}

void ABloomLensFlareActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AScreenSpaceReflectionsActor::AScreenSpaceReflectionsActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AScreenSpaceReflectionsActor::BeginPlay()
{
	Super::BeginPlay();
}

void AScreenSpaceReflectionsActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AAmbientOcclusionActor::AAmbientOcclusionActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AAmbientOcclusionActor::BeginPlay()
{
	Super::BeginPlay();
}

void AAmbientOcclusionActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

ADepthOfFieldActor::ADepthOfFieldActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void ADepthOfFieldActor::BeginPlay()
{
	Super::BeginPlay();
}

void ADepthOfFieldActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AMotionBlurActor::AMotionBlurActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AMotionBlurActor::BeginPlay()
{
	Super::BeginPlay();
}

void AMotionBlurActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AColorGradingActor::AColorGradingActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AColorGradingActor::BeginPlay()
{
	Super::BeginPlay();
}

void AColorGradingActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AChromaticAberrationActor::AChromaticAberrationActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AChromaticAberrationActor::BeginPlay()
{
	Super::BeginPlay();
}

void AChromaticAberrationActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AFilmGrainActor::AFilmGrainActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AFilmGrainActor::BeginPlay()
{
	Super::BeginPlay();
}

void AFilmGrainActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

ASharpenActor::ASharpenActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void ASharpenActor::BeginPlay()
{
	Super::BeginPlay();
}

void ASharpenActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

ARainDropsActor::ARainDropsActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void ARainDropsActor::BeginPlay()
{
	Super::BeginPlay();
}

void ARainDropsActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

AProceduralSkyActor::AProceduralSkyActor()
{
	PrimaryActorTick.bCanEverTick = true;
}

void AProceduralSkyActor::BeginPlay()
{
	Super::BeginPlay();
}

void AProceduralSkyActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

																		int32 UUltimateVFXFunctionLibrary::get_quality_sample_count(const EEffectQuality quality)
																		{
																			return ((quality == EEffectQuality::Potato) ? 8 : (quality == EEffectQuality::Low) ? 16 : (quality == EEffectQuality::Medium) ? 32 : (quality == EEffectQuality::High) ? 64 : (quality == EEffectQuality::Ultra) ? 128 : (quality == EEffectQuality::Cinematic) ? 256 : 32);
																		}

																		float UUltimateVFXFunctionLibrary::get_time_of_day_sun_angle(const ETimeOfDay time)
																		{
																			return ((time == ETimeOfDay::Dawn) ? 15.000000f : (time == ETimeOfDay::Morning) ? 45.000000f : (time == ETimeOfDay::Noon) ? 90.000000f : (time == ETimeOfDay::Afternoon) ? 135.000000f : (time == ETimeOfDay::Dusk) ? 165.000000f : (time == ETimeOfDay::Night) ? 270.000000f : (time == ETimeOfDay::Midnight) ? 270.000000f : 90.000000f);
																		}

																		float UUltimateVFXFunctionLibrary::get_weather_fog_density(const EWeatherType weather)
																		{
																			return ((weather == EWeatherType::Clear) ? 0.010000f : (weather == EWeatherType::Cloudy) ? 0.030000f : (weather == EWeatherType::Overcast) ? 0.050000f : (weather == EWeatherType::LightRain) ? 0.070000f : (weather == EWeatherType::HeavyRain) ? 0.100000f : (weather == EWeatherType::Storm) ? 0.150000f : (weather == EWeatherType::Snow) ? 0.080000f : (weather == EWeatherType::Fog) ? 0.300000f : 0.050000f);
																		}

																		FVector UUltimateVFXFunctionLibrary::lerp_vec3(const FVector a, const FVector b, const float t)
																		{
																			return ((a * ((1.000000f - t))) + (b * t));
																		}

																		FVector UUltimateVFXFunctionLibrary::calculate_sun_color(const ETimeOfDay time)
																		{
																			return ((time == ETimeOfDay::Dawn) ? FVector(1.000000f, 0.600000f, 0.400000f) : (time == ETimeOfDay::Morning) ? FVector(1.000000f, 0.950000f, 0.900000f) : (time == ETimeOfDay::Noon) ? FVector(1.000000f, 1.000000f, 1.000000f) : (time == ETimeOfDay::Afternoon) ? FVector(1.000000f, 0.950000f, 0.850000f) : (time == ETimeOfDay::Dusk) ? FVector(1.000000f, 0.500000f, 0.300000f) : (time == ETimeOfDay::Night) ? FVector(0.200000f, 0.200000f, 0.400000f) : (time == ETimeOfDay::Midnight) ? FVector(0.100000f, 0.100000f, 0.300000f) : FVector(1.000000f, 1.000000f, 1.000000f));
																		}

																		FVector UUltimateVFXFunctionLibrary::get_atmosphere_preset_colors(const EAtmospherePreset preset)
																		{
																			return ((preset == EAtmospherePreset::Earth) ? FVector(0.200000f, 0.500000f, 1.000000f) : (preset == EAtmospherePreset::Mars) ? FVector(0.800000f, 0.400000f, 0.200000f) : (preset == EAtmospherePreset::Alien) ? FVector(0.500000f, 1.000000f, 0.300000f) : (preset == EAtmospherePreset::Toxic) ? FVector(0.600000f, 0.800000f, 0.200000f) : (preset == EAtmospherePreset::Underwater) ? FVector(0.000000f, 0.300000f, 0.600000f) : (preset == EAtmospherePreset::Space) ? FVector(0.000000f, 0.000000f, 0.000000f) : FVector(0.200000f, 0.500000f, 1.000000f));
																		}

																// Module implementation
																// Shader directory registration is handled by static initializers in shader .cpp files

																class FUltimateVFXModule : public IModuleInterface
																{
																public:
																	virtual void StartupModule() override
																	{
																		// Shader directory mapping is registered by static initializers
																		// in each shader .cpp file before IMPLEMENT_GLOBAL_SHADER runs
																	}

																	virtual void ShutdownModule() override
																	{
																		// Cleanup if needed
																	}
																};

																IMPLEMENT_MODULE(FUltimateVFXModule, UltimateVFX)
