// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "K2Continental.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

namespace {
    struct FShaderDirectoryRegistration {
        FShaderDirectoryRegistration() {
            static bool bRegistered = false;
            if (!bRegistered) {
                TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("KainCosmos"));
                if (Plugin.IsValid()) {
                    FString PluginShaderDir = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Shaders"));
                    AddShaderSourceDirectoryMapping(TEXT("/Plugin/KainCosmos"), PluginShaderDir);
                    bRegistered = true;
                } else {
                    UE_LOG(LogShaders, Error, TEXT("Failed to find plugin 'KainCosmos' for shader directory mapping"));
                }
            }
        }
    };
    static FShaderDirectoryRegistration GShaderDirReg_K2Continental;
}

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FK2ContinentalShader, "/Plugin/KainCosmos/Shaders/K2Continental.usf", "K2ContinentalCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_K2Continental(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef tectonic_map,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FK2ContinentalShader::FParameters* Params = GraphBuilder.AllocParameters<FK2ContinentalShader::FParameters>();
    // Bind Textures
    Params->tectonic_map = tectonic_map;
    Params->tectonic_mapSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FK2ContinentalShader::Exec(GraphBuilder, *Params, GroupCount);
}
