// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "K3Thermal.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

namespace {
    struct FShaderDirectoryRegistration {
        FShaderDirectoryRegistration() {
            static bool bRegistered = false;
            if (!bRegistered) {
                TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("KainCosmos"));
                if (Plugin.IsValid()) {
                    FString PluginShaderDir = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Shaders"));
                    AddShaderSourceDirectoryMapping(TEXT("/Plugin/KainCosmos"), PluginShaderDir);
                    bRegistered = true;
                } else {
                    UE_LOG(LogShaders, Error, TEXT("Failed to find plugin 'KainCosmos' for shader directory mapping"));
                }
            }
        }
    };
    static FShaderDirectoryRegistration GShaderDirReg_K3Thermal;
}

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FK3ThermalShader, "/Plugin/KainCosmos/Shaders/K3Thermal.usf", "K3ThermalCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_K3Thermal(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef height_map,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FK3ThermalShader::FParameters* Params = GraphBuilder.AllocParameters<FK3ThermalShader::FParameters>();
    // Bind Textures
    Params->height_map = height_map;
    Params->height_mapSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FK3ThermalShader::Exec(GraphBuilder, *Params, GroupCount);
}
