// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "K5Resources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

namespace {
    struct FShaderDirectoryRegistration {
        FShaderDirectoryRegistration() {
            static bool bRegistered = false;
            if (!bRegistered) {
                TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("KainCosmos"));
                if (Plugin.IsValid()) {
                    FString PluginShaderDir = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Shaders"));
                    AddShaderSourceDirectoryMapping(TEXT("/Plugin/KainCosmos"), PluginShaderDir);
                    bRegistered = true;
                } else {
                    UE_LOG(LogShaders, Error, TEXT("Failed to find plugin 'KainCosmos' for shader directory mapping"));
                }
            }
        }
    };
    static FShaderDirectoryRegistration GShaderDirReg_K5Resources;
}

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FK5ResourcesShader, "/Plugin/KainCosmos/Shaders/K5Resources.usf", "K5ResourcesCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_K5Resources(
    FRDGBuilder& GraphBuilder,
    float seed,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FK5ResourcesShader::FParameters* Params = GraphBuilder.AllocParameters<FK5ResourcesShader::FParameters>();
    // Bind Scalars
    Params->seed = seed;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FK5ResourcesShader::Exec(GraphBuilder, *Params, GroupCount);
}
