// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "K6Normals.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/Paths.h"
#include "ShaderCore.h"

namespace {
    struct FShaderDirectoryRegistration {
        FShaderDirectoryRegistration() {
            static bool bRegistered = false;
            if (!bRegistered) {
                TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(TEXT("KainCosmos"));
                if (Plugin.IsValid()) {
                    FString PluginShaderDir = FPaths::Combine(Plugin->GetBaseDir(), TEXT("Shaders"));
                    AddShaderSourceDirectoryMapping(TEXT("/Plugin/KainCosmos"), PluginShaderDir);
                    bRegistered = true;
                } else {
                    UE_LOG(LogShaders, Error, TEXT("Failed to find plugin 'KainCosmos' for shader directory mapping"));
                }
            }
        }
    };
    static FShaderDirectoryRegistration GShaderDirReg_K6Normals;
}

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FK6NormalsShader, "/Plugin/KainCosmos/Shaders/K6Normals.usf", "K6NormalsCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_K6Normals(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef h_map,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FK6NormalsShader::FParameters* Params = GraphBuilder.AllocParameters<FK6NormalsShader::FParameters>();
    // Bind Textures
    Params->h_map = h_map;
    Params->h_mapSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FK6NormalsShader::Exec(GraphBuilder, *Params, GroupCount);
}
