// Generated by KAIN-PRO - Module Registration
#include "KainCosmos.h"
#include "Modules/ModuleManager.h"

class FKainCosmosModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        // Module startup
    }

    virtual void ShutdownModule() override
    {
        // Module shutdown
    }
};

IMPLEMENT_MODULE(FKainCosmosModule, KainCosmos)
