// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1770864925
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/ActorComponent.h"
#include "Kismet/BlueprintFunctionLibrary.h"

#include "FOrbitVectors.generated.h"


USTRUCT(BlueprintType)
struct KAINCOSMOS_API FOrbitVectors
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector position;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector velocity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FVector momentum;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float inclination;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	float eccentricity;

};













