// Generated by KAIN-PRO Compiler — Runtime Module
using UnrealBuildTool;
using System.IO;

public class VoxelForgePro : ModuleRules
{
	public VoxelForgePro(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"Core",
				"CoreUObject",
				"Engine",
				"Projects",
				"RHI",
				"RenderCore",
				"Renderer"
			}
		);
	}
}
