// Generated by KAIN - UE5 Editor Tools
#pragma once
#include "CoreMinimal.h"
#include "AlphaGen.h"
#include "Modules/ModuleInterface.h"
#include "Modules/ModuleManager.h"
#include "Interfaces/IPluginManager.h"
#include "ShaderCore.h"

class FAlphaGenEditorModuleModule : public IModuleInterface
{
public:
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;
};

