// Generated by KAIN - UE5 Editor Tools
#pragma once
#include "CoreMinimal.h"
#include "AlphaGenEditorTypes.h"
#include "Widgets/SCompoundWidget.h"
#include "Widgets/DeclarativeSyntaxSupport.h"
#include "Widgets/Views/SListView.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Input/SCheckBox.h"
#include "Widgets/Input/SComboBox.h"
#include "Widgets/Input/SEditableTextBox.h"
#include "Widgets/Input/SSlider.h"
#include "Widgets/Input/SSpinBox.h"
#include "Widgets/Text/STextBlock.h"
#include "Widgets/Images/SImage.h"
#include "Widgets/Layout/SScrollBox.h"
#include "Widgets/Layout/SSplitter.h"
#include "Widgets/Layout/SBorder.h"
#include "Widgets/Colors/SColorBlock.h"

class SAlphaGenEditorWidget : public SCompoundWidget
{
public:
	// Layout Optimization Report
	// Static Properties: 17 (no Tick overhead)
	// Reactive Properties: 0 (requires Tick)
	// Event Handlers: 0
	// Estimated Tick Reduction: 100.0%
	//
	// SLATE_ARGUMENT current_generator - Explicit @argument attribute
	// SLATE_ARGUMENT preview_texture - Explicit @argument attribute
	// SLATE_ARGUMENT preview_size - Explicit @argument attribute
	// SLATE_ARGUMENT export_size - Explicit @argument attribute
	// SLATE_ARGUMENT param1 - Explicit @argument attribute
	// SLATE_ARGUMENT param2 - Explicit @argument attribute
	// SLATE_ARGUMENT param3 - Explicit @argument attribute
	// SLATE_ARGUMENT export_path - Explicit @argument attribute
	// SLATE_ARGUMENT export_name - Explicit @argument attribute
	// SLATE_ARGUMENT on_generate_clicked - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_export_clicked - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_generator_changed - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_param1_changed - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_param2_changed - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_param3_changed - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_preview_size_changed - Default (no clear reactive usage)
	// SLATE_ARGUMENT on_export_size_changed - Default (no clear reactive usage)
	SLATE_BEGIN_ARGS(SAlphaGenEditorWidget)
		: _Content()
		, _current_generator(EAlphaGenType())
		, _preview_texture(FTexture2D())
		, _preview_size(0)
		, _export_size(0)
		, _param1(0.0f)
		, _param2(0.0f)
		, _param3(0.0f)
		, _export_path(FString())
		, _export_name(FString())
		, _on_generate_clicked(FOnButtonClicked())
		, _on_export_clicked(FOnButtonClicked())
		, _on_generator_changed(FOnTextEntered())
		, _on_param1_changed(FOnSliderChanged())
		, _on_param2_changed(FOnSliderChanged())
		, _on_param3_changed(FOnSliderChanged())
		, _on_preview_size_changed(FOnTextEntered())
		, _on_export_size_changed(FOnTextEntered())
		{}
		
		SLATE_DEFAULT_SLOT(FArguments, Content)
		SLATE_ARGUMENT(EAlphaGenType, current_generator)
		SLATE_ARGUMENT(FTexture2D, preview_texture)
		SLATE_ARGUMENT(int32, preview_size)
		SLATE_ARGUMENT(int32, export_size)
		SLATE_ARGUMENT(float, param1)
		SLATE_ARGUMENT(float, param2)
		SLATE_ARGUMENT(float, param3)
		SLATE_ARGUMENT(FString, export_path)
		SLATE_ARGUMENT(FString, export_name)
		SLATE_ARGUMENT(FOnButtonClicked, on_generate_clicked)
		SLATE_ARGUMENT(FOnButtonClicked, on_export_clicked)
		SLATE_ARGUMENT(FOnTextEntered, on_generator_changed)
		SLATE_ARGUMENT(FOnSliderChanged, on_param1_changed)
		SLATE_ARGUMENT(FOnSliderChanged, on_param2_changed)
		SLATE_ARGUMENT(FOnSliderChanged, on_param3_changed)
		SLATE_ARGUMENT(FOnTextEntered, on_preview_size_changed)
		SLATE_ARGUMENT(FOnTextEntered, on_export_size_changed)
	SLATE_END_ARGS()
	
	void Construct(const FArguments& InArgs);
	
	FReply Handleon_generate_clicked();
	
	FReply Handleon_export_clicked();
	
	FReply Handleon_generator_changed();
	
	FReply Handleon_param1_changed();
	
	FReply Handleon_param2_changed();
	
	FReply Handleon_param3_changed();
	
	FReply Handleon_preview_size_changed();
	
	FReply Handleon_export_size_changed();
};

