// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771563888
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EEditorToolMode.generated.h"



UENUM(BlueprintType)
enum class EEditorToolMode : uint8
{
	Sculpt UMETA(DisplayName = "Sculpt"),
	BiomePaint UMETA(DisplayName = "BiomePaint"),
	ResourceSeeding UMETA(DisplayName = "ResourceSeeding"),
	SovereignControl UMETA(DisplayName = "SovereignControl"),
	ClimateTweak UMETA(DisplayName = "ClimateTweak"),
	EditorToolMode_MAX UMETA(DisplayName = "EditorToolMode_MAX"),
};













