// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771341970
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EPlanetArchetype.generated.h"

UENUM(BlueprintType)
enum class EPlanetArchetype : uint8
{
	TerranPrime UMETA(DisplayName = "TerranPrime"),
	Oceanic UMETA(DisplayName = "Oceanic"),
	Volcanic UMETA(DisplayName = "Volcanic"),
	FrozenWasteland UMETA(DisplayName = "FrozenWasteland"),
	GasGiant UMETA(DisplayName = "GasGiant"),
	MetallicCore UMETA(DisplayName = "MetallicCore"),
	ShatteredWorld UMETA(DisplayName = "ShatteredWorld"),
	DysonShell UMETA(DisplayName = "DysonShell"),
	AncientRuins UMETA(DisplayName = "AncientRuins"),
	BioLuminescent UMETA(DisplayName = "BioLuminescent"),
	ChronoShifted UMETA(DisplayName = "ChronoShifted"),
	PlanetArchetype_MAX UMETA(DisplayName = "PlanetArchetype_MAX"),
};

