// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771341970
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EResourceTier.generated.h"

UENUM(BlueprintType)
enum class EResourceTier : uint8
{
	Common UMETA(DisplayName = "Common"),
	Rare UMETA(DisplayName = "Rare"),
	Exotic UMETA(DisplayName = "Exotic"),
	Anomalous UMETA(DisplayName = "Anomalous"),
	Celestial UMETA(DisplayName = "Celestial"),
	ResourceTier_MAX UMETA(DisplayName = "ResourceTier_MAX"),
};

