// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771563888
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "FOrbitVectors.generated.h"



USTRUCT(BlueprintType)
struct KAINCOSMOS_API FOrbitVectors
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "OrbitVectors")
	FVector3f position = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "OrbitVectors")
	FVector3f velocity = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "OrbitVectors")
	FVector3f momentum = FVector::ZeroVector;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "OrbitVectors")
	float inclination = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "OrbitVectors")
	float eccentricity = 0.0f;

};













