// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771341970
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EOrbitalDrift.h"
#include "FOrbitVectors.h"

#include "FOrbitalPhysicsComponent.generated.h"

UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class KAINCOSMOS_API UOrbitalPhysicsComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UOrbitalPhysicsComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		FOrbitVectors vectors;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EOrbitalDrift drift_mode;

};

