// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771341970
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"

#include "FResourceLatticeComponent.generated.h"

UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class KAINCOSMOS_API UResourceLatticeComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UResourceLatticeComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 lattice_seed;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float total_minerals;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<FVector> active_extraction_sites;

};

