// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FK12SovereignPBRShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FK12SovereignPBRShader);
    SHADER_USE_PARAMETER_STRUCT(FK12SovereignPBRShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER_RDG_TEXTURE(Texture2D, albedo)
        SHADER_PARAMETER_SAMPLER(SamplerState, albedoSampler)
        SHADER_PARAMETER_RDG_TEXTURE(Texture2D, lights)
        SHADER_PARAMETER_SAMPLER(SamplerState, lightsSampler)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG pixel shader pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters)
    {
        TShaderMapRef<FK12SovereignPBRShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry
        // This is a simplified example - adapt to your rendering pipeline
        // Use AddDrawPass or integrate with your post-process pipeline
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FK12SovereignPBRShader, "/Plugin/YourPlugin/K12SovereignPBR.usf", "K12SovereignPBRPS", SF_Pixel);

// Helper function to add pass to render graph
void AddPass_K12SovereignPBR(
    FRDGBuilder& GraphBuilder,
    FRDGTextureRef albedo,
    FRDGTextureRef lights
);
