// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "MagnetohydrodynamicsLorentz.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMagnetohydrodynamicsLorentzShader, "/Plugin/FluidFlow/MagnetohydrodynamicsLorentz.usf", "MagnetohydrodynamicsLorentzCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_MagnetohydrodynamicsLorentz(
    FRDGBuilder& GraphBuilder,
    FElectroMagneticComponentData em,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FMagnetohydrodynamicsLorentzShader::FParameters* Params = GraphBuilder.AllocParameters<FMagnetohydrodynamicsLorentzShader::FParameters>();
    // Bind Scalars
    Params->em = em;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FMagnetohydrodynamicsLorentzShader::Exec(GraphBuilder, *Params, GroupCount);
}
