// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "MultiphaseSurfaceTension.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FMultiphaseSurfaceTensionShader, "/Plugin/FluidFlow/MultiphaseSurfaceTension.usf", "MultiphaseSurfaceTensionCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_MultiphaseSurfaceTension(
    FRDGBuilder& GraphBuilder,
    FMultiphaseComponentData multiphase,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FMultiphaseSurfaceTensionShader::FParameters* Params = GraphBuilder.AllocParameters<FMultiphaseSurfaceTensionShader::FParameters>();
    // Bind Scalars
    Params->multiphase = multiphase;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FMultiphaseSurfaceTensionShader::Exec(GraphBuilder, *Params, GroupCount);
}
