// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "ParticleCollision.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FParticleCollisionShader, "/Plugin/FluidFlow/ParticleCollision.usf", "ParticleCollisionCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_ParticleCollision(
    FRDGBuilder& GraphBuilder,
    FHyperFluidParticleSystemComponentData particle_system,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FParticleCollisionShader::FParameters* Params = GraphBuilder.AllocParameters<FParticleCollisionShader::FParameters>();
    // Bind Scalars
    Params->particle_system = particle_system;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FParticleCollisionShader::Exec(GraphBuilder, *Params, GroupCount);
}
