// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "PhaseChange_Condensation.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FPhaseChange_CondensationShader, "/Plugin/FluidFlow/PhaseChange_Condensation.usf", "PhaseChange_CondensationCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_PhaseChange_Condensation(
    FRDGBuilder& GraphBuilder,
    FMultiphaseComponentData multiphase,
    FThermalComponentData thermal,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FPhaseChange_CondensationShader::FParameters* Params = GraphBuilder.AllocParameters<FPhaseChange_CondensationShader::FParameters>();
    // Bind Scalars
    Params->multiphase = multiphase;
    Params->thermal = thermal;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FPhaseChange_CondensationShader::Exec(GraphBuilder, *Params, GroupCount);
}
