// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "PlasmaTokamak.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FPlasmaTokamakShader, "/Plugin/FluidFlow/PlasmaTokamak.usf", "PlasmaTokamakCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_PlasmaTokamak(
    FRDGBuilder& GraphBuilder,
    ElectroMagneticComponent em,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FPlasmaTokamakShader::FParameters* Params = GraphBuilder.AllocParameters<FPlasmaTokamakShader::FParameters>();
    // Bind Scalars
    Params->em = em;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FPlasmaTokamakShader::Exec(GraphBuilder, *Params, GroupCount);
}
