// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "SpectralFourierTransform.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FSpectralFourierTransformShader, "/Plugin/FluidFlow/SpectralFourierTransform.usf", "SpectralFourierTransformCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_SpectralFourierTransform(
    FRDGBuilder& GraphBuilder,
    PhysicalPropertiesComponent physics,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FSpectralFourierTransformShader::FParameters* Params = GraphBuilder.AllocParameters<FSpectralFourierTransformShader::FParameters>();
    // Bind Scalars
    Params->physics = physics;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FSpectralFourierTransformShader::Exec(GraphBuilder, *Params, GroupCount);
}
