// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "SurfaceTension_CSF.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FSurfaceTension_CSFShader, "/Plugin/FluidFlow/SurfaceTension_CSF.usf", "SurfaceTension_CSFCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_SurfaceTension_CSF(
    FRDGBuilder& GraphBuilder,
    FMultiphaseComponentData multiphase,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FSurfaceTension_CSFShader::FParameters* Params = GraphBuilder.AllocParameters<FSurfaceTension_CSFShader::FParameters>();
    // Bind Scalars
    Params->multiphase = multiphase;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FSurfaceTension_CSFShader::Exec(GraphBuilder, *Params, GroupCount);
}
