#ifndef RUNTIME_TIERS_H
#define RUNTIME_TIERS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum {
    KAIN_RUNTIME_TIER_NOOP = 0,
    KAIN_RUNTIME_TIER_GATED = 1,
    KAIN_RUNTIME_TIER_FULL = 2,
};

#ifndef KAIN_RUNTIME_CONTROL_TIER
#if defined(NDEBUG)
#define KAIN_RUNTIME_CONTROL_TIER KAIN_RUNTIME_TIER_GATED
#else
#define KAIN_RUNTIME_CONTROL_TIER KAIN_RUNTIME_TIER_FULL
#endif
#endif

#ifndef KAIN_RUNTIME_DIAG_TIER
#define KAIN_RUNTIME_DIAG_TIER KAIN_RUNTIME_CONTROL_TIER
#endif

#ifndef KAIN_RUNTIME_PROFILE_TIER
#define KAIN_RUNTIME_PROFILE_TIER KAIN_RUNTIME_TIER_GATED
#endif

#ifndef KAIN_RUNTIME_FIXUP_TIER
#define KAIN_RUNTIME_FIXUP_TIER KAIN_RUNTIME_CONTROL_TIER
#endif

#define KAIN_RUNTIME_TIER_AT_LEAST(current_tier, minimum_tier) \
    ((int)(current_tier) >= (int)(minimum_tier))

#define KAIN_RUNTIME_DIAG_ENABLED() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_DIAG_TIER, KAIN_RUNTIME_TIER_GATED)

#define KAIN_RUNTIME_PROFILE_ENABLED() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_PROFILE_TIER, KAIN_RUNTIME_TIER_GATED)

#define KAIN_RUNTIME_FIXUP_ENABLED() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_FIXUP_TIER, KAIN_RUNTIME_TIER_GATED)

#define KAIN_RUNTIME_DIAG_FULL() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_DIAG_TIER, KAIN_RUNTIME_TIER_FULL)

#define KAIN_RUNTIME_PROFILE_FULL() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_PROFILE_TIER, KAIN_RUNTIME_TIER_FULL)

#define KAIN_RUNTIME_FIXUP_FULL() \
    KAIN_RUNTIME_TIER_AT_LEAST(KAIN_RUNTIME_FIXUP_TIER, KAIN_RUNTIME_TIER_FULL)

#ifdef __cplusplus
}
#endif

#endif /* RUNTIME_TIERS_H */
