// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771795179
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/ActorComponent.h"
#include "Kismet/BlueprintFunctionLibrary.h"

#include "StdlibTest.generated.h"



FVector GetActorLocation();

void SetActorLocation(const FVector location);

FRotator GetActorRotation();

void SetActorRotation(const FRotator rotation);

FVector GetActorScale();

void SetActorScale(const FVector scale);

FVector GetActorForwardVector();

FVector GetActorRightVector();

FVector GetActorUpVector();

void DestroyActor();

float GetDistanceTo(AActor* other);

void SetActorHiddenInGame(const bool hidden);

void SetActorEnableCollision(const bool enable);

FVector GetActorBounds();

bool IsActorBeingDestroyed();

void AddActorWorldOffset(const FVector offset);

void AddActorWorldRotation(const FRotator rotation);

void SetLifeSpan(const float seconds);

float GetLifeSpan();

void AttachToActor(AActor* parent);

void DetachFromActor();

TArray<AActor*> GetAttachedActors();

AActor* GetAttachParentActor();

USTRUCT(BlueprintType)
struct STDLIBTEST_API FTimerHandle
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TimerHandle")
	int64 handle_id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TimerHandle")
	bool is_active = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TimerHandle")
	int64 loop_count = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TimerHandle")
	float elapsed_time = 0.0f;

};

USTRUCT(BlueprintType)
struct STDLIBTEST_API FInputAction
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InputAction")
	FString action_name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InputAction")
	FString key_binding;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InputAction")
	bool is_pressed = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InputAction")
	float trigger_value = 0.0f;

};

void SetScalarParameter(const UMaterial material, const FString param_name, const float value);

float GetScalarParameter(const UMaterial material, const FString param_name);

void SetVectorParameter(const UMaterial material, const FString param_name, const FVector value);

FVector GetVectorParameter(const UMaterial material, const FString param_name);

void SetTextureParameter(const UMaterial material, const FString param_name, const UTexture2D texture);

UMaterial CreateDynamicMaterialInstance(const UMaterial material);

void SetMaterial(const MeshComponent mesh, const int64 slot, const UMaterial material);

UMaterial GetMaterial(const MeshComponent mesh, const int64 slot);







float max(const float a, const float b);

float min(const float a, const float b);

float abs(const float x);

float sqrt(const float x);

float pow(const float base, const float exp);

float floor(const float x);

float ceil(const float x);

float round(const float x);

float clamp(const float value, const float min_val, const float max_val);

float sin(const float x);

float cos(const float x);

float tan(const float x);

float asin(const float x);

float acos(const float x);

float atan(const float x);

float atan2(const float y, const float x);

float random();

float Vector_Length(const FVector v);

FVector Vector_Normalize(const FVector v);

float Vector_Dot(const FVector a, const FVector b);

FVector Vector_Cross(const FVector a, const FVector b);

float Vector_Distance(const FVector a, const FVector b);

FVector Rotator_GetForwardVector(const FRotator r);

FVector Rotator_GetRightVector(const FRotator r);

FVector Rotator_GetUpVector(const FRotator r);

float Lerp(const float a, const float b, const float alpha);

FVector VLerp(const FVector a, const FVector b, const float alpha);

FRotator RLerp(const FRotator a, const FRotator b, const float alpha, const bool shortest_path);

float FInterpTo(const float current, const float target, const float delta_time, const float speed);

FVector VInterpTo(const FVector current, const FVector target, const float delta_time, const float speed);

AActor* SpawnEmitterAtLocation(const FString system_name, const FVector location);

AActor* SpawnEmitterAttached(const FString system_name, const USceneComponent attach_to, const FString socket_name);

void ActivateSystem(AActor* niagara);

void DeactivateSystem(AActor* niagara);

void SetFloatParameter(AActor* niagara, const FString param_name, const float value);

void SetVectorParameter(AActor* niagara, const FString param_name, const FVector value);

void SetColorParameter(AActor* niagara, const FString param_name, const FVector4 color);

void SetActorParameter(AActor* niagara, const FString param_name, AActor* target);

void SetBoolParameter(AActor* niagara, const FString param_name, const bool value);

UENUM(BlueprintType)
enum class ELootRarity : uint8
{
	Common UMETA(DisplayName = "Common"),
	Uncommon UMETA(DisplayName = "Uncommon"),
	Rare UMETA(DisplayName = "Rare"),
	Epic UMETA(DisplayName = "Epic"),
	Legendary UMETA(DisplayName = "Legendary"),
	Mythic UMETA(DisplayName = "Mythic"),
	LootRarity_MAX UMETA(DisplayName = "LootRarity_MAX"),
};

UENUM(BlueprintType)
enum class EBuffType : uint8
{
	Damage UMETA(DisplayName = "Damage"),
	Defense UMETA(DisplayName = "Defense"),
	Speed UMETA(DisplayName = "Speed"),
	Healing UMETA(DisplayName = "Healing"),
	BuffType_MAX UMETA(DisplayName = "BuffType_MAX"),
};

USTRUCT(BlueprintType)
struct STDLIBTEST_API FInventorySlot
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InventorySlot")
	int64 item_id = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InventorySlot")
	int64 quantity = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "InventorySlot")
	int64 max_stack = 0;

};

USTRUCT(BlueprintType)
struct STDLIBTEST_API FHealthComponent
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "HealthComponent")
	float current_health = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "HealthComponent")
	float max_health = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "HealthComponent")
	bool is_invulnerable = false;

};

void PlayAnimation(const USkeletalMesh mesh, const FString anim_name);

void StopAnimation(const USkeletalMesh mesh);

void SetAnimationSpeed(const USkeletalMesh mesh, const float speed);

bool IsAnimationPlaying(const USkeletalMesh mesh);

FVector GetBoneLocation(const USkeletalMesh mesh, const FString bone_name);

FRotator GetBoneRotation(const USkeletalMesh mesh, const FString bone_name);

void SetBoneTransform(const USkeletalMesh mesh, const FString bone_name, const FVector location, const FRotator rotation);

void AttachToSocket(const USkeletalMesh mesh, const FString socket_name, AActor* target);

FVector GetSocketLocation(const USkeletalMesh mesh, const FString socket_name);

FRotator GetSocketRotation(const USkeletalMesh mesh, const FString socket_name);

void EnableRagdoll(const USkeletalMesh mesh);

void DisableRagdoll(const USkeletalMesh mesh);

void AddImpulseToBone(const USkeletalMesh mesh, const FString bone_name, const FVector impulse);

void SetMorphTarget(const USkeletalMesh mesh, const FString morph_name, const float value);

float GetMorphTarget(const USkeletalMesh mesh, const FString morph_name);

float GetWorldTimeSeconds();

float GetWorldDeltaSeconds();

bool IsServer();

bool IsClient();

bool IsStandalone();

AActor* SpawnActor(const FString class_name, const FVector location, const FRotator rotation);

AActor* SpawnActorDeferred(const FString class_name, const FVector location, const FRotator rotation);

void FinishSpawningActor(AActor* spawned);

void PrintToScreen(const FString message);

void PrintToLog(const FString message);

AActor* GetGameMode();

AActor* GetGameState();

AActor* GetPlayerController();

AActor* GetPlayerPawn();

bool LineTraceSingle(const FVector start, const FVector end, const int64 channel);

TArray<AActor*> LineTraceMulti(const FVector start, const FVector end, const int64 channel);

bool SphereTraceSingle(const FVector start, const FVector end, const float radius, const int64 channel);

bool BoxTraceSingle(const FVector start, const FVector end, const FVector half_size, const int64 channel);

UCLASS(HideCategories=(Input, Collision, LOD))
class STDLIBTEST_API AStdlibTestActor : public AActor
{
	GENERATED_BODY()

	public:
		AStdlibTestActor();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		FVector position;
	};


UCLASS()
	class STDLIBTEST_API UStdlibTestFunctionLibrary : public UBlueprintFunctionLibrary
	{
		GENERATED_BODY()

		public:
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float apply_damage(const float current_health, const float max_health, const float damage, const float armor);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float apply_healing(const float current_health, const float max_health, const float heal_amount);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float get_health_percentage(const float current_health, const float max_health);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool is_low_health(const float current_health, const float max_health, const float threshold);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float calculate_crit_damage(const float base_damage, const float crit_multiplier);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool should_crit(const float crit_chance);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float calculate_armor_mitigation(const float damage, const float armor);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static int64 calculate_experience_for_level(const int64 level);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static int64 add_experience(const int64 current_xp, const int64 xp_to_add, const int64 current_level);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float get_xp_progress(const int64 current_xp, const int64 current_level);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool can_add_item_to_inventory(const int64 current_count, const int64 max_capacity, const int64 item_stack_size);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float calculate_inventory_weight(const TArray<FInventorySlot> items, const TArray<float> item_weights);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool is_cooldown_ready(const float last_use_time, const float cooldown_duration, const float current_time);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float get_cooldown_remaining(const float last_use_time, const float cooldown_duration, const float current_time);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float get_cooldown_percentage(const float last_use_time, const float cooldown_duration, const float current_time);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float apply_buff(const float base_value, const float buff_magnitude, const EBuffType buff_type);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float update_buff_duration(const float remaining_time, const float delta_time);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool is_buff_active(const float remaining_time);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool roll_loot_drop(const float drop_chance);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static ELootRarity determine_loot_rarity(const float luck_stat);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static int64 update_quest_objective(const int64 current_progress, const int64 increment, const int64 required_progress);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool is_quest_objective_complete(const int64 current_progress, const int64 required_progress);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float get_quest_progress_percentage(const int64 current_progress, const int64 required_progress);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector fresnel_schlick(const float cos_theta, const FVector f0);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float distribution_ggx(const FVector n, const FVector h, const float roughness);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float geometry_schlick_ggx(const float n_dot_v, const float roughness);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float hash(const FVector2D p);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float perlin_noise(const FVector2D uv);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float fbm(const FVector2D uv, const int64 octaves);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector apply_contrast(const FVector color, const float contrast);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector apply_saturation(const FVector color, const float saturation);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector tonemap_aces(const FVector color);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector tonemap_reinhard(const FVector color);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector2D rotate_uv(const FVector2D uv, const float angle);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector2D polar_coordinates(const FVector2D uv);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float vignette(const FVector2D uv, const float intensity);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector2D chromatic_aberration(const FVector2D uv, const float offset);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float remap(const float value, const float in_min, const float in_max, const float out_min, const float out_max);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float smooth_step(const float edge0, const float edge1, const float x);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FVector lerp_color(const FVector a, const FVector b, const float alpha);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float distance_2d(const FVector2D a, const FVector2D b);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float random_range(const float min, const float max);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static int64 random_int_range(const int64 min, const int64 max);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static bool random_bool(const float probability);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static int64 weighted_random(const TArray<float> weights);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float clamp_01(const float value);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static float normalize_angle(const float angle);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FString format_time(const float seconds);
			UFUNCTION(BlueprintCallable, Category = "Kain")
			static FString format_number(const float value, const int64 decimals);
	};

