// Generated by KAIN - UE5 Editor Tools
#include "FFluidSimulationEditorToolkit.h"

FFluidSimulationEditorToolkit::FFluidSimulationEditorToolkit() {}
FFluidSimulationEditorToolkit::~FFluidSimulationEditorToolkit() {}

FName FFluidSimulationEditorToolkit::GetToolkitFName() const
{
	return FName("FluidSimulationEditor");
}

FText FFluidSimulationEditorToolkit::GetBaseToolkitName() const
{
	return FText::FromString(TEXT("FluidSimulationEditor"));
}

FString FFluidSimulationEditorToolkit::GetWorldCentricTabPrefix() const
{
	return TEXT("FluidSimulationEditor");
}

FLinearColor FFluidSimulationEditorToolkit::GetWorldCentricTabColorScale() const
{
	return FLinearColor::White;
}

void FFluidSimulationEditorToolkit::OnClose()
{
	FAssetEditorToolkit::OnClose();
}

