// Generated by KAIN - UE5 Editor Tools
#include "FHyperFluidEditorModuleModule.h"

void FHyperFluidEditorModuleModule::StartupModule()
{
	UE_LOG(LogTemp, Log, TEXT("HyperFluidEditorModule has started!"));
	
	// Register shader directory (guarded against duplicate auto-registration)
	if (!AllShaderSourceDirectoryMappings().Contains(TEXT("/Plugin/FluidFlow")))
	{
		FString PluginShaderDir = FPaths::Combine(IPluginManager::Get().FindPlugin(TEXT("FluidFlow"))->GetBaseDir(), TEXT("Shaders"));
		AddShaderSourceDirectoryMapping(TEXT("/Plugin/FluidFlow"), PluginShaderDir);
	}
}

void FHyperFluidEditorModuleModule::ShutdownModule()
{
	UE_LOG(LogTemp, Log, TEXT("HyperFluidEditorModule has shut down!"));
}

IMPLEMENT_MODULE(FHyperFluidEditorModuleModule, FluidFlow)

