// Generated by KAIN - UE5 Editor Tools
#include "FHyperFluidDetailsCustomization.h"
#include "SlateOptMacros.h"

void FHyperFluidDetailsCustomization::CustomizeDetails(IDetailLayoutBuilder& DetailBuilder)
{
	TArray<TWeakObjectPtr<UObject>> Objects;
	DetailBuilder.GetObjectsBeingCustomized(Objects);
	if (Objects.Num() > 0)
	{
		CachedObject = Objects[0];
	}
	
}

