[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
kain-core = { path = "../core" }
kain-error = { path = "../error" }
kain-error-semantic = { path = "../error-semantic" }
rspirv = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
kain-gpu-runtime = { path = "../gpu-runtime" }
