// Copyright 2026 Epic Games, Inc.. All Rights Reserved.
// Generated by KAIN-PRO - Editor Types Header
// This file provides ALL runtime types + delegates for editor code
// Slate widgets, Details customizations, and Viewports should include this

#pragma once

#include "CoreMinimal.h"

// Runtime types (enums, structs, actors, components)
#include "EAlphaGenType.h"
#include "EAlphaGenFilterType.h"
#include "EAlphaSource.h"
#include "FAlphaInfo.h"

// Delegates
#include "AlphaGenDelegates.h"

// Forward declarations for Slate widgets (prevents circular dependencies)
class SAlphaGenEditorWidget;
class SAlphaPreviewWidget;
class SParameterEditorWidget;

