[package]
name = "kain_crate_ffi_bridge_trinity_stack_node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kain-core = { path = "M:\\Code\\Kain\\crates\\kain-core" }
kain-host = { path = "M:\\Code\\Kain\\crates\\kain-host", default-features = false }
trinity_stack_node = { package = "trinity_stack_node", path = "\\\\?\\M:\\Code\\Kain\\smoketest\\py_cargo_node\\trinity_web_lattice\\local_crate" }

[profile.dev]
debug = 0
panic = "unwind"

[workspace]
resolver = "2"
