//! Build script: reads TOML diagnostic specs and codegens a static
//! registry array + typed builder constructors.
//!
//! Output: `$OUT_DIR/registry_data.rs` containing:
//!   - `static DIAGNOSTIC_SPECS: &[GeneratedSpec]`
//!   - `fn load_registry_entries() -> Vec<DiagnosticSpec>`

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct TomlDiagnostic {
    code: String,
    title: String,
    severity: String,
    docs_key: String,
    help: String,
    #[serde(default)]
    example_bad: Option<String>,
    #[serde(default)]
    example_good: Option<String>,
    #[serde(default)]
    fixit: Option<String>,
    #[serde(default)]
    see_also: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct TomlFile {
    diagnostics: Vec<TomlDiagnostic>,
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("registry_data.rs");

    let specs_dir = Path::new("specs");
    assert!(
        specs_dir.is_dir(),
        "diagnostic specs directory missing: {}",
        specs_dir.display()
    );

    let mut all_specs: Vec<TomlDiagnostic> = Vec::new();
    let mut entries: Vec<_> = fs::read_dir(specs_dir)
        .expect("failed to read specs dir")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "toml"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in &entries {
        let content = fs::read_to_string(entry.path())
            .unwrap_or_else(|e| panic!("failed to read {:?}: {e}", entry.path()));
        let parsed: TomlFile = toml::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {:?}: {e}", entry.path()));
        all_specs.extend(parsed.diagnostics);
    }

    assert!(
        !all_specs.is_empty(),
        "no diagnostic specs were loaded from {}",
        specs_dir.display()
    );

    // Sort by code for deterministic output
    all_specs.sort_by(|a, b| a.code.cmp(&b.code));

    let count = all_specs.len();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from specs/*.toml — DO NOT EDIT\n\n");
    out.push_str(&format!(
        "/// Number of diagnostic specs loaded from TOML.\n"
    ));
    out.push_str(&format!(
        "pub const DIAGNOSTIC_SPEC_COUNT: usize = {count};\n\n"
    ));

    // Generate the static spec array
    out.push_str("/// Static diagnostic spec registry generated from TOML specs.\n");
    out.push_str("pub static DIAGNOSTIC_SPECS: &[GeneratedSpec] = &[\n");

    for spec in &all_specs {
        let code = &spec.code;
        let title = escape_str(&spec.title);
        let severity = &spec.severity;
        let docs_key = &spec.docs_key;
        let help = escape_str(&spec.help);
        let example_bad = spec.example_bad.as_deref().map(escape_str);
        let example_good = spec.example_good.as_deref().map(escape_str);
        let fixit = spec.fixit.as_deref().map(escape_str);

        // see_also
        let see_also_entries: Vec<String> = spec
            .see_also
            .iter()
            .map(|s| format!("\"{}\"", escape_str(s)))
            .collect();
        let see_also_arr = if see_also_entries.is_empty() {
            "&[]".to_string()
        } else {
            format!("&[{}]", see_also_entries.join(", "))
        };

        out.push_str(&format!(
            "    GeneratedSpec {{\n\
             \x20       code: \"{code}\",\n\
             \x20       title: \"{title}\",\n\
             \x20       severity: \"{severity}\",\n\
             \x20       docs_key: \"{docs_key}\",\n\
             \x20       help: \"{help}\",\n\
             \x20       example_bad: {},\n\
             \x20       example_good: {},\n\
             \x20       fixit: {},\n\
             \x20       see_also: {see_also_arr},\n\
             \x20   }},\n",
            example_bad
                .map(|s| format!("Some(\"{s}\")"))
                .unwrap_or_else(|| "None".to_string()),
            example_good
                .map(|s| format!("Some(\"{s}\")"))
                .unwrap_or_else(|| "None".to_string()),
            fixit
                .map(|s| format!("Some(\"{s}\")"))
                .unwrap_or_else(|| "None".to_string()),
        ));
    }

    out.push_str("];\n");
    out.push_str(&format!(
        "\n/// Sanity check: ensure the array length matches the count constant.\n"
    ));
    out.push_str(&format!(
        "const _: [(); DIAGNOSTIC_SPEC_COUNT] = [(); DIAGNOSTIC_SPECS.len()];\n"
    ));

    // Generate the load function (called at init)
    out.push_str(&format!(
        "\n/// Load the registry from the generated static data.\n\
         pub fn load_registry_entries() -> Vec<crate::spec::DiagnosticSpec> {{\n\
         \x20   DIAGNOSTIC_SPECS.iter().map(|g| g.into_spec()).collect()\n\
         }}\n"
    ));

    // If count changed, force rebuild
    println!("cargo:rerun-if-changed=specs/");
    println!("cargo:rerun-if-changed=build.rs");

    fs::write(&dest_path, out).expect("failed to write registry_data.rs");

    // Print summary
    println!("cargo:warning=Codegen'd {count} diagnostic specs from TOML");
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}
