// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "FilterBlur.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FFilterBlurShader, "/Plugin/AlphaGen/FilterBlur.usf", "FilterBlurCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FilterBlur(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float radius,
    FRDGTextureRef input_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FFilterBlurShader::FParameters* Params = GraphBuilder.AllocParameters<FFilterBlurShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->radius = radius;
    // Bind Textures
    Params->input_texture = input_texture;
    Params->input_textureSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FFilterBlurShader::Exec(GraphBuilder, *Params, GroupCount);
}
