// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "FilterInvert.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FFilterInvertShader, "/Plugin/AlphaGen/FilterInvert.usf", "FilterInvertCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FilterInvert(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    FRDGTextureRef input_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FFilterInvertShader::FParameters* Params = GraphBuilder.AllocParameters<FFilterInvertShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    // Bind Textures
    Params->input_texture = input_texture;
    Params->input_textureSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FFilterInvertShader::Exec(GraphBuilder, *Params, GroupCount);
}
