// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "FilterContrast.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FFilterContrastShader, "/Plugin/AlphaGen/FilterContrast.usf", "FilterContrastCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FilterContrast(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float contrast,
    FRDGTextureRef input_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FFilterContrastShader::FParameters* Params = GraphBuilder.AllocParameters<FFilterContrastShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->contrast = contrast;
    // Bind Textures
    Params->input_texture = input_texture;
    Params->input_textureSampler = TStaticSamplerState<SF_Bilinear, AM_Clamp, AM_Clamp, AM_Clamp>::GetRHI();
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FFilterContrastShader::Exec(GraphBuilder, *Params, GroupCount);
}
