// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "GenerateScratches.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGenerateScratchesShader, "/Plugin/AlphaGen/GenerateScratches.usf", "GenerateScratchesCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_GenerateScratches(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float density,
    float length,
    float seed,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FGenerateScratchesShader::FParameters* Params = GraphBuilder.AllocParameters<FGenerateScratchesShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->density = density;
    Params->length = length;
    Params->seed = seed;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FGenerateScratchesShader::Exec(GraphBuilder, *Params, GroupCount);
}
