// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "GenerateCells.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGenerateCellsShader, "/Plugin/AlphaGen/GenerateCells.usf", "GenerateCellsCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_GenerateCells(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float scale,
    float contrast,
    float seed,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FGenerateCellsShader::FParameters* Params = GraphBuilder.AllocParameters<FGenerateCellsShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->scale = scale;
    Params->contrast = contrast;
    Params->seed = seed;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FGenerateCellsShader::Exec(GraphBuilder, *Params, GroupCount);
}
