// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "GenerateCheckerboard.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGenerateCheckerboardShader, "/Plugin/AlphaGen/GenerateCheckerboard.usf", "GenerateCheckerboardCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_GenerateCheckerboard(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float scale,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FGenerateCheckerboardShader::FParameters* Params = GraphBuilder.AllocParameters<FGenerateCheckerboardShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->scale = scale;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FGenerateCheckerboardShader::Exec(GraphBuilder, *Params, GroupCount);
}
