// Generated by KAIN Compiler - UE5 Shader Implementation
// Shader registration and dispatch helpers

#include "GenerateCracks.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderParameterUtils.h"
#include "GlobalShader.h"

// Register shader with UE5
IMPLEMENT_GLOBAL_SHADER(FGenerateCracksShader, "/Plugin/AlphaGen/GenerateCracks.usf", "GenerateCracksCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_GenerateCracks(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float scale,
    float width,
    float seed,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount
)
{
    FGenerateCracksShader::FParameters* Params = GraphBuilder.AllocParameters<FGenerateCracksShader::FParameters>();
    // Bind Scalars
    Params->texture_size = texture_size;
    Params->scale = scale;
    Params->width = width;
    Params->seed = seed;
    // Bind UAVs
    Params->OutputTexture = GraphBuilder.CreateUAV(OutputTexture);

    FGenerateCracksShader::Exec(GraphBuilder, *Params, GroupCount);
}
