// Generated by KAIN Compiler
// Derived HLSL output from the KAIN shader artifact pipeline

// Shader: BlackHoleFragment
cbuffer BlackHoleFragmentParams : register(b0)
{
    float time;
    float2 resolution;
    float2 mouse;
};

RWStructuredBuffer<float> _pad : register(u3);

struct BlackHoleFragmentInput
{
    float2 uv : TEXCOORD0;
};

struct BlackHoleFragmentOutput
{
    float4 color : SV_Target0;
};

BlackHoleFragmentOutput BlackHoleFragment(BlackHoleFragmentInput input)
{
    float BH_MASS = 1.0;
    float BH_RS = 2.0;
    float DISK_INNER = 4.0;
    float DISK_OUTER = 24.0;
    float CAM_DIST = 16.0;
    float CAM_THETA = 1.2;
    float fx = (input.uv.x * resolution.x);
    float fy = (input.uv.y * resolution.y);
    float ux = ((((((fx / resolution.x)) * 2.0) - 1.0)) * ((resolution.x / resolution.y)));
    float uy = ((((fy / resolution.y)) * 2.0) - 1.0);
    float cam_theta = (CAM_THETA + (((mouse.y - 0.5)) * 0.5));
    float cam_phi = ((time * 0.05) + (((mouse.x - 0.5)) * 2.0));
    float cam_x = ((CAM_DIST * sin(cam_theta)) * cos(cam_phi));
    float cam_y = (CAM_DIST * cos(cam_theta));
    float cam_z = ((CAM_DIST * sin(cam_theta)) * sin(cam_phi));
    float forward_len = (1.0 / sqrt((((cam_x * cam_x) + (cam_y * cam_y)) + (cam_z * cam_z))));
    float fw_x = ((-cam_x) * forward_len);
    float fw_y = ((-cam_y) * forward_len);
    float fw_z = ((-cam_z) * forward_len);
    float up_len = (1.0 / sqrt((((fw_x * fw_x) + (fw_y * fw_y)) + (fw_z * fw_z))));
    float up_x = (-fw_x);
    float up_y = (1.0 - (fw_y * fw_y));
    float up_z = (-fw_z);
    float up_len2 = (1.0 / sqrt((((up_x * up_x) + (up_y * up_y)) + (up_z * up_z))));
    float s_up_x = (up_x * up_len2);
    float s_up_y = (up_y * up_len2);
    float s_up_z = (up_z * up_len2);
    float rt_x = ((fw_y * s_up_z) - (fw_z * s_up_y));
    float rt_y = ((fw_z * s_up_x) - (fw_x * s_up_z));
    float rt_z = ((fw_x * s_up_y) - (fw_y * s_up_x));
    float rt_len = (1.0 / sqrt((((rt_x * rt_x) + (rt_y * rt_y)) + (rt_z * rt_z))));
    float r_x = (rt_x * rt_len);
    float r_y = (rt_y * rt_len);
    float r_z = (rt_z * rt_len);
    float rd_x = ((fw_x + (r_x * ux)) + (s_up_x * uy));
    float rd_y = ((fw_y + (r_y * ux)) + (s_up_y * uy));
    float rd_z = ((fw_z + (r_z * ux)) + (s_up_z * uy));
    float rd_len = (1.0 / sqrt((((rd_x * rd_x) + (rd_y * rd_y)) + (rd_z * rd_z))));
    float rx = (rd_x * rd_len);
    float ry = (rd_y * rd_len);
    float rz = (rd_z * rd_len);
    float px = cam_x;
    float py = cam_y;
    float pz = cam_z;
    float dx = rx;
    float dy = ry;
    float dz = rz;
    float cr = 0.0;
    float cg = 0.0;
    float cb = 0.0;
    float alpha = 0.0;
    int step_i = 0;
    int hit_disk = 0;
    int hit_horizon = 0;
    float dist = 0.0;
    float step = 0.2;
    while ((step_i < 512)) {
        if ((alpha > 0.99)) {
            step_i = 512;
        } else if ((hit_horizon == 1)) {
            step_i = 512;
        }
        float r = sqrt((((px * px) + (py * py)) + (pz * pz)));
        if ((r < (BH_RS * 0.99))) {
            hit_horizon = 1;
            cr = 0.0;
            cg = 0.0;
            cb = 0.0;
            alpha = 1.0;
        }
        if (((hit_disk == 0) && (hit_horizon == 0))) {
            float rel_y = (py * py);
            float r_xy = sqrt(((px * px) + (pz * pz)));
            if ((((rel_y < (step * step)) && (r_xy >= DISK_INNER)) && (r_xy <= DISK_OUTER))) {
                hit_disk = 1;
                alpha = 1.0;
                float t_norm = (((r_xy - DISK_INNER)) / ((DISK_OUTER - DISK_INNER)));
                float temp_frac = max(0.0, (1.0 - t_norm));
                float disk_r = max(0.0, min(1.0, (temp_frac * 3.0)));
                float disk_g = max(0.0, min(1.0, (((1.0 - (abs((temp_frac - 0.4)) * 2.5))) * 1.5)));
                float disk_b = max(0.0, min(1.0, (((1.0 - temp_frac)) * 1.5)));
                float red_shift = (1.0 / sqrt((1.0 - (BH_RS / r_xy))));
                float shift_factor = max(0.5, min(2.0, (1.0 / ((1.0 + (red_shift * 0.1))))));
                float r_shifted = (disk_r * ((1.0 + (shift_factor * 0.5))));
                float g_shifted = (disk_g * shift_factor);
                float b_shifted = (disk_b * ((1.0 - (shift_factor * 0.3))));
                float doppler = (1.0 / sqrt((1.0 - (BH_RS / r_xy))));
                float blue_side = ((px > 0.0) ? 1.2 : 0.8);
                cr = (r_shifted * blue_side);
                cg = ((g_shifted * blue_side) * 0.8);
                cb = ((b_shifted * blue_side) * 0.6);
            }
        }
        if (((hit_horizon == 0) && (hit_disk == 0))) {
            if ((r > BH_RS)) {
                float r2 = (r * r);
                float bend_str = (BH_RS / ((r2 * 3.0)));
                float ax = (((-px) / r) * bend_str);
                float ay = (((-py) / r) * bend_str);
                float az = (((-pz) / r) * bend_str);
                dx = (dx + (ax * step));
                dy = (dy + (ay * step));
                dz = (dz + (az * step));
                float dl = (1.0 / sqrt((((dx * dx) + (dy * dy)) + (dz * dz))));
                dx = (dx * dl);
                dy = (dy * dl);
                dz = (dz * dl);
            }
            float seed = (((dx * 12.9898) + (dy * 78.233)) + (dz * 45.164));
            float star_noise = ((sin((seed * 43758.5453)) * 0.5) + 0.5);
            float star_thresh = 0.998;
            float star_val = (max(0.0, (((sin((star_noise * 10000.0)) * 0.5) + 0.5) - star_thresh)) * 50.0);
            float milky = max(0.0, (1.0 - (abs(dy) * 2.5)));
            float star_color_val = max(0.0, (star_val * ((0.3 + (milky * 0.7)))));
            star_color_val = min(1.0, star_color_val);
            float glow_val = max(0.0, (1.0 - (r / DISK_OUTER)));
            float glow_v = ((glow_val * glow_val) * 0.3);
            float scv = min(1.0, star_color_val);
            cr = ((cr + (scv * 0.8)) + glow_v);
            cg = ((cg + (scv * 0.9)) + (glow_v * 0.6));
            cb = ((cb + scv) + (glow_v * 0.3));
            alpha = min(1.0, (((alpha + 0.003) + (scv * 0.02)) + (glow_v * 0.01)));
            if ((alpha < 1.0)) {
                alpha = min(1.0, (alpha + 0.0005));
            }
        }
        px = (px + (dx * step));
        py = (py + (dy * step));
        pz = (pz + (dz * step));
        dist = (dist + step);
        step_i = (step_i + 1);
    }
    float min_approach = 1000.0;
    int ap_i = 0;
    float a_px = cam_x;
    float a_py = cam_y;
    float a_pz = cam_z;
    float a_dx = rx;
    float a_dy = ry;
    float a_dz = rz;
    while ((ap_i < 128)) {
        float ar = sqrt((((a_px * a_px) + (a_py * a_py)) + (a_pz * a_pz)));
        float approach = abs((ar - (BH_RS * 1.5)));
        if ((approach < min_approach)) {
            min_approach = approach;
        }
        a_px = (a_px + (a_dx * 0.5));
        a_py = (a_py + (a_dy * 0.5));
        a_pz = (a_pz + (a_dz * 0.5));
        float ar2 = (ar * ar);
        float b_str = (BH_RS / ((max(ar2, 4.0) * 3.0)));
        a_dx = (a_dx + (((((-a_px) / ar)) * b_str) * 0.5));
        a_dy = (a_dy + (((((-a_py) / ar)) * b_str) * 0.5));
        a_dz = (a_dz + (((((-a_pz) / ar)) * b_str) * 0.5));
        float adl = (1.0 / sqrt((((a_dx * a_dx) + (a_dy * a_dy)) + (a_dz * a_dz))));
        a_dx = (a_dx * adl);
        a_dy = (a_dy * adl);
        a_dz = (a_dz * adl);
        ap_i = (ap_i + 1);
    }
    float photon_ring = max(0.0, (1.0 - (min_approach * 3.0)));
    float ring_glow = ((photon_ring * photon_ring) * 0.8);
    float einstein = max(0.0, (1.0 - (abs((min_approach - 0.5)) * 4.0)));
    float einstein_glow = (einstein * 0.5);
    float over_glow_r = (max(0.0, (1.0 - (abs(ry) * 5.0))) * 0.15);
    float fc_r = cr;
    float fc_g = cg;
    float fc_b = cb;
    fc_r = (fc_r + (ring_glow * 1.0));
    fc_g = (fc_g + (ring_glow * 0.7));
    fc_b = (fc_b + (ring_glow * 0.3));
    fc_r = (fc_r + (einstein_glow * 0.8));
    fc_g = (fc_g + (einstein_glow * 0.6));
    fc_b = (fc_b + (einstein_glow * 0.2));
    fc_r = (fc_r + (over_glow_r * 1.0));
    fc_g = (fc_g + (over_glow_r * 0.5));
    fc_b = (fc_b + (over_glow_r * 0.2));
    float horizon_glow = (max(0.0, (1.0 - (min_approach * 0.5))) * 0.3);
    fc_r = (fc_r + (horizon_glow * 0.5));
    fc_g = (fc_g + (horizon_glow * 0.3));
    fc_b = (fc_b + (horizon_glow * 0.1));
    float luminance = (((fc_r * 0.299) + (fc_g * 0.587)) + (fc_b * 0.114));
    float tone_scale = (1.0 / ((1.0 + luminance)));
    fc_r = (fc_r * tone_scale);
    fc_g = (fc_g * tone_scale);
    fc_b = (fc_b * tone_scale);
    float g_r = sqrt(sqrt(max(0.0, min(fc_r, 1.0))));
    float g_g = sqrt(sqrt(max(0.0, min(fc_g, 1.0))));
    float g_b = sqrt(sqrt(max(0.0, min(fc_b, 1.0))));
    float out_r = (g_r * sqrt(g_r));
    float out_g = (g_g * sqrt(g_g));
    float out_b = (g_b * sqrt(g_b));
    BlackHoleFragmentOutput _result;
    _result.color = float4(out_r, out_g, out_b, 1.0);
    return _result;
}

