// Zentako
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342163
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EBoundsMode.generated.h"

UENUM(BlueprintType)
enum class EBoundsMode : uint8
{
	Bounce UMETA(DisplayName = "Bounce"),
	Wrap UMETA(DisplayName = "Wrap"),
	Respawn UMETA(DisplayName = "Respawn"),
};

