// Zentako
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342163
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "FParticleConfig.generated.h"

USTRUCT(BlueprintType)
struct QUANTUMPARTICLES_API FParticleConfig
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleConfig")
	int32 simulation_resolution;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleConfig")
	int32 particle_count;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleConfig")
	float point_size;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleConfig")
	float opacity;

};

