// Zentako
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342163
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "FParticleLifeParams.generated.h"

USTRUCT(BlueprintType)
struct QUANTUMPARTICLES_API FParticleLifeParams
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleLifeParams")
	bool enabled;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleLifeParams")
	float decay_rate;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ParticleLifeParams")
	float respawn_bounds;

};

