// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FParticleRenderShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FParticleRenderShader);
    SHADER_USE_PARAMETER_STRUCT(FParticleRenderShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FVector3f, primary_color)
        SHADER_PARAMETER(FVector3f, secondary_color)
        SHADER_PARAMETER(int32, color_mode)
        SHADER_PARAMETER(float, opacity)
        SHADER_PARAMETER(float, point_size)
        SHADER_PARAMETER_RDG_TEXTURE(Texture2D, position_texture)
        SHADER_PARAMETER_SAMPLER(SamplerState, position_textureSampler)
        SHADER_PARAMETER_RDG_TEXTURE(Texture2D, velocity_texture)
        SHADER_PARAMETER_SAMPLER(SamplerState, velocity_textureSampler)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FParticleRenderShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("ParticleRender Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FParticleRenderShader, "/Plugin/YourPlugin/ParticleRender.usf", "ParticleRenderCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_ParticleRender(
    FRDGBuilder& GraphBuilder,
    FVector3f primary_color,
    FVector3f secondary_color,
    int32 color_mode,
    float opacity,
    float point_size,
    FRDGTextureRef position_texture,
    FRDGTextureRef velocity_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
