// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

// POD mirror for CouplingComponent (GPU-compatible)
struct FCouplingComponentData {
    ECouplingStrategy coupling_strategy;
    int32 coupling_timestep_ratio;
    float coupling_tolerance;
    int32 coupling_max_iterations;
    bool boussinesq_approximation;
    float natural_convection_gain;
    float forced_convection_gain;
    ERadiationModel radiation_model;
    EFSIMethod fsi_method;
    float structural_damping;
    bool added_mass_effect;
    float electrokinetic_mobility;
    float zeta_potential;
    float debye_length;
    float magnetic_reynolds_number;
    float hartmann_number;
    float interaction_parameter;
    EReactionMechanism reaction_mechanism;
    int32 species_count;
    bool acoustic_coupling;
    float speed_of_sound;
    float acoustic_impedance;
};

class FAcousticSourceTermShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FAcousticSourceTermShader);
    SHADER_USE_PARAMETER_STRUCT(FAcousticSourceTermShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FCouplingComponentData, coupling)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FAcousticSourceTermShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("AcousticSourceTerm Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FAcousticSourceTermShader, "/Plugin/YourPlugin/AcousticSourceTerm.usf", "AcousticSourceTermCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_AcousticSourceTerm(
    FRDGBuilder& GraphBuilder,
    FCouplingComponentData coupling,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
