// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771421953
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "EEmissionShape.h"
#include "EParticleType.h"

#include "AHyperFluidEmitter.generated.h"



UCLASS()
class FLUIDFLOW_API AHyperFluidEmitter : public AActor
{
	GENERATED_BODY()

	public:
		AHyperFluidEmitter();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float emission_rate;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		FVector initial_velocity;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float temperature;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float density;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		FVector color;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		EParticleType particle_type;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		EEmissionShape emission_shape;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float emission_radius;

		// Double-buffered Simulation Resources
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_B;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_B;
		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_Emit")
		void Server_Emit(const UHyperFluidSimulationCore* world, const int32 count);

		bool Server_Emit_Validate(const UHyperFluidSimulationCore* world, const int32 count);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_EmitBurst")
		void Server_EmitBurst(const UHyperFluidSimulationCore* world, const int32 count, const FVector velocity);

		bool Server_EmitBurst_Validate(const UHyperFluidSimulationCore* world, const int32 count, const FVector velocity);

	};











































































