// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771421953
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"

#include "AHyperFluidProbe.generated.h"



UCLASS()
class FLUIDFLOW_API AHyperFluidProbe : public AActor
{
	GENERATED_BODY()

	public:
		AHyperFluidProbe();
		virtual void BeginPlay() override;
		virtual void Tick(float DeltaTime) override;

		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		FVector sample_position;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		float radius;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		TArray<float> buffer;
		UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Simulation Settings")
		int32 sample_rate;

		// Double-buffered Simulation Resources
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* PositionRT_B;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_A;
		UPROPERTY(Transient)
		UTextureRenderTarget2D* VelocityRT_B;
		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_Sample")
		void Server_Sample(const UHyperFluidSimulationCore* world);

		bool Server_Sample_Validate(const UHyperFluidSimulationCore* world);

		UFUNCTION(Client, Reliable, BlueprintCallable, Category = "Client_ReceiveSample")
		void Client_ReceiveSample(const TArray<float>& data);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_SampleVelocity")
		void Server_SampleVelocity(const UHyperFluidSimulationCore* world);

		bool Server_SampleVelocity_Validate(const UHyperFluidSimulationCore* world);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_SamplePressure")
		void Server_SamplePressure(const UHyperFluidSimulationCore* world);

		bool Server_SamplePressure_Validate(const UHyperFluidSimulationCore* world);

		UFUNCTION(Server, Reliable, BlueprintCallable, Category = "Server_SampleTemperature")
		void Server_SampleTemperature(const UHyperFluidSimulationCore* world);

		bool Server_SampleTemperature_Validate(const UHyperFluidSimulationCore* world);

	};











































































