// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771388873
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "ECouplingField.generated.h"

UENUM(BlueprintType)
enum class ECouplingField : uint8
{
	Thermal UMETA(DisplayName = "Thermal"),
	Chemical UMETA(DisplayName = "Chemical"),
	Electrical UMETA(DisplayName = "Electrical"),
	Magnetic UMETA(DisplayName = "Magnetic"),
	Quantum UMETA(DisplayName = "Quantum"),
	Structural UMETA(DisplayName = "Structural"),
	Acoustics UMETA(DisplayName = "Acoustics"),
	Radiation UMETA(DisplayName = "Radiation"),
	CosmicRay UMETA(DisplayName = "CosmicRay"),
	Gravity UMETA(DisplayName = "Gravity"),
	Elasticity UMETA(DisplayName = "Elasticity"),
	Porous UMETA(DisplayName = "Porous"),
	BioChemical UMETA(DisplayName = "BioChemical"),
	Electrokinetic UMETA(DisplayName = "Electrokinetic"),
	Photochemical UMETA(DisplayName = "Photochemical"),
	CouplingField_MAX UMETA(DisplayName = "CouplingField_MAX"),
};

