// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771391630
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "EParticleType.generated.h"

UENUM(BlueprintType)
enum class EParticleType : uint8
{
	Tracer UMETA(DisplayName = "Tracer"),
	Droplet UMETA(DisplayName = "Droplet"),
	Bubble UMETA(DisplayName = "Bubble"),
	Solid UMETA(DisplayName = "Solid"),
	ReactiveParticle UMETA(DisplayName = "ReactiveParticle"),
	Evaporating UMETA(DisplayName = "Evaporating"),
	Condensing UMETA(DisplayName = "Condensing"),
	Charged UMETA(DisplayName = "Charged"),
	ParticleType_MAX UMETA(DisplayName = "ParticleType_MAX"),
};

