// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771421947
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "ETrackingScheme.generated.h"



UENUM(BlueprintType)
enum class ETrackingScheme : uint8
{
	Euler_Explicit UMETA(DisplayName = "Euler_Explicit"),
	Runge_Kutta_4 UMETA(DisplayName = "Runge_Kutta_4"),
	Analytical_Integration UMETA(DisplayName = "Analytical_Integration"),
	Implicit_Euler UMETA(DisplayName = "Implicit_Euler"),
	TrackingScheme_MAX UMETA(DisplayName = "TrackingScheme_MAX"),
};










































































