// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771391627
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"

#include "ETurbulenceModel.generated.h"

UENUM(BlueprintType)
enum class ETurbulenceModel : uint8
{
	None UMETA(DisplayName = "None"),
	DNS UMETA(DisplayName = "DNS"),
	LES UMETA(DisplayName = "LES"),
	RANS_kEpsilon UMETA(DisplayName = "RANS_kEpsilon"),
	RANS_kOmega UMETA(DisplayName = "RANS_kOmega"),
	SpalartAllmaras UMETA(DisplayName = "SpalartAllmaras"),
	Smagorinsky UMETA(DisplayName = "Smagorinsky"),
	WALE UMETA(DisplayName = "WALE"),
	DynamicSmagorinsky UMETA(DisplayName = "DynamicSmagorinsky"),
	Vreman UMETA(DisplayName = "Vreman"),
	RNG_kEpsilon UMETA(DisplayName = "RNG_kEpsilon"),
	SST_kOmega UMETA(DisplayName = "SST_kOmega"),
	DetachedEddy UMETA(DisplayName = "DetachedEddy"),
	HybridRANSLES UMETA(DisplayName = "HybridRANSLES"),
	MultiScaleVortex UMETA(DisplayName = "MultiScaleVortex"),
	TurbulenceModel_MAX UMETA(DisplayName = "TurbulenceModel_MAX"),
};

