// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771391635
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "ECouplingField.h"
#include "ECouplingStrategy.h"
#include "EFSIMethod.h"
#include "ERadiationModel.h"
#include "EReactionMechanism.h"

#include "FCouplingComponent.generated.h"

UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class FLUIDFLOW_API UCouplingComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UCouplingComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ECouplingStrategy coupling_strategy;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<ECouplingField> coupling_fields;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 coupling_timestep_ratio;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float coupling_tolerance;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 coupling_max_iterations;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool boussinesq_approximation;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float natural_convection_gain;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float forced_convection_gain;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		ERadiationModel radiation_model;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EFSIMethod fsi_method;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float structural_damping;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool added_mass_effect;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float electrokinetic_mobility;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float zeta_potential;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float debye_length;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float magnetic_reynolds_number;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float hartmann_number;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float interaction_parameter;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		EReactionMechanism reaction_mechanism;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 species_count;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<float> arrhenius_a;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		TArray<float> arrhenius_ea;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		bool acoustic_coupling;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float speed_of_sound;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float acoustic_impedance;

};

