// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771388876
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTable.h"
#include "EAdaptiveStrategy.h"
#include "EBoundaryType.h"
#include "ECouplingField.h"
#include "EFluidClass.h"
#include "EGPUBackend.h"
#include "EQualityTier.h"
#include "ESolverFamily.h"
#include "ETimeIntegrator.h"
#include "ETurbulenceModel.h"

#include "FFluidPreset.generated.h"

USTRUCT(BlueprintType)
struct FLUIDFLOW_API FFluidPreset : public FTableRowBase
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	int32 id;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	FString name;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EFluidClass class;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ESolverFamily solver;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ETurbulenceModel turbulence;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EBoundaryType boundary;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	TArray<ECouplingField> coupling;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EQualityTier quality;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EGPUBackend backend;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	EAdaptiveStrategy adaptive;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	ETimeIntegrator time_integrator;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float viscosity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float density;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float surface_tension;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float compressibility;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float conductivity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float permittivity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float permeability;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float chemical_reactivity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float radiation_absorption;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float gravity_scale;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float anisotropy;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float cavitation_threshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float yield_stress;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float foam_threshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float spray_threshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float bubble_coalescence;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float turbulence_intensity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float vorticity_confinement;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float adaptive_refine_threshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FluidPreset")
	float adaptive_coarsen_threshold;

};

