// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

#include "FluidFlowShaderTypes.h"

class FFluidRaymarchingShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FFluidRaymarchingShader);
    SHADER_USE_PARAMETER_STRUCT(FFluidRaymarchingShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER_STRUCT(FVisualizationComponentData, viz)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FFluidRaymarchingShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("FluidRaymarching Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FFluidRaymarchingShader, "/Plugin/FluidFlow/FluidRaymarching.usf", "FluidRaymarchingCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FluidRaymarching(
    FRDGBuilder& GraphBuilder,
    FVisualizationComponentData viz,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
