// Copyright 2026 Epic Games, Inc.. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3 (Modular Output)
// Master header - forward declarations and includes

#pragma once

#include "CoreMinimal.h"

// Forward declarations
enum class EFluidClass : uint8;
enum class ESolverFamily : uint8;
enum class EHybridSolver : uint8;
enum class EPressureSolver : uint8;
enum class EAdvectionScheme : uint8;
enum class EBoundaryType : uint8;
enum class EVelocityProfile : uint8;
enum class ETemperatureProfile : uint8;
enum class EPressureProfile : uint8;
enum class ETurbulenceModel : uint8;
enum class ELESModel : uint8;
enum class ERANSModel : uint8;
enum class EWallFunction : uint8;
enum class ETransitionModel : uint8;
enum class ESyntheticTurbulence : uint8;
enum class EReynoldsStressModel : uint8;
enum class ECouplingField : uint8;
enum class ECouplingStrategy : uint8;
enum class ERadiationModel : uint8;
enum class EFSIMethod : uint8;
enum class EReactionMechanism : uint8;
enum class EVisualizationMode : uint8;
enum class EQualityTier : uint8;
enum class EGPUBackend : uint8;
enum class EAdaptiveStrategy : uint8;
enum class ETimeIntegrator : uint8;
enum class EParticleType : uint8;
enum class EDragModel : uint8;
enum class ECollisionModel : uint8;
enum class EBreakupModel : uint8;
enum class ECoalescenceModel : uint8;
enum class EEvaporationModel : uint8;
enum class ETrackingScheme : uint8;
enum class ELoadBalancingStrategy : uint8;
enum class EDomainDecomposition : uint8;
enum class ECacheStrategy : uint8;
enum class EPrecisionMode : uint8;
enum class EConvergenceCriteria : uint8;
enum class EValidationCaseType : uint8;
struct FFluidPreset;
struct FFluidMaterial;
struct FMaterialLookup;
struct FBoundaryProfile;
struct FTurbulenceProfile;
struct FCouplingProfile;
struct FVisualizationPreset;
struct FValidationCase;
struct FGridResolutionComponent;
struct FTimeIntegrationComponent;
struct FPhysicalPropertiesComponent;
struct FTurbulenceComponent;
struct FTurbulenceAdvancedComponent;
struct FMultiphaseComponent;
struct FThermalComponent;
struct FElectroMagneticComponent;
struct FQuantumComponent;
struct FParticulateComponent;
struct FHyperFluidParticleSystemComponent;
struct FAdaptiveMeshComponent;
struct FBoundaryConditionComponent;
struct FCollisionComponent;
struct FCouplingComponent;
struct FPerformanceComponent;
struct FDiagnosticsComponent;
struct FVisualizationComponent;
struct FHyperFluidSimulationCore;
class AHyperFluidWorld;
class AHyperFluidEmitter;
enum class EEmissionShape : uint8;
class AHyperFluidProbe;
class AHyperFluidController;
struct FHyperFluidEditorModule;
struct FHyperFluidDetails;
struct FHyperFluidViewport;
struct FRenderTargetConfig;
struct FSFluidSimulationDashboard;
struct FSSimulationControls;
struct FSVisualizationControls;
struct FFluidSimulationViewport;
struct FFluidWorldDetails;
struct FFluidSimulationToolbar;
struct FFluidSimulationEditor;
struct FFluidFlowEditorModule;

// Stdlib functions
#include "KainStdlib.h"

// Module includes
#include "EFluidClass.h"
#include "ESolverFamily.h"
#include "EHybridSolver.h"
#include "EPressureSolver.h"
#include "EAdvectionScheme.h"
#include "EBoundaryType.h"
#include "EVelocityProfile.h"
#include "ETemperatureProfile.h"
#include "EPressureProfile.h"
#include "ETurbulenceModel.h"
#include "ELESModel.h"
#include "ERANSModel.h"
#include "EWallFunction.h"
#include "ETransitionModel.h"
#include "ESyntheticTurbulence.h"
#include "EReynoldsStressModel.h"
#include "ECouplingField.h"
#include "ECouplingStrategy.h"
#include "ERadiationModel.h"
#include "EFSIMethod.h"
#include "EReactionMechanism.h"
#include "EVisualizationMode.h"
#include "EQualityTier.h"
#include "EGPUBackend.h"
#include "EAdaptiveStrategy.h"
#include "ETimeIntegrator.h"
#include "EParticleType.h"
#include "EDragModel.h"
#include "ECollisionModel.h"
#include "EBreakupModel.h"
#include "ECoalescenceModel.h"
#include "EEvaporationModel.h"
#include "ETrackingScheme.h"
#include "ELoadBalancingStrategy.h"
#include "EDomainDecomposition.h"
#include "ECacheStrategy.h"
#include "EPrecisionMode.h"
#include "EConvergenceCriteria.h"
#include "EValidationCaseType.h"
#include "FFluidPreset.h"
#include "FFluidMaterial.h"
#include "FMaterialLookup.h"
#include "FBoundaryProfile.h"
#include "FTurbulenceProfile.h"
#include "FCouplingProfile.h"
#include "FVisualizationPreset.h"
#include "FValidationCase.h"
#include "FGridResolutionComponent.h"
#include "FTimeIntegrationComponent.h"
#include "FPhysicalPropertiesComponent.h"
#include "FTurbulenceComponent.h"
#include "FTurbulenceAdvancedComponent.h"
#include "FMultiphaseComponent.h"
#include "FThermalComponent.h"
#include "FElectroMagneticComponent.h"
#include "FQuantumComponent.h"
#include "FParticulateComponent.h"
#include "FHyperFluidParticleSystemComponent.h"
#include "FAdaptiveMeshComponent.h"
#include "FBoundaryConditionComponent.h"
#include "FCollisionComponent.h"
#include "FCouplingComponent.h"
#include "FPerformanceComponent.h"
#include "FDiagnosticsComponent.h"
#include "FVisualizationComponent.h"
#include "FHyperFluidSimulationCore.h"
#include "AHyperFluidWorld.h"
#include "AHyperFluidEmitter.h"
#include "EEmissionShape.h"
#include "AHyperFluidProbe.h"
#include "AHyperFluidController.h"
#include "FRenderTargetConfig.h"
#include "FluidFlowBlueprintLibrary.h"
