// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771388878
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"

#include "FMultiphaseComponent.generated.h"

UCLASS(ClassGroup=(Custom), meta=(BlueprintSpawnableComponent))
class FLUIDFLOW_API UMultiphaseComponent : public UActorComponent
{
	GENERATED_BODY()

	public:

		UMultiphaseComponent();

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		int32 phases;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float phase_field_mobility;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float interface_thickness;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float surface_tension_coupling;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float contact_angle;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float bubble_spawn_rate;

		UPROPERTY(EditAnywhere, BlueprintReadWrite)
		float droplet_spawn_rate;

};

