// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FPhaseChange_CondensationShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FPhaseChange_CondensationShader);
    SHADER_USE_PARAMETER_STRUCT(FPhaseChange_CondensationShader, FGlobalShader);

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(MultiphaseComponent, multiphase)
        SHADER_PARAMETER(ThermalComponent, thermal)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FPhaseChange_CondensationShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("PhaseChange_Condensation Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FPhaseChange_CondensationShader, "/Plugin/YourPlugin/PhaseChange_Condensation.usf", "PhaseChange_CondensationCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_PhaseChange_Condensation(
    FRDGBuilder& GraphBuilder,
    MultiphaseComponent multiphase,
    ThermalComponent thermal,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
