// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FFilterCopyShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FFilterCopyShader);
    SHADER_USE_PARAMETER_STRUCT(FFilterCopyShader, FGlobalShader);

    using FPermutationDomain = TShaderPermutationDomain<>;

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FUintVector2, texture_size)
        SHADER_PARAMETER_RDG_TEXTURE(Texture2D, input_texture)
        SHADER_PARAMETER_SAMPLER(SamplerState, input_textureSampler)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FFilterCopyShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FPermutationDomain PermutationVector;

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("FilterCopy Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FFilterCopyShader, "/Plugin/YourPlugin/Shaders/FilterCopy.usf", "FilterCopyCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_FilterCopy(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    FRDGTextureRef input_texture,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
