// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FGenerateCracksShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FGenerateCracksShader);
    SHADER_USE_PARAMETER_STRUCT(FGenerateCracksShader, FGlobalShader);

    using FPermutationDomain = TShaderPermutationDomain<>;

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(FUintVector2, texture_size)
        SHADER_PARAMETER(float, scale)
        SHADER_PARAMETER(float, width)
        SHADER_PARAMETER(float, seed)
        SHADER_PARAMETER_RDG_TEXTURE_UAV(RWTexture2D<float4>, OutputTexture)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG compute pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters, FIntVector GroupCount)
    {
        TShaderMapRef<FGenerateCracksShader> ComputeShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FPermutationDomain PermutationVector;

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        FComputeShaderUtils::AddPass(
            GraphBuilder,
            RDG_EVENT_NAME("GenerateCracks Dispatch"),
            ComputeShader,
            PassParameters,
            GroupCount
        );
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FGenerateCracksShader, "/Plugin/YourPlugin/Shaders/GenerateCracks.usf", "GenerateCracksCS", SF_Compute);

// Helper function to add pass to render graph
void AddPass_GenerateCracks(
    FRDGBuilder& GraphBuilder,
    FUintVector2 texture_size,
    float scale,
    float width,
    float seed,
    FRDGTextureRef OutputTexture,
    FIntVector GroupCount = FIntVector(32, 32, 1)
);
