// Generated by KAIN-PRO Compiler — Data-Driven Module
using UnrealBuildTool;
using System.IO;

public class MetaFitter : ModuleRules
{
	public MetaFitter(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;

		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"ChaosClothAssetEngine",
				"ChaosOutfitAssetEngine",
				"Core",
				"CoreUObject",
				"Engine",
				"GeometryCore",
				"GeometryFramework",
				"InputCore",
				"MeshDescription",
				"MetaHumanCharacter",
				"MetaHumanCharacterPalette",
				"MetaHumanDefaultPipeline",
				"MetaHumanSDKRuntime",
				"Projects",
				"RHI",
				"RenderCore",
				"StaticMeshDescription"
			}
		);

		PrivateDependencyModuleNames.AddRange(
			new string[]
			{

			}
		);
	}
}
