//! GraphData class generator for runtime graphs
//!
//! Generates:
//! - UGraphData: Container for all nodes with query methods

use crate::error::Result;
use crate::graph_ir::GraphEditor;

/// Generate GraphData header file
pub fn generate_graph_data_header(graph: &GraphEditor, plugin_name: &str) -> Result<String> {
    let graph_name = &graph.name;
    let api_macro = format!("{}_API", plugin_name.to_uppercase());

    let mut output = String::new();

    // Header guard and includes
    output.push_str(&format!(
        r#"// Generated by KAIN compiler
// Graph: {}

#pragma once

#include "CoreMinimal.h"
#include "{}PinData.h"
#include "{}GraphNodeData.h"
#include "{}GraphData.generated.h"

class U{}PinData;
class U{}GraphNodeData;

"#,
        graph_name, graph_name, graph_name, graph_name, graph_name, graph_name
    ));

    // Generate UGraphData class
    output.push_str(&format!(
        r#"/**
 * Container for {} graph runtime data
 */
UCLASS()
class {} U{}GraphData : public UObject
{{
    GENERATED_BODY()

public:
    /** Find pin by unique identifier */
    U{}PinData* FindPinById(FGuid PinId);
    
    /**
     * Get first node of specific type
     * @return First node of type T, or nullptr if not found
     */
    template <typename T>
    T* GetNodeData()
    {{
        static_assert(TIsDerivedFrom<T, U{}GraphNodeData>::IsDerived, 
                      "T must be derived from U{}GraphNodeData");

        for (int i = 0; i < Nodes.Num(); i++)
        {{
            if (!IsValid(Nodes[i]))
            {{
                continue;
            }}
            if (Nodes[i]->IsA<T>())
            {{
                return Cast<T>(Nodes[i]);
            }}
        }}

        return nullptr;
    }}
    
    /**
     * Get all nodes of specific type
     * @return Array of nodes of type T
     */
    template <typename T>
    TArray<T*> GetListNodeData()
    {{
        static_assert(TIsDerivedFrom<T, U{}GraphNodeData>::IsDerived, 
                      "T must be derived from U{}GraphNodeData");

        TArray<T*> Result;
        for (int i = 0; i < Nodes.Num(); i++)
        {{
            if (!IsValid(Nodes[i]))
            {{
                continue;
            }}
            if (Nodes[i]->IsA<T>())
            {{
                Result.Add(Cast<T>(Nodes[i]));
            }}
        }}

        return Result;
    }}

public:
    /** All nodes in the graph */
    UPROPERTY()
    TArray<U{}GraphNodeData*> Nodes;
}};
"#,
        graph_name,
        api_macro,
        graph_name,
        graph_name,
        graph_name,
        graph_name,
        graph_name,
        graph_name,
        graph_name
    ));

    Ok(output)
}

/// Generate GraphData source file
pub fn generate_graph_data_source(graph: &GraphEditor, _plugin_name: &str) -> Result<String> {
    let graph_name = &graph.name;

    let mut output = String::new();

    // Includes
    output.push_str(&format!(
        r#"// Generated by KAIN compiler
// Graph: {}

#include "{}GraphData.h"

"#,
        graph_name, graph_name
    ));

    // FindPinById implementation
    output.push_str(&format!(
        r#"U{}PinData* U{}GraphData::FindPinById(FGuid PinId)
{{
    for (U{}GraphNodeData* Node : Nodes)
    {{
        for (U{}PinData* Pin : Node->InputPins)
        {{
            if (Pin->PinId == PinId)
            {{
                return Pin;
            }}
        }}

        for (U{}PinData* Pin : Node->OutputPins)
        {{
            if (Pin->PinId == PinId)
            {{
                return Pin;
            }}
        }}
    }}

    return nullptr;
}}

"#,
        graph_name, graph_name, graph_name, graph_name, graph_name
    ));

    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph_ir::*;

    fn create_test_graph() -> GraphEditor {
        let mut graph = GraphEditor::new("Combat");

        // Add a simple node type
        graph.add_node_type(NodeType {
            name: "AttackNode".to_string(),
            category: "Combat".to_string(),
            inputs: vec![PinDefinition {
                name: "Execute".to_string(),
                pin_type: PinType::Exec,
                is_array: false,
                default_value: None,
                tooltip: Some("Execute this node".to_string()),
            }],
            outputs: vec![PinDefinition {
                name: "OnComplete".to_string(),
                pin_type: PinType::Exec,
                is_array: false,
                default_value: None,
                tooltip: Some("Fired when attack completes".to_string()),
            }],
            properties: Vec::new(),
            color: Some([1.0, 0.0, 0.0, 1.0]),
            icon: None,
            tooltip: Some("Execute an attack".to_string()),
            execution_logic: None,
        });

        graph
    }

    #[test]
    fn test_generate_graph_data_header() {
        let graph = create_test_graph();
        let result = generate_graph_data_header(&graph, "TestPlugin");

        assert!(result.is_ok());
        let header = result.unwrap();

        // Check for essential components
        assert!(header.contains("UCombatGraphData"));
        assert!(header.contains("GENERATED_BODY()"));
        assert!(header.contains("FindPinById"));
        assert!(header.contains("GetNodeData"));
        assert!(header.contains("GetListNodeData"));
        assert!(header.contains("TArray<UCombatGraphNodeData*> Nodes"));
    }

    #[test]
    fn test_generate_graph_data_source() {
        let graph = create_test_graph();
        let result = generate_graph_data_source(&graph, "TestPlugin");

        assert!(result.is_ok());
        let source = result.unwrap();

        // Check for essential implementations
        assert!(source.contains("UCombatPinData* UCombatGraphData::FindPinById"));
        assert!(source.contains("#include \"CombatGraphData.h\""));
        assert!(source.contains("return nullptr;"));
    }

    #[test]
    fn test_header_has_correct_api_macro() {
        let graph = create_test_graph();
        let result = generate_graph_data_header(&graph, "MyPlugin");

        assert!(result.is_ok());
        let header = result.unwrap();

        assert!(header.contains("MYPLUGIN_API"));
    }

    #[test]
    fn test_header_has_template_methods() {
        let graph = create_test_graph();
        let result = generate_graph_data_header(&graph, "TestPlugin");

        assert!(result.is_ok());
        let header = result.unwrap();

        // Check template methods are inline in header
        assert!(header.contains("template <typename T>"));
        assert!(header.contains("T* GetNodeData()"));
        assert!(header.contains("TArray<T*> GetListNodeData()"));
        assert!(header.contains("static_assert"));
        assert!(header.contains("TIsDerivedFrom"));
    }

    #[test]
    fn test_source_has_all_implementations() {
        let graph = create_test_graph();
        let result = generate_graph_data_source(&graph, "TestPlugin");

        assert!(result.is_ok());
        let source = result.unwrap();

        // Check graph data method implementation
        assert!(source.contains("FindPinById(FGuid PinId)"));
        assert!(!source.contains("GetNextOutputNodeByPinIndex(int OutputPinIndex)"));
    }

    #[test]
    fn test_pin_data_structure() {
        let graph = create_test_graph();
        let result = generate_graph_data_header(&graph, "TestPlugin");

        assert!(result.is_ok());
        let header = result.unwrap();

        // GraphData should reference existing PinData/GraphNodeData classes
        assert!(header.contains("#include \"CombatPinData.h\""));
        assert!(header.contains("#include \"CombatGraphNodeData.h\""));
        assert!(header.contains("UCombatPinData* FindPinById(FGuid PinId)"));
    }

    #[test]
    fn test_node_data_structure() {
        let graph = create_test_graph();
        let result = generate_graph_data_header(&graph, "TestPlugin");

        assert!(result.is_ok());
        let header = result.unwrap();

        // GraphData owns node list and exposes query helpers
        assert!(header.contains("TArray<UCombatGraphNodeData*> Nodes"));
        assert!(header.contains("T* GetNodeData()"));
        assert!(header.contains("TArray<T*> GetListNodeData()"));
    }
}
