// Generated by KAIN Compiler
// Derived HLSL output from the KAIN shader artifact pipeline

// Shader: OceanFragment
cbuffer OceanFragmentParams : register(b0)
{
    float time;
    float2 resolution;
    float2 mouse;
};

RWStructuredBuffer<float> _padding : register(u3);

struct OceanFragmentInput
{
    float2 uv : TEXCOORD0;
};

struct OceanFragmentOutput
{
    float4 color : SV_Target0;
};

OceanFragmentOutput OceanFragment(OceanFragmentInput input)
{
    float fx = (input.uv.x * resolution.x);
    float fy = (input.uv.y * resolution.y);
    float ux = ((((((fx / resolution.x)) * 2.0) - 1.0)) * ((resolution.x / resolution.y)));
    float uy = ((((fy / resolution.y)) * 2.0) - 1.0);
    float rx = ux;
    float ry = uy;
    float rz = 1.5;
    float rl = (1.0 / sqrt((((rx * rx) + (ry * ry)) + (rz * rz))));
    rx = (rx * rl);
    ry = (ry * rl);
    rz = (rz * rl);
    if ((resolution.x >= 600.0)) {
        float ya = (3.0 * (((((mouse.x + 0.5)) * 2.0) - 1.0)));
        float ys = sin(ya);
        float yc = cos(ya);
        float yoc = (1.0 - yc);
        float yrx = rx;
        float yry = ry;
        float yrz = rz;
        rx = (((((((yoc * 0.0) * 0.0) + yc)) * yrx) + (((((yoc * 0.0) * ((-1.0))) - (0.0 * ys))) * yry)) + (((((yoc * 0.0) * 0.0) + (((-1.0)) * ys))) * yrz));
        ry = (((((((yoc * 0.0) * ((-1.0))) + (0.0 * ys))) * yrx) + (((((yoc * ((-1.0))) * ((-1.0))) + yc)) * yry)) + (((((yoc * ((-1.0))) * 0.0) - (0.0 * ys))) * yrz));
        rz = (((((((yoc * 0.0) * 0.0) - (((-1.0)) * ys))) * yrx) + (((((yoc * ((-1.0))) * 0.0) + (0.0 * ys))) * yry)) + (((((yoc * 0.0) * 0.0) + yc)) * yrz));
        float m_y = ((mouse.y == 0.0) ? 0.27 : mouse.y);
        float xa = (0.5 + (1.5 * (((m_y * 2.0) - 1.0))));
        float csx = sin(xa);
        float ccx = cos(xa);
        float xoc = (1.0 - ccx);
        float xrx = rx;
        float xry = ry;
        float xrz = rz;
        rx = (((((((xoc * 1.0) * 1.0) + ccx)) * xrx) + (((((xoc * 1.0) * 0.0) - (0.0 * csx))) * xry)) + (((((xoc * 0.0) * 1.0) + (0.0 * csx))) * xrz));
        ry = (((((((xoc * 1.0) * 0.0) + (0.0 * csx))) * xrx) + (((((xoc * 0.0) * 0.0) + ccx)) * xry)) + (((((xoc * 0.0) * 0.0) - (1.0 * csx))) * xrz));
        rz = (((((((xoc * 0.0) * 1.0) - (0.0 * csx))) * xrx) + (((((xoc * 0.0) * 0.0) + (1.0 * csx))) * xry)) + (((((xoc * 0.0) * 0.0) + ccx)) * xrz));
    }
    if ((ry >= 0.0)) {
        float sdx = (-0.07735);
        float sdy = (0.5 + (sin(((time * 0.2) + 2.6)) * 0.45));
        float sdz = 0.57735;
        float sdl = (1.0 / sqrt((((sdx * sdx) + (sdy * sdy)) + (sdz * sdz))));
        float sx = (sdx * sdl);
        float sy = (sdy * sdl);
        float sz = (sdz * sdl);
        float st = (1.0 / (((ry * 1.0) + 0.1)));
        float st2 = (1.0 / (((sy * 11.0) + 1.0)));
        float dsr = (((rx * sx) + (ry * sy)) + (rz * sz));
        float raysundt = (dsr * dsr);
        float sd = dsr;
        int si = 0;
        while ((si < 7)) {
            sd = (sd * dsr);
            si = (si + 1);
        }
        sd = max(0.0, sd);
        float bsk_r = (((max(0.0, (((5.5 / 22.4) * ((max(0.0, (1.0 - (5.5 / 22.4))) + (((1.0 - max(0.0, (1.0 - (5.5 / 22.4))))) * st2)))) - ((5.5 * 0.002) * ((st + (((-6.0) * sy) * sy)))))) * st) * ((0.24 + (raysundt * 0.24)))) * ((1.0 + (((1.0 * ((1.0 - ry))) * ((1.0 - ry))) * ((1.0 - ry))))));
        float bsk_g = (((max(0.0, (((13.0 / 22.4) * ((max(0.0, (1.0 - (13.0 / 22.4))) + (((1.0 - max(0.0, (1.0 - (13.0 / 22.4))))) * st2)))) - ((13.0 * 0.002) * ((st + (((-6.0) * sy) * sy)))))) * st) * ((0.24 + (raysundt * 0.24)))) * ((1.0 + (((1.0 * ((1.0 - ry))) * ((1.0 - ry))) * ((1.0 - ry))))));
        float bsk_b = (((max(0.0, ((1.0 * ((max(0.0, (1.0 - (22.4 / 22.4))) + (((1.0 - max(0.0, (1.0 - (22.4 / 22.4))))) * st2)))) - ((22.4 * 0.002) * ((st + (((-6.0) * sy) * sy)))))) * st) * ((0.24 + (raysundt * 0.24)))) * ((1.0 + (((1.0 * ((1.0 - ry))) * ((1.0 - ry))) * ((1.0 - ry))))));
        float spv = max(0.0, dsr);
        int spi = 0;
        while ((spi < 9)) {
            spv = (spv * spv);
            spi = (spi + 1);
        }
        float sp512 = spv;
        float sp128 = max(0.0, dsr);
        spi = 0;
        while ((spi < 7)) {
            sp128 = (sp128 * sp128);
            spi = (spi + 1);
        }
        float sp64 = max(0.0, dsr);
        spi = 0;
        while ((spi < 6)) {
            sp64 = (sp64 * sp64);
            spi = (spi + 1);
        }
        float sp16 = max(0.0, dsr);
        spi = 0;
        while ((spi < 4)) {
            sp16 = (sp16 * sp16);
            spi = (spi + 1);
        }
        float sn = ((((sp512 * sp128) * sp64) * sp16) * 210.0);
        float Cr = ((((bsk_r * 0.5) + sn)) * 2.0);
        float Cg = ((((bsk_g * 0.5) + sn)) * 2.0);
        float Cb = ((((bsk_b * 0.5) + sn)) * 2.0);
        float gr = sqrt(sqrt(max(0.0, min(Cr, 1.0))));
        float gg = sqrt(sqrt(max(0.0, min(Cg, 1.0))));
        float gb = sqrt(sqrt(max(0.0, min(Cb, 1.0))));
        OceanFragmentOutput _result;
        _result.color = float4((gr * sqrt(sqrt(gr))), (gg * sqrt(sqrt(gg))), (gb * sqrt(sqrt(gb))), 1.0);
        return _result;
    }
    float origin_x = (time * 0.2);
    float origin_y = 1.5;
    float origin_z = 1.0;
    float plane_denom = (ry * 1.0);
    float plane_nt = ((-(origin_y)) / max(0.0001, abs(plane_denom)));
    float hpx = (origin_x + (rx * plane_nt));
    float hpy = (origin_y + (ry * plane_nt));
    float hpz = (origin_z + (rz * plane_nt));
    float plane_lt = ((-(((-1.0) - origin_y))) / max(0.0001, abs(plane_denom)));
    float lpx = (origin_x + (rx * plane_lt));
    float lpy = (origin_y + (ry * plane_lt));
    float lpz = (origin_z + (rz * plane_lt));
    float rdx = (lpx - hpx);
    float rdy = (lpy - hpy);
    float rdz = (lpz - hpz);
    float rdl = (1.0 / sqrt((((rdx * rdx) + (rdy * rdy)) + (rdz * rdz))));
    float rnx = (rdx * rdl);
    float rny = (rdy * rdl);
    float rnz = (rdz * rdl);
    float mrpx = hpx;
    float mrpy = hpy;
    float mrpz = hpz;
    float hitDist = (-1.0);
    int mi = 0;
    while ((mi < 64)) {
        float msv = 0.0;
        float msw = 0.0;
        float mfreq = 1.0;
        float mtMul = 2.0;
        float mwgt = 1.0;
        float miter = 0.0;
        float mwx = mrpx;
        float mwy = mrpz;
        int mwci = 0;
        while ((mwci < 12)) {
            float mdx = sin(miter);
            float mdy = cos(miter);
            float mx = ((((((mdx * mwx) + (mdy * mwy))) * mfreq) + (time * mtMul)) + ((((mwx * mwx) + (mwy * mwy))) * 0.1));
            float mv = pow(2.718282, (sin(mx) - 1.0));
            float mdx2 = (mv * ((-cos(mx))));
            mwx = (mwx + (((mdx * mdx2) * mwgt) * 0.38));
            mwy = (mwy + (((mdy * mdx2) * mwgt) * 0.38));
            msv = (msv + (mv * mwgt));
            msw = (msw + mwgt);
            mwgt = (mwgt * 0.8);
            mfreq = (mfreq * 1.18);
            mtMul = (mtMul * 1.07);
            miter = (miter + 1232.399963);
            mwci = (mwci + 1);
        }
        float mh = (((msv / msw) * 1.0) - 1.0);
        if (((mh + 0.01) > mrpy)) {
            float dx = (mrpx - origin_x);
            float dy = (mrpy - origin_y);
            float dz = (mrpz - origin_z);
            hitDist = sqrt((((dx * dx) + (dy * dy)) + (dz * dz)));
            mi = 64;
        } else {
            float step = (mrpy - mh);
            mrpx = (mrpx + (rnx * step));
            mrpy = (mrpy + (rny * step));
            mrpz = (mrpz + (rnz * step));
            mi = (mi + 1);
        }
    }
    if ((hitDist < 0.0)) {
        float dx = (hpx - origin_x);
        float dy = (hpy - origin_y);
        float dz = (hpz - origin_z);
        hitDist = sqrt((((dx * dx) + (dy * dy)) + (dz * dz)));
    }
    float hit_x = (origin_x + (rx * hitDist));
    float hit_y = (origin_y + (ry * hitDist));
    float hit_z = (origin_z + (rz * hitDist));
    float ee = 0.01;
    float nsv = 0.0;
    float nsw = 0.0;
    float nfreq = 1.0;
    float ntm = 2.0;
    float nwgt = 1.0;
    float niter = 0.0;
    float nwx = hit_x;
    float nwy = hit_z;
    int nwi = 0;
    while ((nwi < 36)) {
        float ndx = sin(niter);
        float ndy = cos(niter);
        float nx = ((((((ndx * nwx) + (ndy * nwy))) * nfreq) + (time * ntm)) + ((((nwx * nwx) + (nwy * nwy))) * 0.1));
        float nv = pow(2.718282, (sin(nx) - 1.0));
        float ndx2 = (nv * ((-cos(nx))));
        nwx = (nwx + (((ndx * ndx2) * nwgt) * 0.38));
        nwy = (nwy + (((ndy * ndx2) * nwgt) * 0.38));
        nsv = (nsv + (nv * nwgt));
        nsw = (nsw + nwgt);
        nwgt = (nwgt * 0.8);
        nfreq = (nfreq * 1.18);
        ntm = (ntm * 1.07);
        niter = (niter + 1232.399963);
        nwi = (nwi + 1);
    }
    float nH = ((nsv / nsw) * 1.0);
    float n2sv = 0.0;
    float n2sw = 0.0;
    float n2freq = 1.0;
    float n2tm = 2.0;
    float n2wgt = 1.0;
    float n2iter = 0.0;
    float n2wx = (hit_x - ee);
    float n2wy = hit_z;
    int n2i = 0;
    while ((n2i < 36)) {
        float n2dx = sin(n2iter);
        float n2dy = cos(n2iter);
        float n2x = ((((((n2dx * n2wx) + (n2dy * n2wy))) * n2freq) + (time * n2tm)) + ((((n2wx * n2wx) + (n2wy * n2wy))) * 0.1));
        float n2v = pow(2.718282, (sin(n2x) - 1.0));
        float n2dx2 = (n2v * ((-cos(n2x))));
        n2wx = (n2wx + (((n2dx * n2dx2) * n2wgt) * 0.38));
        n2wy = (n2wy + (((n2dy * n2dx2) * n2wgt) * 0.38));
        n2sv = (n2sv + (n2v * n2wgt));
        n2sw = (n2sw + n2wgt);
        n2wgt = (n2wgt * 0.8);
        n2freq = (n2freq * 1.18);
        n2tm = (n2tm * 1.07);
        n2iter = (n2iter + 1232.399963);
        n2i = (n2i + 1);
    }
    float nHl = ((n2sv / n2sw) * 1.0);
    float n3sv = 0.0;
    float n3sw = 0.0;
    float n3freq = 1.0;
    float n3tm = 2.0;
    float n3wgt = 1.0;
    float n3iter = 0.0;
    float n3wx = hit_x;
    float n3wy = (hit_z + ee);
    int n3i = 0;
    while ((n3i < 36)) {
        float n3dx = sin(n3iter);
        float n3dy = cos(n3iter);
        float n3x = ((((((n3dx * n3wx) + (n3dy * n3wy))) * n3freq) + (time * n3tm)) + ((((n3wx * n3wx) + (n3wy * n3wy))) * 0.1));
        float n3v = pow(2.718282, (sin(n3x) - 1.0));
        float n3dx2 = (n3v * ((-cos(n3x))));
        n3wx = (n3wx + (((n3dx * n3dx2) * n3wgt) * 0.38));
        n3wy = (n3wy + (((n3dy * n3dx2) * n3wgt) * 0.38));
        n3sv = (n3sv + (n3v * n3wgt));
        n3sw = (n3sw + n3wgt);
        n3wgt = (n3wgt * 0.8);
        n3freq = (n3freq * 1.18);
        n3tm = (n3tm * 1.07);
        n3iter = (n3iter + 1232.399963);
        n3i = (n3i + 1);
    }
    float nHu = ((n3sv / n3sw) * 1.0);
    float v1_x = (hit_x - ((hit_x - ee)));
    float v1_y = (nH - nHl);
    float v1_z = (hit_z - hit_z);
    float v2_x = (hit_x - hit_x);
    float v2_y = (nH - nHu);
    float v2_z = (hit_z - ((hit_z + ee)));
    float cx = ((v1_y * v2_z) - (v1_z * v2_y));
    float cy = ((v1_z * v2_x) - (v1_x * v2_z));
    float cz = ((v1_x * v2_y) - (v1_y * v2_x));
    float cl = (1.0 / max(0.0001, sqrt((((cx * cx) + (cy * cy)) + (cz * cz)))));
    float Nx = (cx * cl);
    float Ny = (cy * cl);
    float Nz = (cz * cl);
    float sf = (0.8 * min(1.0, (sqrt((hitDist * 0.01)) * 1.1)));
    Nx = (Nx * ((1.0 - sf)));
    Ny = ((Ny * ((1.0 - sf))) + (1.0 * sf));
    Nz = (Nz * ((1.0 - sf)));
    float ndr = (-((((Nx * rx) + (Ny * ry)) + (Nz * rz))));
    float fp_v = max(0.0, ndr);
    int fpi = 0;
    while ((fpi < 4)) {
        fp_v = (fp_v * ndr);
        fpi = (fpi + 1);
    }
    float fresnel = (0.04 + (0.96 * fp_v));
    float refl_dot = (((Nx * rx) + (Ny * ry)) + (Nz * rz));
    float Rrx = (rx - ((2.0 * refl_dot) * Nx));
    float Rry = (ry - ((2.0 * refl_dot) * Ny));
    float Rrz = (rz - ((2.0 * refl_dot) * Nz));
    Rry = abs(Rry);
    float rrl = (1.0 / max(0.0001, sqrt((((Rrx * Rrx) + (Rry * Rry)) + (Rrz * Rrz)))));
    Rrx = (Rrx * rrl);
    Rry = (Rry * rrl);
    Rrz = (Rrz * rrl);
    float sxd = (-0.07735);
    float syd = (0.5 + (sin(((time * 0.2) + 2.6)) * 0.45));
    float szd = 0.57735;
    float sld = (1.0 / sqrt((((sxd * sxd) + (syd * syd)) + (szd * szd))));
    float sxf = (sxd * sld);
    float syf = (syd * sld);
    float szf = (szd * sld);
    float rst = (1.0 / (((Rry * 1.0) + 0.1)));
    float rdsr = (((Rrx * sxf) + (Rry * syf)) + (Rrz * szf));
    float rrays = (rdsr * rdsr);
    float rsd = rdsr;
    int rsi = 0;
    while ((rsi < 7)) {
        rsd = (rsd * rdsr);
        rsi = (rsi + 1);
    }
    rsd = max(0.0, rsd);
    float rspv = max(0.0, rdsr);
    int rspi = 0;
    while ((rspi < 9)) {
        rspv = (rspv * rspv);
        rspi = (rspi + 1);
    }
    float rsp512 = rspv;
    float rsp128 = max(0.0, rdsr);
    rspi = 0;
    while ((rspi < 7)) {
        rsp128 = (rsp128 * rsp128);
        rspi = (rspi + 1);
    }
    float rsp64 = max(0.0, rdsr);
    rspi = 0;
    while ((rspi < 6)) {
        rsp64 = (rsp64 * rsp64);
        rspi = (rspi + 1);
    }
    float rsp16 = max(0.0, rdsr);
    rspi = 0;
    while ((rspi < 4)) {
        rsp16 = (rsp16 * rsp16);
        rspi = (rspi + 1);
    }
    float rsn = ((((rsp512 * rsp128) * rsp64) * rsp16) * 210.0);
    float ratm = ((((rst * ((0.24 + (rrays * 0.24)))) * ((1.0 + (((1.0 * ((1.0 - Rry))) * ((1.0 - Rry))) * ((1.0 - Rry)))))) * 5.5) / 22.4);
    float ratt_r = ((ratm * 0.4) + (rsn * 0.5));
    float ratt_g = ((ratm * 0.4) + (rsn * 0.5));
    float ratt_b = ((ratm * 0.4) + (rsn * 0.5));
    float depth_frac = (((hit_y + 1.0)) / 1.0);
    float scat_r = ((0.0293 * 0.1) * ((0.2 + depth_frac)));
    float scat_g = ((0.0698 * 0.1) * ((0.2 + depth_frac)));
    float scat_b = ((0.1717 * 0.1) * ((0.2 + depth_frac)));
    float wCr = ((fresnel * ratt_r) + scat_r);
    float wCg = ((fresnel * ratt_g) + scat_g);
    float wCb = ((fresnel * ratt_b) + scat_b);
    float wgr = sqrt(sqrt(max(0.0, min((wCr * 2.0), 1.0))));
    float wgg = sqrt(sqrt(max(0.0, min((wCg * 2.0), 1.0))));
    float wgb = sqrt(sqrt(max(0.0, min((wCb * 2.0), 1.0))));
    OceanFragmentOutput _result;
    _result.color = float4((wgr * sqrt(sqrt(wgr))), (wgg * sqrt(sqrt(wgg))), (wgb * sqrt(sqrt(wgb))), 1.0);
    return _result;
}

