// Copyright 2026 Zentako. All Rights Reserved.
// Generated by KAIN-PRO - Godmode v3
// Period: 1771342071
// Source: KAIN Source
// DO NOT EDIT - Any changes will be overwritten

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/ActorComponent.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "AFlowManager.h"
#include "EFluidMode.h"
#include "EVisualizerType.h"
#include "FFluidSimulationProfile.h"
#include "FInteractionSource.h"

#include "KainFlowBlueprintLibrary.generated.h"

UCLASS()
class KAINFLOW_API UKainFlowBlueprintLibraryFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

	public:
		UFUNCTION(BlueprintCallable, Category = "Kain")
		static FFluidSimulationProfile create_default_profile();
};

