#!/usr/bin/env python3
"""Generate all SMT2 proof files for services.c and handle.c optimization candidates."""

import os

OUTDIR = "X:/runtime/native/src/core/z3/proofs-experimental"
os.makedirs(OUTDIR, exist_ok=True)

def write_smt2(filename, content):
    path = os.path.join(OUTDIR, filename)
    with open(path, 'w') as f:
        f.write(content)
    print(f"  Wrote {path}")

# ============================================================
# 1. Service catalog tokens distinct (31 keys, full 64-bit)
# ============================================================
CATALOG_TOKENS = [
    ("base.memory", 0x40ff954815c29c3c),
    ("memory.ownership", 0x996e110347da4ecb),
    ("base.diagnostics", 0xc8cb120ba774d42c),
    ("contract", 0x698874cc51cd9a1a),
    ("platform.app-host", 0x9ddb6ede77c15466),
    ("platform.input", 0xe093a52140179233),
    ("gfx.viewport", 0xbdee771d7a52ed8b),
    ("gfx.raw-native", 0x6afe64f6fc93ec0a),
    ("gfx.shader.spirv", 0x0fb1512b913fcf4e),
    ("gfx.backend.vulkan", 0xe36f7fad9871cc54),
    ("gfx.backend.d3d12", 0xeaa6564c42ba0b6e),
    ("scene.runtime", 0x776dd99f54c1c0ff),
    ("scene.query", 0x06bd309e3c1efed3),
    ("scene.mutation", 0xa93bcf1323d0f538),
    ("asset.gltf", 0xbf8f73e53cfc8f2f),
    ("asset.ingestion", 0xe25621a63df6f8ff),
    ("asset.realtime", 0x727f805c552fa603),
    ("ui.bundle", 0xc406578ad44bcf06),
    ("reflection", 0xc12b1f6e1af9364e),
    ("runtime.inspection", 0xe1abfe67f1428028),
    ("device.reflection", 0x28e6497b81e13e6d),
    ("actor.runtime", 0xe8609817aa70bec8),
    ("actor.registry", 0x3d8b22a2108b2abe),
    ("async.runtime", 0x6371b1a866d592dc),
    ("async.timers", 0x3936858b89656917),
    ("io.net", 0xbadf8e5201528361),
    ("io.process", 0x316e9b66b64ff4a5),
    ("gfx.compute", 0x5c0e2517e24062ee),
    ("ui.component", 0x1f16ff96f558fce0),
    ("compatibility", 0x378e0a4d70394a9f),
    ("host.bridge", 0xeccb11f598278cf6),
]

content = []
content.append("; Z3 proof: 31 catalog service key tokens are collision-free (full 64-bit check)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
for i, (key, val) in enumerate(CATALOG_TOKENS):
    content.append(f"(define-fun srv_{i:02d} () (_ BitVec 64) #x{val:016x}) ; {key}")
names = " ".join(f"srv_{i:02d}" for i in range(31))
content.append(f"(assert (not (distinct {names})))")
content.append("(check-sat)")
write_smt2("service-catalog-tokens-distinct.smt2", "\n".join(content))

# ============================================================
# 2. Perfect hash: M=2990, top 6 bits (31 catalog keys)
# ============================================================
content = []
content.append("; Z3 proof: Perfect hash for 31 catalog service keys is collision-free")
content.append("; hash(x) = (x * 2990) >> 58  (top 6 bits, 64-slot range)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
content.append("")
content.append("(define-fun hash ((x (_ BitVec 64))) (_ BitVec 6)")
content.append("  ((_ extract 63 58) (bvmul x #x0000000000000bae)))")
content.append("")
for i, (key, val) in enumerate(CATALOG_TOKENS):
    content.append(f"(define-fun ph_{i:02d} () (_ BitVec 64) #x{val:016x}) ; {key}")
names = " ".join(f"(hash ph_{i:02d})" for i in range(31))
content.append(f"(assert (not (distinct {names})))")
content.append("(check-sat)")
write_smt2("service-perfect-hash-m2990-b6.smt2", "\n".join(content))

# ============================================================
# 3. Perfect hash: M=31, top 7 bits (31 catalog keys)
# ============================================================
content = []
content.append("; Z3 proof: Perfect hash for 31 catalog service keys is collision-free")
content.append("; hash(x) = (x * 31) >> 57  (top 7 bits, 128-slot range)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
content.append("")
content.append("(define-fun hash ((x (_ BitVec 64))) (_ BitVec 7)")
content.append("  ((_ extract 63 57) (bvmul x #x000000000000001f)))")
content.append("")
for i, (key, val) in enumerate(CATALOG_TOKENS):
    content.append(f"(define-fun ph_{i:02d} () (_ BitVec 64) #x{val:016x}) ; {key}")
names = " ".join(f"(hash ph_{i:02d})" for i in range(31))
content.append(f"(assert (not (distinct {names})))")
content.append("(check-sat)")
write_smt2("service-perfect-hash-m31-b7.smt2", "\n".join(content))

# ============================================================
# 4. Perfect hash: M=1, top 8 bits (31 catalog keys, no multiply needed)
# ============================================================
content = []
content.append("; Z3 proof: Service keys have unique top 8 bits (no multiplication needed)")
content.append("; hash(x) = x >> 56  (top 8 bits)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
content.append("")
content.append("(define-fun hash ((x (_ BitVec 64))) (_ BitVec 8)")
content.append("  ((_ extract 63 56) x))")
content.append("")
for i, (key, val) in enumerate(CATALOG_TOKENS):
    content.append(f"(define-fun ph_{i:02d} () (_ BitVec 64) #x{val:016x}) ; {key}")
names = " ".join(f"(hash ph_{i:02d})" for i in range(31))
content.append(f"(assert (not (distinct {names})))")
content.append("(check-sat)")
write_smt2("service-perfect-hash-m1-b8.smt2", "\n".join(content))


# ============================================================
# 5. Alias tokens distinct (17 alias keys)
# ============================================================
ALIAS_TOKENS = [
    ("native.app-host", 0xe967a2e7a5088d07),
    ("native.input", 0x1c9e242eb4645378),
    ("native.viewport", 0x8140fe9573cec064),
    ("native.graphics", 0x52b4f4dbb3337bfb),
    ("native.scene", 0x9b6bbed0fbf8a1dd),
    ("native.scene.query", 0xcccf3d4aaed22219),
    ("native.scene.mutation", 0xf26120689e22a9e2),
    ("native.runtime.inspection", 0xf42f6791bc7ef2bd),
    ("native.device.reflection", 0x7a425942690ea4d7),
    ("native.asset.gltf", 0x5b2990da90ab1f38),
    ("native.asset.ingestion", 0x403bc9addf0d3a57),
    ("native.ui.compiled-bundle", 0xe764215896fc05bb),
    ("native.compute", 0x83303d876aa8e678),
    ("native.shader.spirv", 0x25be923470113a81),
    ("native.vulkan", 0x0d2f647f2745c670),
    ("native.dx12", 0x249604c6dc88fc47),
    ("native.d3d12", 0x5a3a87a1ea23aab6),
]
content = []
content.append("; Z3 proof: All 17 alias service key tokens are collision-free (full 64-bit)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
for i, (key, val) in enumerate(ALIAS_TOKENS):
    content.append(f"(define-fun ali_{i:02d} () (_ BitVec 64) #x{val:016x}) ; {key}")
names = " ".join(f"ali_{i:02d}" for i in range(17))
content.append(f"(assert (not (distinct {names})))")
content.append("(check-sat)")
write_smt2("service-alias-tokens-distinct.smt2", "\n".join(content))

# ============================================================
# 6. Handle packing invariants proof
# ============================================================
content = []
content.append("; Z3 proof: Handle packing/unpacking is lossless")
content.append("; handle = (kind & 0xff) << 56 | (magic & 0xffffff) << 32 | (slot + 1)")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
content.append("")
content.append("(declare-const kind (_ BitVec 8))")
content.append("(declare-const slot (_ BitVec 32))")
content.append("(declare-const magic_raw (_ BitVec 32))")
content.append("")
content.append("; Constrain: magic must fit in lower 24 bits, kind any 8-bit, slot any 32-bit")
content.append("(assert (bvult magic_raw (_ bv16777216 32)))")
content.append("")
content.append("; Pack: built exactly like kain_handle_make")
content.append("(define-fun packed () (_ BitVec 64)")
content.append("  (bvor")
content.append("    (bvshl ((_ zero_extend 56) kind) (_ bv56 64))")
content.append("    (bvshl ((_ zero_extend 32) ((_ extract 23 0) magic_raw)) (_ bv32 64))")
content.append("    (bvadd ((_ zero_extend 32) slot) (_ bv1 64))")
content.append("  ))")
content.append("")
content.append("; Extract: exactly like kain_handle_kind, kain_handle_slot, kain_handle_magic")
content.append("(define-fun kind_out () (_ BitVec 8)")
content.append("  ((_ extract 63 56) packed))")
content.append("")
content.append("(define-fun magic_out () (_ BitVec 32)")
content.append("  (bvshl ((_ zero_extend 8) ((_ extract 55 32) packed)) (_ bv0 32)))")
content.append("")
content.append("; kain_handle_slot: encoded = (uint32_t)(handle & 0xffffffff); return encoded-1 or UINT32_MAX if 0")
content.append("(define-fun encoded () (_ BitVec 32) ((_ extract 31 0) packed))")
content.append("(define-fun slot_out () (_ BitVec 32)")
content.append("  (ite (= encoded (_ bv0 32)) (_ bv4294967295 32) (bvsub encoded (_ bv1 32))))")
content.append("")
content.append("; Assert roundtrip preserves all fields when slot != 0xFFFFFFFF")
content.append("(assert (not (= slot (_ bv4294967295 32))))")
content.append("(assert (not")
content.append("  (and")
content.append("    (= kind kind_out)")
content.append("    (= magic_raw magic_out)")
content.append("    (= slot slot_out)")
content.append("  )))")
content.append("(check-sat)")
content.append("")
content.append("; Additional: slot=0xFFFFFFFF makes encoded=0, gets slot_out=0xFFFFFFFF")
content.append("(assert (= slot (_ bv4294967295 32)))")
content.append("")
content.append("(define-fun encoded_sentinel () (_ BitVec 32) ((_ extract 31 0) packed))")
content.append("(define-fun slot_sentinel () (_ BitVec 32)")
content.append("  (ite (= encoded_sentinel (_ bv0 32)) (_ bv4294967295 32) (bvsub encoded_sentinel (_ bv1 32))))")
content.append("(assert (not (= slot_sentinel (_ bv4294967295 32))))")
content.append("(check-sat)")
write_smt2("handle-packing-lossless.smt2", "\n".join(content))

# ============================================================
# 7. Handle stale rejection proof
# ============================================================
content = []
content.append("; Z3 proof: After release, a stale handle (with old magic) cannot validate")
content.append("; Release: entry->magic = nonzero(entry->magic + 1)")
content.append("; Validate: checks table->slots[slot].magic == kain_handle_magic(handle)")
content.append("; Since magic changes on release, old handles are rejected")
content.append("; Generated by runtime-z3-optimizer agent")
content.append("(set-logic QF_BV)")
content.append("")
content.append("(declare-const old_magic (_ BitVec 24))")
content.append("(declare-const slot (_ BitVec 32))")
content.append("(declare-const kind (_ BitVec 8))")
content.append("")
content.append("; Build handle using old magic: same as kain_handle_make")
content.append("(define-fun handle () (_ BitVec 64)")
content.append("  (bvor")
content.append("    (bvshl ((_ zero_extend 56) kind) (_ bv56 64))")
content.append("    (bvshl ((_ zero_extend 40) old_magic) (_ bv32 64))")
content.append("    (bvadd ((_ zero_extend 32) slot) (_ bv1 64))))")
content.append("")
content.append("; Extract magic from handle: same as kain_handle_magic")
content.append("(define-fun handle_magic () (_ BitVec 24)")
content.append("  ((_ extract 55 32) handle))")
content.append("")
content.append("; New magic after release: kain_handle_nonzero_magic(old_magic + 1)")
content.append("; Note: magic is stored as 24-bit in slot, kain_handle_nonzero_magic maps 0->1")
content.append("(define-fun bumped () (_ BitVec 24) (bvadd old_magic (_ bv1 24)))")
content.append("(define-fun new_magic () (_ BitVec 24)")
content.append("  (ite (= bumped (_ bv0 24)) (_ bv1 24) bumped))")
content.append("")
content.append("; Assert: handle's old magic != new magic stored in slot after release")
content.append("; If unsat, magic always differs -> stale handles always rejected")
content.append("(assert (= handle_magic new_magic))")
content.append("(check-sat)")
write_smt2("handle-stale-rejection.smt2", "\n".join(content))

print(f"\nGenerated all proof files in {OUTDIR}")
