// Generated by KAIN Compiler - UE5 Shader Parameter Reflection
// This file provides C++ bindings for shader parameters

#pragma once

#include "CoreMinimal.h"
#include "GlobalShader.h"
#include "ShaderParameters.h"
#include "ShaderParameterStruct.h"
#include "ShaderParameterUtils.h"
#include "RenderGraphResources.h"
#include "RenderGraphBuilder.h"
#include "ShaderCompilerCore.h"
#include "RHIStaticStates.h"

class FDepthOfFieldShader : public FGlobalShader
{
    DECLARE_GLOBAL_SHADER(FDepthOfFieldShader);
    SHADER_USE_PARAMETER_STRUCT(FDepthOfFieldShader, FGlobalShader);

    using FPermutationDomain = TShaderPermutationDomain<>;

    BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
        SHADER_PARAMETER(float, focus_distance)
        SHADER_PARAMETER(float, focus_range)
        SHADER_PARAMETER(float, aperture)
        SHADER_PARAMETER(float, focal_length)
        SHADER_PARAMETER(float, bokeh_shape)
        SHADER_PARAMETER(float, bokeh_rotation)
        SHADER_PARAMETER(float, bokeh_scale)
        SHADER_PARAMETER(float, coc_scale)
        SHADER_PARAMETER(float, max_blur_size)
    END_SHADER_PARAMETER_STRUCT()

    // Automatically generates RDG pixel shader pass
    static void Exec(FRDGBuilder& GraphBuilder, const FParameters& Parameters)
    {
        TShaderMapRef<FDepthOfFieldShader> PixelShader(GetGlobalShaderMap(GMaxRHIFeatureLevel));

        FPermutationDomain PermutationVector;

        FParameters* PassParameters = GraphBuilder.AllocParameters<FParameters>();
        *PassParameters = Parameters;

        // For pixel shaders, you'll need to set up a full-screen quad or custom geometry
        // This is a simplified example - adapt to your rendering pipeline
        // Use AddDrawPass or integrate with your post-process pipeline
    }
};

// In your .cpp file, add:
// IMPLEMENT_GLOBAL_SHADER(FDepthOfFieldShader, "/Plugin/YourPlugin/Shaders/DepthOfField.usf", "DepthOfFieldPS", SF_Pixel);

// Helper function to dispatch shader from game thread
void DispatchDepthOfFieldShader(
    float focus_distance,
    float focus_range,
    float aperture,
    float focal_length,
    float bokeh_shape,
    float bokeh_rotation,
    float bokeh_scale,
    float coc_scale,
    float max_blur_size);
