//! UE5 Engine Knowledge Base
//!
//! A rich, queryable database of Unreal Engine types, classes, components,
//! and their relationships. Replaces the flat StdLibResolver with a system
//! that understands class hierarchies, include paths, property flags,
//! and type categories — enabling compile-time validation of KAIN code
//! against the actual engine API.
//!
//! Knowledge is loaded from `unreal/metadata/engine_knowledge.json` which
//! can be generated by scanning UE5 headers or seeded from reference data.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

// ═══════════════════════════════════════════════════════════════════
// Schema Types
// ═══════════════════════════════════════════════════════════════════

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineClass {
    pub name: String,
    #[serde(default)]
    pub parent: String,
    #[serde(default)]
    pub header: String,
    #[serde(default)]
    pub module: String,
    #[serde(default)]
    pub prefix: String,
    #[serde(default)]
    pub specifiers: Vec<String>,
    #[serde(default)]
    pub functions: Vec<EngineFunction>,
    #[serde(default)]
    pub properties: Vec<EngineProperty>,
    #[serde(default)]
    pub is_abstract: bool,
    #[serde(default)]
    pub category: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineStruct {
    pub name: String,
    #[serde(default)]
    pub header: String,
    #[serde(default)]
    pub module: String,
    #[serde(default)]
    pub fields: Vec<EngineProperty>,
    #[serde(default)]
    pub is_table_row: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineEnum {
    pub name: String,
    #[serde(default)]
    pub header: String,
    #[serde(default)]
    pub module: String,
    #[serde(default)]
    pub values: Vec<String>,
    #[serde(default)]
    pub is_flags: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineFunction {
    pub name: String,
    #[serde(default)]
    pub return_type: String,
    #[serde(default)]
    pub params: Vec<EngineFuncParam>,
    #[serde(default)]
    pub specifiers: Vec<String>,
    #[serde(default)]
    pub is_const: bool,
    #[serde(default)]
    pub is_virtual: bool,
    #[serde(default)]
    pub is_static: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineFuncParam {
    pub name: String,
    #[serde(rename = "type")]
    pub param_type: String,
    #[serde(default)]
    pub default_value: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineProperty {
    pub name: String,
    #[serde(rename = "type")]
    pub prop_type: String,
    #[serde(default)]
    pub specifiers: Vec<String>,
    #[serde(default)]
    pub category: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeAlias {
    pub kain_name: String,
    pub ue5_name: String,
    #[serde(default)]
    pub header: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EngineMetadata {
    #[serde(default)]
    pub engine_version: String,
    #[serde(default)]
    pub classes: Vec<EngineClass>,
    #[serde(default)]
    pub structs: Vec<EngineStruct>,
    #[serde(default)]
    pub enums: Vec<EngineEnum>,
    #[serde(default)]
    pub type_aliases: Vec<TypeAlias>,
    #[serde(default)]
    pub include_map: HashMap<String, String>,
}

// ═══════════════════════════════════════════════════════════════════
// Engine Knowledge — the queryable runtime database
// ═══════════════════════════════════════════════════════════════════

#[derive(Debug, Clone)]
pub struct EngineKnowledge {
    pub classes: HashMap<String, EngineClass>,
    pub structs: HashMap<String, EngineStruct>,
    pub enums: HashMap<String, EngineEnum>,
    pub type_aliases: HashMap<String, String>,
    pub include_map: HashMap<String, String>,
    pub class_hierarchy: HashMap<String, HashSet<String>>,
    pub component_names: HashSet<String>,
    pub actor_class_names: HashSet<String>,
    pub module_types: HashMap<String, HashSet<String>>,
    pub call_templates: HashMap<String, String>,
    pub function_map: HashMap<String, String>,
    /// Named color map: "sunset" -> (R, G, B, A) as linear floats
    /// Sourced from UE_AI JsonValueHelper.cpp TryParseNamedColor
    pub named_colors: HashMap<String, [f32; 4]>,
    /// Constructor format strings for UE5 math types
    /// Maps (type_name, arg_count) -> C++ format string
    /// e.g. ("FVector", 3) -> "FVector({0}, {1}, {2})"
    pub constructor_formats: HashMap<(String, usize), String>,
    /// Property string format for UE5 ImportText/ExportText
    /// Maps type_name -> format string with named fields
    /// e.g. "FVector" -> "(X={0},Y={1},Z={2})"
    pub property_string_formats: HashMap<String, String>,
}

impl Default for EngineKnowledge {
    fn default() -> Self {
        Self::new()
    }
}

impl EngineKnowledge {
    pub fn new() -> Self {
        let mut kb = Self {
            classes: HashMap::new(),
            structs: HashMap::new(),
            enums: HashMap::new(),
            type_aliases: HashMap::new(),
            include_map: HashMap::new(),
            class_hierarchy: HashMap::new(),
            component_names: HashSet::new(),
            actor_class_names: HashSet::new(),
            module_types: HashMap::new(),
            call_templates: HashMap::new(),
            function_map: HashMap::new(),
            named_colors: HashMap::new(),
            constructor_formats: HashMap::new(),
            property_string_formats: HashMap::new(),
        };
        kb.seed_builtin_aliases();
        kb.seed_builtin_includes();
        kb.seed_named_colors();
        kb.seed_constructor_formats();
        kb
    }

    /// Load metadata from JSON (supports both new rich format and legacy format)
    pub fn load_metadata(&mut self, json_data: &str) -> Result<(), String> {
        if let Ok(meta) = serde_json::from_str::<EngineMetadata>(json_data) {
            self.ingest_metadata(meta);
            return Ok(());
        }
        if let Ok(legacy) = serde_json::from_str::<serde_json::Value>(json_data) {
            self.load_legacy_metadata(&legacy)?;
            return Ok(());
        }
        Err("Failed to parse metadata as either new or legacy format".to_string())
    }

    /// Load and validate metadata from file with schema validation
    pub fn load_metadata_validated(
        &mut self,
        file_path: &std::path::Path,
        json_data: &str,
    ) -> Result<(), String> {
        use crate::ue5::metadata_validation::MetadataValidator;

        // Create validator
        let validator = MetadataValidator::new();

        // Validate against schema
        let _validated_json = validator
            .validate_file(file_path, json_data)
            .map_err(|e| e.to_string())?;

        // If validation passes, load normally
        self.load_metadata(json_data)
    }

    /// Load all extension metadata from the extensions directory
    /// Extensions are JSON files in unreal/metadata/extensions/*.json
    /// They follow the same schema as engine_knowledge.json
    pub fn load_extensions(&mut self, extensions_dir: &std::path::Path) -> Result<usize, String> {
        use std::fs;

        if !extensions_dir.exists() {
            // Extensions directory doesn't exist yet, that's okay
            return Ok(0);
        }

        let mut loaded_count = 0;

        // Read all .json files in the extensions directory
        let entries = fs::read_dir(extensions_dir)
            .map_err(|e| format!("Failed to read extensions directory: {}", e))?;

        for entry in entries {
            let entry = entry.map_err(|e| format!("Failed to read directory entry: {}", e))?;
            let path = entry.path();

            // Only process .json files
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }

            // Read the extension file
            let json_data = fs::read_to_string(&path)
                .map_err(|e| format!("Failed to read extension file {:?}: {}", path, e))?;

            // Load the extension metadata
            match self.load_metadata(&json_data) {
                Ok(_) => {
                    loaded_count += 1;
                }
                Err(_e) => {
                    // Silently continue loading other extensions even if one fails
                }
            }
        }

        Ok(loaded_count)
    }

    fn ingest_metadata(&mut self, meta: EngineMetadata) {
        for class in meta.classes {
            let name = class.name.clone();
            if !class.header.is_empty() {
                self.include_map.insert(name.clone(), class.header.clone());
            }
            if !class.module.is_empty() {
                self.module_types
                    .entry(class.module.clone())
                    .or_default()
                    .insert(name.clone());
            }
            for func in &class.functions {
                let key = format!("{}::{}", name, func.name);
                let pp: Vec<String> = (1..=func.params.len()).map(|i| format!("${}", i)).collect();
                let tmpl = if func.is_static {
                    format!("{}::{}({})", name, func.name, pp.join(", "))
                } else {
                    format!("$0->{}({})", func.name, pp.join(", "))
                };
                self.call_templates.insert(key, tmpl.clone());
                self.function_map.insert(func.name.clone(), tmpl);
            }
            // Merge strategy: don't overwrite a class that has more detail (functions/properties)
            if let Some(existing) = self.classes.get(&name) {
                let existing_detail = existing.functions.len() + existing.properties.len();
                let new_detail = class.functions.len() + class.properties.len();
                if new_detail > existing_detail {
                    self.classes.insert(name, class);
                }
                // else: keep existing (it has more detail)
            } else {
                self.classes.insert(name, class);
            }
        }
        for st in meta.structs {
            if !st.header.is_empty() {
                self.include_map.insert(st.name.clone(), st.header.clone());
            }
            if !st.module.is_empty() {
                self.module_types
                    .entry(st.module.clone())
                    .or_default()
                    .insert(st.name.clone());
            }
            // Merge: don't overwrite structs with more fields
            if let Some(existing) = self.structs.get(&st.name) {
                if st.fields.len() > existing.fields.len() {
                    self.structs.insert(st.name.clone(), st);
                }
            } else {
                self.structs.insert(st.name.clone(), st);
            }
        }
        for en in meta.enums {
            if !en.header.is_empty() {
                self.include_map.insert(en.name.clone(), en.header.clone());
            }
            if !en.module.is_empty() {
                self.module_types
                    .entry(en.module.clone())
                    .or_default()
                    .insert(en.name.clone());
            }
            // Merge: don't overwrite enums with more values
            if let Some(existing) = self.enums.get(&en.name) {
                if en.values.len() > existing.values.len() {
                    self.enums.insert(en.name.clone(), en);
                }
            } else {
                self.enums.insert(en.name.clone(), en);
            }
        }
        for alias in meta.type_aliases {
            self.type_aliases
                .insert(alias.kain_name.clone(), alias.ue5_name.clone());
            if !alias.header.is_empty() {
                self.include_map.insert(alias.ue5_name, alias.header);
            }
        }
        for (k, v) in meta.include_map {
            self.include_map.insert(k, v);
        }
        self.rebuild_hierarchy();
    }

    /// Load legacy format: array of {file, content: {functions, properties, classes}}
    fn load_legacy_metadata(&mut self, v: &serde_json::Value) -> Result<(), String> {
        if let Some(files) = v.as_array() {
            for file in files {
                if let Some(content) = file.get("content") {
                    if let Some(funcs) = content.get("functions").and_then(|f| f.as_array()) {
                        for func in funcs {
                            let name = func.get("name").and_then(|n| n.as_str()).unwrap_or("");
                            if name.is_empty() {
                                continue;
                            }
                            let mut template = format!("$0->{}()", name);
                            if let Some(params) = func.get("params").and_then(|p| p.as_array()) {
                                if !params.is_empty() {
                                    let pp: Vec<String> =
                                        (1..=params.len()).map(|i| format!("${}", i)).collect();
                                    template = format!("$0->{}({})", name, pp.join(", "));
                                }
                            }
                            self.function_map.insert(name.to_string(), template);
                        }
                    }
                    if let Some(props) = content.get("properties").and_then(|p| p.as_array()) {
                        for prop in props {
                            let name = prop.get("name").and_then(|n| n.as_str()).unwrap_or("");
                            if name.is_empty() {
                                continue;
                            }
                            self.function_map
                                .insert(format!("get_{}", name), format!("$0->{}", name));
                            self.function_map
                                .insert(format!("set_{}", name), format!("$0->{} = $1", name));
                        }
                    }
                }
            }
        }
        Ok(())
    }

    fn rebuild_hierarchy(&mut self) {
        let class_parents: HashMap<String, String> = self
            .classes
            .iter()
            .filter(|(_, c)| !c.parent.is_empty())
            .map(|(name, c)| (name.clone(), c.parent.clone()))
            .collect();

        for name in self.classes.keys() {
            let mut ancestors = HashSet::new();
            let mut current = name.clone();
            while let Some(parent) = class_parents.get(&current) {
                ancestors.insert(parent.clone());
                current = parent.clone();
            }
            self.class_hierarchy.insert(name.clone(), ancestors);
        }

        self.component_names.clear();
        self.actor_class_names.clear();
        for (name, ancestors) in &self.class_hierarchy {
            if ancestors.contains("UActorComponent")
                || ancestors.contains("USceneComponent")
                || name == "UActorComponent"
                || name == "USceneComponent"
            {
                self.component_names.insert(name.clone());
            }
            if ancestors.contains("AActor") || name == "AActor" {
                self.actor_class_names.insert(name.clone());
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // Query API
    // ═══════════════════════════════════════════════════════════════

    pub fn is_known_type(&self, name: &str) -> bool {
        self.classes.contains_key(name)
            || self.structs.contains_key(name)
            || self.enums.contains_key(name)
            || self.type_aliases.contains_key(name)
    }

    pub fn resolve_type_alias(&self, kain_name: &str) -> Option<&str> {
        self.type_aliases.get(kain_name).map(|s| s.as_str())
    }

    pub fn get_include(&self, type_name: &str) -> Option<&str> {
        if let Some(inc) = self.include_map.get(type_name) {
            return Some(inc.as_str());
        }
        for prefix in &["A", "U", "F", "E"] {
            let prefixed = format!("{}{}", prefix, type_name);
            if let Some(inc) = self.include_map.get(&prefixed) {
                return Some(inc.as_str());
            }
        }
        None
    }

    pub fn is_child_of(&self, class_name: &str, parent_name: &str) -> bool {
        if class_name == parent_name {
            return true;
        }
        self.class_hierarchy
            .get(class_name)
            .map_or(false, |a| a.contains(parent_name))
    }

    pub fn is_engine_component(&self, name: &str) -> bool {
        self.component_names.contains(name) || self.component_names.contains(&format!("U{}", name))
    }

    pub fn is_engine_actor(&self, name: &str) -> bool {
        self.actor_class_names.contains(name)
            || self.actor_class_names.contains(&format!("A{}", name))
    }

    /// Check if a type is a UObject-derived class (requires pointer semantics in C++)
    pub fn is_uobject_derived(&self, name: &str) -> bool {
        // Check with and without prefix
        let names_to_check = [name, &format!("U{}", name), &format!("A{}", name)];

        for check_name in &names_to_check {
            // Direct class lookup
            if let Some(class) = self.classes.get(*check_name) {
                // All UObject-derived classes need pointers
                // Check if it inherits from UObject (or is UObject itself)
                if *check_name == "UObject" || self.is_child_of(check_name, "UObject") {
                    return true;
                }
                // Also check prefix - U* and A* are always UObject-derived
                if class.prefix == "U" || class.prefix == "A" {
                    return true;
                }
            }
        }

        // Check if it's a component or actor (already UObject-derived)
        if self.is_engine_component(name) || self.is_engine_actor(name) {
            return true;
        }

        false
    }

    /// Get the C++ type name for a KAIN type, including pointer suffix if needed
    pub fn get_cpp_type(&self, kain_name: &str) -> Option<String> {
        // Check type aliases first (Vec3 -> FVector, etc.)
        if let Some(ue_type) = self.resolve_type_alias(kain_name) {
            // Debug output
            use std::io::Write;
            let mut file = std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open("C:/temp/kain_debug.txt")
                .ok()?;
            let _ = writeln!(
                file,
                "[DEBUG get_cpp_type] {} -> {} (from alias)",
                kain_name, ue_type
            );

            // Check if the resolved type is UObject-derived and needs a pointer
            if self.is_uobject_derived(ue_type) {
                let _ = writeln!(
                    file,
                    "[DEBUG get_cpp_type] {} is UObject-derived, adding pointer",
                    ue_type
                );
                return Some(format!("{}*", ue_type));
            }

            // Fallback: if it starts with U or A, it's probably UObject-derived even if not in the database
            if ue_type.starts_with('U') || ue_type.starts_with('A') {
                let _ = writeln!(
                    file,
                    "[DEBUG get_cpp_type] {} starts with U/A, adding pointer (fallback)",
                    ue_type
                );
                return Some(format!("{}*", ue_type));
            }

            let _ = writeln!(
                file,
                "[DEBUG get_cpp_type] {} is NOT UObject-derived",
                ue_type
            );
            return Some(ue_type.to_string());
        }

        // Check if it's a known class
        if let Some(class) = self.classes.get(kain_name) {
            let cpp_name = &class.name;
            // UObject-derived types need pointer suffix
            if self.is_uobject_derived(cpp_name) {
                return Some(format!("{}*", cpp_name));
            }
            return Some(cpp_name.clone());
        }

        // Try with prefixes
        for prefix in &["U", "A", "F", "E"] {
            let prefixed = format!("{}{}", prefix, kain_name);
            if let Some(_class) = self.classes.get(&prefixed) {
                if self.is_uobject_derived(&prefixed) {
                    return Some(format!("{}*", prefixed));
                }
                return Some(prefixed);
            }
            if let Some(st) = self.structs.get(&prefixed) {
                return Some(st.name.clone());
            }
            if let Some(en) = self.enums.get(&prefixed) {
                return Some(en.name.clone());
            }
        }

        None
    }

    pub fn is_engine_enum(&self, name: &str) -> bool {
        self.enums.contains_key(name) || self.enums.contains_key(&format!("E{}", name))
    }

    pub fn is_engine_struct(&self, name: &str) -> bool {
        self.structs.contains_key(name) || self.structs.contains_key(&format!("F{}", name))
    }

    pub fn get_class_functions(&self, class_name: &str) -> Vec<&EngineFunction> {
        let mut funcs = Vec::new();
        if let Some(class) = self.classes.get(class_name) {
            funcs.extend(class.functions.iter());
            let mut parent = class.parent.clone();
            while !parent.is_empty() {
                if let Some(pc) = self.classes.get(&parent) {
                    funcs.extend(pc.functions.iter());
                    parent = pc.parent.clone();
                } else {
                    break;
                }
            }
        }
        funcs
    }

    pub fn get_class_properties(&self, class_name: &str) -> Vec<&EngineProperty> {
        let mut props = Vec::new();
        if let Some(class) = self.classes.get(class_name) {
            props.extend(class.properties.iter());
            let mut parent = class.parent.clone();
            while !parent.is_empty() {
                if let Some(pc) = self.classes.get(&parent) {
                    props.extend(pc.properties.iter());
                    parent = pc.parent.clone();
                } else {
                    break;
                }
            }
        }
        props
    }

    pub fn get_module_for_type(&self, type_name: &str) -> Option<&str> {
        for (module, types) in &self.module_types {
            if types.contains(type_name) {
                return Some(module.as_str());
            }
        }
        for prefix in &["A", "U", "F", "E"] {
            let prefixed = format!("{}{}", prefix, type_name);
            for (module, types) in &self.module_types {
                if types.contains(&prefixed) {
                    return Some(module.as_str());
                }
            }
        }
        None
    }

    pub fn resolve_call(&self, name: &str, args: &[String]) -> Option<String> {
        let template = self.function_map.get(name)?;
        let mut result = template.clone();
        for (i, arg) in args.iter().enumerate() {
            result = result.replace(&format!("${}", i), arg);
        }
        Some(result)
    }

    /// Resolve a named color to its FLinearColor constructor string.
    /// Returns None if the color name is not recognized.
    /// Example: resolve_named_color("sunset") -> Some("FLinearColor(1.0f, 0.7f, 0.3f, 1.0f)")
    pub fn resolve_named_color(&self, name: &str) -> Option<String> {
        let lower = name.to_lowercase();
        let rgba = self.named_colors.get(&lower)?;
        Some(format!(
            "FLinearColor({:.1}f, {:.2}f, {:.2}f, {:.1}f)",
            rgba[0], rgba[1], rgba[2], rgba[3]
        ))
    }

    /// Check if a name is a known named color.
    pub fn is_named_color(&self, name: &str) -> bool {
        self.named_colors.contains_key(&name.to_lowercase())
    }

    /// Get the raw RGBA values for a named color (linear-space floats).
    pub fn get_named_color_rgba(&self, name: &str) -> Option<[f32; 4]> {
        self.named_colors.get(&name.to_lowercase()).copied()
    }

    /// Resolve a type constructor call to its C++ equivalent.
    /// Maps KAIN constructor calls like vec3(1, 2, 3) to FVector(1, 2, 3).
    /// The caller provides the resolved UE5 type name and the formatted argument strings.
    /// Example: resolve_constructor("FVector", &["1.0", "2.0", "3.0"]) -> Some("FVector(1.0, 2.0, 3.0)")
    pub fn resolve_constructor(&self, ue5_type: &str, args: &[String]) -> Option<String> {
        let key = (ue5_type.to_string(), args.len());
        let fmt = self.constructor_formats.get(&key)?;
        let mut result = fmt.clone();
        for (i, arg) in args.iter().enumerate() {
            result = result.replace(&format!("{{{}}}", i), arg);
        }
        Some(result)
    }

    /// Get the UE5 property string format for a type (ImportText/ExportText format).
    /// Example: get_property_format("FVector") -> Some("(X={0},Y={1},Z={2})")
    pub fn get_property_format(&self, ue5_type: &str) -> Option<&str> {
        self.property_string_formats
            .get(ue5_type)
            .map(|s| s.as_str())
    }

    /// Format a property value string for UE5 ImportText.
    /// Example: format_property_string("FVector", &["1.0", "2.0", "3.0"]) -> Some("(X=1.0,Y=2.0,Z=3.0)")
    pub fn format_property_string(&self, ue5_type: &str, values: &[String]) -> Option<String> {
        let fmt = self.property_string_formats.get(ue5_type)?;
        let mut result = fmt.clone();
        for (i, val) in values.iter().enumerate() {
            result = result.replace(&format!("{{{}}}", i), val);
        }
        Some(result)
    }

    pub fn validate_property_type(&self, cpp_type: &str) -> Result<(), String> {
        let base = cpp_type
            .trim_end_matches('*')
            .trim_end_matches('&')
            .trim_start_matches("const ")
            .trim();
        if base.starts_with("TArray<")
            || base.starts_with("TMap<")
            || base.starts_with("TSet<")
            || base.starts_with("TOptional<")
        {
            return Ok(());
        }
        let primitives = [
            "bool", "int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64",
            "float", "double", "FString", "FName", "FText", "void", "auto",
        ];
        if primitives.contains(&base) {
            return Ok(());
        }
        // Unknown types pass through (might be user-defined)
        Ok(())
    }

    // ═══════════════════════════════════════════════════════════════
    // Built-in Seeds (from UE_AI BlueprintTypeParser reference)
    // ═══════════════════════════════════════════════════════════════

    fn seed_builtin_aliases(&mut self) {
        let aliases = [
            ("Bool", "bool"),
            ("Int", "int32"),
            ("Int64", "int64"),
            ("Float", "float"),
            ("Double", "double"),
            ("Byte", "uint8"),
            ("String", "FString"),
            ("Name", "FName"),
            ("Text", "FText"),
            ("Vec", "FVector"),
            ("Vec2", "FVector2D"),
            ("Vec3", "FVector"),
            ("Vec4", "FVector4"),
            ("Vector", "FVector"),
            ("Vector2D", "FVector2D"),
            ("Rot", "FRotator"),
            ("Rotator", "FRotator"),
            ("Rotation", "FRotator"),
            ("Transform", "FTransform"),
            ("Quat", "FQuat"),
            ("Color", "FLinearColor"),
            ("LinearColor", "FLinearColor"),
            ("Actor", "AActor"),
            ("Pawn", "APawn"),
            ("Character", "ACharacter"),
            ("PlayerController", "APlayerController"),
            ("GameMode", "AGameModeBase"),
            ("GameState", "AGameStateBase"),
            ("PlayerState", "APlayerState"),
            ("SceneComponent", "USceneComponent"),
            ("StaticMeshComponent", "UStaticMeshComponent"),
            ("SkeletalMeshComponent", "USkeletalMeshComponent"),
            ("CameraComponent", "UCameraComponent"),
            ("SpringArmComponent", "USpringArmComponent"),
            ("AudioComponent", "UAudioComponent"),
            ("LightComponent", "ULightComponent"),
            ("SplineComponent", "USplineComponent"),
            ("WidgetComponent", "UWidgetComponent"),
            ("NiagaraComponent", "UNiagaraComponent"),
            ("CapsuleComponent", "UCapsuleComponent"),
            ("SphereComponent", "USphereComponent"),
            ("BoxComponent", "UBoxComponent"),
            ("StaticMesh", "UStaticMesh"),
            ("SkeletalMesh", "USkeletalMesh"),
            ("AnimMontage", "UAnimMontage"),
            ("AnimSequence", "UAnimSequence"),
            ("Texture2D", "UTexture2D"),
            ("Material", "UMaterial"),
            ("MaterialInstance", "UMaterialInstance"),
            ("MaterialInstanceDynamic", "UMaterialInstanceDynamic"),
            ("SoundBase", "USoundBase"),
            ("SoundWave", "USoundWave"),
            ("SoundCue", "USoundCue"),
            ("ParticleSystem", "UParticleSystem"),
            ("NiagaraSystem", "UNiagaraSystem"),
            ("DataTable", "UDataTable"),
            ("CurveFloat", "UCurveFloat"),
            ("CurveVector", "UCurveVector"),
            ("CurveLinearColor", "UCurveLinearColor"),
            ("WorldSubsystem", "UWorldSubsystem"),
            ("GameInstanceSubsystem", "UGameInstanceSubsystem"),
            ("LocalPlayerSubsystem", "ULocalPlayerSubsystem"),
        ];
        for (k, u) in &aliases {
            self.type_aliases.insert(k.to_string(), u.to_string());
        }
    }

    fn seed_builtin_includes(&mut self) {
        let includes = [
            ("AActor", "GameFramework/Actor.h"),
            ("APawn", "GameFramework/Pawn.h"),
            ("ACharacter", "GameFramework/Character.h"),
            ("APlayerController", "GameFramework/PlayerController.h"),
            ("AGameModeBase", "GameFramework/GameModeBase.h"),
            ("AGameStateBase", "GameFramework/GameStateBase.h"),
            ("APlayerState", "GameFramework/PlayerState.h"),
            ("AStaticMeshActor", "Engine/StaticMeshActor.h"),
            ("APointLight", "Engine/PointLight.h"),
            ("ASpotLight", "Engine/SpotLight.h"),
            ("ADirectionalLight", "Engine/DirectionalLight.h"),
            ("UActorComponent", "Components/ActorComponent.h"),
            ("USceneComponent", "Components/SceneComponent.h"),
            ("UPrimitiveComponent", "Components/PrimitiveComponent.h"),
            ("UStaticMeshComponent", "Components/StaticMeshComponent.h"),
            (
                "USkeletalMeshComponent",
                "Components/SkeletalMeshComponent.h",
            ),
            ("UCameraComponent", "Camera/CameraComponent.h"),
            ("USpringArmComponent", "GameFramework/SpringArmComponent.h"),
            ("UAudioComponent", "Components/AudioComponent.h"),
            ("ULightComponent", "Components/LightComponent.h"),
            ("UPointLightComponent", "Components/PointLightComponent.h"),
            ("USpotLightComponent", "Components/SpotLightComponent.h"),
            (
                "UDirectionalLightComponent",
                "Components/DirectionalLightComponent.h",
            ),
            ("USplineComponent", "Components/SplineComponent.h"),
            (
                "UInstancedStaticMeshComponent",
                "Components/InstancedStaticMeshComponent.h",
            ),
            ("UCapsuleComponent", "Components/CapsuleComponent.h"),
            ("USphereComponent", "Components/SphereComponent.h"),
            ("UBoxComponent", "Components/BoxComponent.h"),
            ("UWidgetComponent", "Components/WidgetComponent.h"),
            ("UNiagaraComponent", "NiagaraComponent.h"),
            ("UStaticMesh", "Engine/StaticMesh.h"),
            ("USkeletalMesh", "Engine/SkeletalMesh.h"),
            ("UTexture2D", "Engine/Texture2D.h"),
            ("UMaterial", "Materials/Material.h"),
            ("UMaterialInstance", "Materials/MaterialInstance.h"),
            (
                "UMaterialInstanceConstant",
                "Materials/MaterialInstanceConstant.h",
            ),
            (
                "UMaterialInstanceDynamic",
                "Materials/MaterialInstanceDynamic.h",
            ),
            ("UAnimMontage", "Animation/AnimMontage.h"),
            ("UAnimSequence", "Animation/AnimSequence.h"),
            ("USoundBase", "Sound/SoundBase.h"),
            ("USoundWave", "Sound/SoundWave.h"),
            ("USoundCue", "Sound/SoundCue.h"),
            ("UParticleSystem", "Particles/ParticleSystem.h"),
            ("UNiagaraSystem", "NiagaraSystem.h"),
            ("UDataTable", "Engine/DataTable.h"),
            ("UCurveFloat", "Curves/CurveFloat.h"),
            ("UCurveVector", "Curves/CurveVector.h"),
            ("UCurveLinearColor", "Curves/CurveLinearColor.h"),
            ("UUserWidget", "Blueprint/UserWidget.h"),
            ("FVector", "Math/Vector.h"),
            ("FVector2D", "Math/Vector2D.h"),
            ("FVector4", "Math/Vector4.h"),
            ("FRotator", "Math/Rotator.h"),
            ("FTransform", "Math/Transform.h"),
            ("FQuat", "Math/Quat.h"),
            ("FLinearColor", "Math/Color.h"),
            ("FColor", "Math/Color.h"),
            ("FHitResult", "Engine/HitResult.h"),
            ("FTimerHandle", "Engine/EngineTypes.h"),
            ("FTimerDelegate", "Engine/EngineTypes.h"),
            ("FTableRowBase", "Engine/DataTable.h"),
        ];
        for (t, h) in &includes {
            self.include_map.insert(t.to_string(), h.to_string());
        }

        // Seed println/print for legacy compat
        self.function_map.insert(
            "println".to_string(),
            "UE_LOG(LogTemp, Warning, TEXT(\"%s\"), *$0)".to_string(),
        );
        self.function_map.insert(
            "print".to_string(),
            "UE_LOG(LogTemp, Warning, TEXT(\"%s\"), *$0)".to_string(),
        );
    }

    /// Seed named colors from UE_AI JsonValueHelper.cpp TryParseNamedColor
    /// All values are linear-space floats matching FLinearColor components
    fn seed_named_colors(&mut self) {
        let colors: &[(&str, [f32; 4])] = &[
            ("white", [1.0, 1.0, 1.0, 1.0]),
            ("black", [0.0, 0.0, 0.0, 1.0]),
            ("red", [1.0, 0.0, 0.0, 1.0]),
            ("green", [0.0, 1.0, 0.0, 1.0]),
            ("blue", [0.0, 0.0, 1.0, 1.0]),
            ("yellow", [1.0, 1.0, 0.0, 1.0]),
            ("cyan", [0.0, 1.0, 1.0, 1.0]),
            ("magenta", [1.0, 0.0, 1.0, 1.0]),
            ("purple", [1.0, 0.0, 1.0, 1.0]),
            ("orange", [1.0, 0.5, 0.0, 1.0]),
            ("gray", [0.5, 0.5, 0.5, 1.0]),
            ("grey", [0.5, 0.5, 0.5, 1.0]),
            ("transparent", [0.0, 0.0, 0.0, 0.0]),
            ("pink", [1.0, 0.75, 0.8, 1.0]),
            ("brown", [0.6, 0.4, 0.2, 1.0]),
            ("lime", [0.5, 1.0, 0.0, 1.0]),
            ("navy", [0.0, 0.0, 0.5, 1.0]),
            ("teal", [0.0, 0.5, 0.5, 1.0]),
            // Temperature-based colors (common for lights)
            ("warm", [1.0, 0.85, 0.6, 1.0]),
            ("warm white", [1.0, 0.85, 0.6, 1.0]),
            ("cool", [0.9, 0.95, 1.0, 1.0]),
            ("cool white", [0.9, 0.95, 1.0, 1.0]),
            ("daylight", [1.0, 1.0, 0.98, 1.0]),
            ("candle", [1.0, 0.6, 0.2, 1.0]),
            ("candlelight", [1.0, 0.6, 0.2, 1.0]),
            ("sunset", [1.0, 0.7, 0.3, 1.0]),
            ("golden", [1.0, 0.7, 0.3, 1.0]),
            // Game-common colors
            ("health", [0.8, 0.1, 0.1, 1.0]),
            ("mana", [0.1, 0.2, 0.9, 1.0]),
            ("stamina", [0.1, 0.8, 0.2, 1.0]),
            ("xp", [0.9, 0.8, 0.1, 1.0]),
            ("gold", [1.0, 0.84, 0.0, 1.0]),
            ("silver", [0.75, 0.75, 0.75, 1.0]),
            ("bronze", [0.8, 0.5, 0.2, 1.0]),
            ("platinum", [0.9, 0.89, 0.88, 1.0]),
            // Rarity tier colors (common in RPGs/looters)
            ("common", [0.7, 0.7, 0.7, 1.0]),
            ("uncommon", [0.1, 0.8, 0.1, 1.0]),
            ("rare", [0.0, 0.44, 0.87, 1.0]),
            ("epic", [0.6, 0.2, 0.9, 1.0]),
            ("legendary", [1.0, 0.5, 0.0, 1.0]),
            ("mythic", [1.0, 0.0, 0.0, 1.0]),
        ];
        for (name, rgba) in colors {
            self.named_colors.insert(name.to_string(), *rgba);
        }
    }

    /// Seed constructor format strings for UE5 math/color/margin types.
    /// Key is (type_name, arg_count) so we can support multiple overloads.
    fn seed_constructor_formats(&mut self) {
        // FVector constructors
        self.constructor_formats
            .insert(("FVector".into(), 0), "FVector::ZeroVector".into());
        self.constructor_formats
            .insert(("FVector".into(), 1), "FVector({0})".into());
        self.constructor_formats
            .insert(("FVector".into(), 3), "FVector({0}, {1}, {2})".into());

        // FVector2D constructors
        self.constructor_formats
            .insert(("FVector2D".into(), 0), "FVector2D::ZeroVector".into());
        self.constructor_formats
            .insert(("FVector2D".into(), 1), "FVector2D({0})".into());
        self.constructor_formats
            .insert(("FVector2D".into(), 2), "FVector2D({0}, {1})".into());

        // FVector4 constructors
        self.constructor_formats.insert(
            ("FVector4".into(), 4),
            "FVector4({0}, {1}, {2}, {3})".into(),
        );

        // FRotator constructors
        self.constructor_formats
            .insert(("FRotator".into(), 0), "FRotator::ZeroRotator".into());
        self.constructor_formats
            .insert(("FRotator".into(), 3), "FRotator({0}, {1}, {2})".into());

        // FQuat constructors
        self.constructor_formats
            .insert(("FQuat".into(), 0), "FQuat::Identity".into());
        self.constructor_formats
            .insert(("FQuat".into(), 4), "FQuat({0}, {1}, {2}, {3})".into());

        // FTransform constructors
        self.constructor_formats
            .insert(("FTransform".into(), 0), "FTransform::Identity".into());

        // FLinearColor constructors
        self.constructor_formats.insert(
            ("FLinearColor".into(), 0),
            "FLinearColor::Transparent".into(),
        );
        self.constructor_formats.insert(
            ("FLinearColor".into(), 3),
            "FLinearColor({0}f, {1}f, {2}f, 1.0f)".into(),
        );
        self.constructor_formats.insert(
            ("FLinearColor".into(), 4),
            "FLinearColor({0}f, {1}f, {2}f, {3}f)".into(),
        );

        // FColor constructors (sRGB 0-255)
        self.constructor_formats
            .insert(("FColor".into(), 3), "FColor({0}, {1}, {2}, 255)".into());
        self.constructor_formats
            .insert(("FColor".into(), 4), "FColor({0}, {1}, {2}, {3})".into());

        // FMargin constructors (Slate padding)
        self.constructor_formats
            .insert(("FMargin".into(), 0), "FMargin(0.0f)".into());
        self.constructor_formats
            .insert(("FMargin".into(), 1), "FMargin({0}f)".into());
        self.constructor_formats
            .insert(("FMargin".into(), 2), "FMargin({0}f, {1}f)".into());
        self.constructor_formats.insert(
            ("FMargin".into(), 4),
            "FMargin({0}f, {1}f, {2}f, {3}f)".into(),
        );

        // Property string formats for ImportText/ExportText
        self.property_string_formats
            .insert("FVector".into(), "(X={0},Y={1},Z={2})".into());
        self.property_string_formats
            .insert("FVector2D".into(), "(X={0},Y={1})".into());
        self.property_string_formats
            .insert("FRotator".into(), "(Pitch={0},Yaw={1},Roll={2})".into());
        self.property_string_formats
            .insert("FLinearColor".into(), "(R={0},G={1},B={2},A={3})".into());
        self.property_string_formats
            .insert("FColor".into(), "(R={0},G={1},B={2},A={3})".into());
        self.property_string_formats.insert(
            "FTransform".into(),
            "(Rotation=(X=0,Y=0,Z=0,W=1),Translation=(X={0},Y={1},Z={2}),Scale3D=(X=1,Y=1,Z=1))"
                .into(),
        );
    }
}

// ═══════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builtin_aliases() {
        let kb = EngineKnowledge::new();
        assert_eq!(kb.resolve_type_alias("Vec3"), Some("FVector"));
        assert_eq!(kb.resolve_type_alias("Actor"), Some("AActor"));
        assert_eq!(
            kb.resolve_type_alias("NiagaraSystem"),
            Some("UNiagaraSystem")
        );
        assert_eq!(kb.resolve_type_alias("NonExistent"), None);
    }

    #[test]
    fn test_builtin_includes() {
        let kb = EngineKnowledge::new();
        assert_eq!(kb.get_include("AActor"), Some("GameFramework/Actor.h"));
        assert_eq!(
            kb.get_include("UStaticMeshComponent"),
            Some("Components/StaticMeshComponent.h")
        );
        // Test unprefixed lookup
        assert_eq!(kb.get_include("Actor"), Some("GameFramework/Actor.h"));
        assert_eq!(
            kb.get_include("StaticMeshComponent"),
            Some("Components/StaticMeshComponent.h")
        );
    }

    #[test]
    fn test_legacy_compat() {
        let kb = EngineKnowledge::new();
        let result = kb.resolve_call("println", &["FString(TEXT(\"hello\"))".to_string()]);
        assert!(result.is_some());
        assert!(result.unwrap().contains("UE_LOG"));
    }

    #[test]
    fn test_hierarchy() {
        let mut kb = EngineKnowledge::new();
        let json = r#"{
            "engine_version": "5.4",
            "classes": [
                {"name": "UObject", "parent": "", "header": "UObject/Object.h", "module": "CoreUObject"},
                {"name": "AActor", "parent": "UObject", "header": "GameFramework/Actor.h", "module": "Engine"},
                {"name": "APawn", "parent": "AActor", "header": "GameFramework/Pawn.h", "module": "Engine"},
                {"name": "ACharacter", "parent": "APawn", "header": "GameFramework/Character.h", "module": "Engine"},
                {"name": "UActorComponent", "parent": "UObject", "header": "Components/ActorComponent.h", "module": "Engine"},
                {"name": "USceneComponent", "parent": "UActorComponent", "header": "Components/SceneComponent.h", "module": "Engine"},
                {"name": "UStaticMeshComponent", "parent": "USceneComponent", "header": "Components/StaticMeshComponent.h", "module": "Engine"}
            ],
            "structs": [],
            "enums": []
        }"#;
        kb.load_metadata(json).unwrap();

        assert!(kb.is_child_of("ACharacter", "AActor"));
        assert!(kb.is_child_of("ACharacter", "UObject"));
        assert!(kb.is_child_of("APawn", "AActor"));
        assert!(!kb.is_child_of("AActor", "ACharacter"));
        assert!(kb.is_engine_actor("ACharacter"));
        assert!(kb.is_engine_actor("APawn"));
        assert!(kb.is_engine_component("UStaticMeshComponent"));
        assert!(kb.is_engine_component("USceneComponent"));
        assert!(!kb.is_engine_component("AActor"));
    }

    #[test]
    fn test_named_colors() {
        let kb = EngineKnowledge::new();
        // Basic colors
        assert!(kb.is_named_color("red"));
        assert!(kb.is_named_color("Red"));
        assert!(kb.is_named_color("RED"));
        assert!(!kb.is_named_color("nonexistent_color"));

        // Resolve to FLinearColor constructor
        let sunset = kb.resolve_named_color("sunset").unwrap();
        assert!(sunset.starts_with("FLinearColor("));
        assert!(sunset.contains("0.7"));
        assert!(sunset.contains("0.3"));

        // Temperature colors from JsonValueHelper
        assert!(kb.is_named_color("warm"));
        assert!(kb.is_named_color("candlelight"));
        assert!(kb.is_named_color("daylight"));

        // Game colors
        assert!(kb.is_named_color("health"));
        assert!(kb.is_named_color("mana"));

        // Rarity colors
        assert!(kb.is_named_color("legendary"));
        assert!(kb.is_named_color("epic"));

        // Raw RGBA access
        let rgba = kb.get_named_color_rgba("white").unwrap();
        assert_eq!(rgba, [1.0, 1.0, 1.0, 1.0]);
        let transparent = kb.get_named_color_rgba("transparent").unwrap();
        assert_eq!(transparent, [0.0, 0.0, 0.0, 0.0]);
    }

    #[test]
    fn test_constructor_resolution() {
        let kb = EngineKnowledge::new();

        // FVector(x, y, z)
        let v = kb
            .resolve_constructor("FVector", &["1.0".into(), "2.0".into(), "3.0".into()])
            .unwrap();
        assert_eq!(v, "FVector(1.0, 2.0, 3.0)");

        // FVector zero
        let vz = kb.resolve_constructor("FVector", &[]).unwrap();
        assert_eq!(vz, "FVector::ZeroVector");

        // FVector uniform
        let vu = kb.resolve_constructor("FVector", &["5.0".into()]).unwrap();
        assert_eq!(vu, "FVector(5.0)");

        // FRotator
        let r = kb
            .resolve_constructor("FRotator", &["0.0".into(), "90.0".into(), "0.0".into()])
            .unwrap();
        assert_eq!(r, "FRotator(0.0, 90.0, 0.0)");

        // FLinearColor(r, g, b)
        let c3 = kb
            .resolve_constructor("FLinearColor", &["1.0".into(), "0.5".into(), "0.0".into()])
            .unwrap();
        assert_eq!(c3, "FLinearColor(1.0f, 0.5f, 0.0f, 1.0f)");

        // FLinearColor(r, g, b, a)
        let c4 = kb
            .resolve_constructor(
                "FLinearColor",
                &["1.0".into(), "0.5".into(), "0.0".into(), "0.8".into()],
            )
            .unwrap();
        assert_eq!(c4, "FLinearColor(1.0f, 0.5f, 0.0f, 0.8f)");

        // FMargin uniform
        let m1 = kb.resolve_constructor("FMargin", &["5.0".into()]).unwrap();
        assert_eq!(m1, "FMargin(5.0f)");

        // FMargin horizontal/vertical
        let m2 = kb
            .resolve_constructor("FMargin", &["10.0".into(), "5.0".into()])
            .unwrap();
        assert_eq!(m2, "FMargin(10.0f, 5.0f)");

        // FMargin full
        let m4 = kb
            .resolve_constructor(
                "FMargin",
                &["1.0".into(), "2.0".into(), "3.0".into(), "4.0".into()],
            )
            .unwrap();
        assert_eq!(m4, "FMargin(1.0f, 2.0f, 3.0f, 4.0f)");

        // Unknown type returns None
        assert!(kb
            .resolve_constructor("FUnknownType", &["1".into()])
            .is_none());

        // Wrong arg count returns None
        assert!(kb
            .resolve_constructor("FVector", &["1".into(), "2".into()])
            .is_none());
    }

    #[test]
    fn test_property_string_format() {
        let kb = EngineKnowledge::new();

        // FVector property string
        let vs = kb
            .format_property_string("FVector", &["1.0".into(), "2.0".into(), "3.0".into()])
            .unwrap();
        assert_eq!(vs, "(X=1.0,Y=2.0,Z=3.0)");

        // FRotator property string
        let rs = kb
            .format_property_string("FRotator", &["0.0".into(), "90.0".into(), "0.0".into()])
            .unwrap();
        assert_eq!(rs, "(Pitch=0.0,Yaw=90.0,Roll=0.0)");

        // FLinearColor property string
        let cs = kb
            .format_property_string(
                "FLinearColor",
                &["1.0".into(), "0.5".into(), "0.0".into(), "1.0".into()],
            )
            .unwrap();
        assert_eq!(cs, "(R=1.0,G=0.5,B=0.0,A=1.0)");

        // Unknown type returns None
        assert!(kb
            .format_property_string("FUnknownType", &["1".into()])
            .is_none());
    }

    #[test]
    fn test_module_resolution() {
        let mut kb = EngineKnowledge::new();
        let json = r#"{
            "engine_version": "5.4",
            "classes": [
                {"name": "UNiagaraComponent", "parent": "USceneComponent", "header": "NiagaraComponent.h", "module": "Niagara"}
            ],
            "structs": [],
            "enums": []
        }"#;
        kb.load_metadata(json).unwrap();
        assert_eq!(kb.get_module_for_type("UNiagaraComponent"), Some("Niagara"));
        assert_eq!(kb.get_module_for_type("NiagaraComponent"), Some("Niagara"));
    }
}
